In [5]:
from pathlib import Path

import pandas as pd

!noglob scp -r hkqai:~/workdir/cc2cc_test5/validate/*.csv ~/workspace/2025.1/validate
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8736     6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7778   181.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5499   127.5KB/s   00:00

In [9]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "test": ["WATER27"],
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend([f"{i_subset}_{ i_set}" for i_set in full_subset_dict[i_subset]])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

# save summary to csv with date
df_summary.to_csv(f"../validate/summary_set_{date}.csv")

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ", "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
)

display(df_summary)

# save summary to csv with date
df_summary.to_csv(f"../validate/summary_subset_{date}.csv")

cc-pVDZ
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['propane', 'c', 'h'], ['propene', 'c', 'h'], ['s4-c2v', 's'], ['acetic', 'c', 'o', 'h'], ['glyoxal', 'c', 'o', 'h']]
[ 19.41995005  17.52912642 -16.80355977  16.2599607   15.20639248]
====Detail of AI error of W4_11====
15: 19.41995004655437
-0.4830054018798897 -1 propane
0.5723009303366778 3 c
2.152505231708056 8 h

23: 17.5291264151846
-2.897192233926232 -1 propene
0.5723009303366778 3 c
2.152505231708056 6 h

128: -16.80355976843325
12.369090028304717 -1 s4-c2v
-1.108617435032133 4 s

52: 16.259960702272796
-2.896038679013616 -1 acetic
0.5723009303366778 2 c
1.8046496178768003 2 o
2.152505231708056 4 h

66: 15.206392481996781
-6.147480922153714 -1 glyoxal
0.5723009303366778 2 c
1.8046496178768003 2 o
2.152505231708056 2 h

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['s4-c2v', 's'], ['sif4', 'si', 'f'], ['s2o', 's', 'o'], ['bef2', 'be', 'f']]
[-52.05705767 -19.18674047 -10.97536229 -10.44230828  -8.54224205]
====Detail of AI error of W4_11====
116: -52.05705767419491
51.57269647922633 -1 p4
-0.1210902987421438 4 p

128: -19.186740474142216
19.24645009296201 -1 s4-c2v
0.0149274047049485 4 s

41: -10.975362290867613
9.254534106033535 -1 sif4
-1.7366390394589053 1 si
0.0039527136562071 4 f

121: -10.442308277467188
10.324773069899289 -1 s2o
0.0149274047049485 2 s
-0.147390016977797 1 o

47: -8.542242045155673
8.366497199603995 -1 bef2
-0.183650272864092 1 be
0.0039527136562071 2 f

Warning: W4_11-sih4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-si2h6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-b2h6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-sih3f not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ph3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h5f not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3f not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-nh3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-methanol not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2ch not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-propyne not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-acetaldehyde not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-allene not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-sif4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h3f not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirane not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2f2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-acetic not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hcoh not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-ketene not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-formic not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-glyoxal not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2cl not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-cf4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirene not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-hocn not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-hooh not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-t-n2h2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-hnco not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-dioxirane not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-nccn not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-honc not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hono not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-hnnn not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-so3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-p4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hooo not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: W4_11-s4-c2v not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['c2', 'c'], ['s3', 's'], ['cs2', 'c', 's'], ['s2o', 's', 'o'], ['cs', 'c', 's']]
[ 16.10785912 -13.31423076 -10.42376417  -8.01203179  -7.21071632]
====Detail of AI error of W4_11====
130: 16.107859119178965
-16.58036847838528 -1 c2
-0.2362546796031581 2 c

126: -13.314230759358995
9.086293237695108 -1 s3
-1.409312507221296 3 s

103: -10.423764172755348
7.368884478709597 -1 cs2
-0.2362546796031581 1 c
-1.409312507221296 2 s

121: -8.012031790774394
4.580093884966766 -1 s2o
-1.409312507221296 2 s
-0.6133128913650362 1 o

105: -7.210716318212063
5.565149131387608 -1 cs
-0.2362546796031581 1 c
-1.409312507221296 1 s

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_22n', 'EA_22'], ['EA_20n', 'EA_20'], ['EA_19n', 'EA_19'], ['EA_24n', 'EA_24']]
[-15.56148959   3.84874462  -3.75388118   3.62147956  -3.52076851]
====Detail of AI error of G21EA====
24: -15.561489585733463
0.1865803499518095 1 EA_25n
15.748069935685272 -1 EA_25

21: 3.8487446212811336
1.9522720253207169 1 EA_22n
-1.8964725959604167 -1 EA_22

19: -3.753881182568128
-0.065322968894728 1 EA_20n
3.6885582136734 -1 EA_20

18: 3.6214795645507967
0.2499509659644877 1 EA_19n
-3.371528598586309 -1 EA_19

23: -3.520768508004529
-2.2363244771197506 1 EA_24n
1.2844440308847784 -1 EA_24

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_17n', 'EA_17'], ['EA_20n', 'EA_20'], ['EA_15n', 'EA_15']]
[-18.2444036   -6.00654178  -3.56984874   3.23528334  -2.58006913]
====Detail of AI error of G21EA====
24: -18.24440359940039
-0.2375307753512343 1 EA_25n
18.006872824049154 -1 EA_25

22: -6.006541779386775
5.413042054701967 1 EA_23n
11.419583834088742 -1 EA_23

16: -3.5698487389131532
-1.0903634708520993 1 EA_17n
2.479485268061054 -1 EA_17

19: 3.2352833443949933
0.277899330958607 1 EA_20n
-2.9573840134363865 -1 EA_20

14: -2.5800691272009675
-1.2083542245145615 1 EA_15n
1.371714902686406 -1 EA_15

Warning: G21EA-EA_c not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_o not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_f not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_si not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_p not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_s not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_cl not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_8n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_9n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_10n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_11n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_12n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_13n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_14n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_15n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_16n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_17n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_18n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_19n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_20n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_21n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_22n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_23n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_24n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_25n not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[]
[]
====Detail of AI error of G21EA====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of G21IP====
[['IP_80', '48'], ['IP_74', '34'], ['IP_72', '26'], ['IP_76', '43'], ['IP_78', '45']]
[-11.30301139  -9.87890904   8.45378456   7.27488888   5.6983195 ]
====Detail of AI error of G21IP====
35: -11.303011386099746
-6.115062189426492 1 IP_80
5.187949196673253 -1 48

29: -9.878909039031502
-9.695676416667691 1 IP_74
0.1832326223638099 -1 34

27: 8.45378455718068
7.267804371291358 1 IP_72
-1.1859801858893209 -1 26

31: 7.274888880244999
9.089576764134987 1 IP_76
1.8146878838899885 -1 43

33: 5.698319495726643
5.885619554490599 1 IP_78
0.1873000587639557 -1 45

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21IP====
[['IP_76', '43'], ['IP_71', '25'], ['IP_72', '26'], ['IP_74', '34'], ['IP_78', '45']]
[ 8.07775153  6.74444296  6.37953085 -5.59013503  5.47345559]
====Detail of AI error of G21IP====
31: 8.077751526575465
12.181684232650436 1 IP_76
4.10393270607497 -1 43

26: 6.744442958138531
7.315415632741993 1 IP_71
0.570972674603462 -1 25

27: 6.379530851029964
4.785703740685022 1 IP_72
-1.593827110344942 -1 26

29: -5.590135026110619
-4.257455246702045 1 IP_74
1.3326797794085736 -1 34

33: 5.473455586894162
5.269791871102592 1 IP_78
-0.2036637157915695 -1 45

Warning: G21IP-h not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-li+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-be+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-b+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-c+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-n+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-o+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-f+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-na+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-mg+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-al+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-si+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-p+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-s+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-cl+ not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_59 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_60 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_61 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_62 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_63 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_64 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_65 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_66 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_67 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_68 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_70 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_71 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_72 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_73 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_74 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_75 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_76 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_77 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_78 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_79 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_80 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of G21IP====
[]
[]
====Detail of AI error of G21IP====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of DIPCS10====
[['c4h4', 'c4h4_2+'], ['c2h4', 'c2h4_2+'], ['n2h2', 'n2h2_2+'], ['c2h6', 'c2h6_2+'], ['ph3', 'ph3_2+']]
[19.00791971 10.32663037 -8.20141404  1.84332908  1.38317004]
====Detail of AI error of DIPCS10====
0: 19.007919714169198
-5.915778513203403 -1 c4h4
13.092141200965797 1 c4h4_2+

2: 10.326630371579622
-1.4345907993350309 -1 c2h4
8.892039572244592 1 c2h4_2+

3: -8.201414044920142
0.1421010065026915 -1 n2h2
-8.05931303841745 1 n2h2_2+

1: 1.8433290829071605
-0.376894842435922 -1 c2h6
1.4664342404712385 1 c2h6_2+

7: 1.3831700355695962
-0.3426368939948518 -1 ph3
1.0405331415747443 1 ph3_2+

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of DIPCS10====
[['c4h4', 'c4h4_2+'], ['n2h2', 'n2h2_2+'], ['c2h4', 'c2h4_2+'], ['c2h6', 'c2h6_2+'], ['ch2o', 'ch2o_2+']]
[ 11.51669157 -10.7018807    8.36976068  -4.45073136   1.40106408]
====Detail of AI error of DIPCS10====
0: 11.516691566947067
-5.468360109114991 -1 c4h4
6.048331457832075 1 c4h4_2+

3: -10.701880696195957
2.3441059636370327 -1 n2h2
-8.357774732558925 1 n2h2_2+

2: 8.369760684489984
-0.783898566755461 -1 c2h4
7.585862117734523 1 c2h4_2+

1: -4.450731359686906
-0.8254198063707375 -1 c2h6
-5.276151166057644 1 c2h6_2+

5: 1.4010640793455251
-0.3324026384396666 -1 ch2o
1.0686614409058586 1 ch2o_2+

Warning: DIPCS10-c4h4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-c2h6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-c2h4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-n2h2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-nh3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-ch2o not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-h2s not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-ph3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-mg not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: DIPCS10-be not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of DIPCS10====
[]
[]
====Detail of AI error of DIPCS10====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of PA26====
[['p4', 'p4p'], ['c2f6', 'c2f6p'], ['p8', 'p8p'], ['p6', 'p6p'], ['ass', 'assp']]
[-11.35028239  -9.91044712  -8.38061401  -8.32174587  -5.21967293]
====Detail of AI error of PA26====
1: -11.350282387969727
-7.336014679442906 1 p4
4.014267708526822 -1 p4p

12: -9.910447123923904
-7.671365675614699 1 c2f6
2.2390814483092045 -1 c2f6p

3: -8.380614006799235
-12.25558245992256 1 p8
-3.874968453123324 -1 p8p

2: -8.321745865844232
-8.282403374706865 1 p6
0.0393424911373659 -1 p6p

17: -5.21967293158545
-24.24608804414649 1 ass
-19.02641511256104 -1 assp

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of PA26====
[['p6', 'p6p'], ['p4', 'p4p'], ['c2f6', 'c2f6p'], ['gly', 'glyp'], ['nh3', 'nh3p']]
[-12.59924031  -8.39930706  -7.19284855   6.37727148   6.19167942]
====Detail of AI error of PA26====
2: -12.599240313968917
-10.916129461411543 1 p6
1.6831108525573728 -1 p6p

1: -8.399307055946602
-6.516367155583493 1 p4
1.882939900363109 -1 p4p

12: -7.192848554792611
-0.8923727147253447 1 c2f6
6.300475840067266 -1 c2f6p

15: 6.377271478523636
-2.097383195200716 1 gly
-8.474654673724352 -1 glyp

4: 6.191679418554298
0.5460184233015473 1 nh3
-5.645660995252751 -1 nh3p

Warning: PA26-p2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-p4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-p6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-nh3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-h2o not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-c2h2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-sih4 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-ph3 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-h2s not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-hcl not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-h2 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-c2f6 not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-ethanol not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file
Warning: PA26-ch3cooh not found in ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ data file

data_path ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ                        \
Type                                           AI AE     DFT AE  Processed
sub1                                        4.692939  18.629823  468 / 468
sub2                                        6.272359   6.562349  222 / 243
sub3                                        4.162538   6.309849  192 / 194
sub4                                        2.254974   2.887648  242 / 244
sub5                                        1.913818   1.245124  259 / 291

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub1                                             3.601181  18.629823
sub2                                             5.700007   6.612165
sub3                                             3.648439   6.764537
sub4                                             2.277669   1.651300
sub5                                             1.775151   1.321288

data_path            ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                   2.700498  24.176867
sub2       210 / 243                                   0.000000   0.000000
sub3       170 / 194                                   0.000000   0.000000
sub4       217 / 244                                   0.000000   0.000000
sub5       268 / 291                                   0.000000   0.000000

data_path
Type      Processed
sub1       91 / 468
sub2        0 / 243
sub3        0 / 194
sub4        0 / 244
sub5        0 / 291

data_path      ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub2_MB16_43                                    11.357448  15.461608
sub5_IDISP                                      15.704176  13.632636
sub1_ALKBDE10                                    5.435985  18.125250
sub1_DC13                                        9.695545  13.090863
sub2_DARC                                        4.818050  10.754152
sub1_YBDE18                                      7.255829   8.145395
sub3_PX13                                       13.059142  11.042025
sub1_AL2X6                                       5.084741   5.659146
sub1_ALK8                                        6.925821   4.400063
sub1_RC21                                        4.696462   4.820927
sub1_SIE4x4                                     17.182399  21.908521
sub1_NBPRC                                       2.745689   2.232550
sub1_HEAVYSB11                                   3.928191   5.391477
sub4_ADIM6                                       3.649860   3.059030
sub3_BH76                                        4.203748   9.107948
sub3_WCPT18                                      4.243739   7.967153
sub1_DIPCS10                                     4.414108  12.310855
sub3_BHDIV10                                     2.461823   6.277708
sub1_G2RC                                        3.044318   5.917204
sub1_PA26                                        3.011796   2.200767
sub4_CHB6                                        3.585377   1.805320
sub5_PCONF21                                     3.418177   3.683764
sub4_S22                                         4.086915   2.291253
sub1_FH51                                        3.055128   3.703658
sub4_AHB21                                       1.766602   2.453821
sub1_W4_11                                       5.805564  29.506869
sub2_ISO34                                       2.057023   2.001744
sub2_BSR36                                      15.616911   8.401182
sub2_RSE43                                       1.951595   3.157601
sub4_S66                                         2.331477   1.894710
sub4_HAL59                                       1.848147   1.649787
sub3_BHPERI                                      2.119660   3.268993
sub1_TAUT15                                      1.871571   2.164531
sub4_IL16                                        1.735752   1.021067
sub2_CDIE20                                      1.160373   1.599507
sub1_G21EA                                       2.127111   9.754524
sub2_PArel                                       1.962423   1.743933
sub1_G21IP                                       2.390142   8.953336
sub5_ACONF                                       0.548364   0.546621
sub5_ICONF                                       0.709620   0.413804
sub5_Amino20x4                                   1.405904   0.656235
sub3_BHROT27                                     1.078680   0.853379
sub5_MCONF                                       3.392493   1.956021
sub1_BH76RC                                      1.212571  80.220383
sub5_SCONF                                       1.591377   0.512352
sub4_CARBHB12                                    1.364792   1.632408
sub5_BUT14DIOL                                   0.783503   0.645099
sub4_PNICO23                                     0.717968   0.776429
sub4_RG18                                        0.503217   0.230018
sub2_C60ISO                                      0.000000   0.000000
sub3_INV24                                       5.668748   2.796356
sub4_HEAVY28                                     0.000000   0.000000
sub2_ISOL24                                      4.843230   5.690557
sub4_WATER27                                     4.210310  13.619146
sub5_UPU23                                       0.000000   0.000000

data_path                 ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ  \
Type            Processed                                           AI AE
sub2_MB16_43      43 / 43                                       15.909280
sub5_IDISP          5 / 6                                       13.337525
sub1_ALKBDE10       9 / 9                                       10.401011
sub1_DC13         13 / 13                                        8.769018
sub2_DARC         14 / 14                                        8.461810
sub1_YBDE18       18 / 18                                        8.128445
sub3_PX13         13 / 13                                        7.171943
sub1_AL2X6          6 / 6                                        6.683938
sub1_ALK8           8 / 8                                        5.330166
sub1_RC21         21 / 21                                        5.258815
sub1_SIE4x4       16 / 16                                        4.526972
sub1_NBPRC        12 / 12                                        4.266559
sub1_HEAVYSB11      7 / 7                                        4.230302
sub4_ADIM6          6 / 6                                        4.186318
sub3_BH76         76 / 76                                        4.142984
sub3_WCPT18       18 / 18                                        4.076216
sub1_DIPCS10      10 / 10                                        3.959661
sub3_BHDIV10      10 / 10                                        3.670803
sub1_G2RC         25 / 25                                        3.605386
sub1_PA26         26 / 26                                        3.603806
sub4_CHB6           4 / 4                                        3.579273
sub5_PCONF21      10 / 18                                        3.485001
sub4_S22          22 / 22                                        3.143330
sub1_FH51         51 / 51                                        3.129089
sub4_AHB21        21 / 21                                        3.116596
sub1_W4_11      140 / 140                                        2.977996
sub2_ISO34        34 / 34                                        2.869448
sub2_BSR36        36 / 36                                        2.745238
sub2_RSE43        43 / 43                                        2.741250
sub4_S66          66 / 66                                        2.658246
sub4_HAL59        29 / 29                                        2.587716
sub3_BHPERI       26 / 26                                        2.410479
sub1_TAUT15       15 / 15                                        2.322749
sub4_IL16         16 / 16                                        2.246179
sub2_CDIE20       20 / 20                                        2.104062
sub1_G21EA        25 / 25                                        2.009397
sub2_PArel        20 / 20                                        1.904611
sub1_G21IP        36 / 36                                        1.840062
sub5_ACONF        15 / 15                                        1.801305
sub5_ICONF        17 / 17                                        1.737822
sub5_Amino20x4    80 / 80                                        1.642470
sub3_BHROT27      27 / 27                                        1.458525
sub5_MCONF        51 / 51                                        1.437692
sub1_BH76RC       30 / 30                                        1.125349
sub5_SCONF        17 / 17                                        0.984123
sub4_CARBHB12     12 / 12                                        0.973519
sub5_BUT14DIOL    64 / 64                                        0.858951
sub4_PNICO23      23 / 23                                        0.714591
sub4_RG18         18 / 18                                        0.315151
sub2_C60ISO         0 / 9                                        0.000000
sub3_INV24        22 / 24                                        0.000000
sub4_HEAVY28        0 / 0                                        0.000000
sub2_ISOL24       12 / 24                                        0.000000
sub4_WATER27      25 / 27                                        0.000000
sub5_UPU23         0 / 23                                        0.000000

data_path                             \
Type               DFT AE  Processed
sub2_MB16_43    15.461608    43 / 43
sub5_IDISP      13.125478      6 / 6
sub1_ALKBDE10   18.125250      9 / 9
sub1_DC13       13.090863    13 / 13
sub2_DARC       10.754152    14 / 14
sub1_YBDE18      8.145395    18 / 18
sub3_PX13       11.042025    13 / 13
sub1_AL2X6       5.659146      6 / 6
sub1_ALK8        4.400063      8 / 8
sub1_RC21        4.820927    21 / 21
sub1_SIE4x4     21.908521    16 / 16
sub1_NBPRC       2.232550    12 / 12
sub1_HEAVYSB11   5.391477      7 / 7
sub4_ADIM6       3.059030      6 / 6
sub3_BH76        9.107948    76 / 76
sub3_WCPT18      7.967153    18 / 18
sub1_DIPCS10    12.310855    10 / 10
sub3_BHDIV10     6.277708    10 / 10
sub1_G2RC        5.917204    25 / 25
sub1_PA26        2.200767    26 / 26
sub4_CHB6        1.805320      4 / 4
sub5_PCONF21     3.214782    18 / 18
sub4_S22         2.291253    22 / 22
sub1_FH51        3.703658    51 / 51
sub4_AHB21       2.453821    21 / 21
sub1_W4_11      29.506869  140 / 140
sub2_ISO34       2.001744    34 / 34
sub2_BSR36       8.401182    36 / 36
sub2_RSE43       3.157601    43 / 43
sub4_S66         1.894710    66 / 66
sub4_HAL59       1.649787    29 / 29
sub3_BHPERI      3.268993    26 / 26
sub1_TAUT15      2.164531    15 / 15
sub4_IL16        1.021067    16 / 16
sub2_CDIE20      1.599507    20 / 20
sub1_G21EA       9.754524    25 / 25
sub2_PArel       1.743933    20 / 20
sub1_G21IP       8.953336    36 / 36
sub5_ACONF       0.546621    15 / 15
sub5_ICONF       0.413804    17 / 17
sub5_Amino20x4   0.656235    80 / 80
sub3_BHROT27     0.853379    27 / 27
sub5_MCONF       1.956021    51 / 51
sub1_BH76RC     80.220383    30 / 30
sub5_SCONF       0.512352    17 / 17
sub4_CARBHB12    1.632408    12 / 12
sub5_BUT14DIOL   0.645099    64 / 64
sub4_PNICO23     0.776429    23 / 23
sub4_RG18        0.230018    18 / 18
sub2_C60ISO      0.000000      0 / 9
sub3_INV24       0.000000     0 / 24
sub4_HEAVY28     0.000000      0 / 0
sub2_ISOL24      0.000000     0 / 24
sub4_WATER27     0.000000     0 / 27
sub5_UPU23       0.000000     0 / 23

data_path      ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ
Type                                                AI AE     DFT AE Processed
sub2_MB16_43                                     0.000000   0.000000    0 / 43
sub5_IDISP                                       0.000000   0.000000     0 / 6
sub1_ALKBDE10                                    0.000000   0.000000     0 / 9
sub1_DC13                                        0.000000   0.000000    0 / 13
sub2_DARC                                        0.000000   0.000000    0 / 14
sub1_YBDE18                                      0.000000   0.000000    0 / 18
sub3_PX13                                        0.000000   0.000000    0 / 13
sub1_AL2X6                                       0.000000   0.000000     0 / 6
sub1_ALK8                                        0.000000   0.000000     0 / 8
sub1_RC21                                        0.000000   0.000000    0 / 21
sub1_SIE4x4                                      0.000000   0.000000    0 / 16
sub1_NBPRC                                       0.000000   0.000000    0 / 12
sub1_HEAVYSB11                                   0.000000   0.000000     0 / 7
sub4_ADIM6                                       0.000000   0.000000     0 / 6
sub3_BH76                                        0.000000   0.000000    0 / 76
sub3_WCPT18                                      0.000000   0.000000    0 / 18
sub1_DIPCS10                                     0.000000   0.000000    0 / 10
sub3_BHDIV10                                     0.000000   0.000000    0 / 10
sub1_G2RC                                        0.000000   0.000000    0 / 25
sub1_PA26                                        0.000000   0.000000    0 / 26
sub4_CHB6                                        0.000000   0.000000     0 / 4
sub5_PCONF21                                     0.000000   0.000000    0 / 18
sub4_S22                                         0.000000   0.000000    0 / 22
sub1_FH51                                        0.000000   0.000000    0 / 51
sub4_AHB21                                       0.000000   0.000000    0 / 21
sub1_W4_11                                       2.700498  24.176867  91 / 140
sub2_ISO34                                       0.000000   0.000000    0 / 34
sub2_BSR36                                       0.000000   0.000000    0 / 36
sub2_RSE43                                       0.000000   0.000000    0 / 43
sub4_S66                                         0.000000   0.000000    0 / 66
sub4_HAL59                                       0.000000   0.000000    0 / 29
sub3_BHPERI                                      0.000000   0.000000    0 / 26
sub1_TAUT15                                      0.000000   0.000000    0 / 15
sub4_IL16                                        0.000000   0.000000    0 / 16
sub2_CDIE20                                      0.000000   0.000000    0 / 20
sub1_G21EA                                       0.000000   0.000000    0 / 25
sub2_PArel                                       0.000000   0.000000    0 / 20
sub1_G21IP                                       0.000000   0.000000    0 / 36
sub5_ACONF                                       0.000000   0.000000    0 / 15
sub5_ICONF                                       0.000000   0.000000    0 / 17
sub5_Amino20x4                                   0.000000   0.000000    0 / 80
sub3_BHROT27                                     0.000000   0.000000    0 / 27
sub5_MCONF                                       0.000000   0.000000    0 / 51
sub1_BH76RC                                      0.000000   0.000000    0 / 30
sub5_SCONF                                       0.000000   0.000000    0 / 17
sub4_CARBHB12                                    0.000000   0.000000    0 / 12
sub5_BUT14DIOL                                   0.000000   0.000000    0 / 64
sub4_PNICO23                                     0.000000   0.000000    0 / 23
sub4_RG18                                        0.000000   0.000000    0 / 18
sub2_C60ISO                                      0.000000   0.000000     0 / 9
sub3_INV24                                       0.000000   0.000000    0 / 24
sub4_HEAVY28                                     0.000000   0.000000     0 / 0
sub2_ISOL24                                      0.000000   0.000000    0 / 24
sub4_WATER27                                     0.000000   0.000000    0 / 27
sub5_UPU23                                       0.000000   0.000000    0 / 23

In [ ]:
Error_molecule = [
    "G21IP-IP_80_cc-pVDZ_0-1_1_0.0000_default",
    "G21EA-EA_23n_cc-pVDZ_0-1_1_0.0000_default",
    "BH76-RKT15_cc-pVDZ_0-1_1_0.0000_default",
]
print(len(Error_molecule))

# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

str_print = ''
for molecule in Error_molecule:
    str_print += molecule.split("_cc-pVDZ_")[0] + " "
print(str_print)

3
G21IP-IP_80 G21EA-EA_23n BH76-RKT15