In [1]:
from pathlib import Path

import pandas as pd

!noglob scp -r hkqai:~/workspace/cc2cc_test5/validate/*.csv ~/workspace/2025.1/validate
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

# for data_path in list(Path("../validate").glob(f"*test*.csv")):
#     data_path.unlink()

ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7643     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5234   120.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   24KB 547.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4881     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7256   169.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7641   179.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   39KB 888.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB   8.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8165     4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB 580.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB 386.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB   7.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB  12.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB   8.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB   7.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5679     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9176     5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   7.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8591     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   34KB 802.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB 493.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   29KB 687.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB 463.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB  11.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2286    26.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6092     3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5592     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   18KB  10.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB 457.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB  13.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB 534.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   20KB   7.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8889     4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB 488.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   4.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8457     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   27KB  12.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB   8.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 243.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB 814.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   77KB   1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7506   173.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9625   224.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 229.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   62KB   1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 281.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB 270.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   6.3MB/s   00:00

In [11]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 1
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    # full_subset_dict = json.load(f)["full_subset_dict"]
    full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099
        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
            }

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = f"{i_subset}-{systems_list[i]}"
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)
for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}
        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []
        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        np.sum(data_subset[name_subset][f"ai{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        np.sum(data_subset[name_subset][f"dft{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if len(data_subset[name_subset]["ai"]) == len(
                data_subset[name_subset]["name"]
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.mean(wtmad_1_ai[d3_name])
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.mean(wtmad_1_dft[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.sum(wtmad_2_ai[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.sum(wtmad_2_dft[d3_name])
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(mean_absolute_deviation_list)
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            )

print("Summary")
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)

print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
# save summary to excel with date
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")

cc-pVDZ
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-01 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-02 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-03 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-04 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-05 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-06 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-07 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-08 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-09 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-10 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-11 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-12 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-13 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-14 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-15 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-16 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-17 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-18 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-19 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-20 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-21 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-22 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-23 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-24 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-25 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-26 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-27 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-28 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-29 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-30 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-31 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-32 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-33 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-34 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-35 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-36 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-37 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-38 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-39 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-40 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-41 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-42 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: MB16_43-43 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h1 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h2 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h3 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h4 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h5 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h6 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h7 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h8 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h9 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h10 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h11 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h12 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h13 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h14 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-h15 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r1 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r2 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r3 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r4 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r5 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r6 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r7 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r8 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r9 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r10 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r11 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r12 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r13 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r14 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r15 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r16 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-c1 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-c2 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-c3 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-c4 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-c5 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-04 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-05 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-06 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-07 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-09 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-10 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-11 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-12 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-13 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-14 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-15 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-16 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-17 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-18 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-19 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-20 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-21 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: S22-22 not found in ccdft_cc-pVDZ_atom-1-3048068_gmtkn-cc-pVDZ data file
Warning: BSR36-r15 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: BSR36-r16 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: BSR36-c2 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: BSR36-c3 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: BSR36-c4 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: BSR36-c5 not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xao not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-4167404_gmtkn-cc-pVDZ data file
Summary
MAE

data_path   3048068                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       1.770511  28.576993  2.756097  30.229942   1.89645  28.932474

data_path             4167404                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
test          0 / 5  3.743915  17.694252  7.443495  21.144715  4.767951

data_path
Disp type DFT_D3ZERO Processed
test       18.539155     3 / 5

wtmad_1

data_path   3048068                                                     \
Disp type        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       1.438707  2.074116  2.094125  2.649053  2.056311   2.588717

data_path              4167404                                          \
Disp type Processed         AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO
test          0 / 5  12.591959  8.172932  8.935446  7.802403   8.87129

data_path
Disp type DFT_D3ZERO Processed
test        7.346482     3 / 5

wtmad_2

data_path   3048068                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       4.047817  28.844593  6.050114  31.298054  5.224827  30.046818

data_path             4167404                                              \
Disp type Processed        AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO
test          0 / 5  45.89819  38.449292  32.180767  29.030255  33.648891

data_path
Disp type DFT_D3ZERO Processed
test       28.918611     3 / 5

Summary of Subset
MAE

data_path   3048068                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
W4_11      1.743675  29.364481  2.722719  31.036719  1.837964  29.701545
MB16_43           0          0         0          0         0          0
BSR36             0          0         0          0         0          0
Amino20x4         0          0         0          0         0          0
S22        2.703046   1.211784  3.915978   2.194433  3.928825    2.20728

data_path               4167404                                              \
Disp type  Processed         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO
W4_11      139 / 140   0.735959  29.506863   1.861904  31.211753   0.835434
MB16_43       0 / 43  12.389747  15.461604  38.343377  36.862998  22.864719
BSR36         0 / 36    9.38645     6.5349   3.457072   0.742062   4.843185
Amino20x4     0 / 80    1.40477   0.692039   1.376662    0.74332   1.374922
S22           4 / 22   3.821307   2.291252   2.343301   2.402928   2.339402

data_path
Disp type DFT_D3ZERO  Processed
W4_11      29.861055  140 / 140
MB16_43    23.165472    43 / 43
BSR36       1.991635    30 / 36
Amino20x4   0.652054    52 / 80
S22         2.291758    22 / 22

In [9]:
5.788692 - 6.125946

-0.3372539999999997

In [5]:
1 / np.mean(data_subset["713074_W4_11"]["cc"])

np.float64(0.0037447095387112004)

In [7]:
wtmad_2_dft[""]

array([1.39803383e-02, 3.60800128e-02, 1.21320751e-02, 5.40368290e-02,
       5.50718156e-02, 1.05093790e-02, 3.84579895e-02, 2.46518927e-02,
       9.74755683e-02, 6.09160383e-02, 7.21057620e-02, 1.15806071e-01,
       7.51926702e-02, 7.50734834e-02, 1.29402160e-01, 1.84606613e-01,
       4.03139859e-02, 2.75289943e-02, 3.99316539e-02, 2.73618113e-02,
       1.56071816e-01, 1.50246608e-01, 9.61089027e-02, 1.78368294e-01,
       8.78263809e-02, 1.71231509e-01, 1.43295110e-01, 1.18902914e-01,
       1.13633624e-01, 1.53270176e-02, 7.38478763e-02, 4.64227782e-02,
       1.52771925e-01, 1.02643183e-01, 4.36767787e-02, 1.67079052e-02,
       1.12213586e-01, 3.02777959e-02, 1.64972020e-01, 1.61582051e-01,
       1.78014954e-01, 1.30489350e-01, 1.20010881e-01, 1.49500597e-01,
       1.65375294e-01, 1.19778349e-01, 9.83327754e-02, 1.08281266e-01,
       9.88923887e-02, 1.71696050e-01, 1.34499309e-01, 4.25771024e-02,
       2.06480236e-01, 1.02314753e-01, 9.73765560e-02, 1.25757849e-01,
       4.68979410e-02, 5.67447968e-02, 9.41539662e-02, 4.35707143e-02,
       9.52127392e-02, 2.47086337e-02, 1.61361632e-01, 5.87144212e-02,
       1.47178231e-01, 1.35126853e-01, 1.88523709e-01, 1.26455843e-01,
       1.04700541e-01, 1.60239502e-01, 1.32762578e-01, 1.08466904e-01,
       1.10296043e-01, 7.90197415e-02, 9.40749231e-02, 5.82561641e-02,
       1.61471921e-01, 1.49979711e-01, 1.59792898e-01, 1.00140796e-01,
       1.47340129e-01, 1.81217696e-01, 1.48079425e-01, 1.01545010e-01,
       1.31269629e-01, 1.62866772e-01, 1.52851341e-01, 6.49862753e-02,
       8.23745770e-02, 7.03662074e-02, 2.20138895e-01, 1.08675664e-01,
       1.46095165e-01, 1.29380975e-01, 7.03334270e-02, 1.20069763e-01,
       1.02779965e-01, 2.00721377e-01, 1.63831029e-01, 1.10925907e-01,
       8.25335480e-02, 1.78030456e-01, 1.78091589e-01, 1.24943677e-01,
       2.42762466e-01, 5.86276053e-02, 9.66661496e-02, 1.83145383e-01,
       8.16802433e-02, 9.45776624e-02, 1.34690766e-01, 1.00662750e-01,
       8.36642320e-02, 2.02549655e-01, 1.74258358e-01, 7.48645707e-02,
       2.43178354e-01, 4.01082924e-02, 9.17873500e-02, 5.84744121e-02,
       1.75002295e-01, 1.39979831e-01, 1.03378937e-01, 5.24810344e-02,
       1.91200167e-01, 7.30153671e-02, 1.33895653e-01, 9.68640041e-02,
       1.98653281e-01, 8.06540639e-02, 8.72201806e-03, 1.58948191e-01,
       1.29297402e-01, 3.21231947e-02, 1.61267497e-01, 1.52987789e-01,
       2.08246639e-01, 1.66299042e-01, 6.82022083e-02, 2.28907554e-02,
       5.38457828e-03, 7.27331440e-02, 7.74755704e-02, 8.30387343e-04,
       9.58387721e-02, 1.92834972e-02, 6.20447966e-04, 3.94640393e-03,
       8.46094372e-03, 9.78416499e-03, 1.98487513e-02, 6.79521933e-02,
       1.14858992e-01, 3.23441859e-02, 5.61864464e-02, 7.87578078e-02,
       3.01615401e-03, 1.04534786e-02, 2.62461593e-02, 1.14500234e-01,
       1.25678706e-01, 2.77965198e-02, 1.73387110e-02, 3.01598356e-02,
       9.80479498e-03, 6.32827435e-03, 3.52821979e-02, 5.06343061e-02,
       4.74401008e-02, 4.09311247e-02, 7.10210951e-03, 1.82212599e-02,
       3.11073592e-02, 4.67280894e-03, 2.58676495e-02, 2.64686004e-02,
       7.48751971e-03, 1.22630214e-01, 5.80825452e-03, 5.35611652e-02,
       4.39909473e-02, 3.15526875e-02, 5.81183903e-02, 3.98258803e-01,
       2.99547296e-01, 4.73746702e-01, 3.13050582e-01, 2.09880695e-01,
       2.66976887e-01, 4.68274326e-01, 3.60769098e-01, 5.47041577e-01,
       4.89562381e-01, 6.56670759e-01, 6.05614087e-01, 3.79061022e-01,
       3.94013590e-01, 9.57079330e-01, 1.67353484e-01, 2.71725809e-01,
       2.75772910e-01, 4.03051013e-01, 5.37862923e-01, 3.87605194e-01,
       4.69710264e-01, 4.09799333e-01, 3.88149372e-01, 8.71392190e-01,
       8.09651483e-01, 7.00110376e-01, 7.50494670e-01, 8.12729961e-01,
       9.57872072e-01, 7.38241953e-01, 9.34719442e-01, 1.42906678e+00,
       1.44257763e+00, 1.92047764e+00, 1.65757300e+00, 5.45841196e-02,
       2.90202376e-01, 4.32969309e-01, 5.91823303e-01, 5.95073440e-03,
       4.01808285e-01, 6.02716562e-02, 9.04039647e-01, 9.46795913e-02,
       1.05223464e-01, 6.38643154e-02, 5.72110417e-01, 4.47230091e-02,
       2.96072954e-01, 3.19034653e-01, 3.64121636e-01, 2.49123844e-01,
       2.45104478e-01, 1.80073880e-01, 4.16747284e-01, 9.61513720e-02,
       2.47012179e-01, 4.08911484e-01, 2.29873072e-01, 3.92364915e-02,
       9.14995943e-02, 6.48572642e-02, 9.75420525e-01, 1.25805358e-01,
       8.34463658e-02, 1.24056836e-01, 2.10614309e-01, 1.56875422e-01,
       1.17676822e-01, 8.16883439e-01, 5.74691294e-01, 3.16765602e-01,
       4.49125958e-01, 9.30310686e-02, 2.74404603e-01, 3.45704295e-02,
       1.69214759e-01, 1.20149540e-01, 7.29796209e-02, 7.11136595e-02,
       1.88143888e-03, 1.35589293e-01, 3.15375713e-01, 6.85696963e-01,
       2.89584313e-01, 1.84864254e-01, 3.04569355e-01, 4.18028291e-01,
       1.14791393e-01, 1.75596018e-01, 2.98665026e-01, 1.72258552e-01,
       5.10098938e-01, 4.43720554e-01, 4.59556339e-01, 3.30663371e-02,
       1.04726139e-01, 3.10991418e-02, 5.10500370e-01, 4.73018488e-01,
       3.00006166e-01, 6.38104404e-01, 4.67204601e-01, 4.76959742e-01,
       3.89717646e-01, 7.73116329e-01, 1.93978381e-01, 4.72739817e-02,
       3.46698611e-01, 1.32133183e-01, 8.15631004e-02, 2.48743489e-01,
       1.63482459e-01, 1.67486668e-01, 1.10858305e-01, 7.49383906e-02,
       1.63658511e-01, 3.51992333e-01, 1.96119675e-01, 9.80484561e-02,
       3.52326490e-02, 4.12530845e-02, 6.20088503e-02, 1.17389156e-01,
       2.03642787e-01, 5.49670658e-01, 5.74206028e-01, 7.39619019e-01,
       8.23554924e-01, 1.20423973e+00, 3.15491232e-02, 1.02391275e-01,
       1.66119171e-01, 1.98666560e-01, 3.45524005e-01, 4.39604605e-01,
       2.67231800e-01])