In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

ccdft_cc-pVDZ_atom-1-1055975_gmtkn.csv        100%  425KB   9.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   40KB 892.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5696   121.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB   3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB   2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3070   540.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  12.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   32KB   7.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5199   998.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4487     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   15KB   3.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4017     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   11KB   2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3155    64.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   11KB   2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6327     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 2478    24.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4596   978.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3750   810.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8717     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   18KB 365.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   10KB   1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   19KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5315     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6544     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   12KB   2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4729     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   18KB 384.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8116   172.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 7661     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB 281.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6643   142.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB   2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3702   778.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4337   941.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5081   110.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8961     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6317     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6042     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5442   121.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   12KB   2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 2676   577.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1180   477.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 7829     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB 310.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   10KB   1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1829    39.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5867     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3965   837.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   12KB   2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4055   761.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB   2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1361    13.7KB/s   00:00

In [2]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "sub1": [
    #     "W4_11",
    #     "G21EA",
    #     "G21IP",
    #     "DIPCS10",
    #     "PA26",
    #     "SIE4x4",
    #     "ALKBDE10",
    #     "YBDE18",
    #     "AL2X6",
    #     "HEAVYSB11",
    #     "NBPRC",
    #     "ALK8",
    #     "RC21",
    #     "G2RC",
    #     "BH76RC",
    #     "FH51",
    #     "TAUT15",
    #     "DC13",
    # ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    # "sub3": [
    #     "BH76",
    #     "BHPERI",
    #     "BHDIV10",
    #     "INV24",
    #     "BHROT27",
    #     "PX13",
    #     "WCPT18",
    # ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"====DFT error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in dft_error_argsort
                    ]
                )
                print(data_name[dft_error_argsort], data_reaction_energy_dft[dft_error_argsort])
                if verbose == 2:
                    print(f"====Detail of DFT error of {i_subset}====")
                    for i in dft_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_dft_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_name[ai_error_argsort], data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=(data_path.stem, "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
    # key=lambda x: float(x),
)
display(df_summary)

cc-pVDZ
====DFT error of MB16_43====
[['21', 'H2', 'BH3', 'O2', 'NaH', 'MgH2', 'AlH3', 'Cl2'], ['38', 'H2', 'BH3', 'CH4', 'N2', 'F2', 'AlH3', 'SiH4', 'P2', 'S2'], ['13', 'H2', 'CH4', 'N2', 'O2', 'MgH2', 'S2'], ['20', 'H2', 'BH3', 'CH4', 'N2', 'F2', 'P2'], ['05', 'H2', 'BH3', 'N2', 'SiH4', 'P2', 'Cl2']]
['20' '37' '12' '19' '4'] [ 50.74830276 -49.51734029 -46.37936763 -46.23450334 -38.69911767]
====Detail of DFT error of MB16_43====
20: 50.74830276081934
2054.973651549404 -2 21
6.218761884145894 -7 H2
63.2453762140842 2 BH3
222.49272884261703 2 O2
280.43262754209366 2 NaH
290.00884331335385 4 MgH2
300.9012645427689 4 AlH3
708.2450424265678 1 Cl2

37: -49.51734028983981
2012.297228404964 -2 38
6.218761884145894 -12 H2
63.2453762140842 2 BH3
81.52465968389048 2 CH4
166.87041545877966 2 N2
264.2986884069901 1 F2
300.9012645427689 2 AlH3
314.0907717625162 4 SiH4
630.9192426099338 1 P2
673.0378092638043 1 S2

12: -46.379367634723394
1689.9723108121125 -2 13
6.218761884145894 -5 H2
81.52465968389048 4 CH4
166.87041545877966 4 N2
222.49272884261703 2 O2
290.00884331335385 2 MgH2
673.0378092638043 2 S2

19: -46.2345033377552
1088.3282344868455 -2 20
6.218761884145894 -11 H2
63.2453762140842 6 BH3
81.52465968389048 4 CH4
166.87041545877966 2 N2
264.2986884069901 2 F2
630.9192426099338 1 P2

4: -38.69911766645032
2230.3249811475494 -2 05
6.218761884145894 -4 H2
63.2453762140842 4 BH3
166.87041545877966 2 N2
314.0907717625162 2 SiH4
630.9192426099338 4 P2
708.2450424265678 1 Cl2

====AI error of MB16_43====
[['21', 'H2', 'BH3', 'O2', 'NaH', 'MgH2', 'AlH3', 'Cl2'], ['03', 'H2', 'LiH', 'CH4', 'O2', 'F2', 'NaH', 'MgH2', 'AlH3', 'S2'], ['43', 'H2', 'BH3', 'N2', 'O2', 'F2', 'AlH3', 'SiH4'], ['34', 'H2', 'BH3', 'CH4', 'N2', 'O2', 'F2', 'MgH2', 'AlH3', 'SiH4', 'P2'], ['16', 'H2', 'LiH', 'BH3', 'O2', 'MgH2', 'AlH3', 'SiH4']]
['20' '2' '42' '33' '15'] [93.80518748 72.20981884 66.4641655  62.05327556 61.5438159 ]
====Detail of AI error of MB16_43====
20: 93.80518748267212
-46.97744668248545 -2 21
-0.3089214969008822 -7 H2
-0.5560311224254278 2 BH3
-0.4116551993015555 2 O2
-0.1448821778978503 2 NaH
-0.1343181900143277 4 MgH2
0.3135409938023858 4 AlH3
-0.8039105765075009 1 Cl2

2: 72.20981884209435
-36.77643281836831 -2 03
-0.3089214969008822 -13 H2
0.2559283190272819 2 LiH
-0.5629231912711424 6 CH4
-0.4116551993015555 1 O2
-1.1955073218572283 1 F2
-0.1448821778978503 2 NaH
-0.1343181900143277 2 MgH2
0.3135409938023858 2 AlH3
-0.9548624754031058 1 S2

42: 66.4641654990232
-38.66309042078039 -2 43
-0.3089214969008822 -7 H2
-0.5560311224254278 2 BH3
-3.076274238203668 3 N2
-0.4116551993015555 1 O2
-1.1955073218572283 1 F2
0.3135409938023858 2 AlH3
-0.4258750819569689 4 SiH4

33: 62.053275559861405
-33.060860431593376 -2 34
-0.3089214969008822 -10 H2
-0.5560311224254278 2 BH3
-0.5629231912711424 2 CH4
-3.076274238203668 1 N2
-0.4116551993015555 2 O2
-1.1955073218572283 1 F2
-0.1343181900143277 2 MgH2
0.3135409938023858 2 AlH3
-0.4258750819569689 2 SiH4
0.6686448700608006 1 P2

15: 61.543815898670864
-30.26199192681704 -2 16
-0.3089214969008822 -19 H2
0.2559283190272819 2 LiH
-0.5560311224254278 6 BH3
-0.4116551993015555 1 O2
-0.1343181900143277 4 MgH2
0.3135409938023858 2 AlH3
-0.4258750819569689 4 SiH4

====DFT error of DARC====
[['cpdiene', 'maleinNH', 'P10'], ['cpdiene', 'maleinNH', 'P10X'], ['cpdiene', 'malein', 'P9'], ['cpdiene', 'malein', 'P9X'], ['furane', 'maleinNH', 'P8']]
['12' '13' '10' '11' '8'] [-14.21318362 -13.98721878 -13.94186154 -13.76479675 -13.60858525]
====Detail of DFT error of DARC====
12: -14.21318362375223
367.1994865530211 -1 cpdiene
601.5884235077024 -1 maleinNH
954.5747264369712 1 P10

13: -13.987218777506428
367.1994865530211 -1 cpdiene
601.5884235077024 -1 maleinNH
954.800691283217 1 P10X

10: -13.941861541169942
367.1994865530211 -1 cpdiene
620.1525237747396 -1 malein
973.4101487865908 1 P9

11: -13.764796754077452
367.1994865530211 -1 cpdiene
620.1525237747396 -1 malein
973.5872135736832 1 P9X

8: -13.608585247850897
405.9629334897597 -1 furane
601.5884235077024 -1 maleinNH
993.9427717496112 1 P8

====AI error of DARC====
[['cpdiene', 'malein', 'P9'], ['cpdiene', 'maleinNH', 'P10'], ['cpdiene', 'maleinNH', 'P10X'], ['cpdiene', 'malein', 'P9X'], ['ethine', 'chdiene', 'P6']]
['10' '12' '13' '11' '5'] [-15.74783851 -15.59546472 -14.37525536 -14.25069059 -12.353537  ]
====Detail of AI error of DARC====
10: -15.747838506029575
-2.9569873360344663 -1 cpdiene
-3.7117418316230673 -1 malein
-22.41656767368711 1 P9

12: -15.59546472053447
-2.9569873360344663 -1 cpdiene
-8.047160415729508 -1 maleinNH
-26.599612472298443 1 P10

13: -14.375255361310227
-2.9569873360344663 -1 cpdiene
-8.047160415729508 -1 maleinNH
-25.3794031130742 1 P10X

11: -14.250690585568476
-2.9569873360344663 -1 cpdiene
-3.7117418316230673 -1 malein
-20.91941975322601 1 P9X

5: -12.35353699691244
-1.262339880504785 -1 ethine
-4.06656244418674 -1 chdiene
-17.682439321603965 1 P6

====DFT error of RSE43====
[['E42', 'P1', 'E1', 'P42'], ['E40', 'P1', 'E1', 'P40'], ['E3', 'P1', 'E1', 'P3'], ['E41', 'P1', 'E1', 'P41'], ['E43', 'P1', 'E1', 'P43']]
['39' '37' '1' '38' '40'] [8.1372315  7.84622863 7.56029787 7.17388453 4.63557261]
====Detail of DFT error of RSE43====
39: 8.137231498814572
463.6954805157215 -1 E42
77.31209761686782 -1 P1
81.54200451740334 1 E1
467.6028051140005 1 P42

37: 7.846228629823543
324.3753824788612 -1 E40
77.31209761686782 -1 P1
81.54200451740334 1 E1
327.9917042081492 1 P40

1: 7.560297865445932
304.7039474194225 -1 E3
77.31209761686782 -1 P1
81.54200451740334 1 E1
308.03433838433284 1 P3

38: 7.173884527549603
446.4003376481893 -1 E41
77.31209761686782 -1 P1
81.54200451740334 1 E1
449.34431527520337 1 P41

40: 4.6355726117929805
221.3042748671212 -1 E43
77.31209761686782 -1 P1
81.54200451740334 1 E1
221.70994057837868 1 P43

====AI error of RSE43====
[['E11', 'P1', 'E1', 'P11'], ['E2', 'P1', 'E1', 'P2'], ['E41', 'P1', 'E1', 'P41'], ['E5', 'P1', 'E1', 'P5'], ['E4', 'P1', 'E1', 'P4']]
['9' '0' '38' '3' '2'] [-3.10666653  3.09527281  3.07627681  2.34096088  2.26194411]
====Detail of AI error of RSE43====
9: -3.1066665264210647
-1.7861250234217645 -1 E11
-0.5129327621386256 -1 P1
-0.5192643069634425 1 E1
-4.886460005018012 1 P11

0: 3.095272810489337
-6.306516819524142 -1 E2
-0.5129327621386256 -1 P1
-0.5192643069634425 1 E1
-3.2049124642099875 1 P2

38: 3.076276811096937
-9.021618326578764 -1 E41
-0.5129327621386256 -1 P1
-0.5192643069634425 1 E1
-5.939009970657009 1 P41

3: 2.340960881221882
-8.377151301936584 -1 E5
-0.5129327621386256 -1 P1
-0.5192643069634425 1 E1
-6.029858875889884 1 P5

2: 2.261944108748286
-1.4784481923771282 -1 E4
-0.5129327621386256 -1 P1
-0.5192643069634425 1 E1
0.7898274611959746 1 P4

====DFT error of BSR36====
[['c2h6', 'c4', 'ch4'], ['c2h6', 'c5', 'ch4'], ['c2h6', 'c3', 'ch4'], ['c2h6', 'c2', 'ch4'], ['c2h6', 'r15', 'ch4']]
['34' '35' '33' '32' '29'] [25.08408521 21.65018825 18.84205233 18.6655821  12.51112964]
====Detail of DFT error of BSR36====
34: 25.084085205986185
156.6999648871464 16 c2h6
1013.8165849213684 -1 c4
81.57215378149932 -18 ch4

35: 21.650188253352326
156.6999648871464 18 c2h6
1004.361796522298 -1 c5
81.57215378149932 -22 ch4

33: 18.84205232718591
156.6999648871464 14 c2h6
869.8029955888741 -1 c3
81.57215378149932 -16 ch4

32: 18.665582104331634
156.6999648871464 14 c2h6
869.9794658117285 -1 c2
81.57215378149932 -16 ch4

29: 12.511129642566402
156.6999648871464 13 c2h6
882.5782609493463 -1 r15
81.57215378149932 -14 ch4

====AI error of BSR36====
[['c2h6', 'c4', 'ch4'], ['c2h6', 'c5', 'ch4'], ['c2h6', 'h15', 'ch4'], ['c2h6', 'c3', 'ch4'], ['c2h6', 'c2', 'ch4']]
['34' '35' '14' '33' '32'] [38.56518557 28.23327787 25.94561637 23.87632726 22.04809387]
====Detail of AI error of BSR36====
34: 38.5651855705081
-1.03306276073154 16 c2h6
-44.31222120448834 -1 c4
-0.5989982520958 -18 ch4

35: 28.23327787161203
-1.03306276073154 18 c2h6
-33.65044601867215 -1 c5
-0.5989982520958 -22 ch4

14: 25.94561637156381
-1.03306276073154 7 c2h6
-29.583066184109786 -1 h15
-0.5989982520958 -6 ch4

33: 23.876327258002096
-1.03306276073154 14 c2h6
-28.755233874710854 -1 c3
-0.5989982520958 -16 ch4

32: 22.048093866639093
-1.03306276073154 14 c2h6
-26.92700048334785 -1 c2
-0.5989982520958 -16 ch4

====DFT error of CDIE20====
[['R25', 'P25'], ['R26', 'P26'], ['R20', 'P20'], ['R60', 'P60'], ['R47', 'P47']]
['3' '4' '0' '19' '12'] [-2.42889567 -2.41749781 -2.27417351 -2.2447105  -2.10187539]
====Detail of DFT error of CDIE20====
3: -2.4288956675535474
444.607133777341 -1 R25
442.17823810978746 1 P25

4: -2.4174978136496748
446.0424450622247 -1 R26
443.62494724857504 1 P26

0: -2.274173511308902
370.5105629448718 -1 R20
368.2363894335629 1 P20

19: -2.2447104962135427
516.9177489809351 -1 R60
514.6730384847216 1 P60

12: -2.1018753909557972
518.1394414015928 -1 R47
516.037566010637 1 P47

====AI error of CDIE20====
[['R25', 'P25'], ['R26', 'P26'], ['R20', 'P20'], ['R48', 'P48'], ['R29', 'P25']]
['3' '4' '0' '13' '6'] [-6.71213052 -4.17624564 -3.69684269 -3.41390016 -3.22706073]
====Detail of AI error of CDIE20====
3: -6.712130517145241
-2.3979784679860363 -1 R25
-9.110108985131276 1 P25

4: -4.176245639098904
-2.76936889809284 -1 R26
-6.945614537191744 1 P26

0: -3.6968426863104256
-1.3503815032882314 -1 R20
-5.047224189598657 1 P20

13: -3.4139001575554233
-3.99460292121466 -1 R48
-7.408503078770083 1 P48

6: -3.2270607315588125
-5.883048253572464 -1 R29
-9.110108985131276 1 P25

====DFT error of ISO34====
[['E12', 'P12'], ['E11', 'P11'], ['E27', 'P27'], ['E13', 'P13'], ['E1', 'P1']]
['11' '10' '26' '12' '0'] [-11.2169155    7.91291537   6.22878425  -4.05466059   3.57681375]
====Detail of DFT error of ISO34====
11: -11.216915501449478
516.1188455571506 -1 E12
504.90193005570114 1 P12

10: 7.9129153730788175
595.2850865539237 -1 E11
603.1980019270026 1 P11

26: 6.2287842502167905
376.9585968772074 -1 E27
383.1873811274242 1 P27

12: -4.054660589451714
587.2413887729657 -1 E13
583.186728183514 1 P13

0: 3.576813754778698
221.3037565914357 -1 E1
224.8805703462144 1 P1

====AI error of ISO34====
[['E11', 'P11'], ['E33', 'P33'], ['E12', 'P12'], ['E10', 'P10'], ['E29', 'P29']]
['10' '32' '11' '9' '28'] [23.29850581 -9.19418617 -7.61088177  6.62660717 -5.44693899]
====Detail of AI error of ISO34====
10: 23.298505808427933
-27.106656637524367 -1 E11
-3.808150829096435 1 P11

32: -9.194186169482125
-7.384674076314555 -1 E33
-16.57886024579668 1 P33

11: -7.610881768136671
-6.317911281980018 -1 E12
-13.928793050116688 1 P12

9: 6.6266071683717165
-7.528873549812666 -1 E10
-0.9022663814409504 1 P10

28: -5.4469389931516465
-2.1432234065065066 -1 E29
-7.590162399658153 1 P29

====DFT error of ISOL24====
[['i5e', 'i5p'], ['i11e', 'i11p'], ['i9e', 'i9p'], ['i10e', 'i10p'], ['i13e', 'i13p']]
['4' '10' '8' '9' '12'] [8.31528119 6.79709742 4.11937585 3.52665005 2.40183074]
====Detail of DFT error of ISOL24====
4: 8.315281187888104
1192.646420302077 -1 i5e
1200.9617014899652 1 i5p

10: 6.797097423235755
1564.9204642129755 -1 i11e
1571.7175616362113 1 i11p

8: 4.119375849665516
869.7107786464418 -1 i9e
873.8301544961073 1 i9p

9: 3.52665005447966
1135.0509209766094 -1 i10e
1138.577571031089 1 i10p

12: 2.4018307422243197
1059.4938689696633 -1 i13e
1061.8956997118876 1 i13p

====AI error of ISOL24====
[['i11e', 'i11p'], ['i13e', 'i13p'], ['i10e', 'i10p'], ['i20e', 'i20p'], ['i3e', 'i3p']]
['10' '12' '9' '19' '2'] [21.13776368 -5.62928379  4.76801703 -3.80228588 -3.64702256]
====Detail of AI error of ISOL24====
10: 21.13776368438605
-17.501930292796757 -1 i11e
3.635833391589294 1 i11p

12: -5.629283787913408
-11.367981085321084 -1 i13e
-16.997264873234492 1 i13p

9: 4.768017031353118
-38.41520773753438 -1 i10e
-33.64719070618126 1 i10p

19: -3.802285879810867
-18.948509055268367 -1 i20e
-22.750794935079234 1 i20p

2: -3.647022559164153
-18.232303420214464 -1 i3e
-21.879325979378617 1 i3p

====DFT error of C60ISO====
[]
[] []
====Detail of DFT error of C60ISO====
====AI error of C60ISO====
[]
[] []
====Detail of AI error of C60ISO====
====DFT error of PArel====
[['aminocoohbz2', 'aminocoohbz1'], ['aminocoohbz2', 'aminocoohbz3'], ['c2h2f41', 'c2h2f42'], ['his1', 'his2'], ['c2cl43', 'c2cl41']]
['12' '13' '17' '6' '19'] [-8.09393432 -5.50913372  3.50106207  3.3219515   2.30471472]
====Detail of DFT error of PArel====
12: -8.093934321815823
828.9539657043069 -1 aminocoohbz2
820.8600313824911 1 aminocoohbz1

13: -5.509133719834722
828.9539657043069 -1 aminocoohbz2
823.4448319844722 1 aminocoohbz3

17: 3.501062065599058
675.3172376271438 -1 c2h2f41
678.8182996927428 1 c2h2f42

6: 3.3219515028915794
929.660062674576 -1 his1
932.9820141774676 1 his2

19: 2.3047147200095424
1550.1771256782906 -1 c2cl43
1552.4818403983002 1 c2cl41

====AI error of PArel====
[['c2cl43', 'c2cl41'], ['c2cl43', 'c2cl42'], ['aminocoohbz2', 'aminocoohbz1'], ['c2h2f41', 'c2h2f42'], ['A0', 'A2']]
['19' '18' '12' '17' '1'] [-11.12100969 -10.53179863  -8.02832399  -5.24594489   5.06053341]
====Detail of AI error of PArel====
19: -11.121009694621424
1.3709639250573151 -1 c2cl43
-9.750045769564109 1 c2cl41

18: -10.531798625728666
1.3709639250573151 -1 c2cl43
-9.16083470067135 1 c2cl42

12: -8.028323993424722
-13.2355642309579 -1 aminocoohbz2
-21.263888224382622 1 aminocoohbz1

17: -5.245944888575268
-8.753398779809766 -1 c2h2f41
-13.999343668385034 1 c2h2f42

1: 5.060533411615914
-23.34748683511885 -1 A0
-18.286953423502936 1 A2

====DFT error of RG18====
[['bzAr', 'ar', 'bz'], ['hfNe', 'ne', 'hf'], ['ar4', 'ar'], ['kr3', 'kr'], ['c2h6Ne', 'ne', 'c2h6']]
['17' '9' '7' '5' '14'] [ 0.59759728 -0.56448348  0.55479119  0.44431117 -0.40259528]
====Detail of DFT error of RG18====
17: 0.5975972816734156
809.3139317604455 -1 bzAr
367.7509643653224 1 ar
442.1605646767965 1 bz

9: -0.5644834772769229
274.84579894286605 -1 hfNe
144.21807517546702 1 ne
130.0632402901221 1 hf

7: 0.554791192269704
1470.4490662690198 -1 ar4
367.7509643653224 4 ar

5: 0.4443111739160486
3085.665103684199 -1 kr3
1028.7031382860384 3 kr

14: -0.40259528293816516
301.29196576242265 -1 c2h6Ne
144.21807517546702 1 ne
156.67129530401746 1 c2h6

====AI error of RG18====
[['ar4', 'ar'], ['bzAr', 'ar', 'bz'], ['kr3', 'kr'], ['ar3', 'ar'], ['hfAr', 'ar', 'hf']]
['7' '17' '5' '4' '10'] [2.91146001 2.3191428  1.90989152 1.568388   1.55582788]
====Detail of AI error of RG18====
7: 2.9114600135585347
-4.40160716964828 -1 ar4
-0.3725367890224362 4 ar

17: 2.3191427953241988
-11.27941539063593 -1 bzAr
-0.3725367890224362 1 ar
-8.587735806289293 1 bz

5: 1.909891517888846
-3.9847274071413006 -1 kr3
-0.6916119630841515 3 kr

4: 1.5683879980602757
-2.6859983651275843 -1 ar3
-0.3725367890224362 3 ar

10: 1.5558278776729266
-2.980366678695763 -1 hfAr
-0.3725367890224362 1 ar
-1.0520020120004006 1 hf

====DFT error of ADIM6====
[['AM7', 'AD7'], ['AM6', 'AD6'], ['AM5', 'AD5'], ['AM4', 'AD4'], ['AM3', 'AD3']]
['5' '4' '3' '2' '1'] [5.37528715 4.25438788 3.38623613 2.54322247 1.75950106]
====Detail of DFT error of ADIM6====
5: 5.375287149525548
528.7183434287905 2 AM7
1052.0613997080554 -1 AD7

4: 4.254387877370618
454.3582153693281 2 AM6
904.4620428612856 -1 AD6

3: 3.3862361303091575
379.99855075958345 2 AM5
756.6108653888577 -1 AD5

2: 2.5432224740778793
305.6359848416942 2 AM4
608.7287472093105 -1 AD4

1: 1.7595010592282847
231.2039916149361 2 AM3
460.6484821706439 -1 AD3

====AI error of ADIM6====
[['AM7', 'AD7'], ['AM6', 'AD6'], ['AM5', 'AD5'], ['AM4', 'AD4'], ['AM3', 'AD3']]
['5' '4' '3' '2' '1'] [18.50110494 15.23808854 12.30253115  9.25629542  8.65768794]
====Detail of AI error of ADIM6====
5: 18.501104940676775
-1.9006769260290164 2 AM7
-22.302458792734807 -1 AD7

4: 15.238088538447299
-2.1177529843311307 2 AM6
-19.47359450710956 -1 AD6

3: 12.302531154693106
-0.8474005870072792 2 AM5
-13.997332328707664 -1 AD5

2: 9.256295424014635
-1.1938589962873998 2 AM4
-11.644013416589434 -1 AD4

1: 8.6576879406733
0.0620050486609763 2 AM3
-8.533677843351347 -1 AD3

====DFT error of S22====
[['15', '15a', '15b'], ['14', '14a', '14b'], ['13', '13a'], ['12', '12a'], ['11', '11a']]
['14' '13' '12' '11' '10'] [8.94442564 6.11690977 5.49348036 4.26488429 4.08264915]
====Detail of DFT error of S22====
14: 8.944425637614358
1576.8926125506748 -1 15
814.7733649462044 1 15a
771.0636732420847 1 15b

13: 6.116909767378843
1111.122990131243 -1 14
675.5300754171936 1 14a
441.7098244814281 1 14b

12: 5.493480362356422
1387.9099818332108 -1 13
696.7017310977836 2 13a

11: 4.264884294576973
941.964735798179 -1 12
473.114810046378 2 12a

10: 4.082649152624413
879.2830611049969 -1 11
441.6828551288107 2 11a

====AI error of S22====
[['15', '15a', '15b'], ['14', '14a', '14b'], ['13', '13a'], ['11', '11a'], ['12', '12a']]
['14' '13' '12' '10' '11'] [19.96850168 14.08278368 13.2839603  11.98981399  9.24548491]
====Detail of AI error of S22====
14: 19.968501680105586
-52.64008504123305 -1 15
-15.178753967081883 1 15a
-17.492829394045582 1 15b

13: 14.082783684267124
-28.51946315905316 -1 14
-9.18152122770532 1 14a
-5.255158247080717 1 14b

12: 13.283960302674338
-43.45858664565425 -1 13
-15.087313171489956 2 13a

10: 11.98981398866495
-21.84990366611918 -1 11
-4.930044838727114 2 11a

11: 9.245484912071916
-15.226712711495637 -1 12
-2.99061389971186 2 12a

====DFT error of S66====
[['26A', '26B', '26'], ['28A', '28B', '28'], ['29A', '29B', '29'], ['41A', '41B', '41'], ['42A', '42B', '42']]
['25' '27' '28' '40' '41'] [5.63393675 5.06790144 4.9297708  4.81334603 4.2679843 ]
====Detail of DFT error of S66====
25: 5.6339367508787745
696.7026088948976 1 26A
696.7026088907243 1 26B
1387.7712810347432 -1 26

27: 5.067901441202821
441.6591260713631 1 28A
696.725448265491 1 28B
1133.3166728956512 -1 28

28: 4.929770802896655
457.31769413123766 1 29A
696.7331299422117 1 29B
1149.1210532705527 -1 29

40: 4.813346026560112
696.7130656497571 1 41A
380.0829687450537 1 41B
1071.9826883682506 -1 41

41: 4.267984298512829
696.7075432114759 1 42A
373.481660442213 1 42B
1065.9212193551762 -1 42

====AI error of S66====
[['26A', '26B', '26'], ['34A', '34B', '34'], ['41A', '41B', '41'], ['46A', '46B', '46'], ['42A', '42B', '42']]
['25' '33' '40' '45' '41'] [13.56872129 13.36701241 12.81689621 12.17631312 10.79327809]
====Detail of AI error of S66====
25: 13.568721285532135
-15.085499498566012 1 26A
-15.085499483977069 1 26B
-43.73972026807522 -1 26

33: 13.367012405614634
-1.5757175174701006 1 34A
-1.5797521556931564 1 34B
-16.52248207877789 -1 34

40: 12.816896211501852
-16.210088607011702 1 41A
-3.5396767525402377 1 41B
-32.56666157105379 -1 41

45: 12.176313115951155
-9.5380648450952 1 46A
-3.4074048104625567 1 46B
-25.12178277150891 -1 46

41: 10.793278085958772
-14.77010698082261 1 42A
-2.3394911525457585 1 42B
-27.90287621932714 -1 42

====DFT error of HEAVY28====
[]
[] []
====Detail of DFT error of HEAVY28====
====AI error of HEAVY28====
[]
[] []
====Detail of AI error of HEAVY28====
====DFT error of WATER27====
[['H2O8d2d', 'H2O'], ['H2O8s4', 'H2O'], ['OHmH2O6', 'OHm', 'H2O'], ['H3OpH2O63d', 'H3Op', 'H2O'], ['OHmH2O5', 'OHm', 'H2O']]
['8' '9' '25' '17' '24'] [-18.92635784 -18.9219188  -17.34725245 -15.29872992 -14.58898984]
====Detail of DFT error of WATER27====
8: -18.926357841880417
924.2809724086004 -1 H2O8d2d
113.16932682084 8 H2O

9: -18.921918803959443
924.2765333706794 -1 H2O8s4
113.16932682084 8 H2O

25: -17.347252453316514
813.1023859955302 -1 OHmH2O6
116.73917261717372 1 OHm
113.16932682084 6 H2O

17: -15.298729921580843
805.3888463414146 -1 H3OpH2O63d
111.0741554947938 1 H3Op
113.16932682084 6 H2O

24: -14.588989837626286
697.174796559 -1 OHmH2O5
116.73917261717372 1 OHm
113.16932682084 5 H2O

====AI error of WATER27====
[['H3OpH2O62d', 'H3Op', 'H2O'], ['H3OpH2O63d', 'H3Op', 'H2O'], ['H2O8s4', 'H2O'], ['H2O8d2d', 'H2O'], ['H3OpH2O3', 'H3Op', 'H2O']]
['18' '17' '9' '8' '16'] [22.48916469 20.41028475 16.37654692 15.73191142 12.70683993]
====Detail of AI error of WATER27====
18: 22.48916468783256
-27.128835468569697 -1 H3OpH2O62d
-0.948529858322063 1 H3Op

data_path ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ
Type                                           AI AE    DFT AE  Processed
sub2                                       11.213308  6.492958  218 / 243
sub4                                        4.614012  2.500555  240 / 244
sub5                                        2.017724  0.795998  159 / 291

data_path ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ
Type                                           AI AE     DFT AE Processed
MB16_43                                    38.553422  15.461608   43 / 43
IDISP                                      30.686695  10.868136     3 / 6
ADIM6                                      11.521961   3.059030     6 / 6
BSR36                                      10.536909   8.401182   36 / 36
DARC                                        9.793607  10.754152   14 / 14
WATER27                                     9.153517  10.513091   23 / 27
S22                                         6.407366   2.291253   22 / 22
ISOL24                                      5.486039   3.363761    8 / 24
S66                                         5.447469   1.894710   66 / 66
IL16                                        4.160007   1.021067   16 / 16
CHB6                                        3.555860   1.805320     4 / 4
PNICO23                                     2.989591   0.776429   23 / 23
HAL59                                       2.952657   1.649787   29 / 29
PArel                                       2.773406   1.743933   20 / 20
AHB21                                       2.736677   2.453821   21 / 21
ISO34                                       2.591132   2.001744   34 / 34
ACONF                                       2.582958   0.546621   15 / 15
CDIE20                                      2.021447   1.599507   20 / 20
SCONF                                       1.773115   0.512352   17 / 17
ICONF                                       1.732491   0.413804   17 / 17
Amino20x4                                   1.466465   0.668115   43 / 80
CARBHB12                                    1.348897   1.632408   12 / 12
BUT14DIOL                                   1.052505   0.645099   64 / 64
RG18                                        1.020948   0.230018   18 / 18
RSE43                                       0.985602   3.157601   43 / 43
C60ISO                                      0.000000   0.000000     0 / 9
HEAVY28                                     0.000000   0.000000     0 / 0
PCONF21                                     0.000000   0.000000    0 / 18
MCONF                                       0.000000   0.000000    0 / 51
UPU23                                       0.000000   0.000000    0 / 23

In [ ]:
mol_name = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",     
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

mol_name = np.array(mol_name)

mol_name[[24, 48]]

array(['molecule_ISOL24', 'molecule_Amino20x4'], dtype='<U18')