In [1]:
from pathlib import Path

import pandas as pd

!noglob scp -r hkqai:~/workspace/cc2cc_test5/validate/*.csv ~/workspace/2025.1/validate
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

# for data_path in list(Path("../validate").glob(f"*test*.csv")):
#     data_path.unlink()

ccdft_cc-pVDZ_atom-1-543942_d3zero_gmtkn-cc-p 100%   90KB  18.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-543942_gmtkn-cc-pVDZ.csv 100%   90KB   1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3522    80.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2433    33.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 375.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2246    29.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3460    79.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3396    79.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   15KB   8.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB 364.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3972     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8163     4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7669     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7147     3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7222     3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2721     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4450     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6020   141.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4034     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   17KB   8.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9503     5.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   13KB   7.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8852     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   13KB   6.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 1067    24.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2830     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5225     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2203   136.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8995   394.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9812     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6723     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6717   155.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4133   519.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6166   917.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3850    90.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   13KB 311.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5678   127.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7612     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4852   110.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   17KB   6.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB 257.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   38KB   6.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3637     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3417    78.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5041     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   29KB 671.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5641   131.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5617     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5792     1.9MB/s   00:00
ccdft_cc-pVTZ_atom-1-543942_d3bj_gmtkn-cc-pVD 100%   49KB  11.9MB/s   00:00
ccdft_cc-pVTZ_atom-1-test_d3bj_gmtkn-cc-pVDZ. 100%   39KB 908.0KB/s   00:00

In [5]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 1
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

full_subset_dict = {
    "test": ["W4_11", "MB16_43", "BSR36", "Amino20x4", "S22"],
}
# full_subset_dict = {
#     "test": ["AHB21"],
#     "sub1": [
#         "W4_11",
#         "G21EA",
#         "G21IP",
#         "DIPCS10",
#         "PA26",
#         "SIE4x4",
#         "ALKBDE10",
#         "YBDE18",
#         "AL2X6",
#         "HEAVYSB11",
#         "NBPRC",
#         "ALK8",
#         "RC21",
#         "G2RC",
#         "BH76RC",
#         "FH51",
#         "TAUT15",
#         "DC13",
#     ],
#     "sub2": [
#         "MB16_43",
#         "DARC",
#         "RSE43",
#         "BSR36",
#         "CDIE20",
#         "ISO34",
#         "ISOL24",
#         "C60ISO",
#         "PArel",
#     ],
#     "sub3": [
#         "BH76",
#         "BHPERI",
#         "BHDIV10",
#         "INV24",
#         "BHROT27",
#         "PX13",
#         "WCPT18",
#     ],
#     "sub4": [
#         "RG18",
#         "ADIM6",
#         "S22",
#         "S66",
#         "HEAVY28",
#         "WATER27",
#         "CARBHB12",
#         "PNICO23",
#         "HAL59",
#         "AHB21",
#         "CHB6",
#         "IL16",
#     ],
#     "sub5": [
#         "IDISP",
#         "ICONF",
#         "ACONF",
#         "Amino20x4",
#         "PCONF21",
#         "MCONF",
#         "SCONF",
#         "UPU23",
#         "BUT14DIOL",
#     ],
# }

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy()
        data_d3bj = data["delta_d3bj"].to_numpy()
        data_d3zero = data["delta_d3zero"].to_numpy()

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        data_scf = data["scf_ene"].to_numpy()
        data_cc = data["cc_ene"].to_numpy()

        for i_subset in subset_list_:
            data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
            }

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = f"{i_subset}-{systems_list[i]}"
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

                    # # if verbose == 2:
                    # print(f"####data_path:{data_path}####")
                    # dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[
                    #     ::-1
                    # ]
                    # ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1]

                    # print(f"====Detail of AI error of {i_subset}====")
                    # for i in ai_error_argsort[:5]:
                    #     print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                    #     systems_list = json_data[f"reaction-{i_subset}"][data_name[i]][
                    #         "systems"
                    #     ]
                    #     stoichiometry_list = json_data[f"reaction-{i_subset}"][
                    #         data_name[i]
                    #     ]["stoichiometry"]
                    #     for j in range(len(systems_list)):
                    #         mole_name = (
                    #             f"{i_subset}-{systems_list[j]}"
                    #             if i_subset != "BH76RC"
                    #             else systems_list[j]
                    #         )

                    #         if mole_name in json_data:
                    #             if isinstance(json_data[mole_name], str):
                    #                 mole_name = json_data[mole_name]

                    #         col = data["name"] == mole_name
                    #         print(
                    #             data[col]["error_scf_ene"].values[0],
                    #             int(stoichiometry_list[j]),
                    #             systems_list[j],
                    #         )
                    #     print()


data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI AE",
            "DFT AE",
            "AI_D3BJ AE",
            "DFT_D3BJ AE",
            "AI_D3ZERO AE",
            "DFT_D3ZERO AE",
            "Processed",
        ],
    ],
    names=["data_path", "Type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)
for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}
        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []
        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI AE",
                    "DFT AE",
                    "AI_D3BJ AE",
                    "DFT_D3BJ AE",
                    "AI_D3ZERO AE",
                    "DFT_D3ZERO AE",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()} AE")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()} AE")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if len(data_subset[name_subset]["ai"]) == len(
                data_subset[name_subset]["name"]
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()} AE")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()} AE")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()} AE")
            ] = np.mean(wtmad_1_ai[d3_name])
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()} AE")
            ] = np.mean(wtmad_1_dft[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()} AE")
            ] = np.mean(wtmad_2_ai[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()} AE")
            ] = np.mean(wtmad_2_dft[d3_name])
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
    mean_absolute_deviation = np.mean(mean_absolute_deviation_list)
    for name_set, subset_list_ in full_subset_dict.items():
        wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()} AE")] = (
            mean_absolute_deviation
            * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()} AE")]
        )
        wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()} AE")] = (
            mean_absolute_deviation
            * wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()} AE")]
        )

print("Summary")
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)

print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# # save summary to csv with date
# df_summary.to_csv(f"../validate/summary_set_{date}.csv")

# header = pd.MultiIndex.from_product(
#     [
#         data_path_name_list,
#         ["AI AE", "DFT AE", "Processed"],
#     ],
#     names=["data_path", "Type"],
# )
# df_summary = pd.DataFrame(
#     summary_list,
#     index=subset_list,
# )
# df_summary.columns = header

# # df_summary.sort_values(
# #     by=("ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ", "AI AE"),
# #     axis=0,
# #     inplace=True,
# #     ascending=False,
# # )

# display(df_summary)

# # save summary to csv with date
# df_summary.to_csv(f"../validate/summary_subset_{date}.csv")
# # save summary to excel with date
# df_summary.to_excel(f"../validate/summary_subset_{date}.xlsx")

cc-pVDZ
Summary
MAE

data_path    713074                                                \
Type          AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE AI_D3ZERO AE
test       4.142604  16.20299  10.757636   24.576413     3.599437

data_path                           2633851                                   \
Type      DFT_D3ZERO AE Processed     AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE
test          16.757546     5 / 5  5.559192  16.20299  13.372083   24.576413

data_path
Type      AI_D3ZERO AE DFT_D3ZERO AE Processed
test          6.818774     16.757546     5 / 5

wtmad_1

data_path    713074                                                \
Type          AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE AI_D3ZERO AE
test       9.766224  8.474582    60.6131   60.448661     8.808453

data_path                            2633851                                   \
Type      DFT_D3ZERO AE Processed      AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE
test            7.40162     5 / 5  14.051588  8.474582  59.085471   60.448661

data_path
Type      AI_D3ZERO AE DFT_D3ZERO AE Processed
test          9.512885       7.40162     5 / 5

wtmad_2

data_path    713074                                                \
Type          AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE AI_D3ZERO AE
test       0.273798  0.214688   0.864084    0.871351    36.874519

data_path                           2633851                                   \
Type      DFT_D3ZERO AE Processed     AI AE    DFT AE AI_D3BJ AE DFT_D3BJ AE
test           28.31654     5 / 5  0.369886  0.214688   0.872712    0.871351

data_path
Type      AI_D3ZERO AE DFT_D3ZERO AE Processed
test         52.311532      28.31654     5 / 5

Summary of Subset
MAE

data_path     713074                                                 \
Type           AI AE     DFT AE AI_D3BJ AE DFT_D3BJ AE AI_D3ZERO AE
W4_11       1.134924  29.506869   2.586504    31.21176     1.384151
MB16_43    12.190644  15.461608   26.19018   36.863006    12.117016
BSR36      13.908602   8.401182  32.724327   32.845381     8.386454
Amino20x4   1.242777   0.656235   3.420988     3.00242     1.090031
S22         2.116219   2.291253  23.325362   23.256625     2.340539

data_path                             2633851                        \
Type      DFT_D3ZERO AE  Processed      AI AE     DFT AE AI_D3BJ AE
W4_11         29.861061  140 / 140   2.233328  29.506869   3.879646
MB16_43       23.165477    43 / 43  12.221747  15.461608  41.929723
BSR36          2.920953    36 / 36  21.020409   8.401182  32.582228
Amino20x4      0.586691    80 / 80    1.45556   0.656235    3.53739
S22            2.291759    22 / 22   3.323642   2.291253  22.289029

data_path
Type      DFT_D3BJ AE AI_D3ZERO AE DFT_D3ZERO AE  Processed
W4_11        31.21176     2.562732     29.861061  140 / 140
MB16_43     36.863006    26.246389     23.165477    43 / 43
BSR36       32.845381     15.49826      2.920953    36 / 36
Amino20x4     3.00242     1.367315      0.586691    80 / 80
S22         23.256625      1.55121      2.291759    22 / 22

In [ ]:
data_path	713074	2633851
Type	AI AE	DFT AE	AI_D3BJ AE	DFT_D3BJ AE	AI_D3ZERO AE	DFT_D3ZERO AE	Processed	AI AE	DFT AE	AI_D3BJ AE	DFT_D3BJ AE	AI_D3ZERO AE	DFT_D3ZERO AE	Processed
W4_11	1.134924	29.506869	2.586504	31.21176	1.384151	29.861061	140 / 140	2.233328	29.506869	3.879646	31.21176	2.562732	29.861061	140 / 140
MB16_43	12.190644	15.461608	26.19018	36.863006	12.117016	23.165477	43 / 43	12.221747	15.461608	41.929723	36.863006	26.246389	23.165477	43 / 43
BSR36	13.908602	8.401182	32.724327	32.845381	8.386454	2.920953	36 / 36	21.020409	8.401182	32.582228	32.845381	15.49826	2.920953	36 / 36
Amino20x4	1.242777	0.656235	3.420988	3.00242	1.090031	0.586691	80 / 80	1.45556	0.656235	3.53739	3.00242	1.367315	0.586691	80 / 80
S22	2.116219	2.291253	23.325362	23.256625	2.340539	2.291759	22 / 22	3.323642	2.291253	22.289029	23.256625	1.55121	2.291759	22 / 22

data_path 713074_d3zero                           713074
Type              AI AE     DFT AE  Processed      AI AE     DFT AE  Processed
W4_11          1.314667  29.861061  140 / 140   0.983209  29.506869  140 / 140
MB16_43        10.77178  23.165477    43 / 43  14.121423  15.461608    43 / 43
BSR36          4.378673   2.920953    36 / 36  10.157595   8.401182    36 / 36