In [1]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 0
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099
        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
            }

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)
for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}
        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []
        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(mean_absolute_deviation_list)
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

print("Summary")
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
# save summary to excel with date
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")

cc-pVDZ
Warning: 29 in 159476_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Warning: 29 in 1424849_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Warning: 29 in 1477959_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Summary
MAE

/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

data_path        159476                                                    \
Disp type            AI        DFT       AI_D3BJ   DFT_D3BJ     AI_D3ZERO
sub1        6425.472972  13.710857   6425.406121  14.259701   6425.316868
sub2        2651.036347   6.612164   2659.737817   9.130035   2655.999316
sub3       14716.588105   6.647378  14717.086971   7.856168  14716.895781
sub4         234.418861    0.72616     234.90058   1.150397    234.959588
sub5                NaN        NaN           NaN        NaN           NaN

data_path                        1424849                       ...            \
Disp type DFT_D3ZERO Processed        AI        DFT   AI_D3BJ  ... AI_D3ZERO
sub1       13.713797   18 / 18  2.002477  13.710857  2.341162  ...  1.840461
sub2        6.757695     7 / 9  5.510109   6.612164   9.25764  ...  6.192243
sub3        7.422183     5 / 7  2.617318   6.261376  3.548881  ...  3.228945
sub4        1.219187    1 / 12   1.93524   3.272197  2.924356  ...  2.900361
sub5             NaN     0 / 9  1.626727   1.321288   1.52729  ...  1.545785

data_path                        1477959                                  \
Disp type DFT_D3ZERO Processed        AI        DFT   AI_D3BJ   DFT_D3BJ
sub1       13.713797   18 / 18  4.024911  13.710857  4.394827  14.259701
sub2        6.757695     7 / 9  6.165144   6.612164  9.243087   9.130035
sub3        6.934991     7 / 7  3.280836   6.261376   4.21537   7.355579
sub4        4.988172   11 / 12  1.861269   3.272197  2.940841    5.03074
sub5        0.872793     8 / 9  2.264135   1.321288   1.52166   0.928323

data_path
Disp type AI_D3ZERO DFT_D3ZERO Processed
sub1       3.888615  13.713797   18 / 18
sub2        6.56423   6.757695     7 / 9
sub3        3.92612   6.934991     7 / 7
sub4       2.901616   4.988172   11 / 12
sub5       1.487843   0.872793     8 / 9

[5 rows x 21 columns]

wtmad_1

data_path        159476                                                    \
Disp type            AI        DFT       AI_D3BJ   DFT_D3BJ     AI_D3ZERO
sub1       10407.833418   7.420922   10408.12846   7.414578  10407.692607
sub2       16760.007227   12.53052  16762.220946   9.968131  16761.278604
sub3       35835.303131   7.071498  35835.988784   8.256972  35835.615629
sub4        1362.667514  11.609785   1360.866701  13.972834   1361.635309
sub5                NaN        NaN           NaN        NaN           NaN

data_path                         1424849                        ...  \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ  ...
sub1        7.102094   18 / 18   3.239113   7.420922   2.966668  ...
sub2       10.005264     7 / 9  13.142366   12.53052    11.9277  ...
sub3        7.680624     5 / 7   4.832263   6.984991   5.854163  ...
sub4       14.994136    1 / 12  11.556831  11.029773  13.901938  ...
sub5             NaN     0 / 9  15.335367  11.571826  14.145431  ...

data_path                                    1477959                        \
Disp type  AI_D3ZERO DFT_D3ZERO Processed         AI        DFT    AI_D3BJ
sub1        2.651677   7.102094   18 / 18   3.789626   7.420922   3.443295
sub2       11.524608  10.005264     7 / 9  11.038943   12.53052   9.121917
sub3        5.522858   7.521852     7 / 7   5.389792   6.984991   6.327282
sub4       12.876599  13.798614   11 / 12  11.131577  11.029773  14.344735
sub5       14.544885   7.523212     8 / 9  20.741529  11.571826    13.6042

data_path
Disp type  DFT_D3BJ  AI_D3ZERO DFT_D3ZERO Processed
sub1       7.414578   3.046364   7.102094   18 / 18
sub2       9.968131   9.389425  10.005264     7 / 9
sub3       8.150912   6.104995   7.521852     7 / 7
sub4       14.87552  13.234994  13.798614   11 / 12
sub5       8.092645  13.667041   7.523212     8 / 9

[5 rows x 21 columns]

wtmad_2

data_path        159476                                                  \
Disp type            AI       DFT       AI_D3BJ  DFT_D3BJ     AI_D3ZERO
sub1        8985.777191  9.060549   8985.698476  9.219193      8985.427
sub2        8570.595373  8.151589   8573.306851  5.327781   8572.344654
sub3       19458.738307  5.637103  19459.109746  6.616453  19458.967473
sub4        2916.779879  2.582984   2921.208121  5.619689   2921.654373
sub5                0.0       0.0           0.0       0.0           0.0

data_path                        1424849                      ...            \
Disp type DFT_D3ZERO Processed        AI       DFT   AI_D3BJ  ... AI_D3ZERO
sub1        8.946353   18 / 18  1.438234  4.040696  1.379994  ...  1.263846
sub2         5.70819     7 / 9  3.339073  3.635331  2.970771  ...  2.735087
sub3        6.274831     5 / 7  1.303233  2.611064   1.66299  ...  1.549133
sub4        6.091645    1 / 12  4.683102  4.159493  6.811273  ...  6.578153
sub5             0.0     0 / 9  6.331811   4.66236   6.30221  ...  6.387196

data_path                        1477959                                \
Disp type DFT_D3ZERO Processed        AI       DFT   AI_D3BJ  DFT_D3BJ
sub1        3.989769   18 / 18  1.921023  4.040696  1.839362  4.111446
sub2        2.545658     7 / 9  3.675662  3.635331  2.522968  2.376009
sub3        2.873647     7 / 7   1.54398  2.611064  1.925105  3.040013
sub4         6.62018   11 / 12  4.306403  4.159493  6.554155  6.856534
sub5         3.19725     8 / 9  8.384364   4.66236  5.942533  3.511844

data_path
Disp type AI_D3ZERO DFT_D3ZERO Processed
sub1        1.68376   3.989769   18 / 18
sub2       2.765968   2.545658     7 / 9
sub3       1.817199   2.873647     7 / 7
sub4       6.318974    6.62018   11 / 12
sub5        5.89853    3.19725     8 / 9

[5 rows x 21 columns]

Summary of Subset
MAE

data_path        159476                                                    \
Disp type            AI        DFT       AI_D3BJ   DFT_D3BJ     AI_D3ZERO
W4_11        317.945892  29.506863    317.751908  31.211753    317.811085
G21EA        140.247439   9.754522    140.249763   9.751745    140.245951
G21IP        122.428215   8.953334    122.420929   8.946699    122.428451
DIPCS10      653.436874  12.310852     653.46012  12.334099    653.390676
PA26          53.123666   2.200766     52.780721   1.900152     52.837378
SIE4x4        30.092303  21.908516     29.663006  22.337814     29.660892
ALKBDE10     603.643712  18.125246    604.109355  18.838948    603.653407
YBDE18       604.829954   8.145393    607.382289   7.265227    605.922782
AL2X6         43.909343   5.659145     46.895518   1.332003       44.9166
HEAVYSB11   43994.56611   5.391476  43993.472993   8.010474  43993.530893
NBPRC       43867.34502    2.23255  43868.658819   2.544088  43868.688191
ALK8       43839.655947   4.400063  43845.336779   3.174803  43841.787588
RC21          59.650852   4.820926     60.547198   6.671006     60.051223
G2RC       27293.139428   5.917203  27293.577909   6.933515   27293.22896
BH76RC     13117.627303   3.484561  13117.736413   3.539828  13117.743508
FH51       12992.795787   3.703657  12991.397263    3.39478  12991.548282
TAUT15        29.733018    2.16453     29.660139   2.175485     29.420529
DC13         341.474691  13.090861    336.042219  12.474047    338.636592
MB16_43     1324.174853  15.461604   1358.878023  36.862998   1343.104292
DARC          21.028751   10.75415     28.749681    3.43411     26.204931
RSE43      11519.580867     3.1576  11519.615995   2.916276  11519.682847
BSR36          0.962172    8.40118      7.660361   1.213694      5.628912
CDIE20        18.347455   1.599507     18.123086   1.336544     18.123061
ISO34          5.232164   2.001743      4.914145   1.577125      4.954521
ISOL24                0          0             0          0             0
C60ISO                0          0             0          0             0
PArel        178.112679   1.743933    178.094383   1.733749    177.979235
BH76       27523.294223   9.107946   27523.21364     9.8892  27523.262202
BHPERI        39.055212   3.268992     41.915204   7.804724       41.0607
BHDIV10      120.313041   6.277706    121.505876   7.448955     120.77316
INV24         85.397656   2.953015     85.133394   2.656199     85.232977
BHROT27    21864.052116   0.888365  21864.068668   0.902173  21864.016968
PX13           7.889305  11.042023      8.673293   11.82601      8.067139
WCPT18      4430.651319   7.967151   4430.793408   9.151986   4430.743546
RG18         400.460499   0.230018    401.162913   0.655714    401.216751
ADIM6          3.272419   2.181125      0.577669   1.593155      0.723773
S22            5.067335   1.071792      6.519427   1.942981      6.550068
S66                   0          0             0          0             0
HEAVY28               0          0             0          0             0
WATER27               0          0             0          0             0
CARBHB12              0          0             0          0             0
PNICO23               0          0             0          0             0
HAL59                 0          0             0          0             0
AHB21                 0          0             0          0             0
CHB6                  0          0             0          0             0
IL16                  0          0             0          0             0
IDISP                 0          0             0          0             0
ICONF                 0          0             0          0             0
ACONF                 0          0             0          0             0
Amino20x4             0          0             0          0             0
PCONF21               0          0             0          0             0
MCONF                 0          0             0          0             0
SCONF                 0          0             0          0             0
UPU23                 0          0             0          0             0
BUT14DIOL             0          0             0          0             0

data_path                          1424849                        ...  \
Disp type DFT_D3ZERO  Processed         AI        DFT    AI_D3BJ  ...
W4_11      29.861055  140 / 140   1.028249  29.506863   2.441523  ...
G21EA       9.757546    25 / 25   0.816732   9.754522   0.812414  ...
G21IP         8.9519    36 / 36   0.694714   8.953334   0.702841  ...
DIPCS10    12.264655    10 / 10   2.042735  12.310852   2.034436  ...
PA26         2.00824    26 / 26   3.009087   2.200766   2.998221  ...
SIE4x4     22.339928    16 / 16   3.430805  21.908516   3.716252  ...
ALKBDE10   18.135588      9 / 9   0.959132  18.125246   1.307356  ...
YBDE18      7.472761    18 / 18   5.939045   8.145393   3.828518  ...
AL2X6       1.829895      6 / 6   6.140013   5.659145   2.086328  ...
HEAVYSB11   5.984154      7 / 7   2.024005   5.391476   3.570429  ...
NBPRC       2.274234    12 / 12   3.058861    2.23255   2.325813  ...
ALK8        2.559066      8 / 8   4.403777   4.400063   3.075723  ...
RC21          6.0297    21 / 21   2.456062   4.820926   2.009509  ...
G2RC        6.417298    25 / 25   1.887093   5.917203    2.60955  ...
BH76RC      3.536982    30 / 30    0.85212   3.484561   1.035153  ...
FH51        3.256908    51 / 51   2.464205   3.703657   2.323411  ...
TAUT15      2.145937    15 / 15   1.702465    2.16453   1.631979  ...
DC13       11.475687    13 / 13   6.170057  13.090861   7.562068  ...
MB16_43    23.165472    43 / 43   13.39941  15.461604  35.416173  ...
DARC         5.57797    14 / 14   7.823359   10.75415   2.327124  ...
RSE43        2.74911    43 / 43    3.11738     3.1576   2.896011  ...
BSR36       3.079106    36 / 36    4.98276    8.40118   3.343296  ...
CDIE20      1.347484    20 / 20   1.450234   1.599507   1.483496  ...
ISO34       1.647042    34 / 34   2.020035   2.001743   1.659329  ...
ISOL24             0     0 / 24          0          0          0  ...
C60ISO             0      0 / 9          0          0          0  ...
PArel       1.645025    20 / 20   3.015433   1.743933   2.882746  ...
BH76        9.676053    76 / 76   2.803583   9.107946   3.232992  ...
BHPERI        6.4139    26 / 26   2.657111   3.268992    6.88257  ...
BHDIV10     6.535109    10 / 10   4.741552   6.277706   5.390696  ...
INV24        2.66316    15 / 24   3.393792   2.697333   3.863218  ...
BHROT27     0.851199    21 / 27   1.713103   0.853379   1.734055  ...
PX13       11.219857    13 / 13   1.059156  11.042023   1.291815  ...
WCPT18      8.744304    18 / 18   2.039614   7.967151   2.977303  ...
RG18        0.709552    18 / 18    0.30936   0.230018   0.765676  ...
ADIM6       1.815067      4 / 6   3.598266   3.059029   2.516398  ...
S22         1.973622     9 / 22   2.728845   2.291252   3.309309  ...
S66                0     0 / 66   2.326488   1.894709    1.79261  ...
HEAVY28            0      0 / 0          0          0          0  ...
WATER27            0     0 / 27    3.02651  16.299413   8.262183  ...
CARBHB12           0     0 / 12   0.484944   1.632408   1.161335  ...
PNICO23            0     0 / 23   0.840943   0.776429   2.313413  ...
HAL59              0     0 / 31   2.035403   1.649786   2.945249  ...
AHB21              0     0 / 21   1.666768   2.453821   2.321702  ...
CHB6               0      0 / 4   1.766454    1.80532   1.334639  ...
IL16               0     0 / 16   1.467889   1.021067   3.988457  ...
IDISP              0      0 / 6  13.356085  13.125475   5.787398  ...
ICONF              0     0 / 17   0.946016   0.413804    0.81078  ...
ACONF              0     0 / 15   3.016487   0.546621   2.340276  ...
Amino20x4          0     0 / 80   1.243276   0.656235   1.235374  ...
PCONF21            0     0 / 18    2.09681   3.214782    2.27087  ...
MCONF              0     0 / 51   1.596087    1.95602   1.874388  ...
SCONF              0     0 / 17   1.154998   0.512352   1.080344  ...
UPU23              0     0 / 23          0          0          0  ...
BUT14DIOL          0     0 / 64   0.879011   0.645099   1.125573  ...

data_path                                     1477959                        \
Disp type  AI_D3ZERO DFT_D3ZERO  Processed         AI        DFT    AI_D3BJ
W4_11       1.248829  29.861055  140 / 140   7.319485  29.506863    8.99233
G21EA       0.823677   9.757546    25 / 25   0.752891   9.754522   0.747659
G21IP       0.685192     8.9519    36 / 36   0.612704   8.953334   0.620029
DIPCS10     2.049052  12.264655    10 / 10   1.721148  12.310852   1.706902
PA26        2.951891    2.00824    26 / 26   2.684473   2.200766   2.822219
SIE4x4      3.729847  22.339928    16 / 16    3.81789  21.908516   4.218367
ALKBDE10     0.94979  18.135588      9 / 9   0.896418  18.125246   1.479719
YBDE18      4.255001   7.472761    18 / 18   5.452287   8.145393   3.320899
AL2X6        2.63339   1.829895      6 / 6   4.724138   5.659145   1.798268
HEAVYSB11   1.845095   5.984154      7 / 7   1.024168   5.391476   3.118704
NBPRC       2.192134   2.274234    12 / 12   2.601596    2.23255   2.592483
ALK8        2.009981   2.559066      8 / 8    5.56631   4.400063   3.052343
RC21        1.816792     6.0297    21 / 21   3.328626   4.820926   2.649382
G2RC        2.145182   6.417298    25 / 25    1.86293   5.917203   2.686862
BH76RC       0.96494   3.536982    30 / 30   1.985102   3.484561   1.911645
FH51        2.136612   3.256908    51 / 51   2.913926   3.703657   2.732422
TAUT15      1.578771   2.145937    15 / 15   2.511695    2.16453   2.392938
DC13        5.746533  11.475687    13 / 13   6.936251  13.090861   6.327038
MB16_43    21.115024  23.165472    43 / 43  12.991142  15.461604  36.011233
DARC        3.060175    5.57797    14 / 14   6.339105   10.75415    2.32823
RSE43       2.755026    2.74911    43 / 43   1.357578     3.1576    1.23113
BSR36       2.368881   3.079106    36 / 36  11.930926    8.40118   4.577403
CDIE20      1.479584   1.347484    20 / 20   1.619806   1.599507    1.55298
ISO34       1.708557   1.647042    34 / 34   2.224034   2.001743   1.880444
ISOL24             0          0     0 / 24          0          0          0
C60ISO             0          0      0 / 9          0          0          0
PArel       2.907704   1.645025    20 / 20   2.570558   1.743933   2.362512
BH76        3.093517   9.676053    76 / 76   3.683541   9.107946    4.23779
BHPERI      5.491745     6.4139    26 / 26    2.92304   3.268992   7.443523
BHDIV10      4.85035   6.535109    10 / 10   4.634879   6.277706   5.134624
INV24       3.631489   2.228547    24 / 24   4.286699   2.697333   4.886376
BHROT27     1.763036    0.78352    27 / 27   1.636124   0.853379   1.687857
PX13        1.212867  11.219857    13 / 13   3.595098  11.042023   2.958974
WCPT18      2.749679   8.744304    18 / 18   2.244051   7.967151    2.75111
RG18        0.819514   0.709552    18 / 18   0.234001   0.230018   0.641911
ADIM6       2.777618   2.390824      6 / 6   3.329851   3.059029   2.637107
S22         3.196728   2.291758    22 / 22   2.554317   2.291252   3.450363
S66         1.834235   2.101976    66 / 66   2.103482   1.894709   1.958299
HEAVY28            0          0      0 / 0          0          0          0
WATER27     9.177355  26.402884    27 / 27   3.330748  16.299413     9.4285
CARBHB12    1.030009   2.841777    12 / 12    0.70798   1.632408   1.349026
PNICO23      1.44661   1.726817    23 / 23    1.21271   0.776429    2.55689
HAL59       2.562614   2.247276    29 / 29   1.886329   1.649786   2.741651
AHB21       2.212706   3.294519    21 / 21   1.151556   2.453821   1.773903
CHB6        1.432927   2.309161      4 / 4   0.502771    1.80532   1.518926
IL16        4.059287   4.409963    16 / 16   1.732386   1.021067   2.039422
IDISP       6.653317   5.245746      6 / 6  13.279612  13.125475   7.425133
ICONF       0.905493   0.493337    17 / 17   1.937776   0.413804   1.743198
ACONF       2.444544   0.274429    15 / 15    1.75089   0.546621   1.407255
Amino20x4   1.240646   0.576975    80 / 80   1.334956   0.656235   1.185534
PCONF21     2.451983   1.099663    18 / 18   3.643302   3.214782   1.563164
MCONF       1.854668   0.711618    51 / 51   3.877701    1.95602   1.656359
SCONF       1.029236   1.317952    17 / 17   1.624566   0.512352   1.285208
UPU23              0          0     0 / 23          0          0          0
BUT14DIOL   1.044006    1.02002    64 / 64    1.09607   0.645099   1.300129

data_path
Disp type   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO  Processed
W4_11      31.211753   7.671953  29.861055  140 / 140
G21EA       9.751745   0.762055   9.757546    25 / 25
G21IP       8.946699   0.614381     8.9519    36 / 36
DIPCS10    12.334099   1.781653  12.264655    10 / 10
PA26        1.900152   2.723703    2.00824    26 / 26
SIE4x4     22.337814   4.226585  22.339928    16 / 16
ALKBDE10   18.838948   0.891988  18.135588      9 / 9
YBDE18      7.265227   3.790343   7.472761    18 / 18
AL2X6       1.332003   1.400038   1.829895      6 / 6
HEAVYSB11   8.010474   1.123495   5.984154      7 / 7
NBPRC       2.544088   2.054559   2.274234    12 / 12
ALK8        3.174803   3.222369   2.559066      8 / 8
RC21        6.671006   2.522696     6.0297    21 / 21
G2RC        6.933515   2.203841   6.417298    25 / 25
BH76RC      3.539828     2.0105   3.536982    30 / 30
FH51         3.39478   2.685611   3.256908    51 / 51
TAUT15      2.175485   2.143758   2.145937    15 / 15
DC13       12.474047   5.223725  11.475687    13 / 13
MB16_43    36.862998  21.210708  23.165472    43 / 43
DARC         3.43411   2.090283    5.57797    14 / 14
RSE43       2.916276   1.151571    2.74911    43 / 43
BSR36       1.213694   6.608853   3.079106    36 / 36
CDIE20      1.336544   1.599577   1.347484    20 / 20
ISO34       1.577125   1.967111   1.647042    34 / 34
ISOL24             0          0          0     0 / 24
C60ISO             0          0          0      0 / 9
PArel       1.733749   2.542718   1.645025    20 / 20
BH76          9.8892   4.048827   9.676053    76 / 76
BHPERI      7.804724   6.052698     6.4139    26 / 26
BHDIV10     7.448955   4.743676   6.535109    10 / 10
INV24       2.346995   4.659452   2.228547    24 / 24
BHROT27     0.858852   1.724082    0.78352    27 / 27
PX13        11.82601    3.40769  11.219857    13 / 13
WCPT18      9.151986   2.581806   8.744304    18 / 18
RG18        0.655714   0.695749   0.709552    18 / 18
ADIM6       2.090256   2.898327   2.390824      6 / 6
S22         2.402928   3.330413   2.291758    22 / 22
S66         2.058561   2.000288   2.101976    66 / 66
HEAVY28            0          0          0      0 / 0
WATER27    25.491048  10.351126  26.402884    27 / 27
CARBHB12    2.973103   1.196297   2.841777    12 / 12
PNICO23     2.604046    1.71233   1.726817    23 / 23
HAL59       2.629912   2.359015   2.247276    29 / 29
AHB21       3.464384   1.623786   3.294519    21 / 21
CHB6        3.038126   0.789961   2.309161      4 / 4
IL16        4.339132   2.118899   4.409963    16 / 16
IDISP       4.423061   6.448828   5.245746      6 / 6
ICONF       0.464652    1.93877   0.493337    17 / 17
ACONF       0.430751    1.39715   0.274429    15 / 15
Amino20x4   0.647041    1.16062   0.576975    80 / 80
PCONF21     1.178453   1.641679   1.099663    18 / 18
MCONF       0.741352   1.641333   0.711618    51 / 51
SCONF       1.432857    1.28859   1.317952    17 / 17
UPU23              0          0          0     0 / 23
BUT14DIOL   1.136703   1.220607    1.02002    64 / 64

[55 rows x 21 columns]

In [4]:
# import numpy as np
np.max(mean_absolute_deviation_list), np.sum(mean_absolute_deviation_list), np.mean(
    mean_absolute_deviation_list
)

(np.float64(1207.482739432191),
 np.float64(98414.09024557225),
 np.float64(71.1084467092285))

In [5]:
mole_name

'BH76RC-NH'

In [9]:
e1 = -4.6025270679642568e02  # orca fc DLPNO-CCSD
e2 = -4.6025221729046751e02  # orca fc CCSD
e3 = -4.6025767731174767e02 # orca nfc CCSD
e4 = -4.6025796979352134e02 # orca nfc DLPNO-CCSD
e = -460.257677434825  # pyscf CCSD
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 3.11912268e+00  3.42629231e+00  7.72321803e-05 -1.83457852e-01]
[-1.07996860e-05 -1.18632336e-05 -2.67409583e-10  6.35206561e-07]

In [14]:
e = -460.2602125077868 # pyscf CCSD(t)
e1 = -4.6026021233042377e02 # orca nfc CCSD(t)
e2 = -4.6026021233042360e02 # orca old nfc CCSD(t)
e3 = -4.6026042971888393e02  # orca nfc DLPNO-CCSD(t)
e4 = -4.6025500524617820e02
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 1.11296967e-04  1.11297074e-04 -1.36302021e-01  3.26760599e+00]
[-3.85353766e-10 -3.85354136e-10  4.71931076e-07 -1.13137340e-05]

In [ ]:
np.array([[-4.366423914512e-02], [0.000000000000e00], [-5.569827800646e-01]])
np.array([[-4.366423911029e-02], [0.000000000000e00], [-5.569827799431e-01]])

[[-4.366423908914e-02], [0.000000000000e00], [-5.569827798789e-01]]

array([[-3.48300000e-11],
       [ 0.00000000e+00],
       [-1.21500032e-10]])