In [1]:
from pathlib import Path

import pandas as pd

!noglob scp -r hkqai:~/workspace/cc2cc_test5/validate/*.csv ~/workspace/2025.1/validate
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 5239   104.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 7925   171.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 8423   178.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   15KB 318.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   38KB   1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   13KB 259.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   17KB 342.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   16KB 344.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 9999   215.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   14KB 287.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 9443   188.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   38KB 995.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   23KB 689.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   32KB 794.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   21KB 438.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 6604   141.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   27KB 555.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   24KB 517.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 9655   202.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   23KB 488.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 5907   127.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   18KB 377.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   38KB 793.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   25KB 516.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   11KB 227.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   11KB 230.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   67KB   1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   13KB 272.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   25KB 511.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   17KB 366.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   25KB 270.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   25KB 530.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   67KB 723.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7643   154.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5234   100.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   24KB 509.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4881    95.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7256   153.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7641   136.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   39KB   1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB 674.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8165   165.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB 531.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB 340.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB 317.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB 483.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB 311.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB 305.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5679   121.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9176   103.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 247.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8591   166.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   34KB 687.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB 415.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   29KB 613.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB 402.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB 524.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2286    45.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6092   128.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB 219.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5592   115.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   18KB 372.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB 393.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB 526.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   13KB 286.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB 470.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   20KB 423.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8889   189.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB 400.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 252.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8457   175.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   27KB 569.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 249.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB 330.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 206.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB 729.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB 469.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   77KB   2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7506   146.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9625   204.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 208.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   62KB   1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 121.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB 234.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 230.7KB/s   00:00

In [4]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 1
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099
        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
            }

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = f"{i_subset}-{systems_list[i]}"
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)
for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}
        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []
        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        np.sum(data_subset[name_subset][f"ai{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        np.sum(data_subset[name_subset][f"dft{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if len(data_subset[name_subset]["ai"]) == len(
                data_subset[name_subset]["name"]
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.mean(wtmad_1_ai[d3_name])
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.mean(wtmad_1_dft[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.sum(wtmad_2_ai[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.sum(wtmad_2_dft[d3_name])
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(mean_absolute_deviation_list)
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            )

print("Summary")
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)

print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
# save summary to excel with date
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")

cc-pVDZ
Warning: ALKBDE10-kf not found in data json, ERROR
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-ch3 not found in data json, ERROR
Warning: BH76RC-f- not found in data json, ERROR
Warning: BH76RC-fch3clcomp1 not found in data json, ERROR
Warning: BH76RC-oh- not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-ch3 not found in data json, ERROR
Warning: BH76RC-hnc not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-oh not found in data json, ERROR
Warning: BH76RC-ch3 not found in data json, ERROR
Warning: BH76RC-oh not found in data json, ERROR
Warning: BH76RC-oh not found in data json, ERROR
Warning: BH76RC-hcl not found in data json, ERROR
Warning: BH76RC-oh not found in data json, ERROR
Warning: BH76RC-f not found in data json, ERROR
Warning: BH76RC-O not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-h not found in data json, ERROR
Warning: BH76RC-O not found in data json, ERROR
Warning: BH76RC-NH not found in data json, ERROR
Warning: BH76RC-NH not found in data json, ERROR
Warning: BH76RC-C2H6 not found in data json, ERROR
Warning: BH76RC-NH not found in data json, ERROR
Warning: G21EA-EA_c not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_f not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_si not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_p not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_s not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_cl not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_8n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_9n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_10n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_11n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_12n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_13n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_14n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_15n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_16n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_17n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_18n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_19n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_20n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_21n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_22n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_23n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_24n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_25n not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-h not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-li+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-be+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-b+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-c+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-n+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-o+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-f+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-na+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-mg+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-al+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-si+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-p+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-s+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-cl+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_59 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_60 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_61 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_62 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_63 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_64 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_65 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_66 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_67 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_68 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_70 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_71 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_72 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_73 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_74 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_75 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_76 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_77 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_78 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_79 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_80 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-c4h4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-c2h4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-n2h2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-ch2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-h2s not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-ph3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-mg not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: DIPCS10-be not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-p2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-p4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-p6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-h2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-c2h2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-sih4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-ph3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-h2s not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-hcl not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-h2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-c2f6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-ethanol not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-ch3cooh not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-gly not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-phenol not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-ass not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-ch2s not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-si2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-cys not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-phosphapyrrol not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-A not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-T not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-G not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: PA26-C not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-he not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-he not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-he not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-he not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: SIE4x4-h2o not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-bef not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-beo not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-cao not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-hf not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-kf not found in data json, ERROR
Warning: ALKBDE10-lif not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-lio not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-mgo not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-mgs not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALKBDE10-nao not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-f2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-f2s-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-h2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-h2s-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-me2s-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nf3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nf3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nh3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nh3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-nme3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-pf3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-pf3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-ph3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-ph3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-pme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: YBDE18-pme3-ch2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2f6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2cl6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2me4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2me5 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: AL2X6-al2me6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-geh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-sh not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-seh not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-pme2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-asme2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Warning: HEAVYSB11-cl not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: HEAVYSB11-br not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh3-bh3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh2-bh2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh2-bh2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh2-bh2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-nh2-bh2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-BH3PH3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_H not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-BF3PMe3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_F not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-BCl3PMe3 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_Cl not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li8 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-na8 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li4_me4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li3_me not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li2_ch4 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li5_ch not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-li2_ch2n_2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: ALK8-na+ not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-1e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-1e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-2e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-2e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-4e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-5e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-8e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-9e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: RC21-10e not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-118 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-40 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-113 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-52 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-30 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-128 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-100 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-25 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-39 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-58 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-67 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-32 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-25 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: G2RC-47 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file

/home/dhem/anaconda3/lib/python3.13/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/lib/python3.13/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

data_path   1424849                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       2.081269  14.411288  2.081269  14.411288  2.081269  14.411288
sub2       5.606356   6.836959  5.606356   6.836959  5.606356   6.836959
sub3       2.858702   8.773489  2.858702   8.773489  2.858702   8.773489
sub4       2.833711   2.291252  2.833711   2.291252  2.833711   2.291252
sub5       1.848226   0.574609  1.848226   0.574609  1.848226   0.574609

data_path             2487024                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1        18 / 18  1.982356  29.506863  1.982356  29.506863  1.982356
sub2          4 / 9  16.08525  12.244196  16.08525  12.244196  16.08525
sub3          1 / 7       NaN        NaN       NaN        NaN       NaN
sub4         2 / 12  2.960992   2.291252  2.960992   2.291252  2.960992
sub5          0 / 9  2.030823   0.606807  2.030823   0.606807  2.030823

data_path
Disp type DFT_D3ZERO Processed
sub1       29.506863    2 / 18
sub2       12.244196     2 / 9
sub3             NaN     0 / 7
sub4        2.291252    2 / 12
sub5        0.606807     0 / 9

wtmad_1

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        3.379524   7.652473   3.379524   7.652473   3.379524   7.652473
sub2       14.560841  12.237809  14.560841  12.237809  14.560841  12.237809
sub3        3.180231   6.822492   3.180231   6.822492   3.180231   6.822492
sub4       28.337115  22.912521  28.337115  22.912521  28.337115  22.912521
sub5       18.482265   5.746089  18.482265   5.746089  18.482265   5.746089

data_path              2487024                                              \
Disp type Processed         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO
sub1        18 / 18   0.198236   2.950686   0.198236   2.950686   0.198236
sub2          4 / 9  10.352089    4.97367  10.352089    4.97367  10.352089
sub3          1 / 7        NaN        NaN        NaN        NaN        NaN
sub4         2 / 12  29.609923  22.912521  29.609923  22.912521  29.609923
sub5          0 / 9  20.308232   6.068072  20.308232   6.068072  20.308232

data_path
Disp type DFT_D3ZERO Processed
sub1        2.950686    2 / 18
sub2         4.97367     2 / 9
sub3             NaN     0 / 7
sub4       22.912521    2 / 12
sub5        6.068072     0 / 9

wtmad_2

data_path   1424849                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       4.086121  11.349407  4.086121  11.349407  4.086121  11.349407
sub2        8.53294   9.650608   8.53294   9.650608   8.53294   9.650608
sub3       1.623782   5.002741  1.623782   5.002741  1.623782   5.002741
sub4       1.255769   1.015376  1.255769   1.015376  1.255769   1.015376
sub5       3.977766   1.236677  3.977766   1.236677  3.977766   1.236677

data_path              2487024                                              \
Disp type Processed         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO
sub1        18 / 18   0.695125  10.346755   0.695125  10.346755   0.695125
sub2          4 / 9  36.660141  16.589049  36.660141  16.589049  36.660141
sub3          1 / 7        0.0        0.0        0.0        0.0        0.0
sub4         2 / 12   5.866182   4.539323   5.866182   4.539323   5.866182
sub5          0 / 9  31.564088   9.431306  31.564088   9.431306  31.564088

data_path
Disp type DFT_D3ZERO Processed
sub1       10.346755    2 / 18
sub2       16.589049     2 / 9
sub3             0.0     0 / 7
sub4        4.539323    2 / 12
sub5        9.431306     0 / 9

Summary of Subset
MAE

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       1.028249  29.506863   1.028249  29.506863   1.028249  29.506863
G21EA       0.816732   9.754522   0.816732   9.754522   0.816732   9.754522
G21IP       0.694714   8.953334   0.694714   8.953334   0.694714   8.953334
DIPCS10     2.042735  12.310852   2.042735  12.310852   2.042735  12.310852
PA26        3.009087   2.200766   3.009087   2.200766   3.009087   2.200766
SIE4x4      3.430805  21.908516   3.430805  21.908516   3.430805  21.908516
ALKBDE10    0.959132  18.125246   0.959132  18.125246   0.959132  18.125246
YBDE18      5.939045   8.145393   5.939045   8.145393   5.939045   8.145393
AL2X6       6.140013   5.659145   6.140013   5.659145   6.140013   5.659145
HEAVYSB11   2.024005   5.391476   2.024005   5.391476   2.024005   5.391476
NBPRC       3.058861    2.23255   3.058861    2.23255   3.058861    2.23255
ALK8        4.403777   4.400063   4.403777   4.400063   4.403777   4.400063
RC21        2.456062   4.820926   2.456062   4.820926   2.456062   4.820926
G2RC        1.887093   5.917203   1.887093   5.917203   1.887093   5.917203
BH76RC             0          0          0          0          0          0
FH51        2.464205   3.703657   2.464205   3.703657   2.464205   3.703657
TAUT15      1.702465    2.16453   1.702465    2.16453   1.702465    2.16453
DC13        6.170057  13.090861   6.170057  13.090861   6.170057  13.090861
MB16_43    13.188469  15.270979  13.188469  15.270979  13.188469  15.270979
DARC        7.823359   10.75415   7.823359   10.75415   7.823359   10.75415
RSE43        3.11738     3.1576    3.11738     3.1576    3.11738     3.1576
BSR36        4.98276    8.40118    4.98276    8.40118    4.98276    8.40118
CDIE20      1.450234   1.599507   1.450234   1.599507   1.450234   1.599507
ISO34       1.791888   1.822617   1.791888   1.822617   1.791888   1.822617
ISOL24             0          0          0          0          0          0
C60ISO             0          0          0          0          0          0
PArel        4.03329   1.558854    4.03329   1.558854    4.03329   1.558854
BH76        2.803583   9.107946   2.803583   9.107946   2.803583   9.107946
BHPERI      3.556878   4.537037   3.556878   4.537037   3.556878   4.537037
BHDIV10            0          0          0          0          0          0
INV24              0          0          0          0          0          0
BHROT27            0          0          0          0          0          0
PX13               0          0          0          0          0          0
WCPT18             0          0          0          0          0          0
RG18               0          0          0          0          0          0
ADIM6              0          0          0          0          0          0
S22         2.833711   2.291252   2.833711   2.291252   2.833711   2.291252
S66                0          0          0          0          0          0
HEAVY28            0          0          0          0          0          0
WATER27            0          0          0          0          0          0
CARBHB12           0          0          0          0          0          0
PNICO23            0          0          0          0          0          0
HAL59              0          0          0          0          0          0
AHB21              0          0          0          0          0          0
CHB6               0          0          0          0          0          0
IL16               0          0          0          0          0          0
IDISP              0          0          0          0          0          0
ICONF              0          0          0          0          0          0
ACONF              0          0          0          0          0          0
Amino20x4   1.848226   0.574609   1.848226   0.574609   1.848226   0.574609
PCONF21            0          0          0          0          0          0
MCONF              0          0          0          0          0          0
SCONF              0          0          0          0          0          0
UPU23              0          0          0          0          0          0
BUT14DIOL          0          0          0          0          0          0

data_path               2487024                                              \
Disp type  Processed         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO
W4_11      140 / 140   1.982356  29.506863   1.982356  29.506863   1.982356
G21EA        25 / 25          0          0          0          0          0
G21IP        36 / 36          0          0          0          0          0
DIPCS10      10 / 10          0          0          0          0          0
PA26         26 / 26          0          0          0          0          0
SIE4x4       16 / 16          0          0          0          0          0
ALKBDE10       9 / 9          0          0          0          0          0
YBDE18       18 / 18          0          0          0          0          0
AL2X6          6 / 6          0          0          0          0          0
HEAVYSB11      7 / 7          0          0          0          0          0
NBPRC        12 / 12          0          0          0          0          0
ALK8           8 / 8          0          0          0          0          0
RC21         21 / 21          0          0          0          0          0
G2RC         25 / 25          0          0          0          0          0
BH76RC         0 / 0          0          0          0          0          0
FH51         51 / 51          0          0          0          0          0
TAUT15       15 / 15          0          0          0          0          0
DC13         13 / 13          0          0          0          0          0
MB16_43      42 / 43  13.334629  15.461604  13.334629  15.461604  13.334629
DARC         14 / 14          0          0          0          0          0
RSE43        43 / 43          0          0          0          0          0
BSR36        36 / 36  19.370715    8.40118  19.370715    8.40118  19.370715
CDIE20       20 / 20          0          0          0          0          0
ISO34        33 / 34          0          0          0          0          0
ISOL24        0 / 24          0          0          0          0          0
C60ISO         0 / 9          0          0          0          0          0
PArel         7 / 20          0          0          0          0          0
BH76         76 / 76          0          0          0          0          0
BHPERI        6 / 26          0          0          0          0          0
BHDIV10       0 / 10          0          0          0          0          0
INV24         0 / 24          0          0          0          0          0
BHROT27       0 / 27          0          0          0          0          0
PX13          0 / 13          0          0          0          0          0
WCPT18        0 / 18          0          0          0          0          0
RG18          0 / 18          0          0          0          0          0
ADIM6          0 / 6          0          0          0          0          0
S22          22 / 22   2.960992   2.291252   2.960992   2.291252   2.960992
S66           0 / 66          0          0          0          0          0
HEAVY28        0 / 0          0          0          0          0          0
WATER27       0 / 27          0          0          0          0          0
CARBHB12      0 / 12          0          0          0          0          0
PNICO23       0 / 23          0          0          0          0          0
HAL59         0 / 31          0          0          0          0          0
AHB21         0 / 21          0          0          0          0          0
CHB6           0 / 4          0          0          0          0          0
IL16          0 / 16          0          0          0          0          0
IDISP          0 / 6          0          0          0          0          0
ICONF         0 / 17          0          0          0          0          0
ACONF         0 / 15          0          0          0          0          0
Amino20x4    24 / 80   2.030823   0.606807   2.030823   0.606807   2.030823
PCONF21       0 / 18          0          0          0          0          0
MCONF         0 / 51          0          0          0          0          0
SCONF         0 / 17          0          0          0          0          0
UPU23         0 / 23          0          0          0          0          0
BUT14DIOL     0 / 64          0          0          0          0          0

data_path
Disp type DFT_D3ZERO  Processed
W4_11      29.506863  140 / 140
G21EA              0     0 / 25
G21IP              0     0 / 36
DIPCS10            0     0 / 10
PA26               0     0 / 26
SIE4x4             0     0 / 16
ALKBDE10           0      0 / 9
YBDE18             0     0 / 18
AL2X6              0      0 / 6
HEAVYSB11          0      0 / 7
NBPRC              0     0 / 12
ALK8               0      0 / 8
RC21               0     0 / 21
G2RC               0     0 / 25
BH76RC             0      0 / 0
FH51               0     0 / 51
TAUT15             0     0 / 15
DC13               0     0 / 13
MB16_43    15.461604    43 / 43
DARC               0     0 / 14
RSE43              0     0 / 43
BSR36        8.40118    36 / 36
CDIE20             0     0 / 20
ISO34              0     0 / 34
ISOL24             0     0 / 24
C60ISO             0      0 / 9
PArel              0     0 / 20
BH76               0     0 / 76
BHPERI             0     0 / 26
BHDIV10            0     0 / 10
INV24              0     0 / 24
BHROT27            0     0 / 27
PX13               0     0 / 13
WCPT18             0     0 / 18
RG18               0     0 / 18
ADIM6              0      0 / 6
S22         2.291252    22 / 22
S66                0     0 / 66
HEAVY28            0      0 / 0
WATER27            0     0 / 27
CARBHB12           0     0 / 12
PNICO23            0     0 / 23
HAL59              0     0 / 31
AHB21              0     0 / 21
CHB6               0      0 / 4
IL16               0     0 / 16
IDISP              0      0 / 6
ICONF              0     0 / 17
ACONF              0     0 / 15
Amino20x4   0.606807    47 / 80
PCONF21            0     0 / 18
MCONF              0     0 / 51
SCONF              0     0 / 17
UPU23              0     0 / 23
BUT14DIOL          0     0 / 64

In [9]:
e1 = -4.6025270679642568e02  # orca fc DLPNO-CCSD
e2 = -4.6025221729046751e02  # orca fc CCSD
e3 = -4.6025767731174767e02 # orca nfc CCSD
e4 = -4.6025796979352134e02 # orca nfc DLPNO-CCSD
e = -460.257677434825  # pyscf CCSD
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 3.11912268e+00  3.42629231e+00  7.72321803e-05 -1.83457852e-01]
[-1.07996860e-05 -1.18632336e-05 -2.67409583e-10  6.35206561e-07]

In [14]:
e = -460.2602125077868 # pyscf CCSD(t)
e1 = -4.6026021233042377e02 # orca nfc CCSD(t)
e2 = -4.6026021233042360e02 # orca old nfc CCSD(t)
e3 = -4.6026042971888393e02  # orca nfc DLPNO-CCSD(t)
e4 = -4.6025500524617820e02
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 1.11296967e-04  1.11297074e-04 -1.36302021e-01  3.26760599e+00]
[-3.85353766e-10 -3.85354136e-10  4.71931076e-07 -1.13137340e-05]

In [ ]:
np.array([[-4.366423914512e-02], [0.000000000000e00], [-5.569827800646e-01]])
np.array([[-4.366423911029e-02], [0.000000000000e00], [-5.569827799431e-01]])

[[-4.366423908914e-02], [0.000000000000e00], [-5.569827798789e-01]]

array([[-3.48300000e-11],
       [ 0.00000000e+00],
       [-1.21500032e-10]])