In [1]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 0
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

print("Summary")
display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset_ele.to_csv(f"../validate/df_summary_subset_ele_{date}.csv")
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
mean_subset.to_csv(f"../validate/mean_subset_{date}.csv")
wtmad_1_subset.to_csv(f"../validate/wtmad_1_subset_{date}.csv")
wtmad_2_subset.to_csv(f"../validate/wtmad_2_subset_{date}.csv")
# save summary to excel with date
df_summary_subset_ele.to_excel(f"../validate/df_summary_subset_ele_{date}.xlsx")
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
Warning: 29 in 3110260_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Warning: 29 in 1424849_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Warning: 29 in 1477959_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol
Warning: 29 in 159476_MB16_43 has a large CC energy: 1207.482739432191 kcal/mol

/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Summary

data_path       3110260                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.203346      0.275207      0.038022      0.035291
W4_11          0.254741      0.110565      0.021234      0.022406
G21EA          0.139015      0.134673           0.0           0.0
G21IP          0.190517      0.102494      0.006208      0.006154
DIPCS10        0.078609      0.107438      0.005015      0.003622
PA26           0.180687        0.2982      0.037726      0.038429
SIE4x4         0.065522      0.093996      0.003479      0.001311
ALKBDE10        0.17346       0.10564      0.058117      0.061711
YBDE18         0.188772      0.276239      0.053997      0.041601
AL2X6          0.341679      0.396501      0.007597      0.002336
HEAVYSB11      0.266969      0.278481      0.015159      0.009043
NBPRC          0.170883      0.252724      0.041341      0.032482
ALK8           0.204334      0.187227      0.041384      0.040223
RC21           0.178815      0.258984      0.075324      0.082447
G2RC           0.122514      0.181463      0.019087      0.015617
BH76RC         0.129873       0.14036       0.05982      0.057338
FH51           0.199888      0.331985      0.031603      0.028047
TAUT15         0.257285      0.413544       0.07541      0.069453
DC13           0.235861      0.397856      0.027393      0.019322
MB16_43        0.404377      0.510082      0.079998      0.081428
DARC            0.24273      0.443789      0.023235      0.019082
RSE43          0.143867      0.226787      0.045493       0.03536
BSR36          0.283351      0.495777      0.005294      0.001683
CDIE20         0.204085       0.35363      0.037289      0.040847
ISO34               NaN           NaN           NaN           NaN
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.347675      0.544069      0.081221      0.069727
BH76           0.129873       0.14036       0.05982      0.057338
BHPERI           0.1535      0.245834      0.041191      0.039482
BHDIV10        0.235738      0.347887      0.057839      0.048752
INV24               NaN           NaN           NaN           NaN
BHROT27             NaN           NaN           NaN           NaN
PX13                NaN           NaN           NaN           NaN
WCPT18              NaN           NaN           NaN           NaN
RG18                NaN           NaN           NaN           NaN
ADIM6               NaN           NaN           NaN           NaN
S22                 NaN           NaN           NaN           NaN
S66                 NaN           NaN           NaN           NaN
HEAVY28             NaN           NaN           NaN           NaN
WATER27             NaN           NaN           NaN           NaN
CARBHB12            NaN           NaN           NaN           NaN
PNICO23             NaN           NaN           NaN           NaN
HAL59               NaN           NaN           NaN           NaN
AHB21               NaN           NaN           NaN           NaN
CHB6                NaN           NaN           NaN           NaN
IL16                NaN           NaN           NaN           NaN
IDISP               NaN           NaN           NaN           NaN
ICONF               NaN           NaN           NaN           NaN
ACONF               NaN           NaN           NaN           NaN
Amino20x4      0.370467      0.662938       0.03153      0.033728
PCONF21             NaN           NaN           NaN           NaN
MCONF               NaN           NaN           NaN           NaN
SCONF               NaN           NaN           NaN           NaN
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL           NaN           NaN           NaN           NaN

data_path       1424849                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary         0.32847      0.352175      0.031172       0.03176
W4_11          0.128193      0.146661      0.023594      0.021439
G21EA          0.079752      0.090296      0.012511      0.012762
G21IP          0.081996      0.086805      0.005995      0.006154
DIPCS10        0.101593      0.107438      0.005017      0.003622
PA26           0.268845        0.2982      0.034744      0.038429
SIE4x4         0.071736      0.093996      0.003569      0.001311
ALKBDE10       0.098409       0.10564      0.065934      0.061711
YBDE18         0.257196      0.276239      0.041119      0.041601
AL2X6          0.395256      0.396501      0.002764      0.002336
HEAVYSB11      0.288568      0.278481      0.011631      0.009043
NBPRC          0.237834      0.252724      0.032958      0.032482
ALK8           0.202733      0.187227      0.040614      0.040223
RC21           0.244294      0.258984      0.071539      0.082447
G2RC           0.163856      0.181463      0.015502      0.015617
BH76RC          0.12608       0.14036      0.055976      0.057338
FH51           0.342554      0.346443      0.024006      0.026834
TAUT15         0.369822      0.413544      0.067899      0.069453
DC13           0.390599      0.397856      0.020702      0.019322
MB16_43        0.500446      0.536587      0.084707      0.086338
DARC           0.426179      0.443789      0.014191      0.019082
RSE43          0.209548      0.233351      0.034582      0.033645
BSR36          0.534747      0.495778      0.004311      0.001683
CDIE20         0.370491       0.36033      0.039229      0.043548
ISO34           0.29061      0.298776      0.025594      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.522926      0.599811      0.074776      0.079046
BH76            0.12608       0.14036      0.055976      0.057338
BHPERI         0.329315      0.326909      0.031284      0.029987
BHDIV10        0.342553      0.361694      0.049657      0.049067
INV24          0.778226      0.784024      0.038296      0.027518
BHROT27        0.289291      0.303021      0.021441      0.018507
PX13           0.215428      0.278637      0.012669       0.01315
WCPT18         0.197421      0.224154      0.060305      0.057861
RG18           0.204128      0.206046        0.0023      0.002641
ADIM6          0.480426      0.434301      0.000826       0.00024
S22            0.385426      0.405222      0.025222      0.024365
S66            0.331414      0.347655      0.022744      0.025355
HEAVY28        0.096282      0.106754      0.017323      0.009702
WATER27        0.393804      0.547345       0.02721      0.033217
CARBHB12       0.176663      0.195377      0.033396      0.036954
PNICO23        0.208847      0.233577        0.0258      0.023517
HAL59          0.399949      0.412527      0.042605      0.036969
AHB21          0.108228      0.129997      0.032458      0.031459
CHB6           0.162305       0.16005      0.019153      0.019259
IL16           0.290156      0.335812      0.049496       0.05021
IDISP           0.89541      0.816401      0.002265      0.000619
ICONF          0.464768      0.533359      0.023171      0.022986
ACONF          0.384884      0.355398      0.003603      0.001781
Amino20x4      0.723524      0.806256       0.02953      0.037327
PCONF21         1.05244      1.184712      0.058859      0.077448
MCONF          0.933391      0.987572      0.038508      0.045477
SCONF          0.606237      0.725383      0.033587      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.338723      0.380054      0.025886       0.02199

data_path       1477959                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.350368      0.352175      0.031145       0.03176
W4_11          0.186413      0.146661      0.023796      0.021439
G21EA          0.192157      0.090296      0.011974      0.012762
G21IP           0.17953      0.086805      0.005725      0.006154
DIPCS10        0.104472      0.107438       0.00465      0.003622
PA26           0.280971        0.2982      0.033641      0.038429
SIE4x4         0.073243      0.093996       0.00307      0.001311
ALKBDE10       0.197857       0.10564      0.059171      0.061711
YBDE18         0.276881      0.276239      0.041751      0.041601
AL2X6          0.397261      0.396501      0.004259      0.002336
HEAVYSB11      0.372505      0.278481      0.012989      0.009043
NBPRC          0.250504      0.252724      0.034747      0.032482
ALK8            0.20123      0.187227      0.040302      0.040223
RC21           0.282382      0.258984      0.077081      0.082447
G2RC           0.171268      0.181463      0.014511      0.015617
BH76RC          0.17284       0.14036      0.055875      0.057338
FH51           0.352062      0.346443      0.024213      0.026834
TAUT15         0.382889      0.413544      0.063327      0.069453
DC13           0.394209      0.397856        0.0199      0.019322
MB16_43        0.518319      0.536587      0.085993      0.086338
DARC            0.43824      0.443789      0.016183      0.019082
RSE43          0.221193      0.233351      0.032998      0.033645
BSR36          0.542894      0.495778      0.004083      0.001683
CDIE20          0.37753       0.36033      0.041556      0.043548
ISO34          0.297902      0.298776      0.025764      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.553555      0.599811      0.074639      0.079046
BH76            0.17284       0.14036      0.055875      0.057338
BHPERI         0.334479      0.326909      0.029768      0.029987
BHDIV10        0.354819      0.361694      0.048886      0.049067
INV24          0.775858      0.784024      0.033142      0.027518
BHROT27          0.2971      0.303021      0.018071      0.018507
PX13           0.231526      0.278637      0.013336       0.01315
WCPT18         0.208865      0.224154      0.056134      0.057861
RG18           0.179104      0.206046      0.001997      0.002641
ADIM6           0.48435      0.434301      0.001643       0.00024
S22            0.387376      0.405222      0.023323      0.024365
S66            0.337834      0.347655      0.024427      0.025355
HEAVY28        0.104617      0.106754      0.010183      0.009702
WATER27        0.434595      0.547345      0.032091      0.033217
CARBHB12       0.180261      0.195377      0.035722      0.036954
PNICO23        0.215655      0.233577      0.025109      0.023517
HAL59          0.414432      0.412527      0.037615      0.036969
AHB21          0.107541      0.129997      0.032795      0.031459
CHB6           0.159904       0.16005      0.018723      0.019259
IL16           0.304386      0.335812      0.047181       0.05021
IDISP          0.889045      0.816401      0.002625      0.000619
ICONF          0.495197      0.533359      0.024403      0.022986
ACONF          0.390973      0.355398      0.004544      0.001781
Amino20x4       0.74916      0.806256      0.032621      0.037327
PCONF21        1.089551      1.184712      0.067288      0.077448
MCONF           0.95053      0.987572      0.042898      0.045477
SCONF          0.646453      0.725383      0.026626      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.357095      0.380054      0.025126       0.02199

data_path        159476
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary         0.33618      0.352175      0.031936       0.03176
W4_11           0.19315      0.146661      0.024329      0.021439
G21EA          0.211761      0.090296      0.013024      0.012762
G21IP          0.177748      0.086805      0.005826      0.006154
DIPCS10        0.098613      0.107438      0.004881      0.003622
PA26           0.268144        0.2982      0.034311      0.038429
SIE4x4         0.070542      0.093996      0.009341      0.001311
ALKBDE10       0.172533       0.10564      0.064789      0.061711
YBDE18         0.261568      0.276239       0.04697      0.041601
AL2X6          0.390976      0.396501       0.00336      0.002336
HEAVYSB11      0.370033      0.278481      0.010724      0.009043
NBPRC          0.241206      0.252724      0.032656      0.032482
ALK8           0.201046      0.187227      0.041985      0.040223
RC21           0.292008      0.258984      0.079362      0.082447
G2RC           0.163206      0.181463      0.016131      0.015617
BH76RC         0.153172       0.14036      0.056446      0.057338
FH51            0.34163      0.346443      0.024024      0.026834
TAUT15         0.363721      0.413544      0.063372      0.069453
DC13           0.382797      0.397856      0.021779      0.019322
MB16_43         0.49997      0.536587      0.084309      0.086338
DARC           0.419245      0.443789      0.017559      0.019082
RSE43           0.21203      0.233351      0.033827      0.033645
BSR36          0.526658      0.495778      0.003411      0.001683
CDIE20         0.363487       0.36033      0.042014      0.043548
ISO34           0.28526      0.298776      0.025396      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.522436      0.599811      0.077732      0.079046
BH76           0.153172       0.14036      0.056446      0.057338
BHPERI         0.319908      0.326909      0.030926      0.029987
BHDIV10        0.342259      0.361694      0.048973      0.049067
INV24          0.748863      0.784024      0.033707      0.027518
BHROT27        0.284163      0.303021      0.021124      0.018507
PX13           0.219264      0.278637      0.011982       0.01315
WCPT18         0.197936      0.224154       0.05551      0.057861
RG18           0.178286      0.206046      0.001938      0.002641
ADIM6          0.479014      0.434301      0.000161       0.00024
S22            0.371083      0.405222      0.023538      0.024365
S66            0.322999      0.347655      0.024984      0.025355
HEAVY28        0.094064      0.106754      0.012324      0.009702
WATER27        0.402764      0.547345      0.030219      0.033217
CARBHB12       0.170664      0.195377      0.035827      0.036954
PNICO23        0.204218      0.233577      0.025572      0.023517
HAL59          0.390665      0.412527      0.042097      0.036969
AHB21          0.100792      0.129997      0.032137      0.031459
CHB6           0.157837       0.16005      0.017535      0.019259
IL16           0.286298      0.335812       0.04876       0.05021
IDISP          0.869694      0.816401      0.003228      0.000619
ICONF          0.475162      0.533359      0.026679      0.022986
ACONF          0.374242      0.355398      0.004458      0.001781
Amino20x4      0.706369      0.806256      0.033034      0.037327
PCONF21        1.024412      1.184712       0.06637      0.077448
MCONF           0.90493      0.987572       0.04053      0.045477
SCONF          0.602564      0.725383      0.033746      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.337652      0.380054      0.029669       0.02199

MAE

data_path   3110260                                                      \
Disp type        AI       DFT    AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       2.911328  7.593534   2.740921  7.770653  2.614779   7.510308
sub2       8.300691  7.679827  10.160184  9.923965  7.524356   7.390144
sub3       2.883636  8.154842    3.59415  9.304708  3.257085   8.930725
sub4            NaN       NaN        NaN       NaN       NaN        NaN
sub5       1.943499  0.565402   1.938866  0.573805   1.90302   0.494451

data_path             1424849                       ...   1477959             \
Disp type Processed        AI        DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1        15 / 18  2.002477  13.710857  2.341162  ...  3.888615  13.713797
sub2          2 / 9  5.510109   6.612164   9.25763  ...  6.564252   6.757718
sub3          1 / 7  2.617318   6.261376  3.548881  ...   3.92612   6.934991
sub4         0 / 12   1.93524   3.272197  2.924356  ...  2.901616   4.988172
sub5          0 / 9  1.626727   1.321288   1.52729  ...  1.487843   0.872793

data_path              159476                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1        18 / 18  2.193095  13.710857  2.652661  14.259701  2.138404
sub2          7 / 9  7.307968   6.612164  11.13986   9.130043  8.413594
sub3          7 / 7    3.2322   6.261376  4.178805   7.355579  3.867937
sub4        11 / 12      1.89   3.272197  3.189003    5.03074  3.149296
sub5          8 / 9  2.134434   1.321288  1.426627   0.928323  1.455522

data_path
Disp type DFT_D3ZERO Processed
sub1       13.713797   18 / 18
sub2        6.757718     7 / 9
sub3        6.934991     7 / 7
sub4        4.988172   11 / 12
sub5        0.872793     8 / 9

[5 rows x 28 columns]

wtmad_1

data_path    3110260                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        4.250499   7.346209   3.866105    7.35409   3.743637   7.046431
sub2       18.522382  13.607499  15.231436  10.598832  16.088013  10.616946
sub3        3.959367   6.280619   5.053085   8.104562     4.3672   7.393063
sub4             NaN        NaN        NaN        NaN        NaN        NaN
sub5       19.434993   5.654023  19.388662   5.738052  19.030202   4.944508

data_path              1424849                        ...    1477959  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1        15 / 18   3.239113   7.420922   2.966668  ...   3.046364
sub2          2 / 9  13.142366   12.53052  11.927691  ...   9.389444
sub3          1 / 7   4.832263   6.984991   5.854163  ...   6.104995
sub4         0 / 12  11.556831  11.029773  13.901938  ...  13.234994
sub5          0 / 9  15.335367  11.571826  14.145431  ...  13.667041

data_path                          159476                                  \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ  DFT_D3BJ
sub1        7.102094   18 / 18   3.964682   7.420922   3.868929  7.414578
sub2       10.005283     7 / 9  12.087202   12.53052  10.046298  9.968137
sub3        7.521852     7 / 7   5.480279   6.984991    6.43503  8.150912
sub4       13.798614   11 / 12  11.506946  11.029773  14.836255  14.87552
sub5        7.523212     8 / 9  20.574666  11.571826  15.230239  8.092645

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        3.421741   7.102094   18 / 18
sub2        10.39895  10.005283     7 / 9
sub3        6.162506   7.521852     7 / 7
sub4       13.767672  13.798614   11 / 12
sub5       15.647331   7.523212     8 / 9

[5 rows x 28 columns]

wtmad_2

data_path   3110260                                                     \
Disp type        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       4.642117  8.204726  4.427596  8.388789  4.288009   8.133723
sub2       9.384654  7.823232  6.024007  4.550244  6.777811   5.073931
sub3       1.618578  4.917443  2.023259  5.601469  1.841603     5.3974
sub4            0.0       0.0       0.0       0.0       0.0        0.0
sub5       2.125853  0.618453  2.120786  0.627644  2.081576   0.540844

data_path             1424849                      ...   1477959             \
Disp type Processed        AI       DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1        15 / 18  1.438234  4.040696  1.379994  ...   1.68376   3.989769
sub2          2 / 9  3.339073  3.635331  2.970762  ...  2.765986   2.545677
sub3          1 / 7  1.303233  2.611064   1.66299  ...  1.817199   2.873647
sub4         0 / 12  4.683102  4.159493  6.811273  ...  6.318974    6.62018
sub5          0 / 9  6.331811   4.66236   6.30221  ...   5.89853    3.19725

data_path              159476                                          \
Disp type Processed        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO
sub1        18 / 18  1.805675  4.040696  1.824002  4.111446  1.628396
sub2          7 / 9  4.219056  3.635331   3.05496  2.376016  3.302024
sub3          7 / 7  1.502142  2.611064  1.888567  3.040013  1.770581
sub4        11 / 12  4.379061  4.159493  6.615548  6.856534   6.37219
sub5          8 / 9  7.607086   4.66236  6.051386  3.511844  6.087667

data_path
Disp type DFT_D3ZERO Processed
sub1        3.989769   18 / 18
sub2        2.545677     7 / 9
sub3        2.873647     7 / 7
sub4         6.62018   11 / 12
sub5         3.19725     8 / 9

[5 rows x 28 columns]

Summary of Subset
MAE

data_path    3110260                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       1.104162  14.046105   1.471259  14.726295    1.10995   14.05428
G21EA       1.220796  10.242827   1.220796   10.24281   1.220796   10.24281
G21IP       1.189518   8.953334   1.196269   8.946699   1.189486     8.9519
DIPCS10     2.459264  12.310852   2.437035  12.334099   2.492113  12.264655
PA26         2.92172   2.200766   2.957593   1.900152   2.894471    2.00824
SIE4x4      3.497919  21.908516    3.89499  22.337814   3.928829  22.339928
ALKBDE10     0.58825  18.125246   1.214033  18.838948   0.596224  18.135588
YBDE18      5.695577   8.145393   3.940864   7.265227   4.350211   7.472761
AL2X6       7.330717   5.659145   2.070144   1.332003   3.596271   1.829895
HEAVYSB11   2.498554   5.391476   1.756769   8.010474   1.014584   5.984154
NBPRC       3.318699    2.23255   5.191872   2.544088   4.244232   2.274234
ALK8        5.714555   4.400063   4.729365   3.174803   4.509772   2.559066
RC21        3.224684   4.820926   2.927041   6.671006   2.554759     6.0297
G2RC        2.599342   5.917203   2.956878   6.933515   2.657365   6.417298
BH76RC      0.686475   3.484561   0.606013   3.539828   0.657968   3.536982
FH51        2.789074   3.416596   2.378812   3.463486   2.364868   3.350373
TAUT15      2.337857    2.16453   2.364055   2.175485   2.318844   2.145937
DC13       13.198298  13.090861  12.255536  12.474047  11.732541  11.475687
MB16_43    13.802651  14.962156  32.589767  35.156222  18.454453  21.867406
DARC       13.130049   10.75415   5.615878    3.43411   7.953869    5.57797
RSE43       2.338544   3.130097   2.178616   2.903277   2.069005   2.748152
BSR36      11.158044   8.400969   3.804651   1.213644   5.836101   3.079026
CDIE20      2.096993   1.603741   1.820061   1.324399     1.8605   1.336151
ISO34              0          0          0          0          0          0
ISOL24             0          0          0          0          0          0
C60ISO             0          0          0          0          0          0
PArel       4.111056   1.365527   3.872234   1.315286    4.15976   1.201492
BH76        2.422966   9.107946    2.94745     9.8892   2.776885   9.676053
BHPERI      3.490353   3.736854   4.906722   7.052359   3.990507   6.124021
BHDIV10     5.964781   5.997058   7.305084   7.372128   6.334207   6.379114
INV24              0          0          0          0          0          0
BHROT27            0          0          0          0          0          0
PX13               0          0          0          0          0          0
WCPT18             0          0          0          0          0          0
RG18               0          0          0          0          0          0
ADIM6              0          0          0          0          0          0
S22                0          0          0          0          0          0
S66                0          0          0          0          0          0
HEAVY28            0          0          0          0          0          0
WATER27            0          0          0          0          0          0
CARBHB12           0          0          0          0          0          0
PNICO23            0          0          0          0          0          0
HAL59              0          0          0          0          0          0
AHB21              0          0          0          0          0          0
CHB6               0          0          0          0          0          0
IL16               0          0          0          0          0          0
IDISP              0          0          0          0          0          0
ICONF              0          0          0          0          0          0
ACONF              0          0          0          0          0          0
Amino20x4   1.943499   0.565402   1.938866   0.573805    1.90302   0.494451
PCONF21            0          0          0          0          0          0
MCONF              0          0          0          0          0          0
SCONF              0          0          0          0          0          0
UPU23              0          0          0          0          0          0
BUT14DIOL          0          0          0          0          0          0

data_path              1424849                        ...    1477959  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11      35 / 140   1.028249  29.506863   2.441523  ...   7.671953
G21EA        7 / 25   0.816732   9.754522   0.812414  ...   0.762055
G21IP       36 / 36   0.694714   8.953334   0.702841  ...   0.614381
DIPCS10     10 / 10   2.042735  12.310852   2.034436  ...   1.781653
PA26        26 / 26   3.009087   2.200766   2.998221  ...   2.723703
SIE4x4      16 / 16   3.430805  21.908516   3.716252  ...   4.226585
ALKBDE10      9 / 9   0.959132  18.125246   1.307356  ...   0.891988
YBDE18      18 / 18   5.939045   8.145393   3.828518  ...   3.790343
AL2X6         6 / 6   6.140013   5.659145   2.086328  ...   1.400038
HEAVYSB11     7 / 7   2.024005   5.391476   3.570429  ...   1.123495
NBPRC       12 / 12   3.058861    2.23255   2.325813  ...   2.054559
ALK8          8 / 8   4.403777   4.400063   3.075723  ...   3.222369
RC21        21 / 21   2.456062   4.820926   2.009509  ...   2.522696
G2RC        25 / 25   1.887093   5.917203    2.60955  ...   2.203841
BH76RC      30 / 30    0.85212   3.484561   1.035153  ...     2.0105
FH51        44 / 51   2.464205   3.703657   2.323411  ...   2.685611
TAUT15      15 / 15   1.702465    2.16453   1.631979  ...   2.143758
DC13        13 / 13   6.170057  13.090861   7.562068  ...   5.223725
MB16_43     35 / 43   13.39941  15.461604  35.416173  ...  21.210708
DARC        14 / 14   7.823359   10.75415   2.327124  ...   2.090283
RSE43       40 / 43    3.11738     3.1576   2.896011  ...   1.151571
BSR36       36 / 36    4.98276    8.40118   3.343238  ...   6.608983
CDIE20      14 / 20   1.450234   1.599507   1.483496  ...   1.599577
ISO34        0 / 34   2.020035   2.001743   1.659329  ...   1.967111
ISOL24       0 / 24          0          0          0  ...          0
C60ISO        0 / 9          0          0          0  ...          0
PArel        9 / 20   3.015433   1.743933   2.882746  ...   2.542718
BH76        76 / 76   2.803583   9.107946   3.232992  ...   4.048827
BHPERI      12 / 26   2.657111   3.268992    6.88257  ...   6.052698
BHDIV10      9 / 10   4.741552   6.277706   5.390696  ...   4.743676
INV24        0 / 24   3.393792   2.697333   3.863218  ...   4.659452
BHROT27      0 / 27   1.713103   0.853379   1.734055  ...   1.724082
PX13         0 / 13   1.059156  11.042023   1.291815  ...    3.40769
WCPT18       0 / 18   2.039614   7.967151   2.977303  ...   2.581806
RG18         0 / 18    0.30936   0.230018   0.765676  ...   0.695749
ADIM6         0 / 6   3.598266   3.059029   2.516398  ...   2.898327
S22          0 / 22   2.728845   2.291252   3.309309  ...   3.330413
S66          0 / 66   2.326488   1.894709    1.79261  ...   2.000288
HEAVY28       0 / 0          0          0          0  ...          0
WATER27      0 / 27    3.02651  16.299413   8.262183  ...  10.351126
CARBHB12     0 / 12   0.484944   1.632408   1.161335  ...   1.196297
PNICO23      0 / 23   0.840943   0.776429   2.313413  ...    1.71233
HAL59        0 / 31   2.035403   1.649786   2.945249  ...   2.359015
AHB21        0 / 21   1.666768   2.453821   2.321702  ...   1.623786
CHB6          0 / 4   1.766454    1.80532   1.334639  ...   0.789961
IL16         0 / 16   1.467889   1.021067   3.988457  ...   2.118899
IDISP         0 / 6  13.356085  13.125475   5.787398  ...   6.448828
ICONF        0 / 17   0.946016   0.413804    0.81078  ...    1.93877
ACONF        0 / 15   3.016487   0.546621   2.340276  ...    1.39715
Amino20x4   20 / 80   1.243276   0.656235   1.235374  ...    1.16062
PCONF21      0 / 18    2.09681   3.214782    2.27087  ...   1.641679
MCONF        0 / 51   1.596087    1.95602   1.874388  ...   1.641333
SCONF        0 / 17   1.154998   0.512352   1.080344  ...    1.28859
UPU23        0 / 23          0          0          0  ...          0
BUT14DIOL    0 / 64   0.879011   0.645099   1.125573  ...   1.220607

data_path                           159476                                   \
Disp type DFT_D3ZERO  Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11      29.861055  140 / 140   1.286939  29.506863   2.760332  31.211753
G21EA       9.757546    25 / 25   0.658726   9.754522    0.65354   9.751745
G21IP         8.9519    36 / 36   0.824931   8.953334   0.831436   8.946699
DIPCS10    12.264655    10 / 10   1.391071  12.310852   1.374795  12.334099
PA26         2.00824    26 / 26   3.451096   2.200766   3.624491   1.900152
SIE4x4     22.339928    16 / 16   4.608686  21.908516    4.99926  22.337814
ALKBDE10   18.135588      9 / 9   1.128721  18.125246   1.655727  18.838948
YBDE18      7.472761    18 / 18   5.287801   8.145393   3.226052   7.265227
AL2X6       1.829895      6 / 6   5.272431   5.659145   2.107522   1.332003
HEAVYSB11   5.984154      7 / 7   1.340974   5.391476   3.326087   8.010474
NBPRC       2.274234    12 / 12   1.865653    2.23255   3.166716   2.544088
ALK8        2.559066      8 / 8   4.860571   4.400063   2.327345   3.174803
RC21          6.0297    21 / 21     2.0906   4.820926   2.553898   6.671006
G2RC        6.417298    25 / 25   2.095055   5.917203   2.758019   6.933515
BH76RC      3.536982    30 / 30   0.567373   3.484561   0.729287   3.539828
FH51        3.256908    51 / 51    2.84409   3.703657   2.676036    3.39478
TAUT15      2.145937    15 / 15   2.938737    2.16453    2.84807   2.175485
DC13       11.475687    13 / 13   8.660819  13.090861  10.121426  12.474047
MB16_43    23.165472    43 / 43   15.45975  15.461604  42.921798  36.862998
DARC         5.57797    14 / 14   7.642319   10.75415   1.475205    3.43411
RSE43        2.74911    43 / 43   1.644613     3.1576    1.46534   2.916276
BSR36       3.079237    36 / 36  14.583644    8.40118   7.230251   1.213741
CDIE20      1.347484    20 / 20   1.805128   1.599507   1.856359   1.336544
ISO34       1.647042    34 / 34   2.449916   2.001743   2.013615   1.577125
ISOL24             0     0 / 24          0          0          0          0
C60ISO             0      0 / 9          0          0          0          0
PArel       1.645025    20 / 20   2.389115   1.743933   2.209585   1.733749
BH76        9.676053    76 / 76   2.764701   9.107946   3.402306     9.8892
BHPERI        6.4139    26 / 26   4.875311   3.268992   9.152285   7.804724
BHDIV10     6.535109    10 / 10    4.30792   6.277706   4.807665   7.448955
INV24       2.228547    24 / 24    5.90539   2.697333   6.338552   2.346995
BHROT27      0.78352    27 / 27   1.654553   0.853379    1.70617   0.858852
PX13       11.219857    13 / 13   2.129179  11.042023   1.840724   11.82601
WCPT18      8.744304    18 / 18   1.833923   7.967151   2.441984   9.151986
RG18        0.709552    18 / 18    0.25197   0.230018   0.643552   0.655714
ADIM6       2.390824      6 / 6   3.246551   3.059029   2.400184   2.090256
S22         2.291758    22 / 22   2.798907   2.291252   4.794765   2.402928
S66         2.101976    66 / 66   2.265931   1.894709   1.985833   2.058561
HEAVY28            0      0 / 0          0          0          0          0
WATER27    26.402884    27 / 27   3.101877  16.299413  10.530712  25.491048
CARBHB12    2.841777    12 / 12   1.130936   1.632408   1.021214   2.973103
PNICO23     1.726817    23 / 23   1.176683   0.776429   2.720352   2.604046
HAL59       2.247276    29 / 29   1.549194   1.649786   2.353709   2.629912
AHB21       3.294519    21 / 21   0.945116   2.453821   1.504996   3.464384
CHB6        2.309161      4 / 4   0.911816    1.80532   1.119068   3.038126
IL16        4.409963    16 / 16   2.075678   1.021067   3.255696   4.339132
IDISP       5.245746      6 / 6  16.655366  13.125475   5.013826   4.423061
ICONF       0.493337    17 / 17    3.28723   0.413804   3.061452   0.464652
ACONF       0.274429    15 / 15   1.221203   0.546621   0.970293   0.430751
Amino20x4   0.576975    80 / 80    1.14307   0.656235    1.22229   0.647041
PCONF21     1.099663    18 / 18   3.006814   3.214782   2.547715   1.178453
MCONF       0.711618    51 / 51   2.934697    1.95602   1.194645   0.741352
SCONF       1.317952    17 / 17   2.174855   0.512352    1.93288   1.432857
UPU23              0     0 / 23          0          0          0          0
BUT14DIOL    1.02002    64 / 64   1.026327   0.645099   0.753534   1.136703

data_path
Disp type  AI_D3ZERO DFT_D3ZERO  Processed
W4_11       1.566923  29.861055  140 / 140
G21EA       0.667552   9.757546    25 / 25
G21IP       0.828134     8.9519    36 / 36
DIPCS10     1.417127  12.264655    10 / 10
PA26        3.514561    2.00824    26 / 26
SIE4x4      5.037052  22.339928    16 / 16
ALKBDE10    1.134636  18.135588      9 / 9
YBDE18      3.647748   7.472761    18 / 18
AL2X6       2.901307   1.829895      6 / 6
HEAVYSB11     1.3591   5.984154      7 / 7
NBPRC       1.967695   2.274234    12 / 12
ALK8        2.398859   2.559066      8 / 8
RC21        2.164664     6.0297    21 / 21
G2RC        2.322526   6.417298    25 / 25
BH76RC       0.66413   3.536982    30 / 30
FH51        2.566568   3.256908    51 / 51
TAUT15      2.552394   2.145937    15 / 15
DC13        8.502893  11.475687    13 / 13
MB16_43    27.457521  23.165472    43 / 43
DARC        2.733875    5.57797    14 / 14
RSE43       1.342873    2.74911    43 / 43
BSR36       9.261701   3.079237    36 / 36
CDIE20      1.864759   1.347484    20 / 20
ISO34       2.109289   1.647042    34 / 34
ISOL24             0          0     0 / 24
C60ISO             0          0      0 / 9
PArel       2.386571   1.645025    20 / 20
BH76        3.197262   9.676053    76 / 76
BHPERI       7.76146     6.4139    26 / 26
BHDIV10     4.416718   6.535109    10 / 10
INV24       6.128354   2.228547    24 / 24
BHROT27     1.727736    0.78352    27 / 27
PX13        2.144293  11.219857    13 / 13
WCPT18       2.21209   8.744304    18 / 18
RG18         0.69739   0.709552    18 / 18
ADIM6       2.661404   2.390824      6 / 6
S22         4.683072   2.291758    22 / 22
S66         2.021056   2.101976    66 / 66
HEAVY28            0          0      0 / 0
WATER27    11.435094  26.402884    27 / 27
CARBHB12    0.903716   2.841777    12 / 12
PNICO23     1.843124   1.726817    23 / 23
HAL59       1.972894   2.247276    29 / 29
AHB21       1.327143   3.294519    21 / 21
CHB6        0.814932   2.309161      4 / 4
IL16        3.322614   4.409963    16 / 16
IDISP       6.162437   5.245746      6 / 6
ICONF       3.249385   0.493337    17 / 17
ACONF       0.929833   0.274429    15 / 15
Amino20x4   1.177498   0.576975    80 / 80
PCONF21     2.647433   1.099663    18 / 18
MCONF        1.13395   0.711618    51 / 51
SCONF         1.9709   1.317952    17 / 17
UPU23              0          0     0 / 23
BUT14DIOL   0.792622    1.02002    64 / 64

[55 rows x 28 columns]

In [2]:
# import numpy as np
np.max(mean_absolute_deviation_list), np.sum(mean_absolute_deviation_list), np.mean(
    mean_absolute_deviation_list
)

(np.float64(1207.482739432191),
 np.float64(98414.09024557225),
 np.float64(71.1084467092285))

In [5]:
mole_name

'BH76RC-NH'

In [9]:
e1 = -4.6025270679642568e02  # orca fc DLPNO-CCSD
e2 = -4.6025221729046751e02  # orca fc CCSD
e3 = -4.6025767731174767e02 # orca nfc CCSD
e4 = -4.6025796979352134e02 # orca nfc DLPNO-CCSD
e = -460.257677434825  # pyscf CCSD
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 3.11912268e+00  3.42629231e+00  7.72321803e-05 -1.83457852e-01]
[-1.07996860e-05 -1.18632336e-05 -2.67409583e-10  6.35206561e-07]

In [14]:
e = -460.2602125077868 # pyscf CCSD(t)
e1 = -4.6026021233042377e02 # orca nfc CCSD(t)
e2 = -4.6026021233042360e02 # orca old nfc CCSD(t)
e3 = -4.6026042971888393e02  # orca nfc DLPNO-CCSD(t)
e4 = -4.6025500524617820e02
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 1.11296967e-04  1.11297074e-04 -1.36302021e-01  3.26760599e+00]
[-3.85353766e-10 -3.85354136e-10  4.71931076e-07 -1.13137340e-05]

In [ ]:
np.array([[-4.366423914512e-02], [0.000000000000e00], [-5.569827800646e-01]])
np.array([[-4.366423911029e-02], [0.000000000000e00], [-5.569827799431e-01]])

[[-4.366423908914e-02], [0.000000000000e00], [-5.569827798789e-01]]

array([[-3.48300000e-11],
       [ 0.00000000e+00],
       [-1.21500032e-10]])