In [11]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_ai = np.argsort(data_subset[name_subset]["ai"])[
                    ::-1
                ][:5]
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ][:5]
                for i in range(len(argsort_atomic_energy_ai)):
                    i_reaction_name = data_subset[name_subset]["name"][
                        argsort_atomic_energy_ai[i]
                    ]
                    i_reaction = json_data[f"reaction-{i_subset}"][i_reaction_name]
                    print(
                        f"Top {i+1} AI: {data_subset[name_subset]['ai'][argsort_atomic_energy_ai[i]]} kcal/mol, {i_reaction_name} in {name_subset}",
                    )
                    systems_list = i_reaction["systems"]
                    stoichiometry_list = i_reaction["stoichiometry"]
                    for j in range(len(systems_list)):
                        mole_name = (
                            systems_list[j]
                            if i_subset == "BH76RC"
                            else f"{i_subset}-{systems_list[j]}"
                        )
                        stoichiometry = int(stoichiometry_list[j])
                        if mole_name in json_data:
                            if isinstance(json_data[mole_name], str):
                                mole_name = json_data[mole_name]
                        print(f"  {stoichiometry} * {mole_name}", end="")
                        col = np.where(data_name == mole_name)[0]
                        if col.size == 1:
                            error_energy_ai = (
                                data_scf[col[0]] - data_cc[col[0]]
                            )
                            print(f"  {stoichiometry} * {error_energy_ai}", end="")
                    print()

                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

print("Summary")
display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset_ele.to_csv(f"../validate/df_summary_subset_ele_{date}.csv")
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
mean_subset.to_csv(f"../validate/mean_subset_{date}.csv")
wtmad_1_subset.to_csv(f"../validate/wtmad_1_subset_{date}.csv")
wtmad_2_subset.to_csv(f"../validate/wtmad_2_subset_{date}.csv")
# save summary to excel with date
df_summary_subset_ele.to_excel(f"../validate/df_summary_subset_ele_{date}.xlsx")
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
Top 1 AI: 28.642543112975545 kcal/mol, 116 in 3110260_W4_11
  -1 * W4_11-p4  -1 * 3.9123830266762525  4 * W4_11-p  4 * 8.13873153491295
Top 2 AI: 15.835139658709522 kcal/mol, 122 in 3110260_W4_11
  -1 * W4_11-p2  -1 * 0.4423234111163765  2 * W4_11-p  2 * 8.13873153491295
Top 3 AI: 7.358472908810086 kcal/mol, 13 in 3110260_W4_11
  -1 * W4_11-ph3  -1 * 0.9053690542641561  1 * W4_11-p  1 * 8.13873153491295  3 * W4_11-h  3 * 0.041703476053783106
Top 4 AI: 6.986845495994203 kcal/mol, 57 in 3110260_W4_11
  -1 * W4_11-becl2  -1 * 7.059663417749107  1 * W4_11-be  1 * -0.012091999411495635  2 * W4_11-cl  2 * 0.042454960581380874
Top 5 AI: 4.620493889204226 kcal/mol, 41 in 3110260_W4_11
  -1 * W4_11-sif4  -1 * 3.7717739615472965  1 * W4_11-si  1 * 0.04056976587162353  4 * W4_11-f  4 * -0.22232242338213837
Top 1 DFT: 64.9391765203327 kcal/mol
Top 2 DFT: 64.82811637483246 kcal/mol
Top 3 DFT: 58.7866408124537 kcal/mol
Top 4 DFT: 55.610892266675364 kcal/mol
Top 5 DFT: 55.139185982690606 kcal/mol
Top 1 AI: 5.456945814948995 kcal/mol, 4 in 3110260_G21EA
  1 * G21EA-EA_p  1 * 8.13879939247272  -1 * G21EA-EA_p-  -1 * 2.681853577523725
Top 2 AI: 5.2981968373351265 kcal/mol, 20 in 3110260_G21EA
  1 * G21EA-EA_21n  1 * 0.9490697379951598  -1 * G21EA-EA_21  -1 * -4.349127099339967
Top 3 AI: 2.5827776629594155 kcal/mol, 14 in 3110260_G21EA
  1 * G21EA-EA_15n  1 * 0.2877018981380388  -1 * G21EA-EA_15  -1 * -2.2950757648213767
Top 4 AI: 2.5698391957084823 kcal/mol, 8 in 3110260_G21EA
  1 * G21EA-EA_9n  1 * -0.28766975984399323  -1 * G21EA-EA_9  -1 * -2.8575089555524755
Top 5 AI: 2.1000224005401833 kcal/mol, 10 in 3110260_G21EA
  1 * G21EA-EA_11n  1 * -0.22423601847549435  -1 * G21EA-EA_11  -1 * 1.875786382064689
Top 1 DFT: 17.922119285416557 kcal/mol
Top 2 DFT: 14.542179432406556 kcal/mol
Top 3 DFT: 13.792081636143848 kcal/mol
Top 4 DFT: 13.585563076587277 kcal/mol
Top 5 DFT: 13.248573637160007 kcal/mol
Top 1 AI: 8.427570651256246 kcal/mol, 12 in 3110260_G21IP
  1 * G21IP-p+  1 * -0.28883511215099134  -1 * G21IP-p  -1 * 8.138735539105255
Top 2 AI: 4.557701185811311 kcal/mol, 32 in 3110260_G21IP
  1 * G21IP-IP_77  1 * -3.460982849006541  -1 * G21IP-44  -1 * 1.09671833680477
Top 3 AI: 2.6624732824857347 kcal/mol, 13 in 3110260_G21IP
  1 * G21IP-s+  1 * 1.594669062353205  -1 * G21IP-s  -1 * -1.0678042201325297
Top 4 AI: 2.293455765931867 kcal/mol, 25 in 3110260_G21IP
  1 * G21IP-IP_70  1 * -1.8144865477224812  -1 * G21IP-22  -1 * 0.47896921820938587
Top 5 AI: 2.149540416052332 kcal/mol, 22 in 3110260_G21IP
  1 * G21IP-IP_66  1 * -0.9090660988877062  -1 * G21IP-19  -1 * 1.240474317164626
Top 1 DFT: 24.652048565418227 kcal/mol
Top 2 DFT: 19.50703940328094 kcal/mol
Top 3 DFT: 16.821335594599077 kcal/mol
Top 4 DFT: 16.4504761478438 kcal/mol
Top 5 DFT: 16.230253286354127 kcal/mol
Top 1 AI: 13.151544620079221 kcal/mol, 0 in 3110260_DIPCS10
  -1 * DIPCS10-c4h4  -1 * 4.931360746821156  1 * DIPCS10-c4h4_2+  1 * -8.220183873258065
Top 2 AI: 2.7858384416031186 kcal/mol, 6 in 3110260_DIPCS10
  -1 * DIPCS10-h2s  -1 * 0.4187827483692672  1 * DIPCS10-h2s_2+  1 * -2.3670556932338513
Top 3 AI: 1.7497801931749564 kcal/mol, 7 in 3110260_DIPCS10
  -1 * DIPCS10-ph3  -1 * 0.8644076259224676  1 * DIPCS10-ph3_2+  1 * -0.8853725672524888
Top 4 AI: 0.7637248396058567 kcal/mol, 3 in 3110260_DIPCS10
  -1 * DIPCS10-n2h2  -1 * 0.21744626626605168  1 * DIPCS10-n2h2_2+  1 * -0.546278573339805
Top 5 AI: 0.34800681106025877 kcal/mol, 9 in 3110260_DIPCS10
  -1 * DIPCS10-be  -1 * -0.012091999411495635  1 * DIPCS10-be_2+  1 * 0.33591481164876313
Top 1 DFT: 21.238722962967586 kcal/mol
Top 2 DFT: 18.410172816045815 kcal/mol
Top 3 DFT: 17.180242111804546 kcal/mol
Top 4 DFT: 16.016684862523107 kcal/mol
Top 5 DFT: 13.03569706963026 kcal/mol
Top 1 AI: 10.075289307103958 kcal/mol, 12 in 3110260_PA26
  1 * PA26-c2f6  1 * -1.2366409514797851  -1 * PA26-c2f6p  -1 * -11.311930258583743
Top 2 AI: 9.43036078233854 kcal/mol, 2 in 3110260_PA26
  1 * PA26-p6  1 * -2.913489336555358  -1 * PA26-p6p  -1 * -12.343850118893897
Top 3 AI: 9.381618391576922 kcal/mol, 3 in 3110260_PA26
  1 * PA26-p8  1 * -5.039990413031774  -1 * PA26-p8p  -1 * -14.421608804608695
Top 4 AI: 6.841010796750197 kcal/mol, 1 in 3110260_PA26
  1 * PA26-p4  1 * -1.2760832408093847  -1 * PA26-p4p  -1 * -8.117094037559582
Top 5 AI: 5.546741634752834 kcal/mol, 15 in 3110260_PA26
  1 * PA26-gly  1 * -0.9816480923036579  -1 * PA26-glyp  -1 * 4.565093542449176
Top 1 DFT: 5.496021041501081 kcal/mol
Top 2 DFT: 3.952208415896166 kcal/mol
Top 3 DFT: 3.843404227809515 kcal/mol
Top 4 DFT: 3.7666994354804046 kcal/mol
Top 5 DFT: 3.7500070057285484 kcal/mol
Top 1 AI: 8.252297865707078 kcal/mol, 11 in 3110260_SIE4x4
  1 * SIE4x4-nh3  1 * 0.09659215021383716  1 * SIE4x4-nh3+  1 * -0.18624499792349525  -1 * SIE4x4-nh32+_1.75  -1 * -8.34195071340946
Top 2 AI: 6.045587770156715 kcal/mol, 3 in 3110260_SIE4x4
  1 * SIE4x4-h  1 * 0.041703475932706624  -1 * SIE4x4-h2+_1.75  -1 * -6.003884294224008
Top 3 AI: 6.019947847359617 kcal/mol, 7 in 3110260_SIE4x4
  1 * SIE4x4-he  1 * -0.059528109031361964  1 * SIE4x4-he+  1 * -0.11116047794121187  -1 * SIE4x4-he2+_1.75  -1 * -6.190636434332191
Top 4 AI: 4.614506821337272 kcal/mol, 9 in 3110260_SIE4x4
  1 * SIE4x4-nh3  1 * 0.09659215021383716  1 * SIE4x4-nh3+  1 * -0.18624499792349525  -1 * SIE4x4-nh32+_1.25  -1 * -4.7041596690396545
Top 5 AI: 4.525759620197732 kcal/mol, 6 in 3110260_SIE4x4
  1 * SIE4x4-he  1 * -0.059528109031361964  1 * SIE4x4-he+  1 * -0.11116047794121187  -1 * SIE4x4-he2+_1.5  -1 * -4.696448207170306
Top 1 DFT: 42.48945061229006 kcal/mol
Top 2 DFT: 36.3825565542179 kcal/mol
Top 3 DFT: 34.02966520233895 kcal/mol
Top 4 DFT: 29.669328280849186 kcal/mol
Top 5 DFT: 29.26023051775701 kcal/mol
Warning: ALKBDE10-kf not found in data json, ERROR
Top 1 AI: 1.1474460433455533 kcal/mol, 1 in 3110260_ALKBDE10
  -1 * ALKBDE10-beo  -1 * 0.7771206785328104  1 * ALKBDE10-be  1 * -0.012091999411495635  1 * ALKBDE10-o  1 * -0.35823336540488526
Top 2 AI: 0.850806721864501 kcal/mol, 8 in 3110260_ALKBDE10
  -1 * ALKBDE10-mgs  -1 * 0.1503180312574841  1 * ALKBDE10-mg  1 * 0.23533581841911655  1 * ALKBDE10-s  1 * -0.9358245090115815
Top 3 AI: 0.8435605316917645 kcal/mol, 5 in 3110260_ALKBDE10
  -1 * ALKBDE10-lif  -1 * -0.5456536798155867  1 * ALKBDE10-li  1 * -0.9707283387351708  1 * ALKBDE10-f  1 * -0.4184858727749088
Top 4 AI: 0.7970571230252972 kcal/mol, 3 in 3110260_ALKBDE10
  -1 * ALKBDE10-hf  -1 * 0.42027472618065076  1 * ALKBDE10-h  1 * 0.04170347593264978  1 * ALKBDE10-f  1 * -0.4184858727749088
Top 5 AI: 0.5106605393739301 kcal/mol, 6 in 3110260_ALKBDE10
  -1 * ALKBDE10-lio  -1 * -0.8183011647706735  1 * ALKBDE10-li  1 * -0.9707283387351708  1 * ALKBDE10-o  1 * -0.35823336540488526
Top 1 DFT: 42.20618001303956 kcal/mol
Top 2 DFT: 26.422307972352428 kcal/mol
Top 3 DFT: 19.54640414734604 kcal/mol
Top 4 DFT: 16.150239486240025 kcal/mol
Top 5 DFT: 15.581684817676432 kcal/mol
Top 1 AI: 16.35184964547807 kcal/mol, 10 in 3110260_YBDE18
  -1 * YBDE18-nme3-cbh22  -1 * 13.408740388258593  1 * YBDE18-nme3  1 * 3.3074661725840997  1 * YBDE18-cbh22  1 * -6.250575429803575
Top 2 AI: 11.975409410180873 kcal/mol, 4 in 3110260_YBDE18
  -1 * YBDE18-me2s-cbh22  -1 * 5.098699011839926  1 * YBDE18-me2s  1 * -0.6261349685373716  1 * YBDE18-cbh22  1 * -6.250575429803575
Top 3 AI: 11.337697420312907 kcal/mol, 12 in 3110260_YBDE18
  -1 * YBDE18-pf3-cbh22  -1 * -3.3643207364948466  1 * YBDE18-pf3  1 * -8.451442727004178  1 * YBDE18-cbh22  1 * -6.250575429803575
Top 4 AI: 8.15214415905939 kcal/mol, 16 in 3110260_YBDE18
  -1 * YBDE18-pme3-cbh22  -1 * 7.16525477176765  1 * YBDE18-pme3  1 * 5.263686042511836  1 * YBDE18-cbh22  1 * -6.250575429803575
Top 5 AI: 7.061685347882303 kcal/mol, 11 in 3110260_YBDE18
  -1 * YBDE18-nme3-ch2  -1 * 10.186905626003863  1 * YBDE18-nme3  1 * 3.3074661725840997  1 * YBDE18-ch2  1 * -0.18224589446253958
Top 1 DFT: 16.44728826175924 kcal/mol
Top 2 DFT: 12.740130906568083 kcal/mol
Top 3 DFT: 10.883027330586629 kcal/mol
Top 4 DFT: 10.488881110526563 kcal/mol
Top 5 DFT: 10.40475183620947 kcal/mol
Top 1 AI: 14.358381757687312 kcal/mol, 3 in 3110260_AL2X6
  -1 * AL2X6-al2me4  -1 * 15.242374974885024  2 * AL2X6-alme2  2 * 0.44199660859885626
Top 2 AI: 12.299650994478725 kcal/mol, 5 in 3110260_AL2X6
  -1 * AL2X6-al2me6  -1 * 18.761417556146625  2 * AL2X6-alme3  2 * 3.2308832808339503
Top 3 AI: 11.439706759992987 kcal/mol, 4 in 3110260_AL2X6
  -1 * AL2X6-al2me5  -1 * 15.112586649425793  1 * AL2X6-alme2  1 * 0.44199660859885626  1 * AL2X6-alme3  1 * 3.2308832808339503
Top 4 AI: 11.158171597402543 kcal/mol, 2 in 3110260_AL2X6
  -1 * AL2X6-al2cl6  -1 * 21.804630232043564  2 * AL2X6-alcl3  2 * 5.323229317320511
Top 5 AI: 2.387112698284909 kcal/mol, 1 in 3110260_AL2X6
  -1 * AL2X6-al2f6  -1 * 2.3444772663060576  2 * AL2X6-alf3  2 * -0.02131771598942578
Top 1 DFT: 9.084031574253459 kcal/mol
Top 2 DFT: 7.0848077459668275 kcal/mol
Top 3 DFT: 5.3300173038151115 kcal/mol
Top 4 DFT: 5.070575412944891 kcal/mol
Top 5 DFT: 4.9637361988425255 kcal/mol
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Top 1 AI: 5.18323316751048 kcal/mol, 7 in 3110260_HEAVYSB11
  2 * HEAVYSB11-asme2  2 * -3.076395070645958  -1 * HEAVYSB11-as2me4  -1 * -0.9695569737814367
Top 2 AI: 4.587720962706953 kcal/mol, 0 in 3110260_HEAVYSB11
  2 * HEAVYSB11-geh3  2 * -3.366732048569247  -1 * HEAVYSB11-ge2h6  -1 * -2.145743134431541
Top 3 AI: 3.737360712373629 kcal/mol, 6 in 3110260_HEAVYSB11
  2 * HEAVYSB11-pme2  2 * 1.372055274900049  -1 * HEAVYSB11-p2me4  -1 * 6.481471262173727
Top 4 AI: 1.1250122329220176 kcal/mol, 4 in 3110260_HEAVYSB11
  2 * HEAVYSB11-seh  2 * -3.5313082044012845  -1 * HEAVYSB11-h2se2  -1 * -5.937604175880551
Top 5 AI: 0.6542561785900034 kcal/mol, 3 in 3110260_HEAVYSB11
  2 * HEAVYSB11-sh  2 * -0.1685295877396129  -1 * HEAVYSB11-h2s2  -1 * -0.9913153540692292
Top 1 DFT: 10.68985605717171 kcal/mol
Top 2 DFT: 9.494120202027261 kcal/mol
Top 3 DFT: 7.114256684028078 kcal/mol
Top 4 DFT: 6.325384678319097 kcal/mol
Top 5 DFT: 1.569642293266952 kcal/mol
Top 1 AI: 14.551393091212958 kcal/mol, 8 in 3110260_NBPRC
  1 * NBPRC-BF3PMe3  1 * -10.939911896421108  -1 * NBPRC-BF3  -1 * -1.5427302409370895  -1 * NBPRC-PMe3  -1 * 5.154211435758043
Top 2 AI: 10.193908280401956 kcal/mol, 3 in 3110260_NBPRC
  -2 * NBPRC-nh2-bh2  -2 * -1.418316851137206  1 * NBPRC-cbut  1 * 7.357274578127544
Top 3 AI: 7.970957694838262 kcal/mol, 11 in 3110260_NBPRC
  1 * NBPRC-K_Cl  1 * 18.60839938861318  -1 * NBPRC-BCl3PMe3  -1 * 10.932327614398673  -1 * NBPRC-H2  -1 * -0.29488592062375574
Top 4 AI: 5.759813805256272 kcal/mol, 5 in 3110260_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * -1.418316851137206  1 * NBPRC-ch  1 * 1.5048632518446539
Top 5 AI: 3.1363012369424723 kcal/mol, 4 in 3110260_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * -1.418316851137206  1 * NBPRC-bz  1 * -0.302193245239323  3 * NBPRC-h2  3 * -0.2721520237431605
Top 1 DFT: 8.843319919425994 kcal/mol
Top 2 DFT: 4.25873367569875 kcal/mol
Top 3 DFT: 3.4078239038353786 kcal/mol
Top 4 DFT: 2.532460168497778 kcal/mol
Top 5 DFT: 2.2723810925637054 kcal/mol
Top 1 AI: 12.731561890090234 kcal/mol, 2 in 3110260_ALK8
  -1 * ALK8-li4_me4  -1 * 8.041766562397243  4 * ALK8-li_me  4 * -1.1724488319232478
Top 2 AI: 11.1521625041496 kcal/mol, 1 in 3110260_ALK8
  -1 * ALK8-na8  -1 * 13.74036004114896  4 * ALK8-na2  4 * 0.6470493842498399
Top 3 AI: 5.051048340981652 kcal/mol, 0 in 3110260_ALK8
  -1 * ALK8-li8  -1 * -4.076887195187737  4 * ALK8-li2  4 * 0.24354028644847858
Top 4 AI: 4.047839514765656 kcal/mol, 6 in 3110260_ALK8
  -1 * ALK8-li2_ch2n_2  -1 * 2.9901586050982587  2 * ALK8-li_ch2n  2 * -0.5288404548336985
Top 5 AI: 1.8713386880281178 kcal/mol, 4 in 3110260_ALK8
  -1 * ALK8-li2_ch4  -1 * -1.4879502839030465  1 * ALK8-li_me  1 * -1.1724488319232478  1 * ALK8-li_h  1 * -2.1868401400079165
Top 1 DFT: 13.423444515326992 kcal/mol
Top 2 DFT: 13.339023275213549 kcal/mol
Top 3 DFT: 3.2870388831361197 kcal/mol
Top 4 DFT: 1.8348026665917132 kcal/mol
Top 5 DFT: 1.3258451606470771 kcal/mol
Top 1 AI: 10.114710481910151 kcal/mol, 12 in 3110260_RC21
  -1 * RC21-6e  -1 * 6.942599280708237  1 * RC21-6p1  1 * -2.9374847468716325  1 * RC21-ethylene  1 * -0.23462645433028229
Top 2 AI: 7.702585141116288 kcal/mol, 11 in 3110260_RC21
  -1 * RC21-6e  -1 * 6.942599280708237  1 * RC21-6int  1 * -0.7599858604080509
Top 3 AI: 6.09506754213362 kcal/mol, 14 in 3110260_RC21
  -1 * RC21-6e  -1 * 6.942599280708237  1 * RC21-1p2  1 * -0.028110495069995522  1 * RC21-pr  1 * 0.8756422336446121
Top 4 AI: 5.548408869646664 kcal/mol, 1 in 3110260_RC21
  -1 * RC21-1e  -1 * 5.246780792018399  1 * RC21-1p2  1 * -0.028110495069995522  1 * RC21-1p3  1 * -0.2735175825582701
Top 5 AI: 4.671549031569157 kcal/mol, 18 in 3110260_RC21
  -1 * RC21-8e  -1 * -3.4469057413516566  1 * RC21-8p1  1 * -7.883828318590531  1 * RC21-ethylene  1 * -0.23462645433028229
Top 1 DFT: 14.185896344562934 kcal/mol
Top 2 DFT: 11.848156853782712 kcal/mol
Top 3 DFT: 9.843254908562812 kcal/mol
Top 4 DFT: 8.613347860442445 kcal/mol
Top 5 DFT: 7.032865641926037 kcal/mol
Top 1 AI: 13.071970715653151 kcal/mol, 10 in 3110260_G2RC
  -1 * G2RC-67  -1 * 14.192222280893475  -1 * G2RC-61  -1 * 0.526256600918714  1 * G2RC-66  1 * 3.6638936139643192  1 * G2RC-62  1 * -2.0173854478634894
Top 2 AI: 12.0559726286956 kcal/mol, 0 in 3110260_G2RC
  -1 * G2RC-118  -1 * -2.064360038319137  1 * G2RC-117  1 * 10.17321210319642  1 * G2RC-13  1 * -0.18159951281995745
Top 3 AI: 4.267222010894329 kcal/mol, 12 in 3110260_G2RC
  -1 * G2RC-25  -1 * -0.002941299564554356  -1 * G2RC-26  -1 * -0.21700412553036585  1 * G2RC-88  1 * 4.047276585799409
Top 4 AI: 3.8658611618884606 kcal/mol, 17 in 3110260_G2RC
  -1 * G2RC-56  -1 * -2.946959156426601  -3 * G2RC-1  -3 * -0.2956895558644419  1 * G2RC-21  1 * 0.395032363536302  2 * G2RC-13  2 * -0.18159951281995745
Top 5 AI: 3.0440807469421998 kcal/mol, 23 in 3110260_G2RC
  -3 * G2RC-25  -3 * -0.002941299564554356  1 * G2RC-94  1 * -3.052904645621311
Top 1 DFT: 16.861372091829253 kcal/mol
Top 2 DFT: 13.550974861325813 kcal/mol
Top 3 DFT: 11.457349740527434 kcal/mol
Top 4 DFT: 10.800692827404418 kcal/mol
Top 5 DFT: 10.432011227676412 kcal/mol
Top 1 AI: 2.998179710819386 kcal/mol, BH76RC_6 in 3110260_BH76RC
  -1 * BH76-fch3clcomp1  -1 * -0.4985412415699102  1 * BH76-fch3clcomp2  1 * -3.496720952389296
Top 2 AI: 2.5538633376563666 kcal/mol, BH76RC_1 in 3110260_BH76RC
  -1 * BH76-h  -1 * 0.04170347593259294  -1 * BH76-n2o  -1 * 2.982829794535064  1 * BH76-oh  1 * -0.2616333846381167  1 * BH76-n2  1 * 0.7323033174470766
Top 3 AI: 2.1310103418363724 kcal/mol, BH76RC_12 in 3110260_BH76RC
  -1 * BH76-ch3  -1 * 0.2068503704322211  -1 * BH76-c2h4  -1 * -0.16863330314663472  1 * BH76-c3h7  1 * 2.1692274091328727
Top 4 AI: 1.949976020201575 kcal/mol, BH76RC_8 in 3110260_BH76RC
  -1 * BH76-hoch3fcomp2  -1 * -3.2119552275689784  1 * BH76-hoch3fcomp1  1 * -1.2619792073674034
Top 5 AI: 1.7431487748981453 kcal/mol, BH76RC_29 in 3110260_BH76RC
  -1 * BH76-C2H6  -1 * 0.5193451034792815  -1 * BH76-NH2  -1 * 0.6065819352952531  1 * BH76-c2h5  1 * -0.44761204390670173  1 * BH76-NH3  1 * -0.16960969220963307
Top 1 DFT: 16.943700659729075 kcal/mol
Top 2 DFT: 11.4192808540829 kcal/mol
Top 3 DFT: 9.908463760002633 kcal/mol
Top 4 DFT: 9.5446835977491 kcal/mol
Top 5 DFT: 7.421772861736827 kcal/mol
Warning: FH51-methylcyclohexane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C3H7CO2C2H3 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanediol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-HCON_C2H5_2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-propylthiophene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C4H9SO3H not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-n-nonane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C6H12O not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-Heptene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-methylcyclohexa-1,3-diene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-ethyl-g-butyrolactone not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-3-methylpentane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-propylfuran not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-ax-methylcyclohexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-methylcyclohexa-1,4-diene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-methyl-d-valerolactone not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-dimethylbutane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C3H7S_2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-3-hexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-hexandione not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-HCO2C5H11 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-1-hexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-diethyloxirane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C4H9NHCONH2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-eq-methylcyclohexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-tetramethylpentane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-n-hexane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-neo-hexane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-CO_2NHC3H7_2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C6H12O not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C4H9SO3H not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanediol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-methylcyclohexane not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-3-hexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-ax-methylcyclohexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-1-hexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-1-hexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-CO_2NHC3H7_2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-eq-methylcyclohexene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-Heptene not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C4H9NHCONH2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-propylfuran not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-HCON_C2H5_2 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-C3H7CO2C2H3 not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file
Warning: FH51-pentanol not found in ccdft_cc-pVDZ_atom-1-3110260_gmtkn-cc-pVDZ data file

/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/dhem/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/_core/_methods.py:145: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

Summary

data_path       3110260                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.198877      0.247006      0.036954      0.032363
W4_11           0.16156      0.148744      0.028608      0.021439
G21EA          0.294814      0.109608      0.014994      0.012762
G21IP          0.151887      0.102494      0.007099      0.006154
DIPCS10         0.07944      0.107438      0.006365      0.003622
PA26           0.183548        0.2982      0.036632      0.038429
SIE4x4         0.070077      0.093996      0.018423      0.001311
ALKBDE10       0.187007       0.10564      0.061391      0.061711
YBDE18         0.186926      0.276239      0.058031      0.041601
AL2X6          0.345115      0.396501      0.008773      0.002336
HEAVYSB11      0.231863      0.278481      0.015922      0.009043
NBPRC          0.174247      0.252724       0.04845      0.032482
ALK8           0.212319      0.187227      0.040648      0.040223
RC21           0.196255      0.258984      0.075438      0.082447
G2RC           0.128206      0.181463      0.020456      0.015617
BH76RC         0.144839       0.14036      0.060358      0.057338
FH51           0.185359      0.291878      0.036715      0.029176
TAUT15          0.26756      0.413544      0.073232      0.069453
DC13           0.245509      0.397856      0.025266      0.019322
MB16_43         0.38961      0.489942       0.07826      0.079477
DARC           0.238854      0.432745      0.024154      0.019359
RSE43          0.129077      0.193985      0.044826      0.034976
BSR36          0.291378      0.495777      0.005656      0.001683
CDIE20         0.193758      0.324292      0.044676      0.044435
ISO34               NaN           NaN           NaN           NaN
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.354378      0.539445      0.079482       0.06207
BH76           0.144839       0.14036      0.060358      0.057338
BHPERI          0.12822      0.197659      0.041323      0.031454
BHDIV10             NaN           NaN           NaN           NaN
INV24               NaN           NaN           NaN           NaN
BHROT27             NaN           NaN           NaN           NaN
PX13                NaN           NaN           NaN           NaN
WCPT18              NaN           NaN           NaN           NaN
RG18                NaN           NaN           NaN           NaN
ADIM6               NaN           NaN           NaN           NaN
S22                 NaN           NaN           NaN           NaN
S66                 NaN           NaN           NaN           NaN
HEAVY28             NaN           NaN           NaN           NaN
WATER27             NaN           NaN           NaN           NaN
CARBHB12            NaN           NaN           NaN           NaN
PNICO23             NaN           NaN           NaN           NaN
HAL59               NaN           NaN           NaN           NaN
AHB21               NaN           NaN           NaN           NaN
CHB6                NaN           NaN           NaN           NaN
IL16                NaN           NaN           NaN           NaN
IDISP               NaN           NaN           NaN           NaN
ICONF               NaN           NaN           NaN           NaN
ACONF               NaN           NaN           NaN           NaN
Amino20x4      0.375241      0.662938      0.032944      0.033728
PCONF21             NaN           NaN           NaN           NaN
MCONF               NaN           NaN           NaN           NaN
SCONF               NaN           NaN           NaN           NaN
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL           NaN           NaN           NaN           NaN

data_path       1424849                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary         0.32847      0.352175      0.031172       0.03176
W4_11          0.128193      0.146661      0.023594      0.021439
G21EA          0.079752      0.090296      0.012511      0.012762
G21IP          0.081996      0.086805      0.005995      0.006154
DIPCS10        0.101593      0.107438      0.005017      0.003622
PA26           0.268845        0.2982      0.034744      0.038429
SIE4x4         0.071736      0.093996      0.003569      0.001311
ALKBDE10       0.098409       0.10564      0.065934      0.061711
YBDE18         0.257196      0.276239      0.041119      0.041601
AL2X6          0.395256      0.396501      0.002764      0.002336
HEAVYSB11      0.288568      0.278481      0.011631      0.009043
NBPRC          0.237834      0.252724      0.032958      0.032482
ALK8           0.202733      0.187227      0.040614      0.040223
RC21           0.244294      0.258984      0.071539      0.082447
G2RC           0.163856      0.181463      0.015502      0.015617
BH76RC          0.12608       0.14036      0.055976      0.057338
FH51           0.342554      0.346443      0.024006      0.026834
TAUT15         0.369822      0.413544      0.067899      0.069453
DC13           0.390599      0.397856      0.020702      0.019322
MB16_43        0.500446      0.536587      0.084707      0.086338
DARC           0.426179      0.443789      0.014191      0.019082
RSE43          0.209548      0.233351      0.034582      0.033645
BSR36          0.534747      0.495778      0.004311      0.001683
CDIE20         0.370491       0.36033      0.039229      0.043548
ISO34           0.29061      0.298776      0.025594      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.522926      0.599811      0.074776      0.079046
BH76            0.12608       0.14036      0.055976      0.057338
BHPERI         0.329315      0.326909      0.031284      0.029987
BHDIV10        0.342553      0.361694      0.049657      0.049067
INV24          0.778226      0.784024      0.038296      0.027518
BHROT27        0.289291      0.303021      0.021441      0.018507
PX13           0.215428      0.278637      0.012669       0.01315
WCPT18         0.197421      0.224154      0.060305      0.057861
RG18           0.204128      0.206046        0.0023      0.002641
ADIM6          0.480426      0.434301      0.000826       0.00024
S22            0.385426      0.405222      0.025222      0.024365
S66            0.331414      0.347655      0.022744      0.025355
HEAVY28        0.096282      0.106754      0.017323      0.009702
WATER27        0.393804      0.547345       0.02721      0.033217
CARBHB12       0.176663      0.195377      0.033396      0.036954
PNICO23        0.208847      0.233577        0.0258      0.023517
HAL59          0.399949      0.412527      0.042605      0.036969
AHB21          0.108228      0.129997      0.032458      0.031459
CHB6           0.162305       0.16005      0.019153      0.019259
IL16           0.290156      0.335812      0.049496       0.05021
IDISP           0.89541      0.816401      0.002265      0.000619
ICONF          0.464768      0.533359      0.023171      0.022986
ACONF          0.384884      0.355398      0.003603      0.001781
Amino20x4      0.723524      0.806256       0.02953      0.037327
PCONF21         1.05244      1.184712      0.058859      0.077448
MCONF          0.933391      0.987572      0.038508      0.045477
SCONF          0.606237      0.725383      0.033587      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.338723      0.380054      0.025886       0.02199

data_path       1477959                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.350368      0.352175      0.031145       0.03176
W4_11          0.186413      0.146661      0.023796      0.021439
G21EA          0.192157      0.090296      0.011974      0.012762
G21IP           0.17953      0.086805      0.005725      0.006154
DIPCS10        0.104472      0.107438       0.00465      0.003622
PA26           0.280971        0.2982      0.033641      0.038429
SIE4x4         0.073243      0.093996       0.00307      0.001311
ALKBDE10       0.197857       0.10564      0.059171      0.061711
YBDE18         0.276881      0.276239      0.041751      0.041601
AL2X6          0.397261      0.396501      0.004259      0.002336
HEAVYSB11      0.372505      0.278481      0.012989      0.009043
NBPRC          0.250504      0.252724      0.034747      0.032482
ALK8            0.20123      0.187227      0.040302      0.040223
RC21           0.282382      0.258984      0.077081      0.082447
G2RC           0.171268      0.181463      0.014511      0.015617
BH76RC          0.17284       0.14036      0.055875      0.057338
FH51           0.352062      0.346443      0.024213      0.026834
TAUT15         0.382889      0.413544      0.063327      0.069453
DC13           0.394209      0.397856        0.0199      0.019322
MB16_43        0.518319      0.536587      0.085993      0.086338
DARC            0.43824      0.443789      0.016183      0.019082
RSE43          0.221193      0.233351      0.032998      0.033645
BSR36          0.542894      0.495778      0.004083      0.001683
CDIE20          0.37753       0.36033      0.041556      0.043548
ISO34          0.297902      0.298776      0.025764      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.553555      0.599811      0.074639      0.079046
BH76            0.17284       0.14036      0.055875      0.057338
BHPERI         0.334479      0.326909      0.029768      0.029987
BHDIV10        0.354819      0.361694      0.048886      0.049067
INV24          0.775858      0.784024      0.033142      0.027518
BHROT27          0.2971      0.303021      0.018071      0.018507
PX13           0.231526      0.278637      0.013336       0.01315
WCPT18         0.208865      0.224154      0.056134      0.057861
RG18           0.179104      0.206046      0.001997      0.002641
ADIM6           0.48435      0.434301      0.001643       0.00024
S22            0.387376      0.405222      0.023323      0.024365
S66            0.337834      0.347655      0.024427      0.025355
HEAVY28        0.104617      0.106754      0.010183      0.009702
WATER27        0.434595      0.547345      0.032091      0.033217
CARBHB12       0.180261      0.195377      0.035722      0.036954
PNICO23        0.215655      0.233577      0.025109      0.023517
HAL59          0.414432      0.412527      0.037615      0.036969
AHB21          0.107541      0.129997      0.032795      0.031459
CHB6           0.159904       0.16005      0.018723      0.019259
IL16           0.304386      0.335812      0.047181       0.05021
IDISP          0.889045      0.816401      0.002625      0.000619
ICONF          0.495197      0.533359      0.024403      0.022986
ACONF          0.390973      0.355398      0.004544      0.001781
Amino20x4       0.74916      0.806256      0.032621      0.037327
PCONF21        1.089551      1.184712      0.067288      0.077448
MCONF           0.95053      0.987572      0.042898      0.045477
SCONF          0.646453      0.725383      0.026626      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.357095      0.380054      0.025126       0.02199

data_path        159476
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary         0.33618      0.352175      0.031936       0.03176
W4_11           0.19315      0.146661      0.024329      0.021439
G21EA          0.211761      0.090296      0.013024      0.012762
G21IP          0.177748      0.086805      0.005826      0.006154
DIPCS10        0.098613      0.107438      0.004881      0.003622
PA26           0.268144        0.2982      0.034311      0.038429
SIE4x4         0.070542      0.093996      0.009341      0.001311
ALKBDE10       0.172533       0.10564      0.064789      0.061711
YBDE18         0.261568      0.276239       0.04697      0.041601
AL2X6          0.390976      0.396501       0.00336      0.002336
HEAVYSB11      0.370033      0.278481      0.010724      0.009043
NBPRC          0.241206      0.252724      0.032656      0.032482
ALK8           0.201046      0.187227      0.041985      0.040223
RC21           0.292008      0.258984      0.079362      0.082447
G2RC           0.163206      0.181463      0.016131      0.015617
BH76RC         0.153172       0.14036      0.056446      0.057338
FH51            0.34163      0.346443      0.024024      0.026834
TAUT15         0.363721      0.413544      0.063372      0.069453
DC13           0.382797      0.397856      0.021779      0.019322
MB16_43         0.49997      0.536587      0.084309      0.086338
DARC           0.419245      0.443789      0.017559      0.019082
RSE43           0.21203      0.233351      0.033827      0.033645
BSR36          0.526658      0.495778      0.003411      0.001683
CDIE20         0.363487       0.36033      0.042014      0.043548
ISO34           0.28526      0.298776      0.025396      0.026941
ISOL24              NaN           NaN           NaN           NaN
C60ISO              NaN           NaN           NaN           NaN
PArel          0.522436      0.599811      0.077732      0.079046
BH76           0.153172       0.14036      0.056446      0.057338
BHPERI         0.319908      0.326909      0.030926      0.029987
BHDIV10        0.342259      0.361694      0.048973      0.049067
INV24          0.748863      0.784024      0.033707      0.027518
BHROT27        0.284163      0.303021      0.021124      0.018507
PX13           0.219264      0.278637      0.011982       0.01315
WCPT18         0.197936      0.224154       0.05551      0.057861
RG18           0.178286      0.206046      0.001938      0.002641
ADIM6          0.479014      0.434301      0.000161       0.00024
S22            0.371083      0.405222      0.023538      0.024365
S66            0.322999      0.347655      0.024984      0.025355
HEAVY28        0.094064      0.106754      0.012324      0.009702
WATER27        0.402764      0.547345      0.030219      0.033217
CARBHB12       0.170664      0.195377      0.035827      0.036954
PNICO23        0.204218      0.233577      0.025572      0.023517
HAL59          0.390665      0.412527      0.042097      0.036969
AHB21          0.100792      0.129997      0.032137      0.031459
CHB6           0.157837       0.16005      0.017535      0.019259
IL16           0.286298      0.335812       0.04876       0.05021
IDISP          0.869694      0.816401      0.003228      0.000619
ICONF          0.475162      0.533359      0.026679      0.022986
ACONF          0.374242      0.355398      0.004458      0.001781
Amino20x4      0.706369      0.806256      0.033034      0.037327
PCONF21        1.024412      1.184712       0.06637      0.077448
MCONF           0.90493      0.987572       0.04053      0.045477
SCONF          0.602564      0.725383      0.033746      0.024507
UPU23               NaN           NaN           NaN           NaN
BUT14DIOL      0.337652      0.380054      0.029669       0.02199

MAE

data_path    3110260                                                        \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1        2.372453  14.280722   2.428717  14.924369  2.133859  14.348492
sub2       10.425595   8.684263  10.068753  10.397427  8.073331   7.899968
sub3        2.640863   9.098642   2.967028   9.914242  2.850656   9.689848
sub4             NaN        NaN        NaN        NaN       NaN        NaN
sub5        1.273278   0.565402    1.27075   0.573805  1.227705   0.494451

data_path             1424849                       ...   1477959             \
Disp type Processed        AI        DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1        17 / 18  2.002477  13.710857  2.341161  ...  3.888615  13.713797
sub2          1 / 9  5.510109   6.612164  9.257621  ...  6.564266   6.757732
sub3          1 / 7  2.617318   6.261376  3.548881  ...   3.92612   6.934991
sub4         0 / 12   1.93524   3.272197  2.924356  ...  2.901616   4.988172
sub5          0 / 9  1.626727   1.321288   1.52729  ...  1.487843   0.872793

data_path              159476                                             \
Disp type Processed        AI        DFT    AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1        18 / 18  2.193095  13.710857   2.652661  14.259701  2.138403
sub2          7 / 9  7.307968   6.612164  11.139874   9.130052  8.413608
sub3          7 / 7    3.2322   6.261376   4.178805   7.355579  3.867937
sub4        11 / 12      1.89   3.272197   3.189003    5.03074  3.149296
sub5          8 / 9  2.134434   1.321288   1.426627   0.928323  1.455522

data_path
Disp type DFT_D3ZERO Processed
sub1       13.713797   18 / 18
sub2        6.757732     7 / 9
sub3        6.934991     7 / 7
sub4        4.988172   11 / 12
sub5        0.872793     8 / 9

[5 rows x 28 columns]

wtmad_1

data_path    3110260                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        4.355732   7.377209   3.995796   7.414035   3.818076   7.096457
sub2       17.660464  14.209048  14.387062  11.172939  15.047083  11.187724
sub3        4.979405   8.749748   6.835036  10.853316   6.243599  10.207157
sub4             NaN        NaN        NaN        NaN        NaN        NaN
sub5       12.732778   5.654023    12.7075   5.738052  12.277054   4.944508

data_path              1424849                        ...    1477959  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1        17 / 18   3.239113   7.420922   2.966668  ...   3.046364
sub2          1 / 9  13.142366   12.53052  11.927684  ...   9.389455
sub3          1 / 7   4.832263   6.984991   5.854163  ...   6.104995
sub4         0 / 12  11.556831  11.029773  13.901938  ...  13.234994
sub5          0 / 9  15.335367  11.571826  14.145431  ...  13.667041

data_path                          159476                                  \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ  DFT_D3BJ
sub1        7.102094   18 / 18   3.964682   7.420922   3.868929  7.414578
sub2       10.005295     7 / 9  12.087202   12.53052   10.04631  9.968145
sub3        7.521852     7 / 7   5.480279   6.984991    6.43503  8.150912
sub4       13.798614   11 / 12  11.506946  11.029773  14.836255  14.87552
sub5        7.523212     8 / 9  20.574666  11.571826  15.230239  8.092645

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        3.421741   7.102094   18 / 18
sub2       10.398962  10.005295     7 / 9
sub3        6.162506   7.521852     7 / 7
sub4       13.767672  13.798614   11 / 12
sub5       15.647331   7.523212     8 / 9

[5 rows x 28 columns]

wtmad_2

data_path    3110260                                                      \
Disp type         AI        DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1        6.548376  14.218321  6.340195  14.65431  6.068882  14.212224
sub2       11.489861   8.822553  6.945341  4.488376  7.997865    5.31153
sub3        1.778836   6.182447  1.990599  6.728201  1.914592    6.57848
sub4             0.0        0.0       0.0       0.0       0.0        0.0
sub5        1.912903    0.84943  1.909106  0.862054  1.844438   0.742836

data_path             1424849                      ...   1477959             \
Disp type Processed        AI       DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1        17 / 18  1.438234  4.040696  1.379994  ...   1.68376   3.989769
sub2          1 / 9  3.339073  3.635331  2.970755  ...  2.765998   2.545688
sub3          1 / 7  1.303233  2.611064   1.66299  ...  1.817199   2.873647
sub4         0 / 12  4.683102  4.159493  6.811273  ...  6.318974    6.62018
sub5          0 / 9  6.331811   4.66236   6.30221  ...   5.89853    3.19725

data_path              159476                                          \
Disp type Processed        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO
sub1        18 / 18  1.805675  4.040696  1.824002  4.111446  1.628396
sub2          7 / 9  4.219056  3.635331  3.054971  2.376023  3.302036
sub3          7 / 7  1.502142  2.611064  1.888567  3.040013  1.770581
sub4        11 / 12  4.379061  4.159493  6.615548  6.856534   6.37219
sub5          8 / 9  7.607086   4.66236  6.051386  3.511844  6.087667

data_path
Disp type DFT_D3ZERO Processed
sub1        3.989769   18 / 18
sub2        2.545688     7 / 9
sub3        2.873647     7 / 7
sub4         6.62018   11 / 12
sub5         3.19725     8 / 9

[5 rows x 28 columns]

Summary of Subset
MAE

data_path    3110260                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       1.283783  29.506863   1.829601  31.211753   1.170543  29.861055
G21EA       1.308792   9.754522   1.314104   9.751745   1.300673   9.757546
G21IP       1.073901   8.953334   1.080964   8.946699   1.075434     8.9519
DIPCS10     1.941904  12.310852   1.932049  12.334099    1.98976  12.264655
PA26        2.711683   2.200766   2.800009   1.900152   2.789493    2.00824
SIE4x4       2.85344  21.908516   3.224883  22.337814   3.282441  22.339928
ALKBDE10    0.593435  18.125246     0.5386  18.838948   0.583093  18.135588
YBDE18      5.074164   8.145393   3.228603   7.265227   3.637949   7.472761
AL2X6       8.936535   5.659145   3.155039   1.332003   5.107285   1.829895
HEAVYSB11   2.252862   5.391476   2.270553   8.010474   0.894766   5.984154
NBPRC       4.351381    2.23255     5.1807   2.544088   4.534255   2.274234
ALK8        4.591736   4.400063   3.698529   3.174803   2.668097   2.559066
RC21        2.930378   4.820926   2.583504   6.671006   2.257191     6.0297
G2RC        2.352266   5.917203   2.761017   6.933515   2.539796   6.417298
BH76RC      0.955492   3.484561   0.819127   3.539828   0.924793   3.536982
FH51        2.567083   2.916822   2.413515   3.385014   2.209178   3.155435
TAUT15      2.714948    2.16453    2.74366   2.175485   2.688323   2.145937
DC13       11.785004  13.090861  12.535288  12.474047  11.200103  11.475687
MB16_43    16.432498  15.852413  27.007341  33.975204  16.071406  21.536477
DARC        12.38055  10.505453    4.86861   3.347456    7.34017   5.465073
RSE43        2.37684   3.042021   2.186353    2.83457    2.05159   2.700194
BSR36      12.976767   8.400969   5.623455   1.213694   7.654904   3.079106
CDIE20      1.823816   1.695626   1.572399   1.413647   1.601785   1.402871
ISO34              0          0          0          0          0          0
ISOL24             0          0          0          0          0          0
C60ISO             0          0          0          0          0          0
PArel       3.695566   1.738616   3.554205   1.659679   3.714653   1.539787
BH76        2.578501   9.107946   2.863882     9.8892   2.760177   9.676053
BHPERI      7.380308   8.391549  10.806191  11.817432    9.72702  10.738261
BHDIV10            0          0          0          0          0          0
INV24              0          0          0          0          0          0
BHROT27            0          0          0          0          0          0
PX13               0          0          0          0          0          0
WCPT18             0          0          0          0          0          0
RG18               0          0          0          0          0          0
ADIM6              0          0          0          0          0          0
S22                0          0          0          0          0          0
S66                0          0          0          0          0          0
HEAVY28            0          0          0          0          0          0
WATER27            0          0          0          0          0          0
CARBHB12           0          0          0          0          0          0
PNICO23            0          0          0          0          0          0
HAL59              0          0          0          0          0          0
AHB21              0          0          0          0          0          0
CHB6               0          0          0          0          0          0
IL16               0          0          0          0          0          0
IDISP              0          0          0          0          0          0
ICONF              0          0          0          0          0          0
ACONF              0          0          0          0          0          0
Amino20x4   1.273278   0.565402    1.27075   0.573805   1.227705   0.494451
PCONF21            0          0          0          0          0          0
MCONF              0          0          0          0          0          0
SCONF              0          0          0          0          0          0
UPU23              0          0          0          0          0          0
BUT14DIOL          0          0          0          0          0          0

data_path               1424849                        ...    1477959  \
Disp type  Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11      140 / 140   1.028249  29.506863   2.441523  ...   7.671953
G21EA        25 / 25   0.816732   9.754522   0.812414  ...   0.762055
G21IP        36 / 36   0.694714   8.953334    0.70284  ...   0.614381
DIPCS10      10 / 10   2.042735  12.310852   2.034436  ...   1.781653
PA26         26 / 26   3.009087   2.200766   2.998221  ...   2.723703
SIE4x4       16 / 16   3.430805  21.908516   3.716252  ...   4.226585
ALKBDE10       9 / 9   0.959132  18.125246   1.307356  ...   0.891988
YBDE18       18 / 18   5.939045   8.145393   3.828518  ...   3.790343
AL2X6          6 / 6   6.140013   5.659145   2.086328  ...   1.400038
HEAVYSB11      7 / 7   2.024005   5.391476   3.570429  ...   1.123495
NBPRC        12 / 12   3.058861    2.23255   2.325813  ...   2.054559
ALK8           8 / 8   4.403777   4.400063   3.075723  ...   3.222369
RC21         21 / 21   2.456062   4.820926   2.009509  ...   2.522696
G2RC         25 / 25   1.887093   5.917203    2.60955  ...   2.203841
BH76RC       30 / 30    0.85212   3.484561   1.035153  ...     2.0105
FH51         24 / 51   2.464205   3.703657   2.323411  ...   2.685611
TAUT15       15 / 15   1.702465    2.16453   1.631979  ...   2.143758
DC13         13 / 13   6.170057  13.090861   7.562068  ...   5.223725
MB16_43      31 / 43   13.39941  15.461604  35.416173  ...  21.210708
DARC         13 / 14   7.823359   10.75415   2.327124  ...   2.090283
RSE43        22 / 43    3.11738     3.1576   2.896011  ...   1.151571
BSR36        36 / 36    4.98276    8.40118   3.343187  ...   6.609064
CDIE20       10 / 20   1.450234   1.599507   1.483496  ...   1.599577
ISO34         0 / 34   2.020035   2.001743   1.659329  ...   1.967111
ISOL24        0 / 24          0          0          0  ...          0
C60ISO         0 / 9          0          0          0  ...          0
PArel         6 / 20   3.015433   1.743933   2.882746  ...   2.542718
BH76         76 / 76   2.803583   9.107946   3.232992  ...   4.048827
BHPERI        1 / 26   2.657111   3.268992    6.88257  ...   6.052698
BHDIV10       0 / 10   4.741552   6.277706   5.390696  ...   4.743676
INV24         0 / 24   3.393792   2.697333   3.863218  ...   4.659452
BHROT27       0 / 27   1.713103   0.853379   1.734055  ...   1.724082
PX13          0 / 13   1.059156  11.042023   1.291815  ...    3.40769
WCPT18        0 / 18   2.039614   7.967151   2.977303  ...   2.581806
RG18          0 / 18    0.30936   0.230018   0.765676  ...   0.695749
ADIM6          0 / 6   3.598266   3.059029   2.516398  ...   2.898327
S22           0 / 22   2.728845   2.291252   3.309309  ...   3.330413
S66           0 / 66   2.326488   1.894709    1.79261  ...   2.000288
HEAVY28        0 / 0          0          0          0  ...          0
WATER27       0 / 27    3.02651  16.299413   8.262183  ...  10.351126
CARBHB12      0 / 12   0.484944   1.632408   1.161335  ...   1.196297
PNICO23       0 / 23   0.840943   0.776429   2.313413  ...    1.71233
HAL59         0 / 31   2.035403   1.649786   2.945249  ...   2.359015
AHB21         0 / 21   1.666768   2.453821   2.321702  ...   1.623786
CHB6           0 / 4   1.766454    1.80532   1.334639  ...   0.789961
IL16          0 / 16   1.467889   1.021067   3.988457  ...   2.118899
IDISP          0 / 6  13.356085  13.125475   5.787398  ...   6.448828
ICONF         0 / 17   0.946016   0.413804    0.81078  ...    1.93877
ACONF         0 / 15   3.016487   0.546621   2.340276  ...    1.39715
Amino20x4    20 / 80   1.243276   0.656235   1.235374  ...    1.16062
PCONF21       0 / 18    2.09681   3.214782    2.27087  ...   1.641679
MCONF         0 / 51   1.596087    1.95602   1.874388  ...   1.641333
SCONF         0 / 17   1.154998   0.512352   1.080344  ...    1.28859
UPU23         0 / 23          0          0          0  ...          0
BUT14DIOL     0 / 64   0.879011   0.645099   1.125573  ...   1.220607

data_path                           159476                                   \
Disp type DFT_D3ZERO  Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11      29.861054  140 / 140   1.286939  29.506863   2.760331  31.211752
G21EA       9.757546    25 / 25   0.658726   9.754522    0.65354   9.751745
G21IP         8.9519    36 / 36   0.824931   8.953334   0.831436   8.946699
DIPCS10    12.264655    10 / 10   1.391071  12.310852   1.374795  12.334099
PA26         2.00824    26 / 26   3.451096   2.200766   3.624491   1.900152
SIE4x4     22.339928    16 / 16   4.608686  21.908516    4.99926  22.337814
ALKBDE10   18.135588      9 / 9   1.128721  18.125246   1.655727  18.838948
YBDE18      7.472761    18 / 18   5.287801   8.145393   3.226052   7.265227
AL2X6       1.829895      6 / 6   5.272431   5.659145   2.107522   1.332003
HEAVYSB11   5.984154      7 / 7   1.340974   5.391476   3.326087   8.010474
NBPRC       2.274234    12 / 12   1.865653    2.23255   3.166716   2.544088
ALK8        2.559066      8 / 8   4.860571   4.400063   2.327345   3.174803
RC21          6.0297    21 / 21     2.0906   4.820926   2.553898   6.671006
G2RC        6.417298    25 / 25   2.095055   5.917203   2.758019   6.933515
BH76RC      3.536982    30 / 30   0.567373   3.484561   0.729287   3.539828
FH51        3.256908    51 / 51    2.84409   3.703657   2.676036    3.39478
TAUT15      2.145937    15 / 15   2.938737    2.16453    2.84807   2.175485
DC13       11.475687    13 / 13   8.660819  13.090861  10.121426  12.474047
MB16_43    23.165472    43 / 43   15.45975  15.461604  42.921798  36.862998
DARC         5.57797    14 / 14   7.642319   10.75415   1.475205    3.43411
RSE43        2.74911    43 / 43   1.644613     3.1576    1.46534   2.916276
BSR36       3.079317    36 / 36  14.583644    8.40118   7.230332    1.21379
CDIE20      1.347484    20 / 20   1.805128   1.599507   1.856359   1.336544
ISO34       1.647042    34 / 34   2.449916   2.001743   2.013615   1.577125
ISOL24             0     0 / 24          0          0          0          0
C60ISO             0      0 / 9          0          0          0          0
PArel       1.645025    20 / 20   2.389115   1.743933   2.209585   1.733749
BH76        9.676053    76 / 76   2.764701   9.107946   3.402306     9.8892
BHPERI        6.4139    26 / 26   4.875311   3.268992   9.152285   7.804724
BHDIV10     6.535109    10 / 10    4.30792   6.277706   4.807665   7.448955
INV24       2.228547    24 / 24    5.90539   2.697333   6.338552   2.346995
BHROT27      0.78352    27 / 27   1.654553   0.853379    1.70617   0.858852
PX13       11.219857    13 / 13   2.129179  11.042023   1.840724   11.82601
WCPT18      8.744304    18 / 18   1.833923   7.967151   2.441984   9.151986
RG18        0.709552    18 / 18    0.25197   0.230018   0.643552   0.655714
ADIM6       2.390824      6 / 6   3.246551   3.059029   2.400184   2.090256
S22         2.291758    22 / 22   2.798907   2.291252   4.794765   2.402928
S66         2.101976    66 / 66   2.265931   1.894709   1.985833   2.058561
HEAVY28            0      0 / 0          0          0          0          0
WATER27    26.402884    27 / 27   3.101877  16.299413  10.530712  25.491048
CARBHB12    2.841777    12 / 12   1.130936   1.632408   1.021214   2.973103
PNICO23     1.726817    23 / 23   1.176683   0.776429   2.720352   2.604046
HAL59       2.247276    29 / 29   1.549194   1.649786   2.353709   2.629912
AHB21       3.294519    21 / 21   0.945116   2.453821   1.504996   3.464384
CHB6        2.309161      4 / 4   0.911816    1.80532   1.119068   3.038126
IL16        4.409963    16 / 16   2.075678   1.021067   3.255696   4.339132
IDISP       5.245746      6 / 6  16.655366  13.125475   5.013826   4.423061
ICONF       0.493337    17 / 17    3.28723   0.413804   3.061452   0.464652
ACONF       0.274429    15 / 15   1.221203   0.546621   0.970293   0.430751
Amino20x4   0.576975    80 / 80    1.14307   0.656235    1.22229   0.647041
PCONF21     1.099663    18 / 18   3.006814   3.214782   2.547715   1.178453
MCONF       0.711618    51 / 51   2.934697    1.95602   1.194645   0.741352
SCONF       1.317952    17 / 17   2.174855   0.512352    1.93288   1.432857
UPU23              0     0 / 23          0          0          0          0
BUT14DIOL    1.02002    64 / 64   1.026327   0.645099   0.753534   1.136703

data_path
Disp type  AI_D3ZERO DFT_D3ZERO  Processed
W4_11       1.566922  29.861054  140 / 140
G21EA       0.667552   9.757546    25 / 25
G21IP       0.828134     8.9519    36 / 36
DIPCS10     1.417127  12.264655    10 / 10
PA26        3.514561    2.00824    26 / 26
SIE4x4      5.037052  22.339928    16 / 16
ALKBDE10    1.134636  18.135588      9 / 9
YBDE18      3.647748   7.472761    18 / 18
AL2X6       2.901307   1.829895      6 / 6
HEAVYSB11     1.3591   5.984154      7 / 7
NBPRC       1.967695   2.274234    12 / 12
ALK8        2.398859   2.559066      8 / 8
RC21        2.164664     6.0297    21 / 21
G2RC        2.322526   6.417298    25 / 25
BH76RC       0.66413   3.536982    30 / 30
FH51        2.566568   3.256908    51 / 51
TAUT15      2.552394   2.145937    15 / 15
DC13        8.502893  11.475687    13 / 13
MB16_43    27.457521  23.165472    43 / 43
DARC        2.733875    5.57797    14 / 14
RSE43       1.342873    2.74911    43 / 43
BSR36       9.261782   3.079317    36 / 36
CDIE20      1.864759   1.347484    20 / 20
ISO34       2.109289   1.647042    34 / 34
ISOL24             0          0     0 / 24
C60ISO             0          0      0 / 9
PArel       2.386571   1.645025    20 / 20
BH76        3.197262   9.676053    76 / 76
BHPERI       7.76146     6.4139    26 / 26
BHDIV10     4.416718   6.535109    10 / 10
INV24       6.128354   2.228547    24 / 24
BHROT27     1.727736    0.78352    27 / 27
PX13        2.144293  11.219857    13 / 13
WCPT18       2.21209   8.744304    18 / 18
RG18         0.69739   0.709552    18 / 18
ADIM6       2.661404   2.390824      6 / 6
S22         4.683072   2.291758    22 / 22
S66         2.021056   2.101976    66 / 66
HEAVY28            0          0      0 / 0
WATER27    11.435094  26.402884    27 / 27
CARBHB12    0.903716   2.841777    12 / 12
PNICO23     1.843124   1.726817    23 / 23
HAL59       1.972894   2.247276    29 / 29
AHB21       1.327143   3.294519    21 / 21
CHB6        0.814932   2.309161      4 / 4
IL16        3.322614   4.409963    16 / 16
IDISP       6.162437   5.245746      6 / 6
ICONF       3.249385   0.493337    17 / 17
ACONF       0.929833   0.274429    15 / 15
Amino20x4   1.177498   0.576975    80 / 80
PCONF21     2.647433   1.099663    18 / 18
MCONF        1.13395   0.711618    51 / 51
SCONF         1.9709   1.317952    17 / 17
UPU23              0          0     0 / 23
BUT14DIOL   0.792622    1.02002    64 / 64

[55 rows x 28 columns]

In [2]:
# import numpy as np
np.max(mean_absolute_deviation_list), np.sum(mean_absolute_deviation_list), np.mean(
    mean_absolute_deviation_list
)

(np.float64(1207.482739432191),
 np.float64(98414.09024557225),
 np.float64(71.1084467092285))

In [5]:
mole_name

'BH76RC-NH'

In [9]:
e1 = -4.6025270679642568e02  # orca fc DLPNO-CCSD
e2 = -4.6025221729046751e02  # orca fc CCSD
e3 = -4.6025767731174767e02 # orca nfc CCSD
e4 = -4.6025796979352134e02 # orca nfc DLPNO-CCSD
e = -460.257677434825  # pyscf CCSD
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 3.11912268e+00  3.42629231e+00  7.72321803e-05 -1.83457852e-01]
[-1.07996860e-05 -1.18632336e-05 -2.67409583e-10  6.35206561e-07]

In [14]:
e = -460.2602125077868 # pyscf CCSD(t)
e1 = -4.6026021233042377e02 # orca nfc CCSD(t)
e2 = -4.6026021233042360e02 # orca old nfc CCSD(t)
e3 = -4.6026042971888393e02  # orca nfc DLPNO-CCSD(t)
e4 = -4.6025500524617820e02
print((np.array([e1, e2, e3, e4]) - e) * 627.5094733748099)
print((np.array([e1, e2, e3, e4]) - e) / e)

[ 1.11296967e-04  1.11297074e-04 -1.36302021e-01  3.26760599e+00]
[-3.85353766e-10 -3.85354136e-10  4.71931076e-07 -1.13137340e-05]

In [ ]:
np.array([[-4.366423914512e-02], [0.000000000000e00], [-5.569827800646e-01]])
np.array([[-4.366423911029e-02], [0.000000000000e00], [-5.569827799431e-01]])

[[-4.366423908914e-02], [0.000000000000e00], [-5.569827798789e-01]]

array([[-3.48300000e-11],
       [ 0.00000000e+00],
       [-1.21500032e-10]])