In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  32.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343   146.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051    71.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997   140.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB  18.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312   122.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089    93.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB  18.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB 567.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB 219.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426   127.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511   198.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198   146.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 335.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600   154.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   6.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB 145.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107   120.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   8.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732     5.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447   378.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841    69.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140    73.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185    27.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   7.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB   8.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   9.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490   104.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724   110.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053    70.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643   180.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652   181.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   6.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070   187.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326    50.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   9.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB  11.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995    92.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774    88.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    30.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB 158.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   21KB  11.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 249.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   8.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4083     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4550     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   40KB 951.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2908    68.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3942    90.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5860    68.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   7.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   5.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB 277.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3073    35.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   7.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB 347.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2669     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7820     3.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 1183    14.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6027   380.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4067    95.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2894     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4347     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6330   150.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 154.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6640     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8019   184.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   8.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7577   171.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   9.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 431.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4727     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6538     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5309   120.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8699   199.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 257.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4589    53.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3757     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6328   147.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3147    73.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2464    29.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   32KB 744.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5205   119.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4012     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   15KB 180.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4481    52.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8736   104.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   32KB  13.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   11KB 130.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4484   102.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   15KB   7.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB   9.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   13KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100%   15KB 357.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100%   11KB   6.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   11KB 253.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 5200     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4002     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4480    53.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   32KB 753.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB   6.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   15KB 843.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 6335     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 2469    31.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB 259.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5212     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4010    92.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6328     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 2457    28.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 3152     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4595     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 3770     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 8684     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   10KB 237.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3151    37.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4593   105.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   18KB 428.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   18KB   9.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3767   239.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 8701   194.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   10KB 119.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 5298     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB   8.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB 433.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 6536     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   12KB 287.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5312     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 4742   108.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6540   152.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   10KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%   18KB 428.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4736   107.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 7909     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 7640   416.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6451     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 4492    52.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100%   32KB  15.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5499   126.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7778     3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 8829     3.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 5195   121.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4290    98.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 4004    47.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 6322     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 2472    29.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 9347   211.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 2852     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 3147    71.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100% 6318     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 3550    81.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 3546     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ_mo 100% 4116     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB 235.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4040    91.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7715     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5898    68.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ_mo 100%  965    21.9KB/s   00:00

In [2]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "test": ["WATER27"],
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend([f"{i_subset}_{ i_set}" for i_set in full_subset_dict[i_subset]])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ", "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
)

display(df_summary)

cc-pVDZ
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['s4-c2v', 's'], ['sif4', 'si', 'f'], ['s2o', 's', 'o'], ['bef2', 'be', 'f']]
[-52.05705767 -19.18674047 -10.97536229 -10.44230828  -8.54224205]
====Detail of AI error of W4_11====
116: -52.05705767419491
51.57269647922633 -1 p4
-0.1210902987421438 4 p

128: -19.186740474142216
19.24645009296201 -1 s4-c2v
0.0149274047049485 4 s

41: -10.975362290867613
9.254534106033535 -1 sif4
-1.7366390394589053 1 si
0.0039527136562071 4 f

121: -10.442308277467188
10.324773069899289 -1 s2o
0.0149274047049485 2 s
-0.147390016977797 1 o

47: -8.542242045155673
8.366497199603995 -1 bef2
-0.183650272864092 1 be
0.0039527136562071 2 f

Warning: W4_11-alh3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-sih4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bh3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2-trip not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-sih not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-si2h6 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-b2h6 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-sih3f not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ph3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h6 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2-sing not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-h2s not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hs not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h5f not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3f not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-nh3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-methanol not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hcl not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-nh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bhf2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-h2o not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hf not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2ch not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-propyne not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-acetaldehyde not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-allene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-sif4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bf3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h3f not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirane not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2f2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-alf3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bef2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2c not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-acetic not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-h2co not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-h2cn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-becl2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hcoh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hcoh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ketene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-sif not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-formic not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hcnh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-glyoxal not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hcof not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2cl not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cf4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hccf not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hcn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hnc not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cch not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hco not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-co not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-f2co not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hocn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hooh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-t-n2h2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hnco not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c-n2h2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cf2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-co2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-fccf not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-dioxirane not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cf not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ssh not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hocl not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-nccn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ocs not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-clcn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hoo not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hcno not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-honc not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hno not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hof not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hono not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hono not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cs2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-hnnn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cs not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-so3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-ccl2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-so2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-so not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-n2o not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hooo not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-p4 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cl2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-o2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-f2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hooo not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-s2o not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-no2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-s3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cl2o not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-s4-c2v not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-of not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-c2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-oclo not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-f2o not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-fo2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-cloo not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-foof not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-o3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: W4_11-bn not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p2', 'p'], ['clf', 'cl', 'f'], ['clo', 'cl', 'o'], ['s2', 's'], ['sio', 'si', 'o']]
[-20.36042754  -7.85968861  -3.95619015  -2.22090014  -2.05659248]
====Detail of AI error of W4_11====
122: -20.360427544985548
5.935765103743531 -1 p2
-7.212331220621008 2 p

123: -7.859688606250726
7.558533625667429 -1 clf
-0.0409463620702839 1 cl
-0.2602086185130134 1 f

125: -3.956190146062023
3.862602788673122 -1 clo
-0.0409463620702839 1 cl
-0.0526409953186171 1 o

115: -2.220900143173405
2.324380967339813 -1 s2
0.051740412083204 2 s

94: -2.056592477026066
1.0251071797661242 -1 sio
-0.9788443019413248 1 si
-0.0526409953186171 1 o

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['s4-c2v', 's'], ['cs2', 'c', 's'], ['s3', 's'], ['c2', 'c']]
[-39.96168941 -19.54840554 -17.22022322 -17.20266654  13.15562662]
====Detail of AI error of W4_11====
116: -39.96168940673931
38.77608187524481 -1 p4
-0.2964018828736247 4 p

128: -19.548405540468618
11.99699224081797 -1 s4-c2v
-1.8878533249126617 4 s

103: -17.220223215061182
12.60861299061713 -1 cs2
-0.8359035746187287 1 c
-1.8878533249126617 2 s

126: -17.202666544506506
11.539106569768522 -1 s3
-1.8878533249126617 3 s

130: 13.155626623805029
-14.827433773042486 -1 c2
-0.8359035746187287 2 c

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['ocs', 'o', 'c', 's'], ['s2o', 's', 'o'], ['co2', 'c', 'o'], ['si2h6', 'si', 'h']]
[-38.94445807  -7.40548991  -6.60715521  -6.51507115  -6.10375468]
====Detail of AI error of W4_11====
116: -38.94445806920766
36.77121181828969 -1 p4
-0.5433115627294918 4 p

93: -7.405489907180912
7.181608608558664 -1 ocs
-0.358987492953858 1 o
0.0630600843496487 1 c
0.0720461099819614 1 s

121: -6.607155210488461
6.392259937498526 -1 s2o
0.0720461099819614 2 s
-0.358987492953858 1 o

84: -6.515071153403158
5.86015625184509 -1 co2
0.0630600843496487 1 c
-0.358987492953858 2 o

8: -6.103754682625703
4.260294510338742 -1 si2h6
-0.8930664958437838 2 si
-0.0095545300998988 6 h

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['propane', 'c', 'h'], ['si2h6', 'si', 'h'], ['c2h6', 'c', 'h'], ['ethanol', 'c', 'o', 'h'], ['b2h6', 'b', 'h']]
[-21.95718574 -19.57724966 -17.18616385 -16.49682391 -15.90737214]
====Detail of AI error of W4_11====
15: -21.957185739001055
-2.738693990105153 -1 propane
-0.3144920455034626 3 c
-2.9690504490744773 8 h

8: -19.577249660991054
0.2394710491399388 -1 si2h6
-0.7617379587021244 2 si
-2.9690504490744773 6 h

14: -17.186163846108542
-1.2571229393452508 -1 c2h6
-0.3144920455034626 2 c
-2.9690504490744773 6 h

25: -16.49682391189505
-2.569078383506531 -1 ethanol
-0.3144920455034626 2 c
-0.6226155099477888 1 o
-2.9690504490744773 6 h

11: -15.907372140703394
-1.4021583032270375 -1 b2h6
0.2523861252582167 2 b
-2.9690504490744773 6 h

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_17n', 'EA_17'], ['EA_20n', 'EA_20'], ['EA_15n', 'EA_15']]
[-18.2444036   -6.00654178  -3.56984874   3.23528334  -2.58006913]
====Detail of AI error of G21EA====
24: -18.24440359940039
-0.2375307753512343 1 EA_25n
18.006872824049154 -1 EA_25

22: -6.006541779386775
5.413042054701967 1 EA_23n
11.419583834088742 -1 EA_23

16: -3.5698487389131532
-1.0903634708520993 1 EA_17n
2.479485268061054 -1 EA_17

19: 3.2352833443949933
0.277899330958607 1 EA_20n
-2.9573840134363865 -1 EA_20

14: -2.5800691272009675
-1.2083542245145615 1 EA_15n
1.371714902686406 -1 EA_15

Warning: G21EA-EA_9n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_10n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_12n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_15n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_16n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_18n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_19 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_21n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_23n not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_p', 'EA_p-'], ['EA_24n', 'EA_24'], ['EA_20n', 'EA_20'], ['EA_14n', 'EA_14']]
[-14.64259026  -8.92856041  -4.96223822   4.20752369  -2.12578495]
====Detail of AI error of G21EA====
24: -14.642590260456922
-2.4896997640766383 1 EA_25n
12.152890496380284 -1 EA_25

4: -8.92856040977864
-8.48489041395435 1 EA_p
0.4436699958242896 -1 EA_p-

23: -4.962238221607586
6.3456312554750935 1 EA_24n
11.30786947708268 -1 EA_24

19: 4.207523685138572
1.2215132978796777 1 EA_20n
-2.9860103872588937 -1 EA_20

13: -2.1257849522085235
-0.8536113610208634 1 EA_14n
1.2721735911876602 -1 EA_14

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_c', 'EA_c-'], ['EA_25n', 'EA_25'], ['EA_s', 'EA_s-'], ['EA_17n', 'EA_17'], ['EA_9n', 'EA_9']]
[-5.57837799  4.67502155 -3.70487332 -2.83327245 -2.80094553]
====Detail of AI error of G21EA====
0: -5.578377985623777
-0.672540585606195 1 EA_c
4.905837400017582 -1 EA_c-

24: 4.675021547282025
2.082826027129699 1 EA_25n
-2.592195520152326 -1 EA_25

5: -3.704873322170795
-2.026326281231764 1 EA_s
1.6785470409390308 -1 EA_s-

16: -2.8332724495223722
1.343327922852806 1 EA_17n
4.176600372375178 -1 EA_17

8: -2.8009455264109278
-3.089256652155602 1 EA_9n
-0.2883111257446742 -1 EA_9

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_24n', 'EA_24'], ['EA_s', 'EA_s-'], ['EA_16n', 'EA_16']]
[-6.75488883 -4.73312135 -4.59416815 -1.51251311 -1.28159217]
====Detail of AI error of G21EA====
24: -6.754888825489704
1.2341914076237177 1 EA_25n
7.989080233113422 -1 EA_25

22: -4.733121352956172
2.6500512550998643 1 EA_23n
7.383172608056037 -1 EA_23

23: -4.5941681511915755
0.7024729284844707 1 EA_24n
5.296641079676046 -1 EA_24

5: -1.5125131066521875
0.0011060439363733 1 EA_s
1.5136191505885608 -1 EA_s-

15: -1.2815921737339209
-0.2161710812350332 1 EA_16n
1.0654210924988876 -1 EA_16

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_21n', 'EA_21'], ['EA_24n', 'EA_24'], ['EA_22n', 'EA_22']]
[-15.3735434   -7.77538025  -2.2940384   -2.08755503   2.05247411]
====Detail of AI error of G21EA====
24: -15.373543403225051
-0.0746938764282929 1 EA_25n
15.298849526796758 -1 EA_25

22: -7.775380246489535
-4.905035052475857 1 EA_23n
2.870345194013677 -1 EA_23

20: -2.2940383996951033
-1.3622212263294493 1 EA_21n
0.9318171733656538 -1 EA_21

23: -2.0875550277104464
-0.2441618207643377 1 EA_24n
1.8433932069461088 -1 EA_24

21: 2.052474110655577
-1.1911320973360655 1 EA_22n
-3.2436062079916423 -1 EA_22

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21IP====
[['IP_76', '43'], ['IP_71', '25'], ['IP_72', '26'], ['IP_74', '34'], ['IP_78', '45']]
[ 8.07775153  6.74444296  6.37953085 -5.59013503  5.47345559]
====Detail of AI error of G21IP====
31: 8.077751526575465
12.181684232650436 1 IP_76
4.10393270607497 -1 43

26: 6.744442958138531
7.315415632741993 1 IP_71
0.570972674603462 -1 25

27: 6.379530851029964
4.785703740685022 1 IP_72
-1.593827110344942 -1 26

29: -5.590135026110619
-4.257455246702045 1 IP_74
1.3326797794085736 -1 34

33: 5.473455586894162
5.269791871102592 1 IP_78
-0.2036637157915695 -1 45

Warning: G21IP-IP_59 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_60 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_61 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_62 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_63 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub1                                             3.601181  18.629823
sub2                                             5.700007   6.612165
sub3                                             3.648439   6.764537
sub4                                             2.277669   1.651300
sub5                                             1.775151   1.321288

data_path            ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                   2.330106  11.902151
sub2       210 / 243                                   0.000000   0.000000
sub3       170 / 194                                   0.000000   0.000000
sub4       217 / 244                                   0.000000   0.000000
sub5       268 / 291                                   0.000000   0.000000

data_path           ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ            \
Type      Processed                                      AI AE    DFT AE
sub1       60 / 468                                   3.317532  18.69565
sub2        0 / 243                                   0.000000   0.00000
sub3        0 / 194                                   0.000000   0.00000
sub4        0 / 244                                   0.000000   0.00000
sub5        0 / 291                                   0.000000   0.00000

data_path            ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       301 / 468                                   2.735337  18.629823
sub2         0 / 243                                   7.500320   6.823806
sub3         0 / 194                                   2.329471   9.107948
sub4         0 / 244                                   0.000000   0.000000
sub5         0 / 291                                   0.000000   0.000000

data_path            ccdft_cc-pVDZ_atom-1-3775677_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                   4.117631  18.629823
sub2       152 / 243                                   7.608994   6.866788
sub3        76 / 194                                   5.097269   8.611355
sub4         0 / 244                                   0.000000   0.000000
sub5         0 / 291                                   0.000000   0.000000

data_path
Type       Processed
sub1       468 / 468
sub2       195 / 243
sub3        85 / 194
sub4         0 / 244
sub5         0 / 291

data_path      ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                     AI AE     DFT AE
sub2_MB16_43                                         15.909280  15.461608
sub2_BSR36                                            2.745238   8.401182
sub2_DARC                                             8.461810  10.754152
sub1_AL2X6                                            6.683938   5.659146
sub1_DC13                                             8.769018  13.090863
sub1_YBDE18                                           8.128445   8.145395
sub1_ALK8                                             5.330166   4.400063
sub1_SIE4x4                                           4.526972  21.908521
sub1_PA26                                             3.603806   2.200767
sub1_RC21                                             5.258815   4.820927
sub1_FH51                                             3.129089   3.703658
sub1_G2RC                                             3.605386   5.917204
sub1_DIPCS10                                          3.959661  12.310855
sub1_HEAVYSB11                                        4.230302   5.391477
sub2_RSE43                                            2.741250   3.157601
sub3_BH76                                             4.142984   9.107948
sub1_TAUT15                                           2.322749   2.164531
sub1_ALKBDE10                                        10.401011  18.125250
sub1_NBPRC                                            4.266559   2.232550
sub2_ISO34                                            2.869448   2.001744
sub1_W4_11                                            2.977996  29.506869
sub1_G21IP                                            1.840062   8.953336
sub1_G21EA                                            2.009397   9.754524
sub2_CDIE20                                           2.104062   1.599507
sub1_BH76RC                                           1.125349  80.220383
sub2_C60ISO                                           0.000000   0.000000
sub2_ISOL24                                           0.000000   0.000000
sub2_PArel                                            1.904611   1.743933
sub3_BHPERI                                           2.410479   3.268993
sub3_BHDIV10                                          3.670803   6.277708
sub3_INV24                                            0.000000   0.000000
sub3_BHROT27                                          1.458525   0.853379
sub3_PX13                                             7.171943  11.042025
sub3_WCPT18                                           4.076216   7.967153
sub4_RG18                                             0.315151   0.230018
sub4_ADIM6                                            4.186318   3.059030
sub4_S22                                              3.143330   2.291253
sub4_S66                                              2.658246   1.894710
sub4_HEAVY28                                          0.000000   0.000000
sub4_WATER27                                          0.000000   0.000000
sub4_CARBHB12                                         0.973519   1.632408
sub4_PNICO23                                          0.714591   0.776429
sub4_HAL59                                            2.587716   1.649787
sub4_AHB21                                            3.116596   2.453821
sub4_CHB6                                             3.579273   1.805320
sub4_IL16                                             2.246179   1.021067
sub5_IDISP                                           13.337525  13.125478
sub5_ICONF                                            1.737822   0.413804
sub5_ACONF                                            1.801305   0.546621
sub5_Amino20x4                                        1.642470   0.656235
sub5_PCONF21                                          3.485001   3.214782
sub5_MCONF                                            1.437692   1.956021
sub5_SCONF                                            0.984123   0.512352
sub5_UPU23                                            0.000000   0.000000
sub5_BUT14DIOL                                        0.858951   0.645099

data_path                 ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ  \
Type            Processed                                      AI AE
sub2_MB16_43      43 / 43                                   0.000000
sub2_BSR36        36 / 36                                   0.000000
sub2_DARC         14 / 14                                   0.000000
sub1_AL2X6          6 / 6                                   0.000000
sub1_DC13         13 / 13                                   0.000000
sub1_YBDE18       18 / 18                                   0.000000
sub1_ALK8           8 / 8                                   0.000000
sub1_SIE4x4       16 / 16                                   0.000000
sub1_PA26         26 / 26                                   0.000000
sub1_RC21         21 / 21                                   0.000000
sub1_FH51         51 / 51                                   0.000000
sub1_G2RC         25 / 25                                   0.000000
sub1_DIPCS10      10 / 10                                   2.868842
sub1_HEAVYSB11      7 / 7                                   0.000000
sub2_RSE43        43 / 43                                   0.000000
sub3_BH76         76 / 76                                   0.000000
sub1_TAUT15       15 / 15                                   0.000000
sub1_ALKBDE10       9 / 9                                   0.000000
sub1_NBPRC        12 / 12                                   0.000000
sub2_ISO34        34 / 34                                   0.000000
sub1_W4_11      140 / 140                                   2.908457
sub1_G21IP        36 / 36                                   1.480393
sub1_G21EA        25 / 25                                   2.633783
sub2_CDIE20       20 / 20                                   0.000000
sub1_BH76RC       30 / 30                                   0.000000
sub2_C60ISO         0 / 9                                   0.000000
sub2_ISOL24        0 / 24                                   0.000000
sub2_PArel        20 / 20                                   0.000000
sub3_BHPERI       26 / 26                                   0.000000
sub3_BHDIV10      10 / 10                                   0.000000
sub3_INV24         0 / 24                                   0.000000
sub3_BHROT27      27 / 27                                   0.000000
sub3_PX13         13 / 13                                   0.000000
sub3_WCPT18       18 / 18                                   0.000000
sub4_RG18         18 / 18                                   0.000000
sub4_ADIM6          6 / 6                                   0.000000
sub4_S22          22 / 22                                   0.000000
sub4_S66          66 / 66                                   0.000000
sub4_HEAVY28        0 / 0                                   0.000000
sub4_WATER27       0 / 27                                   0.000000
sub4_CARBHB12     12 / 12                                   0.000000
sub4_PNICO23      23 / 23                                   0.000000
sub4_HAL59        29 / 29                                   0.000000
sub4_AHB21        21 / 21                                   0.000000
sub4_CHB6           4 / 4                                   0.000000
sub4_IL16         16 / 16                                   0.000000
sub5_IDISP          6 / 6                                   0.000000
sub5_ICONF        17 / 17                                   0.000000
sub5_ACONF        15 / 15                                   0.000000
sub5_Amino20x4    80 / 80                                   0.000000
sub5_PCONF21      18 / 18                                   0.000000
sub5_MCONF        51 / 51                                   0.000000
sub5_SCONF        17 / 17                                   0.000000
sub5_UPU23         0 / 23                                   0.000000
sub5_BUT14DIOL    64 / 64                                   0.000000

data_path                            \
Type               DFT AE Processed
sub2_MB16_43     0.000000    0 / 43
sub2_BSR36       0.000000    0 / 36
sub2_DARC        0.000000    0 / 14
sub1_AL2X6       0.000000     0 / 6
sub1_DC13        0.000000    0 / 13
sub1_YBDE18      0.000000    0 / 18
sub1_ALK8        0.000000     0 / 8
sub1_SIE4x4      0.000000    0 / 16
sub1_PA26        0.000000    0 / 26
sub1_RC21        0.000000    0 / 21
sub1_FH51        0.000000    0 / 51
sub1_G2RC        0.000000    0 / 25
sub1_DIPCS10    14.155397    8 / 10
sub1_HEAVYSB11   0.000000     0 / 7
sub2_RSE43       0.000000    0 / 43
sub3_BH76        0.000000    0 / 76
sub1_TAUT15      0.000000    0 / 15
sub1_ALKBDE10    0.000000     0 / 9
sub1_NBPRC       0.000000    0 / 12
sub2_ISO34       0.000000    0 / 34
sub1_W4_11      15.646408  15 / 140
sub1_G21IP       9.765279   21 / 36
sub1_G21EA      10.069932   16 / 25
sub2_CDIE20      0.000000    0 / 20
sub1_BH76RC      0.000000    0 / 30
sub2_C60ISO      0.000000     0 / 9
sub2_ISOL24      0.000000    0 / 24
sub2_PArel       0.000000    0 / 20
sub3_BHPERI      0.000000    0 / 26
sub3_BHDIV10     0.000000    0 / 10
sub3_INV24       0.000000    0 / 24
sub3_BHROT27     0.000000    0 / 27
sub3_PX13        0.000000    0 / 13
sub3_WCPT18      0.000000    0 / 18
sub4_RG18        0.000000    0 / 18
sub4_ADIM6       0.000000     0 / 6
sub4_S22         0.000000    0 / 22
sub4_S66         0.000000    0 / 66
sub4_HEAVY28     0.000000     0 / 0
sub4_WATER27     0.000000    0 / 27
sub4_CARBHB12    0.000000    0 / 12
sub4_PNICO23     0.000000    0 / 23
sub4_HAL59       0.000000    0 / 29
sub4_AHB21       0.000000    0 / 21
sub4_CHB6        0.000000     0 / 4
sub4_IL16        0.000000    0 / 16
sub5_IDISP       0.000000     0 / 6
sub5_ICONF       0.000000    0 / 17
sub5_ACONF       0.000000    0 / 15
sub5_Amino20x4   0.000000    0 / 80
sub5_PCONF21     0.000000    0 / 18
sub5_MCONF       0.000000    0 / 51
sub5_SCONF       0.000000    0 / 17
sub5_UPU23       0.000000    0 / 23
sub5_BUT14DIOL   0.000000    0 / 64

data_path      ccdft_cc-pVDZ_atom-1-1918154_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub2_MB16_43                                     0.000000   0.000000
sub2_BSR36                                       0.000000   0.000000
sub2_DARC                                        0.000000   0.000000
sub1_AL2X6                                      10.198577   5.659146
sub1_DC13                                        0.000000   0.000000
sub1_YBDE18                                      5.815678   8.145395
sub1_ALK8                                        5.255970   3.123069
sub1_SIE4x4                                      5.116135  21.908521
sub1_PA26                                        2.112350   2.132077
sub1_RC21                                        0.000000   0.000000
sub1_FH51                                        0.000000   0.000000
sub1_G2RC                                        0.000000   0.000000
sub1_DIPCS10                                     1.376148  12.310855
sub1_HEAVYSB11                                   4.494898   5.391477
sub2_RSE43                                       0.000000   0.000000
sub3_BH76                                        0.000000   0.000000
sub1_TAUT15                                      0.000000   0.000000
sub1_ALKBDE10                                    2.373368  18.125250
sub1_NBPRC                                       1.515042   1.522637
sub2_ISO34                                       0.000000   0.000000
sub1_W4_11                                       3.386700  29.506869
sub1_G21IP                                       2.133135   8.953336
sub1_G21EA                                       1.747370   9.754524
sub2_CDIE20                                      0.000000   0.000000
sub1_BH76RC                                      0.000000   0.000000
sub2_C60ISO                                      0.000000   0.000000
sub2_ISOL24                                      0.000000   0.000000
sub2_PArel                                       0.000000   0.000000
sub3_BHPERI                                      0.000000   0.000000
sub3_BHDIV10                                     0.000000   0.000000
sub3_INV24                                       0.000000   0.000000
sub3_BHROT27                                     0.000000   0.000000
sub3_PX13                                        0.000000   0.000000
sub3_WCPT18                                      0.000000   0.000000
sub4_RG18                                        0.000000   0.000000
sub4_ADIM6                                       0.000000   0.000000
sub4_S22                                         0.000000   0.000000
sub4_S66                                         0.000000   0.000000
sub4_HEAVY28                                     0.000000   0.000000
sub4_WATER27                                     0.000000   0.000000
sub4_CARBHB12                                    0.000000   0.000000
sub4_PNICO23                                     0.000000   0.000000
sub4_HAL59                                       0.000000   0.000000
sub4_AHB21                                       0.000000   0.000000
sub4_CHB6                                        0.000000   0.000000
sub4_IL16                                        0.000000   0.000000
sub5_IDISP                                       0.000000   0.000000
sub5_ICONF                                       0.000000   0.000000
sub5_ACONF                                       0.000000   0.000000
sub5_Amino20x4                                   0.000000   0.000000
sub5_PCONF21                                     0.000000   0.000000
sub5_MCONF                                       0.000000   0.000000
sub5_SCONF                                       0.000000   0.000000
sub5_UPU23                                       0.000000   0.000000
sub5_BUT14DIOL                                   0.000000   0.000000

data_path                 ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ  \
Type            Processed                                      AI AE
sub2_MB16_43       0 / 43                                  13.690423
sub2_BSR36         0 / 36                                  13.572930
sub2_DARC          0 / 14                                   9.636193
sub1_AL2X6          6 / 6                                   8.682721
sub1_DC13          0 / 13                                   7.965097
sub1_YBDE18       18 / 18                                   6.307105
sub1_ALK8           7 / 8                                   6.066294
sub1_SIE4x4       16 / 16                                   4.522553
sub1_PA26         20 / 26                                   3.888106
sub1_RC21          0 / 21                                   3.622278
sub1_FH51          0 / 51                                   3.233394
sub1_G2RC          0 / 25                                   2.975693
sub1_DIPCS10      10 / 10                                   2.799253
sub1_HEAVYSB11      7 / 7                                   2.629338
sub2_RSE43         0 / 43                                   2.515089
sub3_BH76          0 / 76                                   2.329471
sub1_TAUT15        0 / 15                                   2.318659
sub1_ALKBDE10       9 / 9                                   1.995201
sub1_NBPRC         7 / 12                                   1.938247
sub2_ISO34         0 / 34                                   1.736229
sub1_W4_11      140 / 140                                   1.724925
sub1_G21IP        36 / 36                                   1.513849
sub1_G21EA        25 / 25                                   1.209867
sub2_CDIE20        0 / 20                                   1.154341
sub1_BH76RC        0 / 30                                   0.833128
sub2_C60ISO         0 / 9                                   0.000000
sub2_ISOL24        0 / 24                                   0.000000
sub2_PArel         0 / 20                                   0.000000
sub3_BHPERI        0 / 26                                   0.000000
sub3_BHDIV10       0 / 10                                   0.000000
sub3_INV24         0 / 24                                   0.000000
sub3_BHROT27       0 / 27                                   0.000000
sub3_PX13          0 / 13                                   0.000000
sub3_WCPT18        0 / 18                                   0.000000
sub4_RG18          0 / 18                                   0.000000
sub4_ADIM6          0 / 6                                   0.000000
sub4_S22           0 / 22                                   0.000000
sub4_S66           0 / 66                                   0.000000
sub4_HEAVY28        0 / 0                                   0.000000
sub4_WATER27       0 / 27                                   0.000000
sub4_CARBHB12      0 / 12                                   0.000000
sub4_PNICO23       0 / 23                                   0.000000
sub4_HAL59         0 / 29                                   0.000000
sub4_AHB21         0 / 21                                   0.000000
sub4_CHB6           0 / 4                                   0.000000
sub4_IL16          0 / 16                                   0.000000
sub5_IDISP          0 / 6                                   0.000000
sub5_ICONF         0 / 17                                   0.000000
sub5_ACONF         0 / 15                                   0.000000
sub5_Amino20x4     0 / 80                                   0.000000
sub5_PCONF21       0 / 18                                   0.000000
sub5_MCONF         0 / 51                                   0.000000
sub5_SCONF         0 / 17                                   0.000000
sub5_UPU23         0 / 23                                   0.000000
sub5_BUT14DIOL     0 / 64                                   0.000000

data_path                             \
Type               DFT AE  Processed
sub2_MB16_43    15.409322    34 / 43
sub2_BSR36       6.217511    28 / 36
sub2_DARC       10.754152    14 / 14
sub1_AL2X6       5.659146      6 / 6
sub1_DC13       13.090863    13 / 13
sub1_YBDE18      8.145395    18 / 18
sub1_ALK8        4.400063      8 / 8
sub1_SIE4x4     21.908521    16 / 16
sub1_PA26        2.200767    26 / 26
sub1_RC21        4.820927    21 / 21
sub1_FH51        3.703658    51 / 51
sub1_G2RC        5.917204    25 / 25
sub1_DIPCS10    12.310855    10 / 10
sub1_HEAVYSB11   5.391477      7 / 7
sub2_RSE43       3.157601    43 / 43
sub3_BH76        9.107948    76 / 76
sub1_TAUT15      2.164531    15 / 15
sub1_ALKBDE10   18.125250      9 / 9
sub1_NBPRC       2.232550    12 / 12
sub2_ISO34       1.561740    23 / 34
sub1_W4_11      29.506869  140 / 140
sub1_G21IP       8.953336    36 / 36
sub1_G21EA       9.754524    25 / 25
sub2_CDIE20      1.695626    10 / 20
sub1_BH76RC     80.220383    30 / 30
sub2_C60ISO      0.000000      0 / 9
sub2_ISOL24      0.000000     0 / 24
sub2_PArel       0.000000     0 / 20
sub3_BHPERI      0.000000     0 / 26
sub3_BHDIV10     0.000000     0 / 10
sub3_INV24       0.000000     0 / 24
sub3_BHROT27     0.000000     0 / 27
sub3_PX13        0.000000     0 / 13
sub3_WCPT18      0.000000     0 / 18
sub4_RG18        0.000000     0 / 18
sub4_ADIM6       0.000000      0 / 6
sub4_S22         0.000000     0 / 22
sub4_S66         0.000000     0 / 66
sub4_HEAVY28     0.000000      0 / 0
sub4_WATER27     0.000000     0 / 27
sub4_CARBHB12    0.000000     0 / 12
sub4_PNICO23     0.000000     0 / 23
sub4_HAL59       0.000000     0 / 29
sub4_AHB21       0.000000     0 / 21
sub4_CHB6        0.000000      0 / 4
sub4_IL16        0.000000     0 / 16
sub5_IDISP       0.000000      0 / 6
sub5_ICONF       0.000000     0 / 17
sub5_ACONF       0.000000     0 / 15

In [ ]:
Error_molecule = [
    "G21IP-IP_80_cc-pVDZ_0-1_1_0.0000_default",
    "G21EA-EA_23n_cc-pVDZ_0-1_1_0.0000_default",
    "BH76-RKT15_cc-pVDZ_0-1_1_0.0000_default",
]
print(len(Error_molecule))

# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

str_print = ''
for molecule in Error_molecule:
    str_print += molecule.split("_cc-pVDZ_")[0] + " "
print(str_print)

3
G21IP-IP_80 G21EA-EA_23n BH76-RKT15