In [9]:
from pathlib import Path

import pandas as pd

!noglob scp -r hkqai:~/workspace/cc2cc_test5/validate/*.csv ~/workspace/2025.1/validate
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 1520    30.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 2942   374.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 3630    80.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100% 1513    32.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ_mo 100%   67KB 939.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100% 1946    41.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100% 4734   802.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100% 4037   648.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100% 2762   600.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ_mo 100%   67KB   9.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7643     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5234   107.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   24KB 523.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4881     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7256     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7641     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   39KB   7.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8165     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB   3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB   2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB   2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB   2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB   3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5679     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9176     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8591     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   34KB   6.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB   4.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   29KB   5.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   26KB   3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2286    48.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6092     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5592     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   18KB 416.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   19KB   4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   25KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   13KB   2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   20KB   2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8889     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   21KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8457     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   27KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   16KB   3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB   1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   35KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   23KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   77KB  10.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7506   474.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9625   209.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB   2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   62KB   1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   2.4MB/s   00:00

In [10]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 1
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    # full_subset_dict = json.load(f)["full_subset_dict"]
    full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099
        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if modified_dft_d3bj := data.get("modified_dft_d3bj"):
            data_dft_d3bj = modified_dft_d3bj.to_numpy()
        else:
            data_dft_d3bj = data_d3bj
        if modified_dft_d3zero := data.get("modified_dft_d3zero"):
            data_dft_d3zero = modified_dft_d3zero.to_numpy()
        else:
            data_dft_d3zero = data_d3zero

        if modified_ai_d3bj := data.get("modified_ai_d3bj"):
            data_ai_d3bj = modified_ai_d3bj.to_numpy()
        else:
            data_ai_d3bj = data_d3bj
        if modified_ai_d3zero := data.get("modified_ai_d3zero"):
            data_ai_d3zero = modified_ai_d3zero.to_numpy()
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
            }

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = f"{i_subset}-{systems_list[i]}"
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)
for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}
        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []
        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        np.sum(data_subset[name_subset][f"ai{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        np.sum(data_subset[name_subset][f"dft{d3_name}"])
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if len(data_subset[name_subset]["ai"]) == len(
                data_subset[name_subset]["name"]
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.mean(wtmad_1_ai[d3_name])
            wtmad_1_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.mean(wtmad_1_dft[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"AI{d3_name.upper()}")
            ] = np.sum(wtmad_2_ai[d3_name])
            wtmad_2_subset.loc[
                name_set, (data_path_name, f"DFT{d3_name.upper()}")
            ] = np.sum(wtmad_2_dft[d3_name])
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            f"{sum(processed)} / " f"{len(processed)}"
        )
    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(mean_absolute_deviation_list)
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            )

print("Summary")
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)

print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
# save summary to excel with date
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")

cc-pVDZ
Warning: MB16_43-01 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-02 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-03 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-04 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-05 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-06 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-07 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-08 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-09 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-10 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-11 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-12 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-13 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-14 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-15 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-16 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-17 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-18 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-19 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-20 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-21 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-22 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-23 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-24 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-25 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-26 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-27 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-28 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-29 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-30 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-31 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-32 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-33 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-34 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-35 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ALA_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ARG_xci not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASN_xaf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ASP_xaz not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-CYS_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLN_xai not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLU_xbi not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-GLY_xac not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-HIS_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-ILE_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LEU_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-LYS_xap not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-MET_xbf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PHE_xaw not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-PRO_xae not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-SER_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-THR_xaq not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xaf not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TRP_xac not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-TYR_xag not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: Amino20x4-VAL_xad not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-01 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-02 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-03 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-04 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-05 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-06 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-07a not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-08 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-09 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-10 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-11 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-12 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-13 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-14 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-15a not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-16 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-17 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-18 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-19 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-20 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-21a not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: S22-22 not found in ccdft_cc-pVDZ_atom-1-1424849_gmtkn-cc-pVDZ data file
Warning: MB16_43-01 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-02 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-03 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-04 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-05 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-06 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-07 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-08 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-09 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-10 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-11 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-12 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-13 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-14 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-15 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-16 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-17 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-18 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-19 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-20 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-21 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-22 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-23 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-24 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-25 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-26 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-27 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-28 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-29 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-30 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-31 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-32 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-33 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-34 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: MB16_43-H2 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file
Warning: BSR36-c2h6 not found in ccdft_cc-pVDZ_atom-1-2487024_gmtkn-cc-pVDZ data file

data_path   1424849                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       1.092594  29.105933  1.092594  29.105933  1.092594  29.105933

data_path             2487024                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
test          1 / 5  1.996902  28.915381  1.996902  28.915381  1.996902

data_path
Disp type DFT_D3ZERO Processed
test       28.915381     1 / 5

wtmad_1

data_path   1424849                                                     \
Disp type        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       9.627512  6.679594  9.627512  6.679594  9.627512   6.679594

data_path              2487024                                            \
Disp type Processed         AI       DFT    AI_D3BJ  DFT_D3BJ  AI_D3ZERO
test          1 / 5  13.477618  8.039799  13.477618  8.039799  13.477618

data_path
Disp type DFT_D3ZERO Processed
test        8.039799     1 / 5

wtmad_2

data_path   1424849                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
test       4.292538  30.447177  4.292538  30.447177  4.292538  30.447177

data_path             2487024                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
test          1 / 5  7.941354  31.251429  7.941354  31.251429  7.941354

data_path
Disp type DFT_D3ZERO Processed
test       31.251429     1 / 5

Summary of Subset
MAE

data_path   1424849                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
W4_11       1.08085  29.506863   1.08085  29.506863   1.08085  29.506863
MB16_43           0          0         0          0         0          0
BSR36             0          0         0          0         0          0
Amino20x4  1.914694    1.04085  1.914694    1.04085  1.914694    1.04085
S22               0          0         0          0         0          0

data_path              2487024                                            \
Disp type  Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
W4_11      140 / 140  1.982356  29.506863  1.982356  29.506863  1.982356
MB16_43       0 / 43         0          0         0          0         0
BSR36         0 / 36         0          0         0          0         0
Amino20x4     2 / 80    2.6757   1.312891    2.6757   1.312891    2.6757
S22           0 / 22         0          0         0          0         0

data_path
Disp type DFT_D3ZERO  Processed
W4_11      29.506863  140 / 140
MB16_43            0     0 / 43
BSR36              0     0 / 36
Amino20x4   1.312891     3 / 80
S22                0     0 / 22