In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

# for data_path in list(Path("../validate").glob(f"*test*.csv")):
#     data_path.unlink()


for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB   9.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051   139.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997   142.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB 753.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179   118.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089    75.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB 933.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   4.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   6.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   7.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600     3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447    55.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841   137.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185    26.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB 355.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   7.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB 434.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490   104.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053    36.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643     4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652     4.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070   166.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818     3.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB 303.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326   100.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB 432.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB  12.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995    92.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774    86.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    56.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8679     5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4012    47.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6328     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2464    30.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3147    73.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4589     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3757    43.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8699     4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB 229.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 420.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   6.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5309   592.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6538   152.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4727     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 427.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8019   186.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7577     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6640     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4347   840.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6330   146.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2894    66.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 1183    27.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   6.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 311.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB 236.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5860     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   21KB   9.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 252.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   32KB  14.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 309.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 307.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4067    93.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6027   143.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2669    62.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   40KB  13.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7820     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 306.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3073    70.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2908     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3942    89.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4550   103.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4083    92.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4966   114.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7025     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4481     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   15KB   5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 258.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5205     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_W4_11 100%  330     7.5KB/s   00:00

In [3]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "test": ["INV24"],
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        print(
                            f"Warning: {mole_name} not found in {data_path.stem} data file"
                        )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

# df_summary.sort_values(
#     by=("ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ", "AI AE"),
#     axis=0,
#     inplace=True,
#     ascending=False,
# )

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ", "Processed"),
    axis=0,
    inplace=True,
    ascending=False,
    key=lambda x: [int(i.split("/")[1]) - int(i.split("/")[0]) for i in x],
)

display(df_summary)

cc-pVDZ
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['s4-c2v', 's'], ['sif4', 'si', 'f'], ['s2o', 's', 'o'], ['bef2', 'be', 'f']]
[-52.05705767 -19.18674047 -10.97536229 -10.44230828  -8.54224205]
====Detail of AI error of W4_11====
116: -52.05705767419491
51.57269647922633 -1 p4
-0.1210902987421438 4 p

128: -19.186740474142216
19.24645009296201 -1 s4-c2v
0.0149274047049485 4 s

41: -10.975362290867613
9.254534106033535 -1 sif4
-1.7366390394589053 1 si
0.0039527136562071 4 f

121: -10.442308277467188
10.324773069899289 -1 s2o
0.0149274047049485 2 s
-0.147390016977797 1 o

47: -8.542242045155673
8.366497199603995 -1 bef2
-0.183650272864092 1 be
0.0039527136562071 2 f

Warning: W4_11-h2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alh3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sih4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bh3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2-trip not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sih not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-si2h6 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-b2h6 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sih3f not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ph3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h6 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2-sing not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-h2s not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hs not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h5f not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3f not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-nh3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch3nh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-methanol not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hcl not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-nh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bhf2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-h2o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2ch not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-oh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-propyne not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-acetaldehyde not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-allene not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sif4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bf3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h3f not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirane not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2f2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alf3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bef2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2c not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ch2nh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-acetic not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2h2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-h2co not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-h2cn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-becl2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hcoh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hcoh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-alcl not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ketene not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sif not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-formic not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hcnh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-glyoxal not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hcof not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-nh2cl not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cf4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hccf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hcn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hnc not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cch not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hco not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-co not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-oxirene not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-f2co not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hocn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hooh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-t-n2h2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hnco not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c-n2h2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cf2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-co2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-fccf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-dioxirane not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ssh not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hocl not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-nccn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-n2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-n2h not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ocs not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-sio not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-clcn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hoo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hcno not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-honc not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hno not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hof not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hono not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hono not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cs2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-hnnn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cs not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-so3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-ccl2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bn3pi not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-so2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-no not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-so not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-n2o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c-hooo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-s2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-p4 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cl2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-o2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-f2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-t-hooo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-s2o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-p2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-clf not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-no2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-clo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-s3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cl2o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-s4-c2v not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-of not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-c2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-oclo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-f2o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-b2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-fo2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-cloo not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-foof not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-o3 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-bn not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: W4_11-be2 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[]
[]
====Detail of AI error of W4_11====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ.csv####
====AI error of W4_11====
[['p4', 'p'], ['p2', 'p'], ['sif4', 'si', 'f'], ['s4-c2v', 's'], ['ph3', 'p', 'h']]
[-88.20352711 -23.16571218 -11.71996421 -11.20472999  -8.49512955]
====Detail of AI error of W4_11====
116: -88.20352710922522
53.65733872082396 -1 p4
-8.636547097100316 4 p

122: -23.165712184395915
5.892617990195283 -1 p2
-8.636547097100316 2 p

41: -11.719964213073808
9.442070455050832 -1 sif4
-0.9788443021196735 1 si
-0.3247623639758258 4 f

128: -11.20472998856536
11.390151203413456 -1 s4-c2v
0.046355303712024 4 s

13: -8.495129550322126
-0.5353203405619253 -1 ph3
-8.636547097100316 1 p
-0.1313009312612456 3 h

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_17n', 'EA_17'], ['EA_20n', 'EA_20'], ['EA_15n', 'EA_15']]
[-18.2444036   -6.00654178  -3.56984874   3.23528334  -2.58006913]
====Detail of AI error of G21EA====
24: -18.24440359940039
-0.2375307753512343 1 EA_25n
18.006872824049154 -1 EA_25

22: -6.006541779386775
5.413042054701967 1 EA_23n
11.419583834088742 -1 EA_23

16: -3.5698487389131532
-1.0903634708520993 1 EA_17n
2.479485268061054 -1 EA_17

19: 3.2352833443949933
0.277899330958607 1 EA_20n
-2.9573840134363865 -1 EA_20

14: -2.5800691272009675
-1.2083542245145615 1 EA_15n
1.371714902686406 -1 EA_15

Warning: G21EA-EA_c not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_o not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_f not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_si not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_p not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_s not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_cl not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_8n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_9n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_10n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_11n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_12n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_13n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_14n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_15n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_16n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_17n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_18n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_19n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_20n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_21n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_22n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_23n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_24n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21EA-EA_25n not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[]
[]
====Detail of AI error of G21EA====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_23n', 'EA_23'], ['EA_p', 'EA_p-'], ['EA_24n', 'EA_24'], ['EA_20n', 'EA_20']]
[-14.64530639 -11.45689859  -9.29328946  -4.96117828   4.22758848]
====Detail of AI error of G21EA====
24: -14.645306388022973
-2.48969976379128 1 EA_25n
12.155606624231693 -1 EA_25

22: -11.456898593085857
6.419939625852122 1 EA_23n
17.87683821893798 -1 EA_23

4: -9.293289457011486
-8.849159389612684 1 EA_p
0.4441300673988026 -1 EA_p-

23: -4.961178276346649
6.345635489193985 1 EA_24n
11.306813765540634 -1 EA_24

19: 4.227588484514452
1.2215132978975125 1 EA_20n
-3.006075186616939 -1 EA_20

####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ.csv####
====AI error of G21IP====
[['IP_76', '43'], ['IP_71', '25'], ['IP_72', '26'], ['IP_74', '34'], ['IP_78', '45']]
[ 8.07775153  6.74444296  6.37953085 -5.59013503  5.47345559]
====Detail of AI error of G21IP====
31: 8.077751526575465
12.181684232650436 1 IP_76
4.10393270607497 -1 43

26: 6.744442958138531
7.315415632741993 1 IP_71
0.570972674603462 -1 25

27: 6.379530851029964
4.785703740685022 1 IP_72
-1.593827110344942 -1 26

29: -5.590135026110619
-4.257455246702045 1 IP_74
1.3326797794085736 -1 34

33: 5.473455586894162
5.269791871102592 1 IP_78
-0.2036637157915695 -1 45

Warning: G21IP-h not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-li+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-be+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-b+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-c+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-n+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-o+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-f+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-na+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-mg+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-al+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-si+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-p+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-s+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-cl+ not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_59 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_60 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_61 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_62 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_63 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_64 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_65 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_66 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_67 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_68 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_70 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_71 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_72 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: G21IP-IP_73 not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub1                                             3.601181  18.629823
sub2                                             5.700007   6.612165
sub3                                             3.648439   6.764537
sub4                                             2.277669   1.651300
sub5                                             1.775151   1.321288

data_path            ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ             \
Type       Processed                                   AI AE     DFT AE
sub1       468 / 468                                     0.0   0.000000
sub2       210 / 243                                     0.0   7.620232
sub3       170 / 194                                     0.0   2.780821
sub4       217 / 244                                     0.0  13.631465
sub5       268 / 291                                     0.0   0.000000

data_path           ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ             \
Type      Processed                                      AI AE     DFT AE
sub1        0 / 468                                   3.594924  18.629823
sub2       20 / 243                                   6.325743   6.612165
sub3       23 / 194                                   3.788152   7.323977
sub4       25 / 244                                   2.015394   1.679062
sub5        0 / 291                                   1.876735   1.321288

data_path
Type       Processed
sub1       468 / 468
sub2       210 / 243
sub3       155 / 194
sub4       205 / 244
sub5       268 / 291

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
WATER27                                          0.000000   0.000000
ISOL24                                           0.000000   0.000000
INV24                                            0.000000   0.000000
UPU23                                            0.000000   0.000000
BHROT27                                          1.458525   0.853379
C60ISO                                           0.000000   0.000000
RG18                                             0.315151   0.230018
HAL59                                            2.587716   1.649787
AL2X6                                            6.683938   5.659146
HEAVYSB11                                        4.230302   5.391477
NBPRC                                            4.266559   2.232550
ALK8                                             5.330166   4.400063
RC21                                             5.258815   4.820927
G2RC                                             3.605386   5.917204
BH76RC                                           1.125349  80.220383
YBDE18                                           8.128445   8.145395
W4_11                                            2.977996  29.506869
G21EA                                            2.009397   9.754524
G21IP                                            1.840062   8.953336
DIPCS10                                          3.959661  12.310855
PA26                                             3.603806   2.200767
SIE4x4                                           4.526972  21.908521
ALKBDE10                                        10.401011  18.125250
CDIE20                                           2.104062   1.599507
BSR36                                            2.745238   8.401182
RSE43                                            2.741250   3.157601
DARC                                             8.461810  10.754152
MB16_43                                         15.909280  15.461608
DC13                                             8.769018  13.090863
TAUT15                                           2.322749   2.164531
FH51                                             3.129089   3.703658
BHDIV10                                          3.670803   6.277708
BHPERI                                           2.410479   3.268993
PX13                                             7.171943  11.042025
WCPT18                                           4.076216   7.967153
ADIM6                                            4.186318   3.059030
BH76                                             4.142984   9.107948
PArel                                            1.904611   1.743933
ISO34                                            2.869448   2.001744
HEAVY28                                          0.000000   0.000000
S66                                              2.658246   1.894710
S22                                              3.143330   2.291253
CARBHB12                                         0.973519   1.632408
AHB21                                            3.116596   2.453821
CHB6                                             3.579273   1.805320
IL16                                             2.246179   1.021067
PNICO23                                          0.714591   0.776429
IDISP                                           13.337525  13.125478
ICONF                                            1.737822   0.413804
Amino20x4                                        1.642470   0.656235
ACONF                                            1.801305   0.546621
PCONF21                                          3.485001   3.214782
MCONF                                            1.437692   1.956021
SCONF                                            0.984123   0.512352
BUT14DIOL                                        0.858951   0.645099

data_path            ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ             \
Type       Processed                                   AI AE     DFT AE
WATER27       0 / 27                                     0.0  13.631465
ISOL24        0 / 24                                     0.0   7.620232
INV24         0 / 24                                     0.0   2.780821
UPU23         0 / 23                                     0.0   0.000000
BHROT27      27 / 27                                     0.0   0.000000
C60ISO         0 / 9                                     0.0   0.000000
RG18         18 / 18                                     0.0   0.000000
HAL59        29 / 29                                     0.0   0.000000
AL2X6          6 / 6                                     0.0   0.000000
HEAVYSB11      7 / 7                                     0.0   0.000000
NBPRC        12 / 12                                     0.0   0.000000
ALK8           8 / 8                                     0.0   0.000000
RC21         21 / 21                                     0.0   0.000000
G2RC         25 / 25                                     0.0   0.000000
BH76RC       30 / 30                                     0.0   0.000000
YBDE18       18 / 18                                     0.0   0.000000
W4_11      140 / 140                                     0.0   0.000000
G21EA        25 / 25                                     0.0   0.000000
G21IP        36 / 36                                     0.0   0.000000
DIPCS10      10 / 10                                     0.0   0.000000
PA26         26 / 26                                     0.0   0.000000
SIE4x4       16 / 16                                     0.0   0.000000
ALKBDE10       9 / 9                                     0.0   0.000000
CDIE20       20 / 20                                     0.0   0.000000
BSR36        36 / 36                                     0.0   0.000000
RSE43        43 / 43                                     0.0   0.000000
DARC         14 / 14                                     0.0   0.000000
MB16_43      43 / 43                                     0.0   0.000000
DC13         13 / 13                                     0.0   0.000000
TAUT15       15 / 15                                     0.0   0.000000
FH51         51 / 51                                     0.0   0.000000
BHDIV10      10 / 10                                     0.0   0.000000
BHPERI       26 / 26                                     0.0   0.000000
PX13         13 / 13                                     0.0   0.000000
WCPT18       18 / 18                                     0.0   0.000000
ADIM6          6 / 6                                     0.0   0.000000
BH76         76 / 76                                     0.0   0.000000
PArel        20 / 20                                     0.0   0.000000
ISO34        34 / 34                                     0.0   0.000000
HEAVY28        0 / 0                                     0.0   0.000000
S66          66 / 66                                     0.0   0.000000
S22          22 / 22                                     0.0   0.000000
CARBHB12     12 / 12                                     0.0   0.000000
AHB21        21 / 21                                     0.0   0.000000
CHB6           4 / 4                                     0.0   0.000000
IL16         16 / 16                                     0.0   0.000000
PNICO23      23 / 23                                     0.0   0.000000
IDISP          6 / 6                                     0.0   0.000000
ICONF        17 / 17                                     0.0   0.000000
Amino20x4    80 / 80                                     0.0   0.000000
ACONF        15 / 15                                     0.0   0.000000
PCONF21      18 / 18                                     0.0   0.000000
MCONF        51 / 51                                     0.0   0.000000
SCONF        17 / 17                                     0.0   0.000000
BUT14DIOL    64 / 64                                     0.0   0.000000

data_path           ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ             \
Type      Processed                                      AI AE     DFT AE
WATER27     25 / 27                                   0.000000   0.000000
ISOL24      20 / 24                                   0.000000   0.000000
INV24       23 / 24                                   0.000000   0.000000
UPU23        0 / 23                                   0.000000   0.000000
BHROT27      0 / 27                                   1.851359   0.690527
C60ISO        0 / 9                                   0.000000   0.000000
RG18         0 / 18                                   0.251269   0.218967
HAL59        0 / 29                                   1.592203   1.380346
AL2X6         0 / 6                                   8.260703   5.659146
HEAVYSB11     0 / 7                                   4.303570   5.391477
NBPRC        0 / 12                                   4.484560   2.232550
ALK8          0 / 8                                   4.321261   4.400063
RC21         0 / 21                                   4.699639   4.820927
G2RC         0 / 25                                   3.490657   5.917204
BH76RC       0 / 30                                   1.041755  80.220383
YBDE18       0 / 18                                   9.546590   8.145395
W4_11       0 / 140                                   2.570469  29.506869
G21EA        0 / 25                                   2.530240   9.754524
G21IP        0 / 36                                   1.623938   8.953336
DIPCS10      0 / 10                                   4.224936  12.310855
PA26         0 / 26                                   3.649045   2.200767
SIE4x4       0 / 16                                   3.692163  21.908521
ALKBDE10      0 / 9                                   9.920985  18.125250
CDIE20       0 / 20                                   2.217768   1.599507
BSR36        0 / 36                                   6.878226   8.401182
RSE43        0 / 43                                   3.209180   3.157601
DARC         0 / 14                                   7.560743  10.754152
MB16_43      0 / 43                                  14.903818  15.461608
DC13         0 / 13                                  10.727333  13.090863
TAUT15       0 / 15                                   2.459828   2.164531
FH51         0 / 51                                   3.566198   3.703658
BHDIV10      0 / 10                                   3.968997   6.277708
BHPERI       0 / 26                                   2.460891   3.268993
PX13         0 / 13                                   6.212648  11.042025
WCPT18       0 / 18                                   3.187194   7.967153
ADIM6         0 / 6                                   3.262108   3.059030
BH76         0 / 76                                   4.251845   9.107948
PArel        0 / 20                                   2.614092   1.743933
ISO34        0 / 34                                   2.924808   2.001744
HEAVY28       0 / 0                                   0.000000   0.000000
S66          0 / 66                                   2.719766   1.894710
S22          0 / 22                                   2.806679   2.291253
CARBHB12     0 / 12                                   0.730135   1.632408
AHB21        0 / 21                                   2.170446   2.453821
CHB6          0 / 4                                   2.638625   1.805320
IL16         0 / 16                                   1.583691   1.021067
PNICO23      0 / 23                                   0.801674   0.776429
IDISP         0 / 6                                  16.242576  13.125478
ICONF        0 / 17                                   1.746365   0.413804
Amino20x4    0 / 80                                   1.681793   0.656235
ACONF        0 / 15                                   1.121573   0.546621
PCONF21      0 / 18                                   4.242832   3.214782
MCONF        0 / 51                                   1.366393   1.956021
SCONF        0 / 17                                   0.779665   0.512352
BUT14DIOL    0 / 64                                   1.017860   0.645099

data_path
Type       Processed
WATER27       0 / 27
ISOL24        0 / 24
INV24         0 / 24
UPU23         0 / 23
BHROT27      12 / 27
C60ISO         0 / 9
RG18          9 / 18
HAL59        26 / 29
AL2X6          6 / 6
HEAVYSB11      7 / 7
NBPRC        12 / 12
ALK8           8 / 8
RC21         21 / 21
G2RC         25 / 25
BH76RC       30 / 30
YBDE18       18 / 18
W4_11      140 / 140
G21EA        25 / 25
G21IP        36 / 36
DIPCS10      10 / 10
PA26         26 / 26
SIE4x4       16 / 16
ALKBDE10       9 / 9
CDIE20       20 / 20
BSR36        36 / 36
RSE43        43 / 43
DARC         14 / 14
MB16_43      43 / 43
DC13         13 / 13
TAUT15       15 / 15
FH51         51 / 51
BHDIV10      10 / 10
BHPERI       26 / 26
PX13         13 / 13
WCPT18       18 / 18
ADIM6          6 / 6
BH76         76 / 76
PArel        20 / 20
ISO34        34 / 34
HEAVY28        0 / 0
S66          66 / 66
S22          22 / 22
CARBHB12     12 / 12
AHB21        21 / 21
CHB6           4 / 4
IL16         16 / 16
PNICO23      23 / 23
IDISP          6 / 6
ICONF        17 / 17
Amino20x4    80 / 80
ACONF        15 / 15
PCONF21      18 / 18
MCONF        51 / 51
SCONF        17 / 17
BUT14DIOL    64 / 64

In [ ]:
Error_molecule = [
    "WATER27-OHm",
    "WATER27-H2O",
    "WATER27-H3Op",
    "WATER27-OHmH2O",
    "WATER27-H2O2",
    "WATER27-H3OpH2O",
    "WATER27-OHmH2O2",
    "WATER27-H2O3",
    "WATER27-H3OpH2O2",
    "WATER27-OHmH2O3",
    "WATER27-H2O4",
    "WATER27-H3OpH2O3",
    "WATER27-OHmH2O4cs",
    "WATER27-OHmH2O4c4",
    "WATER27-H2O5",
    "WATER27-OHmH2O5",
    "WATER27-H2O6c2",
    "WATER27-H2O6b",
    "WATER27-H2O6",
    "WATER27-H2O6c",
    "WATER27-OHmH2O6",
    "WATER27-H3OpH2O62d",
    "WATER27-H3OpH2O63d",
    "WATER27-H2O8d2d",
    "WATER27-H2O8s4",
    "WATER27-H3OpH2O6OHm",
    "WATER27-H2O20fc",
    "WATER27-H2O20fs",
    "WATER27-H2O20es",
    "WATER27-H2O20",
]
print(len(Error_molecule))
# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

30