In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-1055975_gmtkn.csv        100%  430KB  11.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   40KB  19.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5696   130.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB 339.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB 310.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3070    70.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   11KB   5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  14.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   32KB  21.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5199   120.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4487   102.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   15KB 348.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4017    91.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   11KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3155     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   11KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6327     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 2478    55.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4596     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3750     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8717     4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   18KB  13.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   10KB   3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   19KB 433.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5315     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6544   815.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   12KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4729     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   18KB   6.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8116   973.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 7661   176.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB   7.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6643   154.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   13KB   4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3911     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4337     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5081     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 8961   210.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6317   145.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 6042     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5442     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   12KB   4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 2676   677.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1180    27.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 7829     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   10KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1829    41.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 5867     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 3965     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB   4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 4055     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100%   14KB   5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ_mo 100% 1361    30.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5201     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4016     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4487     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   15KB   8.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   32KB  10.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   11KB   3.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 3155     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 6328     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 2467    55.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4583     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 3763     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 8703     3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   10KB   3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   18KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   18KB 435.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5312     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 6534     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   12KB 287.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4725     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   18KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 8115   188.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 7651     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   13KB   5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 3491     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 6638     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   13KB   2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4335     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5074     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 8958     3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 6311   148.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 6045     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5441     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 2668   996.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   11KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   32KB  13.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 1182    26.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5688     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 7806   178.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   14KB 341.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   14KB 328.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   13KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 3078     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   10KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 1619    36.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 5872     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 3949     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 7047     3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100% 4087     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1717981_gmtkn-cc-pVDZ_mo 100%   12KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2075    48.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5201     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6553     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB   7.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4163    96.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1145    26.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   8.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   27KB  13.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 288.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4349   101.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3384     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2683     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7170     4.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   15KB 364.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6772     5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6332     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   15KB  11.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   9.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3797     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9077     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3754     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 9433     3.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5393   740.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2136     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3908     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3190   433.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8578     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   15KB   8.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4609   127.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5537   731.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 244.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3983    93.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5463     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3602     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6101     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7539     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5104     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4446   102.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2153    26.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 5060   115.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   10KB 233.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   34KB 797.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%  993    23.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4767     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB 295.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6558   154.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   6.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   11KB   7.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2515    57.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8528     4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 1859    42.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4823     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   14KB   6.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3375     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2024    44.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3426     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100%   12KB   4.3MB/s   00:00

In [6]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 0
data_set = "gmtkn"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"====DFT error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in dft_error_argsort
                    ]
                )
                print(data_name[dft_error_argsort], data_reaction_energy_dft[dft_error_argsort])
                if verbose == 2:
                    print(f"====Detail of DFT error of {i_subset}====")
                    for i in dft_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_dft_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_name[ai_error_argsort], data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

# df_summary.sort_values(
#     by=("ccdft_cc-pVDZ_atom-1-3111142_gmtkn", "AI AE"),
#     axis=0,
#     inplace=True,
#     ascending=False,
# )

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-test_gmtkn", "Processed"),
    axis=0,
    inplace=True,
    ascending=False,
    key=lambda x: [int(i.split("/")[1]) - int(i.split("/")[0]) for i in x],
)

display(df_summary)

cc-pVDZ

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn
Type                                AI AE     DFT AE  Processed
sub1                                  0.0  18.629823  468 / 468
sub2                                  0.0   6.506382  220 / 243
sub3                                  0.0   6.435978  186 / 194
sub4                                  0.0   2.694038  241 / 244
sub5                                  0.0   0.792081  177 / 291

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn
Type                                AI AE     DFT AE  Processed
MCONF                                 0.0   0.000000     0 / 51
UPU23                                 0.0   0.000000     0 / 23
Amino20x4                             0.0   0.661026    60 / 80
PCONF21                               0.0   0.000000     0 / 18
ISOL24                                0.0   4.284919    10 / 24
C60ISO                                0.0   0.000000      0 / 9
INV24                                 0.0   2.945039    16 / 24
WATER27                               0.0  12.122125    24 / 27
IDISP                                 0.0   8.826633      4 / 6
HEAVYSB11                             0.0   5.391477      7 / 7
AL2X6                                 0.0   5.659146      6 / 6
ALK8                                  0.0   4.400063      8 / 8
RC21                                  0.0   4.820927    21 / 21
G2RC                                  0.0   5.917204    25 / 25
NBPRC                                 0.0   2.232550    12 / 12
YBDE18                                0.0   8.145395    18 / 18
W4_11                                 0.0  29.506869  140 / 140
G21EA                                 0.0   9.754524    25 / 25
G21IP                                 0.0   8.953336    36 / 36
DIPCS10                               0.0  12.310855    10 / 10
PA26                                  0.0   2.200767    26 / 26
SIE4x4                                0.0  21.908521    16 / 16
ALKBDE10                              0.0  18.125250      9 / 9
CDIE20                                0.0   1.599507    20 / 20
BSR36                                 0.0   8.401182    36 / 36
RSE43                                 0.0   3.157601    43 / 43
DARC                                  0.0  10.754152    14 / 14
MB16_43                               0.0  15.461608    43 / 43
DC13                                  0.0  13.090863    13 / 13
TAUT15                                0.0   2.164531    15 / 15
FH51                                  0.0   3.703658    51 / 51
BH76RC                                0.0  80.220383    30 / 30
PX13                                  0.0  11.042025    13 / 13
BHROT27                               0.0   0.853379    27 / 27
ISO34                                 0.0   2.001744    34 / 34
PArel                                 0.0   1.743933    20 / 20
BH76                                  0.0   9.107948    76 / 76
BHPERI                                0.0   3.268993    26 / 26
BHDIV10                               0.0   6.277708    10 / 10
HEAVY28                               0.0   0.000000      0 / 0
S66                                   0.0   1.894710    66 / 66
S22                                   0.0   2.291253    22 / 22
ADIM6                                 0.0   3.059030      6 / 6
RG18                                  0.0   0.230018    18 / 18
WCPT18                                0.0   7.967153    18 / 18
PNICO23                               0.0   0.776429    23 / 23
CARBHB12                              0.0   1.632408    12 / 12
IL16                                  0.0   1.021067    16 / 16
CHB6                                  0.0   1.805320      4 / 4
AHB21                                 0.0   2.453821    21 / 21
HAL59                                 0.0   1.649787    29 / 29
ICONF                                 0.0   0.413804    17 / 17
ACONF                                 0.0   0.546621    15 / 15
SCONF                                 0.0   0.512352    17 / 17
BUT14DIOL                             0.0   0.645099    64 / 64

In [ ]:
import json

mol_name = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",     
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

data_set = "gmtkn-cc-pVDZ"
with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)

len_mol = 0
for i in mol_name:
    len_mol += len(json_data[i])
    # print(i, len(json_data[i]))

print(len_mol)

# mol_name = np.array(mol_name)
# mol_name[[24, 48]]

KeyError: 'PCONF21-99_cc-pVDZ_0_1_0.0000_default'

In [12]:
import json

mol_name = [
    "ISOL24-i23p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i23e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i18p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i12p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i12e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i2p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i2e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i15p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i15e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i8p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i8e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i22e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i17e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i17p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i22p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i6e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i6p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i7p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i16e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i16p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i7e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i24p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i24e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i1p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i1e_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i4p_cc-pVDZ_0_1_0.0000_default",
    "ISOL24-i4e_cc-pVDZ_0_1_0.0000_default",
]

print(json.dumps([_.split("_cc-pVDZ")[0] for _ in mol_name]))

["ISOL24-i23p", "ISOL24-i23e", "ISOL24-i18p", "ISOL24-i12p", "ISOL24-i12e", "ISOL24-i2p", "ISOL24-i2e", "ISOL24-i15p", "ISOL24-i15e", "ISOL24-i8p", "ISOL24-i8e", "ISOL24-i22e", "ISOL24-i17e", "ISOL24-i17p", "ISOL24-i22p", "ISOL24-i6e", "ISOL24-i6p", "ISOL24-i7p", "ISOL24-i16e", "ISOL24-i16p", "ISOL24-i7e", "ISOL24-i24p", "ISOL24-i24e", "ISOL24-i1p", "ISOL24-i1e", "ISOL24-i4p", "ISOL24-i4e"]