In [8]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for data_path in list(Path("../validate").glob(f"*test*.csv")):
    data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  16.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343   348.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051   137.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997   137.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB 735.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179   119.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089    92.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB 928.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB 272.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB 422.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426   124.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511   196.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198   138.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 327.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867    64.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592   104.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB 276.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   5.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732   227.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB 231.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447    56.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185    26.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   7.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643   173.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652   177.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 319.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326     3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB 422.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB 492.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    55.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648   964.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   21KB   9.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 248.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB 312.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4083     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4550     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   40KB  10.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2908   863.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3942     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5860     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB 233.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   5.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3073     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB 326.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2669     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7820     3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 1183    26.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6027     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4067     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2894     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4347   185.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6330   105.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 298.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6640   104.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8019   137.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB 309.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7577   113.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 936.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4727   228.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6538     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5309     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8699   115.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB 791.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB 252.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB 585.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4589   278.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3757   153.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6328   322.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3147     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2464    38.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   32KB   1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5205     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4012     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   15KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4481     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8736     4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5852   134.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   31KB   9.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   10KB   5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB 252.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3950    90.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5124     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   21KB 502.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4006    63.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6263     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   10KB   3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 2457    54.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3119     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4578     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 8567     3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5274   345.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   12KB   4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   15KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4546     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB 810.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6539     3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4733     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB   9.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   11KB   4.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 7631     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   13KB 941.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   13KB 300.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6326   297.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 7825   181.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   13KB 304.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3722    84.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 3084     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4105    92.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4487     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   10KB   3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   18KB   5.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   12KB   2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   14KB   5.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 8150     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   14KB   4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6624     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   40KB  12.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 1189    14.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100%   14KB   4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 2899     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4798     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 7778     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 4339    71.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 8967     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 6028   466.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 5458     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ_mo 100% 2665   972.4KB/s   00:00

In [9]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 0
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    # "test": ["WATER27"],
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        print(
                            f"Warning: {mole_name} not found in {data_path.stem} data file"
                        )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ", "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
)

# df_summary.sort_values(
#     by=("ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ", "Processed"),
#     axis=0,
#     inplace=True,
#     ascending=False,
#     key=lambda x: [int(i.split("/")[1]) - int(i.split("/")[0]) for i in x],
# )

display(df_summary)

cc-pVDZ
Warning: ISOL24-i1e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i2e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i3e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i4e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i5e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i6e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i7e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i8e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i9e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i10e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i11e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i12e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i13e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i14e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i15e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i16e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i17e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i18e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i19e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i20e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i21e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i22e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i23e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i24e not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: ISOL24-i1e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i2e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i4e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i6e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i7e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i8e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i12e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i15e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i16e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i17e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i22e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i24e not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: ISOL24-i1e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i2e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i3e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i4e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i5e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i6e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i7e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i8e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i9e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i10e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i11e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i12e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i13e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i14e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i15e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i16e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i17e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i18e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i19e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i20e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i21e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i22e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i23e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: ISOL24-i24e not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: C60ISO-1 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-H2O not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-H2S not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-SO2 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Ether not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Thioether not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-NMe3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-NCl3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-PMe3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-PCl3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-PH2Ph not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-PPh3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocycloheptene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Pentahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Hexahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocarbazole not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Methinecyanine not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Corannulene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Corannulene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Sumanene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Triazasumanene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Sumanene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrabenzopyracylene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: INV24-Hexahelicene_TS not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: INV24-H2O not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-H2S not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-SO2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Ether not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Thioether not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-NMe3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-NCl3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-PMe3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-PCl3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-PH2Ph not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-PPh3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocycloheptene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrahelicene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Pentahelicene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Hexahelicene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocarbazole not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Methinecyanine not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Corannulene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Corannulene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Sumanene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Triazasumanene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Sumanene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrabenzopyracylene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O2 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O4 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O5 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6c not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6b not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6c2 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O8d2d not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O8s4 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20fc not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20fs not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20es not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O2 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O63d not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O62d not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O2 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O3 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O4c4 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O4cs not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O5 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O6 not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O6OHm not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20fc not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20es not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O5 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6c not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6b not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O6c2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O8d2d not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O8s4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20fc not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20fs not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H2O20es not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O63d not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O62d not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O2 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O3 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O4c4 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O4cs not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O5 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-OHmH2O6 not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: WATER27-H3OpH2O6OHm not found in ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ data file
Warning: IDISP-F22f not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-357 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-300 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-114 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-412 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-691 not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-SER_aR not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-SER_pII not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: PCONF21-SER_b not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file
Warning: UPU23-2p not found in ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ data file

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
sub1                                             3.601181  18.629823
sub2                                             5.700007   6.612165
sub3                                             3.648439   6.764537
sub4                                             2.277669   1.651300
sub5                                             1.775151   1.321288

data_path            ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                   4.692939  18.629823
sub2       210 / 243                                   6.272359   6.562349
sub3       170 / 194                                   4.162538   6.309849
sub4       217 / 244                                   2.254974   2.887648
sub5       268 / 291                                   1.913818   1.245124

data_path            ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
sub1       468 / 468                                   3.241547  18.629823
sub2       222 / 243                                   7.635573   6.612165
sub3       192 / 194                                   2.641689   6.764537
sub4       242 / 244                                   1.822206   1.651300
sub5       259 / 291                                   1.969781   1.321288

data_path
Type       Processed
sub1       468 / 468
sub2       210 / 243
sub3       170 / 194
sub4       217 / 244
sub5       268 / 291

data_path ccdft_cc-pVDZ_atom-1-3881456_4750_gmtkn-cc-pVDZ             \
Type                                                AI AE     DFT AE
IDISP                                           13.337525  13.125478
BSR36                                            2.745238   8.401182
MB16_43                                         15.909280  15.461608
DARC                                             8.461810  10.754152
DC13                                             8.769018  13.090863
AL2X6                                            6.683938   5.659146
YBDE18                                           8.128445   8.145395
ALK8                                             5.330166   4.400063
SIE4x4                                           4.526972  21.908521
PX13                                             7.171943  11.042025
RC21                                             5.258815   4.820927
BHDIV10                                          3.670803   6.277708
ALKBDE10                                        10.401011  18.125250
TAUT15                                           2.322749   2.164531
G2RC                                             3.605386   5.917204
PA26                                             3.603806   2.200767
FH51                                             3.129089   3.703658
ADIM6                                            4.186318   3.059030
HEAVYSB11                                        4.230302   5.391477
PCONF21                                          3.485001   3.214782
S22                                              3.143330   2.291253
DIPCS10                                          3.959661  12.310855
BH76                                             4.142984   9.107948
NBPRC                                            4.266559   2.232550
ISO34                                            2.869448   2.001744
BHPERI                                           2.410479   3.268993
S66                                              2.658246   1.894710
CDIE20                                           2.104062   1.599507
SCONF                                            0.984123   0.512352
W4_11                                            2.977996  29.506869
MCONF                                            1.437692   1.956021
IL16                                             2.246179   1.021067
PArel                                            1.904611   1.743933
RSE43                                            2.741250   3.157601
ICONF                                            1.737822   0.413804
BHROT27                                          1.458525   0.853379
HAL59                                            2.587716   1.649787
AHB21                                            3.116596   2.453821
G21IP                                            1.840062   8.953336
G21EA                                            2.009397   9.754524
ACONF                                            1.801305   0.546621
Amino20x4                                        1.642470   0.656235
CHB6                                             3.579273   1.805320
WCPT18                                           4.076216   7.967153
CARBHB12                                         0.973519   1.632408
BUT14DIOL                                        0.858951   0.645099
PNICO23                                          0.714591   0.776429
BH76RC                                           1.125349  80.220383
RG18                                             0.315151   0.230018
C60ISO                                           0.000000   0.000000
INV24                                            0.000000   0.000000
HEAVY28                                          0.000000   0.000000
ISOL24                                           0.000000   0.000000
WATER27                                          0.000000   0.000000
UPU23                                            0.000000   0.000000

data_path            ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
IDISP          6 / 6                                  15.704176  13.632636
BSR36        36 / 36                                  15.616911   8.401182
MB16_43      43 / 43                                  11.357448  15.461608
DARC         14 / 14                                   4.818050  10.754152
DC13         13 / 13                                   9.695545  13.090863
AL2X6          6 / 6                                   5.084741   5.659146
YBDE18       18 / 18                                   7.255829   8.145395
ALK8           8 / 8                                   6.925821   4.400063
SIE4x4       16 / 16                                  17.182399  21.908521
PX13         13 / 13                                  13.059142  11.042025
RC21         21 / 21                                   4.696462   4.820927
BHDIV10      10 / 10                                   2.461823   6.277708
ALKBDE10       9 / 9                                   5.435985  18.125250
TAUT15       15 / 15                                   1.871571   2.164531
G2RC         25 / 25                                   3.044318   5.917204
PA26         26 / 26                                   3.011796   2.200767
FH51         51 / 51                                   3.055128   3.703658
ADIM6          6 / 6                                   3.649860   3.059030
HEAVYSB11      7 / 7                                   3.928191   5.391477
PCONF21      18 / 18                                   3.418177   3.683764
S22          22 / 22                                   4.086915   2.291253
DIPCS10      10 / 10                                   4.414108  12.310855
BH76         76 / 76                                   4.203748   9.107948
NBPRC        12 / 12                                   2.745689   2.232550
ISO34        34 / 34                                   2.057023   2.001744
BHPERI       26 / 26                                   2.119660   3.268993
S66          66 / 66                                   2.331477   1.894710
CDIE20       20 / 20                                   1.160373   1.599507
SCONF        17 / 17                                   1.591377   0.512352
W4_11      140 / 140                                   5.805564  29.506869
MCONF        51 / 51                                   3.392493   1.956021
IL16         16 / 16                                   1.735752   1.021067
PArel        20 / 20                                   1.962423   1.743933
RSE43        43 / 43                                   1.951595   3.157601
ICONF        17 / 17                                   0.709620   0.413804
BHROT27      27 / 27                                   1.078680   0.853379
HAL59        29 / 29                                   1.848147   1.649787
AHB21        21 / 21                                   1.766602   2.453821
G21IP        36 / 36                                   2.390142   8.953336
G21EA        25 / 25                                   2.127111   9.754524
ACONF        15 / 15                                   0.548364   0.546621
Amino20x4    80 / 80                                   1.405904   0.656235
CHB6           4 / 4                                   3.585377   1.805320
WCPT18       18 / 18                                   4.243739   7.967153
CARBHB12     12 / 12                                   1.364792   1.632408
BUT14DIOL    64 / 64                                   0.783503   0.645099
PNICO23      23 / 23                                   0.717968   0.776429
BH76RC       30 / 30                                   1.212571  80.220383
RG18         18 / 18                                   0.503217   0.230018
C60ISO         0 / 9                                   0.000000   0.000000
INV24         0 / 24                                   5.668748   2.796356
HEAVY28        0 / 0                                   0.000000   0.000000
ISOL24        0 / 24                                   4.843230   5.690557
WATER27       0 / 27                                   4.210310  13.619146
UPU23         0 / 23                                   0.000000   0.000000

data_path            ccdft_cc-pVDZ_atom-1-3011875_gmtkn-cc-pVDZ             \
Type       Processed                                      AI AE     DFT AE
IDISP          5 / 6                                  16.391443  13.125478
BSR36        36 / 36                                  15.760088   8.401182
MB16_43      43 / 43                                  14.143650  15.461608
DARC         14 / 14                                  13.099602  10.754152
DC13         13 / 13                                  10.366464  13.090863
AL2X6          6 / 6                                   8.894529   5.659146
YBDE18       18 / 18                                   6.516461   8.145395
ALK8           8 / 8                                   6.047365   4.400063
SIE4x4       16 / 16                                   5.216139  21.908521
PX13         13 / 13                                   4.542266  11.042025
RC21         21 / 21                                   4.528531   4.820927
BHDIV10      10 / 10                                   4.527059   6.277708
ALKBDE10       9 / 9                                   4.382134  18.125250
TAUT15       15 / 15                                   4.231991   2.164531
G2RC         25 / 25                                   4.223215   5.917204
PA26         26 / 26                                   3.771610   2.200767
FH51         51 / 51                                   3.687652   3.703658
ADIM6          6 / 6                                   3.620309   3.059030
HEAVYSB11      7 / 7                                   3.445613   5.391477
PCONF21      10 / 18                                   3.283385   3.214782
S22          22 / 22                                   2.930795   2.291253
DIPCS10      10 / 10                                   2.910152  12.310855
BH76         76 / 76                                   2.771447   9.107948
NBPRC        12 / 12                                   2.721367   2.232550
ISO34        34 / 34                                   2.627635   2.001744
BHPERI       26 / 26                                   2.420098   3.268993
S66          66 / 66                                   2.292499   1.894710
CDIE20       20 / 20                                   2.063270   1.599507
SCONF        17 / 17                                   2.056696   0.512352
W4_11      140 / 140                                   2.020613  29.506869
MCONF        51 / 51                                   2.010921   1.956021
IL16         16 / 16                                   1.946990   1.021067
PArel        20 / 20                                   1.866417   1.743933
RSE43        43 / 43                                   1.781451   3.157601
ICONF        17 / 17                                   1.717642   0.413804
BHROT27      27 / 27                                   1.715673   0.853379
HAL59        29 / 29                                   1.647527   1.649787
AHB21        21 / 21                                   1.636629   2.453821
G21IP        36 / 36                                   1.609505   8.953336
G21EA        25 / 25                                   1.591239   9.754524
ACONF        15 / 15                                   1.494521   0.546621
Amino20x4    80 / 80                                   1.405702   0.656235
CHB6           4 / 4                                   1.394721   1.805320
WCPT18       18 / 18                                   1.382857   7.967153
CARBHB12     12 / 12                                   1.095832   1.632408
BUT14DIOL    64 / 64                                   1.075891   0.645099
PNICO23      23 / 23                                   0.789794   0.776429
BH76RC       30 / 30                                   0.785408  80.220383
RG18         18 / 18                                   0.428948   0.230018
C60ISO         0 / 9                                   0.000000   0.000000
INV24        22 / 24                                   0.000000   0.000000
HEAVY28        0 / 0                                   0.000000   0.000000
ISOL24       12 / 24                                   0.000000   0.000000
WATER27      25 / 27                                   0.000000   0.000000
UPU23         0 / 23                                   0.000000   0.000000

data_path
Type       Processed
IDISP          6 / 6
BSR36        36 / 36
MB16_43      43 / 43
DARC         14 / 14
DC13         13 / 13
AL2X6          6 / 6
YBDE18       18 / 18
ALK8           8 / 8
SIE4x4       16 / 16
PX13         13 / 13
RC21         21 / 21
BHDIV10      10 / 10
ALKBDE10       9 / 9
TAUT15       15 / 15
G2RC         25 / 25
PA26         26 / 26
FH51         51 / 51
ADIM6          6 / 6
HEAVYSB11      7 / 7
PCONF21      18 / 18
S22          22 / 22
DIPCS10      10 / 10
BH76         76 / 76
NBPRC        12 / 12
ISO34        34 / 34
BHPERI       26 / 26
S66          66 / 66
CDIE20       20 / 20
SCONF        17 / 17
W4_11      140 / 140
MCONF        51 / 51
IL16         16 / 16
PArel        20 / 20
RSE43        43 / 43
ICONF        17 / 17
BHROT27      27 / 27
HAL59        29 / 29
AHB21        21 / 21
G21IP        36 / 36
G21EA        25 / 25
ACONF        15 / 15
Amino20x4    80 / 80
CHB6           4 / 4
WCPT18       18 / 18
CARBHB12     12 / 12
BUT14DIOL    64 / 64
PNICO23      23 / 23
BH76RC       30 / 30
RG18         18 / 18
C60ISO         0 / 9
INV24         0 / 24
HEAVY28        0 / 0
ISOL24        0 / 24
WATER27       0 / 27
UPU23         0 / 23

In [ ]:
Error_molecule = [
    "G21IP-IP_80_cc-pVDZ_0-1_1_0.0000_default",
    "G21EA-EA_23n_cc-pVDZ_0-1_1_0.0000_default",
    "BH76-RKT15_cc-pVDZ_0-1_1_0.0000_default",
]
print(len(Error_molecule))

# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

str_print = ''
for molecule in Error_molecule:
    str_print += molecule.split("_cc-pVDZ_")[0] + " "
print(str_print)

3
G21IP-IP_80 G21EA-EA_23n BH76-RKT15