In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  31.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8341     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867    65.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB 927.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB 671.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648   938.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   5.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643   174.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   4.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    55.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774     1.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070     3.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB   9.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   32KB   8.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179     2.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185    26.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   4.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   4.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   3.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447    54.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   3.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4966     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2368    52.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3885     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 6366     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4470     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   15KB   5.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5189     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3993     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6329     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3145     1.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4586     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3760    85.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2461    56.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8684   196.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   6.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5314     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6529     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4718     1.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   18KB   5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8127     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7643     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   4.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6624     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4335     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 8969     3.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6311     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 6026     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5446     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2660   926.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   12KB 275.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   40KB 919.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 1188    26.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 7817     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   4.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   13KB   4.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3071    70.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   10KB   3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 2903     1.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 5835     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 3941     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   21KB   9.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4554   104.5KB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   11KB   3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100% 4092     1.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ_mo 100%   14KB   4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_W4_11 100%  330     3.9KB/s   00:00

In [7]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    "test": ["INV24"],
    # "sub1": [
    #     "W4_11",
    #     "G21EA",
    #     "G21IP",
    #     "DIPCS10",
    #     "PA26",
    #     "SIE4x4",
    #     "ALKBDE10",
    #     "YBDE18",
    #     "AL2X6",
    #     "HEAVYSB11",
    #     "NBPRC",
    #     "ALK8",
    #     "RC21",
    #     "G2RC",
    #     "BH76RC",
    #     "FH51",
    #     "TAUT15",
    #     "DC13",
    # ],
    # "sub2": [
    #     "MB16_43",
    #     "DARC",
    #     "RSE43",
    #     "BSR36",
    #     "CDIE20",
    #     "ISO34",
    #     "ISOL24",
    #     "C60ISO",
    #     "PArel",
    # ],
    # "sub3": [
    #     "BH76",
    #     "BHPERI",
    #     "BHDIV10",
    #     "INV24",
    #     "BHROT27",
    #     "PX13",
    #     "WCPT18",
    # ],
    # "sub4": [
    #     "RG18",
    #     "ADIM6",
    #     "S22",
    #     "S66",
    #     "HEAVY28",
    #     "WATER27",
    #     "CARBHB12",
    #     "PNICO23",
    #     "HAL59",
    #     "AHB21",
    #     "CHB6",
    #     "IL16",
    # ],
    # "sub5": [
    #     "IDISP",
    #     "ICONF",
    #     "ACONF",
    #     "Amino20x4",
    #     "PCONF21",
    #     "MCONF",
    #     "SCONF",
    #     "UPU23",
    #     "BUT14DIOL",
    # ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        print(
                            f"Warning: {mole_name} not found in {data_path.stem} data file"
                        )
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

# df_summary.sort_values(
#     by=("ccdft_cc-pVDZ_atom-1-1150169_gmtkn", "AI AE"),
#     axis=0,
#     inplace=True,
#     ascending=False,
# )

# df_summary.sort_values(
#     by=("ccdft_cc-pVDZ_atom-1-1150169_gmtkn", "Processed"),
#     axis=0,
#     inplace=True,
#     ascending=False,
#     key=lambda x: [int(i.split("/")[1]) - int(i.split("/")[0]) for i in x],
# )

display(df_summary)

cc-pVDZ
Warning: INV24-Hexahelicene not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene_TS not found in ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ.csv####
====AI error of INV24====
[['Tetrabenzopyracylene', 'Tetrabenzopyracylene_TS'], ['BN_Sumanene', 'BN_Sumanene_TS'], ['Triazasumanene', 'Triazasumanene_TS'], ['Sumanene', 'Sumanene_TS'], ['BN_Corannulene', 'BN_Corannulene_TS']]
[0. 0. 0. 0. 0.]
====Detail of AI error of INV24====
22: 0.0
0.0 -1 Tetrabenzopyracylene
0.0 1 Tetrabenzopyracylene_TS

21: 0.0
0.0 -1 BN_Sumanene
0.0 1 BN_Sumanene_TS

20: 0.0
0.0 -1 Triazasumanene
0.0 1 Triazasumanene_TS

19: 0.0
0.0 -1 Sumanene
0.0 1 Sumanene_TS

18: 0.0
0.0 -1 BN_Corannulene
0.0 1 BN_Corannulene_TS

Warning: INV24-Hexahelicene_TS not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene not found in ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ.csv####
====AI error of INV24====
[['PCl3', 'PCl3_TS'], ['Sumanene', 'Sumanene_TS'], ['PPh3', 'PPh3_TS'], ['Tetrabenzopyracylene', 'Tetrabenzopyracylene_TS'], ['Triazasumanene', 'Triazasumanene_TS']]
[17.03352384 15.25884095 12.94544383 12.11755674  9.76339774]
====Detail of AI error of INV24====
8: 17.033523842001998
5.839746866446043 -1 PCl3
22.87327070844804 1 PCl3_TS

19: 15.258840952900947
-53.31465983592253 -1 Sumanene
-38.05581888302158 1 Sumanene_TS

10: 12.945443831966337
-54.894707164009176 -1 PPh3
-41.94926333204284 1 PPh3_TS

22: 12.117556737727014
-67.70574609933266 -1 Tetrabenzopyracylene
-55.58818936160564 1 Tetrabenzopyracylene_TS

20: 9.763397738205988
-48.733180872335126 -1 Triazasumanene
-38.96978313412914 1 Triazasumanene_TS

Warning: INV24-H2O not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-H2S not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-SO2 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Ether not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Thioether not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-NMe3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-NCl3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-PMe3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-PCl3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-PH2Ph not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-PPh3 not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocycloheptene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Pentahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Hexahelicene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Dibenzocarbazole not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Methinecyanine not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Corannulene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Corannulene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Sumanene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Triazasumanene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-BN_Sumanene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Tetrabenzopyracylene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
Warning: INV24-Triindenotriphenylene not found in ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ data file
####data_path:../validate/ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ.csv####
====AI error of INV24====
[]
[]
====Detail of AI error of INV24====

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ                      \
Type                                        AI AE    DFT AE Processed
test                                          0.0  2.796373   22 / 24

data_path ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ                      \
Type                                           AI AE    DFT AE Processed
test                                        5.668748  2.796356   22 / 24

data_path ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ
Type                                           AI AE DFT AE Processed
test                                               0      0    0 / 24

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ                      \
Type                                        AI AE    DFT AE Processed
INV24                                         0.0  2.796373   22 / 24

data_path ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ                      \
Type                                           AI AE    DFT AE Processed
INV24                                       5.668748  2.796356   22 / 24

data_path ccdft_cc-pVDZ_atom-1-3881456_gmtkn-cc-pVDZ
Type                                           AI AE DFT AE Processed
INV24                                              0      0    0 / 24

In [1]:
Error_molecule = [
    "W4_11-cl2_cc-pVDZ_0-1_1_-0.5000_default",
    "G2RC-24_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-nh_cc-pVDZ_0-1_1_0.5000_default",
    "G21IP-IP_70_cc-pVDZ_0-1_1_0.5000_default",
    "G21EA-EA_11n_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-cl2_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-bn3pi_cc-pVDZ_0-1_1_0.5000_default",
    "G2RC-45_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-oclo_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-n2h_cc-pVDZ_0-1_1_-0.5000_default",
    "BH76-NH2_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-nh2_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-no2_cc-pVDZ_0-1_1_0.5000_default",
    "G21EA-EA_12n_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-bef2_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-t-hooo_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-c-hooo_cc-pVDZ_0-1_1_0.5000_default",
    "G21IP-IP_64_cc-pVDZ_0-1_1_0.5000_default",
    "SIE4x4-h2o2+_1.75_cc-pVDZ_0-1_1_-0.5000_default",
    "SIE4x4-nh32+_1.5_cc-pVDZ_0-1_1_0.5000_default",
    "SIE4x4-nh32+_1.75_cc-pVDZ_0-1_1_-0.5000_default",
    "SIE4x4-nh32+_1.75_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-pme2_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-asme2_cc-pVDZ_0-1_1_0.5000_default",
]
# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

In [14]:
a = np.random.random((2, 2, 2))

In [15]:
print(a)
print(a.reshape((4, 2)))

[[[0.60304111 0.57142901]
  [0.47472272 0.82949855]]

 [[0.24165046 0.32076752]
  [0.27413131 0.19826097]]]
[[0.60304111 0.57142901]
 [0.47472272 0.82949855]
 [0.24165046 0.32076752]
 [0.27413131 0.19826097]]