In [1]:
from pathlib import Path

import pandas as pd

!scp -r hkqai:~/workdir/cc2cc_test5/validate/ ~/workspace/2025.1/
name_mol_list = [
    "molecule_W4_11",
    "molecule_G21EA",
    "molecule_G21IP",
    "molecule_DIPCS10",
    "molecule_PA26",
    "molecule_SIE4x4",
    "molecule_ALKBDE10",
    "molecule_YBDE18",
    "molecule_AL2X6",
    "molecule_HEAVYSB11",
    "molecule_NBPRC",
    "molecule_ALK8",
    "molecule_RC21",
    "molecule_G2RC",
    "molecule_BH76",
    "molecule_FH51",
    "molecule_TAUT15",
    "molecule_DC13",
    "molecule_MB16_43",
    "molecule_DARC",
    "molecule_RSE43",
    "molecule_BSR36",
    "molecule_CDIE20",
    "molecule_ISO34",
    "molecule_ISOL24",
    "molecule_C60ISO",
    "molecule_PArel",
    "molecule_BHPERI",
    "molecule_BHDIV10",
    "molecule_INV24",
    "molecule_BHROT27",
    "molecule_PX13",
    "molecule_WCPT18",
    "molecule_RG18",
    "molecule_ADIM6",
    "molecule_S22",
    "molecule_S66",
    "molecule_HEAVY28",
    "molecule_WATER27",
    "molecule_CARBHB12",
    "molecule_PNICO23",
    "molecule_HAL59",
    "molecule_AHB21",
    "molecule_CHB6",
    "molecule_IL16",
    "molecule_IDISP",
    "molecule_ICONF",
    "molecule_ACONF",
    "molecule_Amino20x4",
    "molecule_PCONF21",
    "molecule_MCONF",
    "molecule_SCONF",
    "molecule_UPU23",
    "molecule_BUT14DIOL",
]

if_start_file = {}

for i, name_mol in enumerate(name_mol_list):
    data_path_list = sorted(
        list(Path("../validate").glob(f"*{name_mol}.csv")),
        key=lambda p: p.stat().st_ctime,
    )
    
    for data_path in data_path_list:
        summary_data_path = data_path.stem.split("_" + name_mol)[0] + ".csv"

        with open(data_path, "r") as f:
            data = pd.read_csv(f)

        if if_start_file.get(summary_data_path, True):
            with open(Path("../validate") / summary_data_path, "w") as f2:
                data.to_csv(f2, index=False)
            if_start_file[summary_data_path] = False
        else:
            with open(Path("../validate") / summary_data_path, "a") as f2:
                data.to_csv(f2, index=False, header=False)

for i, name_mol in enumerate(name_mol_list):
    for data_path in list(Path("../validate").glob(f"*{name_mol}.csv")):
        data_path.unlink()

for summary_data_path in list(Path("../validate").glob("*-cc-pVDZ.csv")):
    with open(summary_data_path, "r") as f:
        data = pd.read_csv(f)

    with open(Path("../validate") / summary_data_path.name.replace("-cc-pVDZ", ""), "w") as f2:
        data.to_csv(f2, index=False)

ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   40KB  11.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 1185   944.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7652     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 318.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4604   107.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 8717     4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-3111142_gmtkn-cc-pVDZ.cs 100%  264KB  13.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   7.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   32KB 752.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   15KB 358.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4490   105.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   11KB   5.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5179     2.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3995   877.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6343     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2470    56.8KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3140     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4592     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3774    87.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8511     5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB 233.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB  12.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB  10.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5312     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6468     4.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   7.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4724     2.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   18KB  10.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8070     4.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 7643     4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5107     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6600     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4326     2.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 9732     6.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 8818   209.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6198     3.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 6051     3.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5426     2.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2648    60.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   12KB   6.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5997     3.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB   7.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   13KB   7.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4006     2.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 6329     3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 2473    56.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 3151     2.0MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 3764     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   10KB   6.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 2029    24.0KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3053     1.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   6.4MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2447    55.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 3354     1.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 5841     3.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   18KB   9.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   19KB  10.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 6547     3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4730     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   18KB  10.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 7651     4.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 6654     3.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4331     2.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 6023   142.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   12KB 281.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   14KB 347.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   10KB   5.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   11KB   5.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 8158     4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   21KB  11.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 4089     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 6310     3.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 2661     1.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 7834     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 3078    71.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 3961     2.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4088     2.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   14KB 329.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 5317   121.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   12KB   6.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 8140     4.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   13KB   6.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   13KB   6.9MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 8979     5.5MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 5429     3.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   40KB  19.8MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   14KB 330.1KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 5876   136.3KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   14KB 330.6KB/s   00:00
ccdft_cc-pVDZ_atom-1-test_gmtkn-cc-pVDZ_molec 100% 4601   105.9KB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100%   10KB   5.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 1182   823.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   13KB   8.2MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   21KB 504.7KB/s   00:00
ccdft_cc-pVDZ_atom-1-1796537_gmtkn-cc-pVDZ_mo 100% 6444     4.3MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   11KB   4.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 3959     1.6MB/s   00:00
ccdft_cc-pVDZ_atom-1-1150169_gmtkn-cc-pVDZ_mo 100% 2867     1.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   15KB  11.7MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 4494   105.4KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   32KB  10.1MB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100%   11KB 251.2KB/s   00:00
ccdft_cc-pVDZ_atom-1-1935936_gmtkn-cc-pVDZ_mo 100% 5203     2.1MB/s   00:00

In [2]:
import json
from pathlib import Path

import pandas as pd
import numpy as np

verbose = 2
data_set = "gmtkn"

data_path_list = sorted(
    list(Path("../validate").glob(f"*{data_set}.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"../cc2cc/utils/{data_set}.json") as f:
    json_data = json.load(f)


full_subset_dict = {
    "sub1": [
        "W4_11",
        "G21EA",
        "G21IP",
        "DIPCS10",
        "PA26",
        "SIE4x4",
        "ALKBDE10",
        "YBDE18",
        "AL2X6",
        "HEAVYSB11",
        "NBPRC",
        "ALK8",
        "RC21",
        "G2RC",
        "BH76RC",
        "FH51",
        "TAUT15",
        "DC13",
    ],
    "sub2": [
        "MB16_43",
        "DARC",
        "RSE43",
        "BSR36",
        "CDIE20",
        "ISO34",
        "ISOL24",
        "C60ISO",
        "PArel",
    ],
    "sub3": [
        "BH76",
        "BHPERI",
        "BHDIV10",
        "INV24",
        "BHROT27",
        "PX13",
        "WCPT18",
    ],
    "sub4": [
        "RG18",
        "ADIM6",
        "S22",
        "S66",
        "HEAVY28",
        "WATER27",
        "CARBHB12",
        "PNICO23",
        "HAL59",
        "AHB21",
        "CHB6",
        "IL16",
    ],
    "sub5": [
        "IDISP",
        "ICONF",
        "ACONF",
        "Amino20x4",
        "PCONF21",
        "MCONF",
        "SCONF",
        "UPU23",
        "BUT14DIOL",
    ],
}
subset_list = []
for i_subset in full_subset_dict.keys():
    subset_list.extend(full_subset_dict[i_subset])

# accumulate summary dictionaries for each file
summary_list = []
subset_summary_list = []

for name_set, subset_list_ in full_subset_dict.items():
    summary_data_list = {}
    for i_subset in subset_list_:
        summary = {}

        for data_path in data_path_list:
            data = pd.read_csv(data_path)
            data["name"] = data["name"].str.split(f"_{basis_args}").str[0]

            data_name = []
            data_reaction_energy_dft = []
            data_reaction_energy_ai = []

            reaction_dict = json_data[f"reaction-{i_subset}"]
            reaction_dict_copy = reaction_dict.copy()
            for i_reaction_name, i_reaction in reaction_dict_copy.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_ai = 0
                for i in range(len(systems_list)):
                    finished = True
                    mole_name = (
                        f"{i_subset}-{systems_list[i]}"
                        if i_subset != "BH76RC"
                        else systems_list[i]
                    )

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished = False
                        reaction_dict.pop(i_reaction_name)
                        break

                    col = data["name"] == mole_name
                    if col.any():
                        atomic_energy_dft += data[col]["error_dft_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                        atomic_energy_ai += data[col]["error_scf_ene"].values[0] * int(
                            stoichiometry_list[i]
                        )
                    else:
                        finished = False
                        break

                if finished:
                    data_reaction_energy_dft.append(atomic_energy_dft)
                    data_reaction_energy_ai.append(atomic_energy_ai)
                    data_name.append(i_reaction_name)

            data_name = np.array(data_name)
            data_reaction_energy_dft = np.array(data_reaction_energy_dft)
            data_reaction_energy_ai = np.array(data_reaction_energy_ai)

            if verbose > 0:
                dft_error_argsort = np.argsort(np.abs(data_reaction_energy_dft))[::-1][:5]
                ai_error_argsort = np.argsort(np.abs(data_reaction_energy_ai))[::-1][:5]

                print(f"####data_path:{data_path}####")
                
                # print(f"====DFT error of {i_subset}====")
                # print(
                #     [
                #         json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         for i in dft_error_argsort
                #     ]
                # )
                # print(data_reaction_energy_dft[dft_error_argsort])
                # if verbose == 2:
                #     print(f"====Detail of DFT error of {i_subset}====")
                #     for i in dft_error_argsort:
                #         print(f"{data_name[i]}: {data_reaction_energy_dft[i]}")
                #         systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                #         stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                #         for j in range(len(systems_list)):
                #             mole_name = (
                #                 f"{i_subset}-{systems_list[j]}"
                #                 if i_subset != "BH76RC"
                #                 else systems_list[j]
                #             )

                #             if mole_name in json_data:
                #                 if isinstance(json_data[mole_name], str):
                #                     mole_name = json_data[mole_name]

                #             col = data["name"] == mole_name
                #             print(
                #                 data[col]["error_dft_ene"].values[0],
                #                 int(stoichiometry_list[j]),
                #                 systems_list[j],
                #             )
                #         print()
                            
                print(f"====AI error of {i_subset}====")
                print(
                    [
                        json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        for i in ai_error_argsort
                    ]
                )
                print(data_reaction_energy_ai[ai_error_argsort])
                if verbose == 2:
                    print(f"====Detail of AI error of {i_subset}====")
                    for i in ai_error_argsort:
                        print(f"{data_name[i]}: {data_reaction_energy_ai[i]}")
                        systems_list = json_data[f"reaction-{i_subset}"][data_name[i]]["systems"]
                        stoichiometry_list = json_data[f"reaction-{i_subset}"][data_name[i]]["stoichiometry"]
                        for j in range(len(systems_list)):
                            mole_name = (
                                f"{i_subset}-{systems_list[j]}"
                                if i_subset != "BH76RC"
                                else systems_list[j]
                            )

                            if mole_name in json_data:
                                if isinstance(json_data[mole_name], str):
                                    mole_name = json_data[mole_name]

                            col = data["name"] == mole_name
                            print(
                                data[col]["error_scf_ene"].values[0],
                                int(stoichiometry_list[j]),
                                systems_list[j],
                            )
                        print()
                            
            summary.update(
                {
                    f"{data_path.stem} AI AE": (
                        np.mean(np.abs(data_reaction_energy_ai))
                        if len(data_reaction_energy_ai)
                        else 0
                    ),
                    f"{data_path.stem} DFT AE": (
                        np.mean(np.abs(data_reaction_energy_dft))
                        if len(data_reaction_energy_dft)
                        else 0
                    ),
                    f"{data_path.stem} Processed": f"{len(data_reaction_energy_dft)} / {len(reaction_dict)}",
                }
            )

            if f"{data_path.stem} AI AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} AI AE"] = data_reaction_energy_ai
            else:
                summary_data_list[f"{data_path.stem} AI AE"] = np.append(
                    summary_data_list[f"{data_path.stem} AI AE"],
                    data_reaction_energy_ai,
                )

            if f"{data_path.stem} DFT AE" not in summary_data_list:
                summary_data_list[f"{data_path.stem} DFT AE"] = data_reaction_energy_dft
            else:
                summary_data_list[f"{data_path.stem} DFT AE"] = np.append(
                    summary_data_list[f"{data_path.stem} DFT AE"],
                    data_reaction_energy_dft,
                )

            if f"{data_path.stem} reaction_dict" not in summary_data_list:
                summary_data_list[f"{data_path.stem} reaction_dict"] = len(
                    reaction_dict
                )
            else:
                summary_data_list[f"{data_path.stem} reaction_dict"] += len(
                    reaction_dict
                )

        summary_list.append(summary)

    subset_summary = {}
    for data_path in data_path_list:
        subset_summary.update(
            {
                f"{data_path.stem} AI AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} AI AE"]))
                    if len(summary_data_list[f"{data_path.stem} AI AE"])
                    else 0
                ),
                f"{data_path.stem} DFT AE": (
                    np.mean(np.abs(summary_data_list[f"{data_path.stem} DFT AE"]))
                    if len(summary_data_list[f"{data_path.stem} DFT AE"])
                    else 0
                ),
                f"{data_path.stem} Processed": f"{len(summary_data_list[f"{data_path.stem} AI AE"])} / {summary_data_list[f"{data_path.stem} reaction_dict"]}",
            }
        )
    subset_summary_list.append(subset_summary)

# display one summary table for all files
header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    subset_summary_list,
    index=full_subset_dict.keys(),
)
df_summary.columns = header
display(df_summary)

header = pd.MultiIndex.from_product(
    [
        [data_path.stem for data_path in data_path_list],
        ["AI AE", "DFT AE", "Processed"],
    ],
    names=["data_path", "Type"],
)
df_summary = pd.DataFrame(
    summary_list,
    index=subset_list,
)
df_summary.columns = header

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-1150169_gmtkn", "AI AE"),
    axis=0,
    inplace=True,
    ascending=False,
)

df_summary.sort_values(
    by=("ccdft_cc-pVDZ_atom-1-1150169_gmtkn", "Processed"),
    axis=0,
    inplace=True,
    ascending=False,
    key=lambda x: [int(i.split("/")[1]) - int(i.split("/")[0]) for i in x],
)

display(df_summary)

cc-pVDZ
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of W4_11====
[['propane', 'c', 'h'], ['propene', 'c', 'h'], ['s4-c2v', 's'], ['acetic', 'c', 'o', 'h'], ['glyoxal', 'c', 'o', 'h']]
[ 19.41995005  17.52912642 -16.80355977  16.2599607   15.20639248]
====Detail of AI error of W4_11====
15: 19.41995004655437
-0.4830054018798897 -1 propane
0.5723009303366778 3 c
2.152505231708056 8 h

23: 17.5291264151846
-2.897192233926232 -1 propene
0.5723009303366778 3 c
2.152505231708056 6 h

128: -16.80355976843325
12.369090028304717 -1 s4-c2v
-1.108617435032133 4 s

52: 16.259960702272796
-2.896038679013616 -1 acetic
0.5723009303366778 2 c
1.8046496178768003 2 o
2.152505231708056 4 h

66: 15.206392481996781
-6.147480922153714 -1 glyoxal
0.5723009303366778 2 c
1.8046496178768003 2 o
2.152505231708056 2 h

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of W4_11====
[['sif4', 'si', 'f'], ['cf4', 'c', 'f'], ['cloo', 'cl', 'o'], ['p4', 'p'], ['t-hooo', 'h', 'o']]
[13.36934093 10.89090885 -8.61629693 -7.23636697  3.89957331]
====Detail of AI error of W4_11====
41: 13.36934093477512
-15.968891100191902 -1 sif4
0.5773703212367801 1 si
-0.79423012166339 4 f

69: 10.89090884813984
-14.439472133994244 -1 cf4
-0.3716427992008418 1 c
-0.79423012166339 4 f

135: -8.616296931431076
7.672105431705736 -1 cloo
-0.4733292232017221 1 cl
-0.2354311382618097 2 o

116: -7.236366974319471
7.522812587960249 -1 p4
0.0716114034101946 4 p

120: 3.8995733102149193
-4.609285037788258 -1 t-hooo
-0.003418312787909 1 h
-0.2354311382618097 3 o

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of W4_11====
[['sif4', 'si', 'f'], ['cf4', 'c', 'f'], ['cloo', 'cl', 'o'], ['sio', 'si', 'o'], ['s2o', 's', 'o']]
[13.36978028 11.86868331 -9.06962966  4.97297763 -3.58066218]
====Detail of AI error of W4_11====
41: 13.369780284697665
-10.667620480012223 -1 sif4
1.0626647794884263 1 si
0.4098737562992538 4 f

69: 11.868683305039674
-10.363819662227856 -1 cf4
-0.1346313823851961 1 c
0.4098737562992538 4 f

135: -9.06962966108846
9.46245221820922 -1 cloo
-0.4983973300792745 1 cl
0.4456099436000174 2 o

94: 4.972977625223507
-3.4647029021350626 -1 sio
1.0626647794884263 1 si
0.4456099436000174 1 o

121: -3.5806621760552164
2.221482117722791 -1 s2o
-0.9023950009662216 2 s
0.4456099436000174 1 o

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of W4_11====
[]
[]
====Detail of AI error of W4_11====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of W4_11====
[]
[]
====Detail of AI error of W4_11====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_22n', 'EA_22'], ['EA_20n', 'EA_20'], ['EA_19n', 'EA_19'], ['EA_24n', 'EA_24']]
[-15.56148959   3.84874462  -3.75388118   3.62147956  -3.52076851]
====Detail of AI error of G21EA====
24: -15.561489585733463
0.1865803499518095 1 EA_25n
15.748069935685272 -1 EA_25

21: 3.8487446212811336
1.9522720253207169 1 EA_22n
-1.8964725959604167 -1 EA_22

19: -3.753881182568128
-0.065322968894728 1 EA_20n
3.6885582136734 -1 EA_20

18: 3.6214795645507967
0.2499509659644877 1 EA_19n
-3.371528598586309 -1 EA_19

23: -3.520768508004529
-2.2363244771197506 1 EA_24n
1.2844440308847784 -1 EA_24

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_20n', 'EA_20'], ['EA_24n', 'EA_24'], ['EA_23n', 'EA_23'], ['EA_22n', 'EA_22']]
[-10.40947189  -4.61876487  -3.93666911  -3.57697351  -1.12097829]
====Detail of AI error of G21EA====
24: -10.40947189073624
1.1088559118793613 1 EA_25n
11.518327802615602 -1 EA_25

19: -4.61876486939719
-1.3802687857272338 1 EA_20n
3.238496083669957 -1 EA_20

23: -3.936669107126732
-2.045553032535988 1 EA_24n
1.891116074590744 -1 EA_24

22: -3.57697351191851
1.5086776516837448 1 EA_23n
5.085651163602255 -1 EA_23

21: -1.1209782943868885
-0.3908860574813535 1 EA_22n
0.7300922369055349 -1 EA_22

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of G21EA====
[['EA_25n', 'EA_25'], ['EA_24n', 'EA_24'], ['EA_20n', 'EA_20'], ['EA_23n', 'EA_23'], ['EA_21n', 'EA_21']]
[-13.29325356  -5.40182699  -3.05678718  -2.94769831  -1.70608162]
====Detail of AI error of G21EA====
24: -13.293253561905091
-1.0209240976394327 1 EA_25n
12.272329464265658 -1 EA_25

23: -5.401826989574376
-1.3658102364434663 1 EA_24n
4.03601675313091 -1 EA_24

19: -3.0567871809156424
1.1216862850304743 1 EA_20n
4.178473465946117 -1 EA_20

22: -2.947698310362093
2.4986544361227465 1 EA_23n
5.446352746484839 -1 EA_23

20: -1.7060816161806165
-0.7170712636682298 1 EA_21n
0.9890103525123868 -1 EA_21

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of G21EA====
[]
[]
====Detail of AI error of G21EA====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of G21EA====
[]
[]
====Detail of AI error of G21EA====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of G21IP====
[['IP_80', '48'], ['IP_74', '34'], ['IP_72', '26'], ['IP_76', '43'], ['IP_78', '45']]
[-11.30301139  -9.87890904   8.45378456   7.27488888   5.6983195 ]
====Detail of AI error of G21IP====
35: -11.303011386099746
-6.115062189426492 1 IP_80
5.187949196673253 -1 48

29: -9.878909039031502
-9.695676416667691 1 IP_74
0.1832326223638099 -1 34

27: 8.45378455718068
7.267804371291358 1 IP_72
-1.1859801858893209 -1 26

31: 7.274888880244999
9.089576764134987 1 IP_76
1.8146878838899885 -1 43

33: 5.698319495726643
5.885619554490599 1 IP_78
0.1873000587639557 -1 45

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of G21IP====
[['IP_74', '34'], ['IP_75', '37'], ['IP_76', '43'], ['IP_79', '51'], ['IP_80', '48']]
[-11.18554536  -8.70633914   6.2154155    4.82083584   3.85932247]
====Detail of AI error of G21IP====
29: -11.185545362259377
-10.073010619004783 1 IP_74
1.1125347432545938 -1 34

30: -8.706339141928813
-10.088836148939814 1 IP_75
-1.3824970070110008 -1 37

31: 6.215415496191394
7.24112348244466 1 IP_76
1.0257079862532663 -1 43

34: 4.820835840002671
4.389398217145362 1 IP_79
-0.4314376228573083 -1 51

35: 3.8593224688048187
3.3199982476530003 1 IP_80
-0.5393242211518183 -1 48

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of G21IP====
[['IP_74', '34'], ['IP_75', '37'], ['IP_77', '44'], ['IP_80', '48'], ['IP_78', '45']]
[-10.65998044  -8.982086     4.57364553   3.73309721   3.64702078]
====Detail of AI error of G21IP====
29: -10.659980441504054
-10.589810453601007 1 IP_74
0.0701699879030463 -1 34

30: -8.982086001453155
-7.863619229765579 1 IP_75
1.118466771687575 -1 37

32: 4.573645532164294
3.226883595659637 1 IP_77
-1.3467619365046564 -1 44

35: 3.733097205806491
3.726206591606084 1 IP_80
-0.0068906142004066 -1 48

33: 3.6470207793128964
2.6266752287125863 1 IP_78
-1.0203455506003103 -1 45

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of G21IP====
[]
[]
====Detail of AI error of G21IP====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of G21IP====
[]
[]
====Detail of AI error of G21IP====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of DIPCS10====
[['c4h4', 'c4h4_2+'], ['c2h4', 'c2h4_2+'], ['n2h2', 'n2h2_2+'], ['c2h6', 'c2h6_2+'], ['ph3', 'ph3_2+']]
[19.00791971 10.32663037 -8.20141404  1.84332908  1.38317004]
====Detail of AI error of DIPCS10====
0: 19.007919714169198
-5.915778513203403 -1 c4h4
13.092141200965797 1 c4h4_2+

2: 10.326630371579622
-1.4345907993350309 -1 c2h4
8.892039572244592 1 c2h4_2+

3: -8.201414044920142
0.1421010065026915 -1 n2h2
-8.05931303841745 1 n2h2_2+

1: 1.8433290829071605
-0.376894842435922 -1 c2h6
1.4664342404712385 1 c2h6_2+

7: 1.3831700355695962
-0.3426368939948518 -1 ph3
1.0405331415747443 1 ph3_2+

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of DIPCS10====
[['c4h4', 'c4h4_2+'], ['n2h2', 'n2h2_2+'], ['c2h4', 'c2h4_2+'], ['ch2o', 'ch2o_2+'], ['mg', 'mg_2+']]
[11.39615885 -5.15753357  4.50221772  2.96892738 -2.08034757]
====Detail of AI error of DIPCS10====
0: 11.396158847791542
-3.3564043736969285 -1 c4h4
8.039754474094613 1 c4h4_2+

3: -5.15753357263175
-1.189343915935619 -1 n2h2
-6.346877488567369 1 n2h2_2+

2: 4.50221772333783
-1.3331021432158965 -1 c2h4
3.1691155801219337 1 c2h4_2+

5: 2.968927384617868
-0.925449239632976 -1 ch2o
2.043478144984892 1 ch2o_2+

8: -2.0803475743934516
1.6591610928763436 -1 mg
-0.4211864815171082 1 mg_2+

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of DIPCS10====
[['c4h4', 'c4h4_2+'], ['n2h2', 'n2h2_2+'], ['c2h4', 'c2h4_2+'], ['mg', 'mg_2+'], ['c2h6', 'c2h6_2+']]
[10.70589912 -5.4690356   3.4497178  -2.36311056 -1.50448591]
====Detail of AI error of DIPCS10====
0: 10.705899124612218
-5.265128992916274 -1 c4h4
5.440770131695944 1 c4h4_2+

3: -5.469035602875298
-1.1368295579987122 -1 n2h2
-6.60586516087401 1 n2h2_2+

2: 3.449717798929569
-0.8864168781511718 -1 c2h4
2.563300920778397 1 c2h4_2+

8: -2.363110564692639
2.6281737428703136 -1 mg
0.2650631781776744 1 mg_2+

1: -1.5044859101533703
-1.139040267456954 -1 c2h6
-2.6435261776103243 1 c2h6_2+

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of DIPCS10====
[]
[]
====Detail of AI error of DIPCS10====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of DIPCS10====
[]
[]
====Detail of AI error of DIPCS10====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of PA26====
[['p4', 'p4p'], ['c2f6', 'c2f6p'], ['p8', 'p8p'], ['p6', 'p6p'], ['ass', 'assp']]
[-11.35028239  -9.91044712  -8.38061401  -8.32174587  -5.21967293]
====Detail of AI error of PA26====
1: -11.350282387969727
-7.336014679442906 1 p4
4.014267708526822 -1 p4p

12: -9.910447123923904
-7.671365675614699 1 c2f6
2.2390814483092045 -1 c2f6p

3: -8.380614006799235
-12.25558245992256 1 p8
-3.874968453123324 -1 p8p

2: -8.321745865844232
-8.282403374706865 1 p6
0.0393424911373659 -1 p6p

17: -5.21967293158545
-24.24608804414649 1 ass
-19.02641511256104 -1 assp

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of PA26====
[['cys', 'cysp'], ['gly', 'glyp'], ['C', 'Cp'], ['ethanol', 'ethanolp'], ['nh3', 'nh3p']]
[13.7391339  12.85920532 11.95102594 10.89644892 10.41555336]
====Detail of AI error of PA26====
20: 13.739133900814277
-11.994711149305552 1 cys
-25.73384505011983 -1 cysp

15: 12.859205320905794
-6.790643411135156 1 gly
-19.64984873204095 -1 glyp

25: 11.951025937084623
-10.574001119623976 1 C
-22.5250270567086 -1 Cp

13: 10.896448921784414
-1.2861437329750702 1 ethanol
-12.182592654759484 -1 ethanolp

4: 10.41555335877725
-0.6177283714663382 1 nh3
-11.033281730243589 -1 nh3p

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of PA26====
[['gly', 'glyp'], ['ethanol', 'ethanolp'], ['cys', 'cysp'], ['nh3', 'nh3p'], ['C', 'Cp']]
[11.4295824  10.12654004  9.99810564  8.8923305   8.34330657]
====Detail of AI error of PA26====
15: 11.429582395566566
-5.1431785059342365 1 gly
-16.572760901500803 -1 glyp

13: 10.12654003652304
-0.4921580460039239 1 ethanol
-10.618698082526963 -1 ethanolp

20: 9.998105643783445
-12.305291118792082 1 cys
-22.303396762575527 -1 cysp

4: 8.892330499165999
-0.2673850702600589 1 nh3
-9.159715569426057 -1 nh3p

25: 8.3433065687058
-9.977115496269056 1 C
-18.320422064974856 -1 Cp

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of PA26====
[]
[]
====Detail of AI error of PA26====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of PA26====
[]
[]
====Detail of AI error of PA26====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of SIE4x4====
[['he', 'he+', 'he2+_1.75'], ['he', 'he+', 'he2+_1.5'], ['h2o', 'h2o+', 'h2o2+_1.75'], ['he', 'he+', 'he2+_1.25'], ['h2o', 'h2o+', 'h2o2+_1.5']]
[-40.00099233 -33.87352263 -27.80697905 -27.49842142 -23.04519719]
====Detail of AI error of SIE4x4====
7: -40.00099233247413
0.0194472924464676 1 he
-0.0637854528594646 1 he+
39.95665417206113 -1 he2+_1.75

6: -33.87352263300122
0.0194472924464676 1 he
-0.0637854528594646 1 he+
33.829184472588224 -1 he2+_1.5

15: -27.806979053532768
-0.0332920116646655 1 h2o
-0.8380759146217719 1 h2o+
26.93561112724633 -1 h2o2+_1.75

5: -27.49842142437202
0.0194472924464676 1 he
-0.0637854528594646 1 he+
27.45408326395902 -1 he2+_1.25

14: -23.045197185306158
-0.0332920116646655 1 h2o
-0.8380759146217719 1 h2o+
22.17382925901972 -1 h2o2+_1.5

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of SIE4x4====
[['h2o', 'h2o+', 'h2o2+_1.75'], ['h2o', 'h2o+', 'h2o2+_1.5'], ['h2o', 'h2o+', 'h2o2+_1.0'], ['h2o', 'h2o+', 'h2o2+_1.25'], ['nh3', 'nh3+', 'nh32+_1.75']]
[-21.73966444 -15.27242545  -6.07885371  -5.9705116   -4.51552959]
====Detail of AI error of SIE4x4====
15: -21.73966444386271
-0.5287316704063204 1 h2o
-0.972356052289806 1 h2o+
20.238576721166584 -1 h2o2+_1.75

14: -15.272425450238298
-0.5287316704063204 1 h2o
-0.972356052289806 1 h2o+
13.771337727542171 -1 h2o2+_1.5

12: -6.078853711462855
-0.5287316704063204 1 h2o
-0.972356052289806 1 h2o+
4.577765988766729 -1 h2o2+_1.0

13: -5.970511603403466
-0.5287316704063204 1 h2o
-0.972356052289806 1 h2o+
4.46942388070734 -1 h2o2+_1.25

11: -4.515529588522311
-0.721585376209393 1 nh3
-1.0293863124283245 1 nh3+
2.764557899884593 -1 nh32+_1.75

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of SIE4x4====
[['h2o', 'h2o+', 'h2o2+_1.75'], ['h2o', 'h2o+', 'h2o2+_1.25'], ['h2o', 'h2o+', 'h2o2+_1.5'], ['h2o', 'h2o+', 'h2o2+_1.0'], ['nh3', 'nh3+', 'nh32+_1.75']]
[-24.81585144 -10.89582528  -9.2751308   -8.49791674  -4.04845948]
====Detail of AI error of SIE4x4====
15: -24.815851444189814
-0.2333471356967844 1 h2o
-0.7228278459513998 1 h2o+
23.85967646254163 -1 h2o2+_1.75

13: -10.89582527848909
-0.2333471356967844 1 h2o
-0.7228278459513998 1 h2o+
9.939650296840906 -1 h2o2+_1.25

14: -9.275130803843009
-0.2333471356967844 1 h2o
-0.7228278459513998 1 h2o+
8.318955822194825 -1 h2o2+_1.5

12: -8.4979167407369
-0.2333471356967844 1 h2o
-0.7228278459513998 1 h2o+
7.541741759088715 -1 h2o2+_1.0

11: -4.048459476137427
-0.3942244100404784 1 nh3
-0.5346137870274862 1 nh3+
3.119621279069462 -1 nh32+_1.75

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of SIE4x4====
[]
[]
====Detail of AI error of SIE4x4====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of SIE4x4====
[]
[]
====Detail of AI error of SIE4x4====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of ALKBDE10====
[['cao', 'ca', 'o'], ['lio', 'li', 'o'], ['mgo', 'mg', 'o'], ['nao', 'na', 'o'], ['mgs', 'mg', 's']]
[-29.08185265  -5.07678663  -3.86351405  -2.8622958   -2.21883357]
====Detail of AI error of ALKBDE10====
2: -29.081852653303887
30.124608761957525 -1 cao
-0.4301624717567788 1 ca
1.4729185804104168 1 o

6: -5.076786632967117
6.567603823203342 -1 lio
0.0178986098258087 1 li
1.4729185804104168 1 o

7: -3.8635140536377994
5.472718696835201 -1 mgo
0.1362860627869845 1 mg
1.4729185804104168 1 o

9: -2.8622958038062665
4.702135523871591 -1 nao
0.3669211396549079 1 na
1.4729185804104168 1 o

8: -2.2188335730507838
1.7408981056964534 -1 mgs
0.1362860627869845 1 mg
-0.6142215301413146 1 s

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of ALKBDE10====
[['cao', 'ca', 'o'], ['mgs', 'mg', 's'], ['mgo', 'mg', 'o'], ['beo', 'be', 'o'], ['nao', 'na', 'o']]
[-25.05257158  -7.59418092  -7.20417292  -6.59252805  -0.84585878]
====Detail of AI error of ALKBDE10====
2: -25.052571577328173
24.283128714325617 -1 cao
-0.5147264930273971 1 ca
-0.25471636997516 1 o

8: -7.594180922840131
8.540653369133693 -1 mgs
1.6591610877398937 1 mg
-0.7126886414463312 1 s

7: -7.204172921078771
8.608617638843505 -1 mgo
1.6591610877398937 1 mg
-0.25471636997516 1 o

1: -6.59252804511213
6.2510337925573385 -1 beo
-0.0867778825796315 1 be
-0.25471636997516 1 o

9: -0.8458587767317989
0.1083804382109365 -1 nao
-0.4827619685457024 1 na
-0.25471636997516 1 o

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of ALKBDE10====
[['cao', 'ca', 'o'], ['mgs', 'mg', 's'], ['mgo', 'mg', 'o'], ['beo', 'be', 'o'], ['nao', 'na', 'o']]
[-18.1320782   -6.93960778  -6.56870931  -6.25039271  -1.98791016]
====Detail of AI error of ALKBDE10====
2: -18.132078202787973
20.722284755347232 -1 cao
2.1188204453241446 1 ca
0.4713861072351142 1 o

8: -6.939607777977368
8.665095179368823 -1 mgs
2.6281737376625243 1 mg
-0.9026863362710702 1 s

7: -6.568709313116513
9.668269158014152 -1 mgo
2.6281737376625243 1 mg
0.4713861072351142 1 o

1: -6.250392707247844
6.606234499066152 -1 beo
-0.1155443154168063 1 be
0.4713861072351142 1 o

9: -1.9879101610552563
3.357319490098424 -1 nao
0.8980232218080535 1 na
0.4713861072351142 1 o

####data_path:../validate/ccdft_cc-pVDZ_atom-1-test_gmtkn.csv####
====AI error of ALKBDE10====
[]
[]
====Detail of AI error of ALKBDE10====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1796537_gmtkn.csv####
====AI error of ALKBDE10====
[]
[]
====Detail of AI error of ALKBDE10====
####data_path:../validate/ccdft_cc-pVDZ_atom-1-1150169_gmtkn.csv####
====AI error of YBDE18====
[['nme3-cbh22', 'nme3', 'cbh22'], ['pf3-cbh22', 'pf3', 'cbh22'], ['pme3-cbh22', 'pme3', 'cbh22'], ['me2s-cbh22', 'me2s', 'cbh22'], ['nme3-ch2', 'nme3', 'ch2']]
[20.80484784 14.36691375 14.31400496 12.09637803 10.31367625]
====Detail of AI error of YBDE18====
10: 20.804847839455533
-19.568212422836066 -1 nme3-cbh22
-4.265921118001262 1 nme3
5.502556534620729 1 cbh22

12: 14.366913745551315
5.673033088869105 -1 pf3-cbh22
14.53739029979969 1 pf3
5.502556534620729 1 cbh22

16: 14.314004964882173
-11.515976393531073 -1 pme3-cbh22
-2.7045279632696304 1 pme3
5.502556534620729 1 cbh22

4: 12.096378025703356
-8.504272593664082 -1 me2s-cbh22
-1.9104511025814543 1 me2s
5.502556534620729 1 cbh22

11: 10.313676248320238
-14.483758827271574 -1 nme3-ch2
-4.265921118001262 1 nme3
0.0958385390499258 1 ch2

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1717981_gmtkn.csv####
====AI error of YBDE18====
[['nme3-cbh22', 'nme3', 'cbh22'], ['pf3-cbh22', 'pf3', 'cbh22'], ['nh3-cbh22', 'nh3', 'cbh22'], ['me2s-cbh22', 'me2s', 'cbh22'], ['pme3-cbh22', 'pme3', 'cbh22']]
[29.31541672 19.3334361  17.4566912  15.31506869 14.4559576 ]
====Detail of AI error of YBDE18====
10: 29.315416717575268
-22.548069165407973 -1 nme3-cbh22
-5.80696065097114 1 nme3
12.574308203138434 1 cbh22

12: 19.33343610205457
-10.17699067866971 -1 pf3-cbh22
-3.417862779753577 1 pf3
12.574308203138434 1 cbh22

8: 17.456691195692482
-5.570515440298378 -1 nh3-cbh22
-0.6881324477443311 1 nh3
12.574308203138434 1 cbh22

4: 15.315068694264905
-5.958569478597429 -1 me2s-cbh22
-3.217808987470958 1 me2s
12.574308203138434 1 cbh22

16: 14.455957604349628
-9.212645600007864 -1 pme3-cbh22
-7.3309961987966705 1 pme3
12.574308203138434 1 cbh22

####data_path:../validate/ccdft_cc-pVDZ_atom-1-1935936_gmtkn.csv####
====AI error of YBDE18====
[['nme3-cbh22', 'nme3', 'cbh22'], ['pf3-cbh22', 'pf3', 'cbh22'], ['nh3-cbh22', 'nh3', 'cbh22'], ['me2s-cbh22', 'me2s', 'cbh22'], ['pme3-cbh22', 'pme3', 'cbh22']]
[28.85658561 20.71047692 17.79214185 15.75593422 14.05020081]
====Detail of AI error of YBDE18====
10: 28.856585611140417
-21.345176042114545 -1 nme3-cbh22
-6.613210432001334 1 nme3
14.124620001027209 1 cbh22

12: 20.71047691698866
-6.690269179614492 -1 pf3-cbh22
-0.1044122636530402 1 pf3
14.124620001027209 1 cbh22

8: 17.792141850648882
-4.007123295876951 -1 nh3-cbh22
-0.3396014462552799 1 nh3
14.124620001027209 1 cbh22

4: 15.755934222967234

data_path ccdft_cc-pVDZ_atom-1-1150169_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
sub1                                4.692939  18.629823  468 / 468
sub2                                6.272359   6.562349  222 / 243
sub3                                4.162538   6.309849  192 / 194
sub4                                2.254974   2.887648  242 / 244
sub5                                1.913818   1.245124  259 / 291

data_path ccdft_cc-pVDZ_atom-1-1717981_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
sub1                                2.986900  18.629823  468 / 468
sub2                                7.758985   6.492958  218 / 243
sub3                                3.746488   6.575948  181 / 194
sub4                                3.930368   2.459420  198 / 244
sub5                                3.089299   0.700116  131 / 291

data_path ccdft_cc-pVDZ_atom-1-1935936_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
sub1                                2.893938  18.629823  468 / 468
sub2                                7.115725   6.612165  210 / 243
sub3                                4.379820   6.764537  170 / 194
sub4                                3.366489   1.651300  217 / 244
sub5                                3.525111   0.891337  244 / 291

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn                       \
Type                                AI AE     DFT AE Processed
sub1                                  0.0   0.000000   0 / 468
sub2                                  0.0   0.000000   0 / 243
sub3                                  0.0   2.796373  22 / 194
sub4                                  0.0  10.513091  23 / 244
sub5                                  0.0   5.650719  20 / 291

data_path ccdft_cc-pVDZ_atom-1-1796537_gmtkn
Type                                   AI AE    DFT AE Processed
sub1                                0.000000  0.000000   0 / 468
sub2                                9.042412  5.901253  15 / 243
sub3                                0.000000  0.000000   0 / 194
sub4                                0.000000  0.000000   0 / 244
sub5                                0.000000  0.000000   0 / 291

data_path ccdft_cc-pVDZ_atom-1-1150169_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
UPU23                               0.000000   0.000000     0 / 23
ISOL24                              4.843230   5.690557    12 / 24
C60ISO                              0.000000   0.000000      0 / 9
PCONF21                             3.418177   3.683764    10 / 18
INV24                               5.668748   2.796356    22 / 24
WATER27                             4.210310  13.619146    25 / 27
IDISP                              15.704176  13.632636      5 / 6
YBDE18                              7.255829   8.145395    18 / 18
DC13                                9.695545  13.090863    13 / 13
MB16_43                            11.357448  15.461608    43 / 43
W4_11                               5.805564  29.506869  140 / 140
ALKBDE10                            5.435985  18.125250      9 / 9
AL2X6                               5.084741   5.659146      6 / 6
DARC                                4.818050  10.754152    14 / 14
ALK8                                6.925821   4.400063      8 / 8
RC21                                4.696462   4.820927    21 / 21
DIPCS10                             4.414108  12.310855    10 / 10
WCPT18                              4.243739   7.967153    18 / 18
BH76                                4.203748   9.107948    76 / 76
S22                                 4.086915   2.291253    22 / 22
PX13                               13.059142  11.042025    13 / 13
SIE4x4                             17.182399  21.908521    16 / 16
BSR36                              15.616911   8.401182    36 / 36
CHB6                                3.585377   1.805320      4 / 4
ADIM6                               3.649860   3.059030      6 / 6
HEAVYSB11                           3.928191   5.391477      7 / 7
MCONF                               3.392493   1.956021    51 / 51
PA26                                3.011796   2.200767    26 / 26
NBPRC                               2.745689   2.232550    12 / 12
FH51                                3.055128   3.703658    51 / 51
G2RC                                3.044318   5.917204    25 / 25
S66                                 2.331477   1.894710    66 / 66
G21EA                               2.127111   9.754524    25 / 25
BHPERI                              2.119660   3.268993    26 / 26
ISO34                               2.057023   2.001744    34 / 34
PArel                               1.962423   1.743933    20 / 20
RSE43                               1.951595   3.157601    43 / 43
BHDIV10                             2.461823   6.277708    10 / 10
G21IP                               2.390142   8.953336    36 / 36
HAL59                               1.848147   1.649787    29 / 29
TAUT15                              1.871571   2.164531    15 / 15
AHB21                               1.766602   2.453821    21 / 21
IL16                                1.735752   1.021067    16 / 16
CARBHB12                            1.364792   1.632408    12 / 12
BH76RC                              1.212571  80.220383    30 / 30
SCONF                               1.591377   0.512352    17 / 17
Amino20x4                           1.405904   0.656235    80 / 80
BHROT27                             1.078680   0.853379    27 / 27
CDIE20                              1.160373   1.599507    20 / 20
BUT14DIOL                           0.783503   0.645099    64 / 64
PNICO23                             0.717968   0.776429    23 / 23
ACONF                               0.548364   0.546621    15 / 15
ICONF                               0.709620   0.413804    17 / 17
RG18                                0.503217   0.230018    18 / 18
HEAVY28                             0.000000   0.000000      0 / 0

data_path ccdft_cc-pVDZ_atom-1-1717981_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
UPU23                               0.000000   0.000000     0 / 23
ISOL24                              5.654190   3.363761     8 / 24
C60ISO                              0.000000   0.000000      0 / 9
PCONF21                             0.000000   0.000000     0 / 18
INV24                               3.483537   3.661398    11 / 24
WATER27                             7.108348  10.513091    23 / 27
IDISP                              17.912489   9.077474      2 / 6
YBDE18                              9.738606   8.145395    18 / 18
DC13                               10.479130  13.090863    13 / 13
MB16_43                            22.372036  15.461608    43 / 43
W4_11                               1.129996  29.506869  140 / 140
ALKBDE10                            5.455799  18.125250      9 / 9
AL2X6                              18.962937   5.659146      6 / 6
DARC                                8.191902  10.754152    14 / 14
ALK8                                5.066431   4.400063      8 / 8
RC21                                3.181678   4.820927    21 / 21
DIPCS10                             2.938845  12.310855    10 / 10
WCPT18                              2.904425   7.967153    18 / 18
BH76                                3.112103   9.107948    76 / 76
S22                                 6.258149   2.057836    20 / 22
PX13                                9.284470  11.042025    13 / 13
SIE4x4                              4.352369  21.908521    16 / 16
BSR36                               9.085181   8.401182    36 / 36
CHB6                                3.660181   1.805320      4 / 4
ADIM6                              12.416516   3.059030      6 / 6
HEAVYSB11                           4.358954   5.391477      7 / 7
MCONF                               0.000000   0.000000     0 / 51
PA26                                4.157854   2.200767    26 / 26
NBPRC                               3.635708   2.232550    12 / 12
FH51                                3.330916   3.703658    51 / 51
G2RC                                1.974651   5.917204    25 / 25
S66                                 2.730301   0.812831    26 / 66
G21EA                               1.306739   9.754524    25 / 25
BHPERI                              4.073258   3.268993    26 / 26
ISO34                               2.835025   2.001744    34 / 34
PArel                               3.115034   1.743933    20 / 20
RSE43                               1.108485   3.157601    43 / 43
BHDIV10                             7.611527   6.277708    10 / 10
G21IP                               1.555443   8.953336    36 / 36
HAL59                               3.617033   1.649787    29 / 29
TAUT15                              3.011013   2.164531    15 / 15
AHB21                               2.485230   2.453821    21 / 21
IL16                                2.464107   1.021067    16 / 16
CARBHB12                            1.982940   1.632408    12 / 12
BH76RC                              0.785847  80.220383    30 / 30
SCONF                               2.721750   0.512352    17 / 17
Amino20x4                           2.903271   0.567958    23 / 80
BHROT27                             1.788065   0.853379    27 / 27
CDIE20                              1.805911   1.599507    20 / 20
BUT14DIOL                           3.524170   0.641284    57 / 64
PNICO23                             3.069988   0.776429    23 / 23
ACONF                               1.350796   0.546621    15 / 15
ICONF                               2.040502   0.413804    17 / 17
RG18                                2.139763   0.230018    18 / 18
HEAVY28                             0.000000   0.000000      0 / 0

data_path ccdft_cc-pVDZ_atom-1-1935936_gmtkn                        \
Type                                   AI AE     DFT AE  Processed
UPU23                               0.000000   0.000000     0 / 23
ISOL24                              0.000000   0.000000     0 / 24
C60ISO                              0.000000   0.000000      0 / 9
PCONF21                             0.000000   0.000000     0 / 18
INV24                               0.000000   0.000000     0 / 24
WATER27                             0.000000   0.000000     0 / 27
IDISP                               0.000000   0.000000      0 / 6
YBDE18                             10.015370   8.145395    18 / 18
DC13                                9.775129  13.090863    13 / 13
MB16_43                            18.857537  15.461608    43 / 43
W4_11                               1.374598  29.506869  140 / 140
ALKBDE10                            4.709731  18.125250      9 / 9
AL2X6                              17.618694   5.659146      6 / 6
DARC                                9.702381  10.754152    14 / 14
ALK8                                5.095435   4.400063      8 / 8
RC21                                2.661874   4.820927    21 / 21
DIPCS10                             2.601626  12.310855    10 / 10
WCPT18                              3.217643   7.967153    18 / 18
BH76                                3.778889   9.107948    76 / 76
S22                                 5.820110   2.291253    22 / 22
PX13                               13.913575  11.042025    13 / 13
SIE4x4                              4.441085  21.908521    16 / 16
BSR36                               8.208814   8.401182    36 / 36
CHB6                                2.948838   1.805320      4 / 4
ADIM6                               8.219808   3.059030      6 / 6
HEAVYSB11                           3.063275   5.391477      7 / 7
MCONF                               5.597069   1.956021    51 / 51
PA26                                3.571097   2.200767    26 / 26
NBPRC                               3.339061   2.232550    12 / 12
FH51                                3.240438   3.703658    51 / 51
G2RC                                1.824038   5.917204    25 / 25
S66                                 4.509038   1.894710    66 / 66
G21EA                               1.416441   9.754524    25 / 25
BHPERI                              4.051210   3.268993    26 / 26
ISO34                               2.575802   2.001744    34 / 34
PArel                               3.463495   1.743933    20 / 20
RSE43                               1.295861   3.157601    43 / 43
BHDIV10                             6.405104   6.277708    10 / 10
G21IP                               1.568532   8.953336    36 / 36
HAL59                               2.367128   1.649787    29 / 29
TAUT15                              2.254629   2.164531    15 / 15
AHB21                               2.496251   2.453821    21 / 21
IL16                                2.712129   1.021067    16 / 16
CARBHB12                            1.352969   1.632408    12 / 12
BH76RC                              0.726953  80.220383    30 / 30
SCONF                               3.042881   0.512352    17 / 17
Amino20x4                           2.693110   0.656235    80 / 80
BHROT27                             1.822123   0.853379    27 / 27
CDIE20                              1.975418   1.599507    20 / 20
BUT14DIOL                           3.868154   0.645099    64 / 64
PNICO23                             1.614491   0.776429    23 / 23
ACONF                               1.024909   0.546621    15 / 15
ICONF                               2.621375   0.413804    17 / 17
RG18                                1.441338   0.230018    18 / 18
HEAVY28                             0.000000   0.000000      0 / 0

data_path ccdft_cc-pVDZ_atom-1-test_gmtkn                       \
Type                                AI AE     DFT AE Processed
UPU23                                 0.0   0.000000    0 / 23
ISOL24                                0.0   0.000000    0 / 24
C60ISO                                0.0   0.000000     0 / 9
PCONF21                               0.0   2.990081   15 / 18
INV24                                 0.0   2.796373   22 / 24
WATER27                               0.0  10.513091   23 / 27
IDISP                                 0.0  13.632636     5 / 6
YBDE18                                0.0   0.000000    0 / 18
DC13                                  0.0   0.000000    0 / 13
MB16_43                               0.0   0.000000    0 / 43
W4_11                                 0.0   0.000000   0 / 140
ALKBDE10                              0.0   0.000000     0 / 9
AL2X6                                 0.0   0.000000     0 / 6
DARC                                  0.0   0.000000    0 / 14
ALK8                                  0.0   0.000000     0 / 8
RC21                                  0.0   0.000000    0 / 21
DIPCS10                               0.0   0.000000    0 / 10
WCPT18                                0.0   0.000000    0 / 18
BH76                                  0.0   0.000000    0 / 76
S22                                   0.0   0.000000    0 / 22
PX13                                  0.0   0.000000    0 / 13
SIE4x4                                0.0   0.000000    0 / 16
BSR36                                 0.0   0.000000    0 / 36
CHB6                                  0.0   0.000000     0 / 4
ADIM6                                 0.0   0.000000     0 / 6
HEAVYSB11                             0.0   0.000000     0 / 7
MCONF                                 0.0   0.000000    0 / 51
PA26                                  0.0   0.000000    0 / 26
NBPRC                                 0.0   0.000000    0 / 12
FH51                                  0.0   0.000000    0 / 51
G2RC                                  0.0   0.000000    0 / 25
S66                                   0.0   0.000000    0 / 66
G21EA                                 0.0   0.000000    0 / 25
BHPERI                                0.0   0.000000    0 / 26
ISO34                                 0.0   0.000000    0 / 34
PArel                                 0.0   0.000000    0 / 20
RSE43                                 0.0   0.000000    0 / 43
BHDIV10                               0.0   0.000000    0 / 10
G21IP                                 0.0   0.000000    0 / 36
HAL59                                 0.0   0.000000    0 / 29
TAUT15                                0.0   0.000000    0 / 15
AHB21                                 0.0   0.000000    0 / 21
IL16                                  0.0   0.000000    0 / 16
CARBHB12                              0.0   0.000000    0 / 12
BH76RC                                0.0   0.000000    0 / 30
SCONF                                 0.0   0.000000    0 / 17
Amino20x4                             0.0   0.000000    0 / 80
BHROT27                               0.0   0.000000    0 / 27
CDIE20                                0.0   0.000000    0 / 20
BUT14DIOL                             0.0   0.000000    0 / 64
PNICO23                               0.0   0.000000    0 / 23
ACONF                                 0.0   0.000000    0 / 15
ICONF                                 0.0   0.000000    0 / 17
RG18                                  0.0   0.000000    0 / 18
HEAVY28                               0.0   0.000000     0 / 0

data_path ccdft_cc-pVDZ_atom-1-1796537_gmtkn
Type                                   AI AE    DFT AE Processed
UPU23                               0.000000  0.000000    0 / 23
ISOL24                              9.042412  5.901253   15 / 24
C60ISO                              0.000000  0.000000     0 / 9
PCONF21                             0.000000  0.000000    0 / 18
INV24                               0.000000  0.000000    0 / 24
WATER27                             0.000000  0.000000    0 / 27
IDISP                               0.000000  0.000000     0 / 6
YBDE18                              0.000000  0.000000    0 / 18
DC13                                0.000000  0.000000    0 / 13
MB16_43                             0.000000  0.000000    0 / 43
W4_11                               0.000000  0.000000   0 / 140
ALKBDE10                            0.000000  0.000000     0 / 9
AL2X6                               0.000000  0.000000     0 / 6
DARC                                0.000000  0.000000    0 / 14
ALK8                                0.000000  0.000000     0 / 8
RC21                                0.000000  0.000000    0 / 21
DIPCS10                             0.000000  0.000000    0 / 10
WCPT18                              0.000000  0.000000    0 / 18
BH76                                0.000000  0.000000    0 / 76
S22                                 0.000000  0.000000    0 / 22
PX13                                0.000000  0.000000    0 / 13
SIE4x4                              0.000000  0.000000    0 / 16
BSR36                               0.000000  0.000000    0 / 36
CHB6                                0.000000  0.000000     0 / 4
ADIM6                               0.000000  0.000000     0 / 6
HEAVYSB11                           0.000000  0.000000     0 / 7
MCONF                               0.000000  0.000000    0 / 51
PA26                                0.000000  0.000000    0 / 26
NBPRC                               0.000000  0.000000    0 / 12
FH51                                0.000000  0.000000    0 / 51
G2RC                                0.000000  0.000000    0 / 25
S66                                 0.000000  0.000000    0 / 66
G21EA                               0.000000  0.000000    0 / 25
BHPERI                              0.000000  0.000000    0 / 26
ISO34                               0.000000  0.000000    0 / 34
PArel                               0.000000  0.000000    0 / 20
RSE43                               0.000000  0.000000    0 / 43
BHDIV10                             0.000000  0.000000    0 / 10
G21IP                               0.000000  0.000000    0 / 36
HAL59                               0.000000  0.000000    0 / 29
TAUT15                              0.000000  0.000000    0 / 15
AHB21                               0.000000  0.000000    0 / 21
IL16                                0.000000  0.000000    0 / 16
CARBHB12                            0.000000  0.000000    0 / 12
BH76RC                              0.000000  0.000000    0 / 30
SCONF                               0.000000  0.000000    0 / 17
Amino20x4                           0.000000  0.000000    0 / 80
BHROT27                             0.000000  0.000000    0 / 27
CDIE20                              0.000000  0.000000    0 / 20
BUT14DIOL                           0.000000  0.000000    0 / 64
PNICO23                             0.000000  0.000000    0 / 23
ACONF                               0.000000  0.000000    0 / 15
ICONF                               0.000000  0.000000    0 / 17
RG18                                0.000000  0.000000    0 / 18
HEAVY28                             0.000000  0.000000     0 / 0

In [1]:
Error_molecule = [
    "W4_11-cl2_cc-pVDZ_0-1_1_-0.5000_default",
    "G2RC-24_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-nh_cc-pVDZ_0-1_1_0.5000_default",
    "G21IP-IP_70_cc-pVDZ_0-1_1_0.5000_default",
    "G21EA-EA_11n_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-cl2_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-bn3pi_cc-pVDZ_0-1_1_0.5000_default",
    "G2RC-45_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-oclo_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-n2h_cc-pVDZ_0-1_1_-0.5000_default",
    "BH76-NH2_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-nh2_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-no2_cc-pVDZ_0-1_1_0.5000_default",
    "G21EA-EA_12n_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-bef2_cc-pVDZ_0-1_1_-0.5000_default",
    "W4_11-t-hooo_cc-pVDZ_0-1_1_0.5000_default",
    "W4_11-c-hooo_cc-pVDZ_0-1_1_0.5000_default",
    "G21IP-IP_64_cc-pVDZ_0-1_1_0.5000_default",
    "SIE4x4-h2o2+_1.75_cc-pVDZ_0-1_1_-0.5000_default",
    "SIE4x4-nh32+_1.5_cc-pVDZ_0-1_1_0.5000_default",
    "SIE4x4-nh32+_1.75_cc-pVDZ_0-1_1_-0.5000_default",
    "SIE4x4-nh32+_1.75_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-pme2_cc-pVDZ_0-1_1_0.5000_default",
    "HEAVYSB11-asme2_cc-pVDZ_0-1_1_0.5000_default",
]
# mol_name =
# Error molecule: ['MB16_43-26_cc-pVDZ_0-1_1_0.5000_default', 'MB16_43-36_cc-pVDZ_0-1_1_-0.5000_default', 'BSR36-h11_cc-pVDZ_0-1_1_0.5000_default', 'BSR36-h7_cc-pVDZ_0-1_1_-0.5000_default']

In [13]:
import numpy as np

np.shape(np.transpose(np.array([np.random.random((4, 3)), np.random.random((4, 3))]), (1, 2, 0)))

(4, 3, 2)

In [14]:
a = np.random.random((2, 2, 2))

In [15]:
print(a)
print(a.reshape((4, 2)))

[[[0.60304111 0.57142901]
  [0.47472272 0.82949855]]

 [[0.24165046 0.32076752]
  [0.27413131 0.19826097]]]
[[0.60304111 0.57142901]
 [0.47472272 0.82949855]
 [0.24165046 0.32076752]
 [0.27413131 0.19826097]]