In [1]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate_hkqai").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict_ccpvdz"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if "modified_dft_d3bj" in data.columns:
            data_dft_d3bj = data["modified_dft_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3bj = data_d3bj
        if "modified_dft_d3zero" in data.columns:
            data_dft_d3zero = data["modified_dft_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3zero = data_d3zero
        if "modified_ai_d3bj" in data.columns:
            data_ai_d3bj = data["modified_ai_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3bj = data_d3bj
        if "modified_ai_d3zero" in data.columns:
            data_ai_d3zero = data["modified_ai_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_ai = np.argsort(data_subset[name_subset]["ai"])[
                    ::-1
                ][:5]
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ][:5]
                for i in range(len(argsort_atomic_energy_ai)):
                    i_reaction_name = data_subset[name_subset]["name"][
                        argsort_atomic_energy_ai[i]
                    ]
                    i_reaction = json_data[f"reaction-{i_subset}"][i_reaction_name]
                    print(
                        f"Top {i+1} AI: {data_subset[name_subset]['ai'][argsort_atomic_energy_ai[i]]} kcal/mol, {i_reaction_name} in {name_subset}",
                    )
                    systems_list = i_reaction["systems"]
                    stoichiometry_list = i_reaction["stoichiometry"]
                    for j in range(len(systems_list)):
                        mole_name = (
                            systems_list[j]
                            if i_subset == "BH76RC"
                            else f"{i_subset}-{systems_list[j]}"
                        )
                        stoichiometry = int(stoichiometry_list[j])
                        if mole_name in json_data:
                            if isinstance(json_data[mole_name], str):
                                mole_name = json_data[mole_name]
                        print(f"  {stoichiometry} * {mole_name}", end="")
                        col = np.where(data_name == mole_name)[0]
                        if col.size == 1:
                            error_energy_ai = data_scf[col[0]] - data_cc[col[0]]
                            print(f"  {stoichiometry} * {error_energy_ai}", end="")
                    print()

                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["ai"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["ai"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {data_path_name}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

    wtmad_1_subset.loc["summary", (data_path_name, "Processed")] = "--"
    wtmad_2_subset.loc["summary", (data_path_name, "Processed")] = "--"
    for d3_name in ["", "_d3bj", "_d3zero"]:
        wtmad_1_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_1_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        for name_set in full_subset_dict.keys():
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]

# print("Summary")
# display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset_ele.to_csv(f"../validate/df_summary_subset_ele_{date}.csv")
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
mean_subset.to_csv(f"../validate/mean_subset_{date}.csv")
wtmad_1_subset.to_csv(f"../validate/wtmad_1_subset_{date}.csv")
wtmad_2_subset.to_csv(f"../validate/wtmad_2_subset_{date}.csv")
# save summary to excel with date
df_summary_subset_ele.to_excel(f"../validate/df_summary_subset_ele_{date}.xlsx")
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: W4_11-propane not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: W4_11-propene not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: W4_11-ethanol not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Top 1 AI: 38.4684967326466 kcal/mol, 133 in 3036943_W4_11
  -1 * W4_11-b2  -1 * 10.333999411293917  2 * W4_11-b  2 * 0.00735858251391619
Top 2 AI: 32.5134282814106 kcal/mol, 128 in 3036943_W4_11
  -1 * W4_11-s4-c2v  -1 * -13.62584772054106  4 * W4_11-s  4 * -0.08260939861065708
Top 3 AI: 26.098701825831085 kcal/mol, 131 in 3036943_W4_11
  -1 * W4_11-oclo  -1 * -32.23040660680272  2 * W4_11-o  2 * -0.01763694222609047  1 * W4_11-cl  1 * 0.3182955590891652
Top 4 AI: 22.529547434707638 kcal/mol, 104 in 3036943_W4_11
  -1 * W4_11-hnnn  -1 * -12.704742801826796  1 * W4_11-h  1 * -0.12572445527990794  3 * W4_11-n  3 * -0.08974874942941824
Top 5 AI: 21.856567947237636 kcal/mol, 129 in 3036943_W4_11
  -1 * W4_11-of  -1 * -12.823814730218146  1 * W4_11-o  1 * -0.01763694222609047  1 * W4_11-f  1 * -0.10107343958225101
Top 1 DFT: 64.9391765203327 kcal/mol
Top 2 DFT: 64.82811637483246 kcal/mol
Top 3 DFT: 58.7866408124537 kcal/mol
Top 4 DFT: 55.610892266675364 kcal/mol
Top 5 DFT: 55.139185982690606 kcal/mol
Top 1 AI: 9.585657042392995 kcal/mol, 23 in 3036943_G21EA
  1 * G21EA-EA_24n  1 * 1.3152324028778821  -1 * G21EA-EA_24  -1 * -8.270424639515113
Top 2 AI: 8.138593870506156 kcal/mol, 20 in 3036943_G21EA
  1 * G21EA-EA_21n  1 * -4.366583400638774  -1 * G21EA-EA_21  -1 * -12.50517727114493
Top 3 AI: 6.889371904893778 kcal/mol, 22 in 3036943_G21EA
  1 * G21EA-EA_23n  1 * -9.742394547909498  -1 * G21EA-EA_23  -1 * -16.631766452803276
Top 4 AI: 6.307816647211439 kcal/mol, 19 in 3036943_G21EA
  1 * G21EA-EA_20n  1 * -6.283387968753232  -1 * G21EA-EA_20  -1 * -12.59120461596467
Top 5 AI: 4.760592643549899 kcal/mol, 14 in 3036943_G21EA
  1 * G21EA-EA_15n  1 * 1.5934718028292991  -1 * G21EA-EA_15  -1 * -3.1671208407205995
Top 1 DFT: 17.922119285416557 kcal/mol
Top 2 DFT: 14.542179432406556 kcal/mol
Top 3 DFT: 13.792081636143848 kcal/mol
Top 4 DFT: 13.585563076587277 kcal/mol
Top 5 DFT: 13.248573637160007 kcal/mol
Top 1 AI: 9.60531509752036 kcal/mol, 30 in 3036943_G21IP
  1 * G21IP-IP_75  1 * 3.3186318516382016  -1 * G21IP-37  -1 * -6.286683245882159
Top 2 AI: 8.7030120870877 kcal/mol, 15 in 3036943_G21IP
  1 * G21IP-IP_59  1 * -8.577099000602175  -1 * G21IP-8  -1 * 0.12591308648552513
Top 3 AI: 8.322673837537877 kcal/mol, 31 in 3036943_G21IP
  1 * G21IP-IP_76  1 * -12.624879720504396  -1 * G21IP-43  -1 * -4.302205882966518
Top 4 AI: 6.855148584982089 kcal/mol, 27 in 3036943_G21IP
  1 * G21IP-IP_72  1 * -6.375594352932239  -1 * G21IP-26  -1 * 0.4795542320498498
Top 5 AI: 6.110582144057844 kcal/mol, 26 in 3036943_G21IP
  1 * G21IP-IP_71  1 * -7.400157801050227  -1 * G21IP-25  -1 * -1.2895756569923833
Top 1 DFT: 24.652048565418227 kcal/mol
Top 2 DFT: 19.50703940328094 kcal/mol
Top 3 DFT: 16.821335594599077 kcal/mol
Top 4 DFT: 16.4504761478438 kcal/mol
Top 5 DFT: 16.230253286354127 kcal/mol
Top 1 AI: 10.230825317346898 kcal/mol, 2 in 3036943_DIPCS10
  -1 * DIPCS10-c2h4  -1 * 0.7581960244860966  1 * DIPCS10-c2h4_2+  1 * -9.472629292860802
Top 2 AI: 9.91031130621559 kcal/mol, 0 in 3036943_DIPCS10
  -1 * DIPCS10-c4h4  -1 * 3.28497328114463  1 * DIPCS10-c4h4_2+  1 * -6.62533802507096
Top 3 AI: 7.331258183316095 kcal/mol, 3 in 3036943_DIPCS10
  -1 * DIPCS10-n2h2  -1 * -1.2511848552094307  1 * DIPCS10-n2h2_2+  1 * 6.080073328106664
Top 4 AI: 6.032941800047411 kcal/mol, 1 in 3036943_DIPCS10
  -1 * DIPCS10-c2h6  -1 * 1.4826388781511923  1 * DIPCS10-c2h6_2+  1 * -4.550302921896218
Top 5 AI: 5.580052857403643 kcal/mol, 7 in 3036943_DIPCS10
  -1 * DIPCS10-ph3  -1 * -0.08439779200125486  1 * DIPCS10-ph3_2+  1 * -5.664450649404898
Top 1 DFT: 21.238722962967586 kcal/mol
Top 2 DFT: 18.410172816045815 kcal/mol
Top 3 DFT: 17.180242111804546 kcal/mol
Top 4 DFT: 16.016684862523107 kcal/mol
Top 5 DFT: 13.03569706963026 kcal/mol
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-Gp not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-G not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-Tp not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-assp not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-ass not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-p8p not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-p8 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-ass not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-Tp not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: PA26-G not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Top 1 AI: 7.869731577899074 kcal/mol, 2 in 3036943_PA26
  1 * PA26-p6  1 * -0.5887456877098884  -1 * PA26-p6p  -1 * -8.458477265608963
Top 2 AI: 6.7994712828076445 kcal/mol, 1 in 3036943_PA26
  1 * PA26-p4  1 * 0.14490687321813311  -1 * PA26-p4p  -1 * -6.654564409589511
Top 3 AI: 4.395615906862076 kcal/mol, 11 in 3036943_PA26
  1 * PA26-h2  1 * -0.0969329404488235  -1 * PA26-h2p  -1 * -0.5951220761256764
Top 4 AI: 3.7927897270419635 kcal/mol, 15 in 3036943_PA26
  1 * PA26-gly  1 * -6.966502804047195  -1 * PA26-glyp  -1 * -4.8174592393042985
Top 5 AI: 3.468611360178329 kcal/mol, 19 in 3036943_PA26
  1 * PA26-si2h6  1 * -0.9954877357231453  -1 * PA26-si2h6p  -1 * -2.1441083317040466
Top 1 DFT: 3.952208415896166 kcal/mol
Top 2 DFT: 3.843404227809515 kcal/mol
Top 3 DFT: 3.7666994354804046 kcal/mol
Top 4 DFT: 3.7500070057285484 kcal/mol
Top 5 DFT: 3.293136214633705 kcal/mol
Top 1 AI: 33.239877640779014 kcal/mol, 7 in 3036943_SIE4x4
  1 * SIE4x4-he  1 * 0.11152212505271564  1 * SIE4x4-he+  1 * 0.012206718850393372  -1 * SIE4x4-he2+_1.75  -1 * -33.11614879687613
Top 2 AI: 31.48699839458277 kcal/mol, 15 in 3036943_SIE4x4
  1 * SIE4x4-h2o  1 * -0.4043404430267401  1 * SIE4x4-h2o+  1 * 2.0314803352666786  -1 * SIE4x4-h2o2+_1.75  -1 * -29.859858502357383
Top 3 AI: 28.249457078119576 kcal/mol, 6 in 3036943_SIE4x4
  1 * SIE4x4-he  1 * 0.11152212505271564  1 * SIE4x4-he+  1 * 0.012206718850393372  -1 * SIE4x4-he2+_1.5  -1 * -28.125728234216695
Top 4 AI: 26.746468769415515 kcal/mol, 11 in 3036943_SIE4x4
  1 * SIE4x4-nh3  1 * 0.10397291852132184  1 * SIE4x4-nh3+  1 * 1.9414151204182417  -1 * SIE4x4-nh32+_1.75  -1 * -24.70108073047595
Top 5 AI: 26.56278557163023 kcal/mol, 14 in 3036943_SIE4x4
  1 * SIE4x4-h2o  1 * -0.4043404430267401  1 * SIE4x4-h2o+  1 * 2.0314803352666786  -1 * SIE4x4-h2o2+_1.5  -1 * -24.935645679404843
Top 1 DFT: 42.48945061229006 kcal/mol
Top 2 DFT: 36.3825565542179 kcal/mol
Top 3 DFT: 34.02966520233895 kcal/mol
Top 4 DFT: 29.669328280849186 kcal/mol
Top 5 DFT: 29.26023051775701 kcal/mol
Warning: ALKBDE10-kf not found in data json, ERROR
Top 1 AI: 45.316982352218474 kcal/mol, 2 in 3036943_ALKBDE10
  -1 * ALKBDE10-cao  -1 * -45.460252896067686  1 * ALKBDE10-ca  1 * -0.09926281013758853  1 * ALKBDE10-o  1 * -0.04400773371162359
Top 2 AI: 12.52597591362428 kcal/mol, 7 in 3036943_ALKBDE10
  -1 * ALKBDE10-mgo  -1 * -12.770751846401254  1 * ALKBDE10-mg  1 * -0.20076819906535093  1 * ALKBDE10-o  1 * -0.04400773371162359
Top 3 AI: 10.262314241175773 kcal/mol, 9 in 3036943_ALKBDE10
  -1 * ALKBDE10-nao  -1 * -10.625722907454474  1 * ALKBDE10-na  1 * -0.3194009325670777  1 * ALKBDE10-o  1 * -0.04400773371162359
Top 4 AI: 8.757217067213787 kcal/mol, 5 in 3036943_ALKBDE10
  -1 * ALKBDE10-lif  -1 * -8.952109106205171  1 * ALKBDE10-li  1 * -0.05279544017139415  1 * ALKBDE10-f  1 * -0.14209659882180858
Top 5 AI: 8.613683662413678 kcal/mol, 0 in 3036943_ALKBDE10
  -1 * ALKBDE10-bef  -1 * -8.80621114524547  1 * ALKBDE10-be  1 * -0.050430884011802846  1 * ALKBDE10-f  1 * -0.14209659882180858
Top 1 DFT: 42.20618001303956 kcal/mol
Top 2 DFT: 26.422307972352428 kcal/mol
Top 3 DFT: 19.54640414734604 kcal/mol
Top 4 DFT: 16.150239486240025 kcal/mol
Top 5 DFT: 15.581684817676432 kcal/mol
Warning: YBDE18-pme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: YBDE18-pme3-cbh22 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Top 1 AI: 16.71075652066793 kcal/mol, 10 in 3036943_YBDE18
  -1 * YBDE18-nme3-cbh22  -1 * 16.0870616438624  1 * YBDE18-nme3  1 * 3.26261926809093  1 * YBDE18-cbh22  1 * -3.8863141448964598
Top 2 AI: 11.14414315742033 kcal/mol, 4 in 3036943_YBDE18
  -1 * YBDE18-me2s-cbh22  -1 * 7.249240408535115  1 * YBDE18-me2s  1 * -0.008588603988755494  1 * YBDE18-cbh22  1 * -3.8863141448964598
Top 3 AI: 10.211615572305163 kcal/mol, 7 in 3036943_YBDE18
  -1 * YBDE18-nf3-ch2  -1 * -37.45686213581939  1 * YBDE18-nf3  1 * -27.185497577360366  1 * YBDE18-ch2  1 * -0.05974898615386337
Top 4 AI: 10.19367986069119 kcal/mol, 12 in 3036943_YBDE18
  -1 * YBDE18-pf3-cbh22  -1 * -16.06482123839669  1 * YBDE18-pf3  1 * -22.37218695419142  1 * YBDE18-cbh22  1 * -3.8863141448964598
Top 5 AI: 8.724058067637088 kcal/mol, 8 in 3036943_YBDE18
  -1 * YBDE18-nh3-cbh22  -1 * 4.888983855853439  1 * YBDE18-nh3  1 * 0.05123993311281083  1 * YBDE18-cbh22  1 * -3.8863141448964598
Top 1 DFT: 16.44728826175924 kcal/mol
Top 2 DFT: 12.740130906568083 kcal/mol
Top 3 DFT: 10.488881110526563 kcal/mol
Top 4 DFT: 10.40475183620947 kcal/mol
Top 5 DFT: 10.307641494440759 kcal/mol
Top 1 AI: 8.026137581386138 kcal/mol, 5 in 3036943_AL2X6
  -1 * AL2X6-al2me6  -1 * 8.243552222091239  2 * AL2X6-alme3  2 * 0.1087073203525506
Top 2 AI: 6.098896254086867 kcal/mol, 1 in 3036943_AL2X6
  -1 * AL2X6-al2f6  -1 * -28.95793446630705  2 * AL2X6-alf3  2 * -17.52841536019696
Top 3 AI: 6.075755969883176 kcal/mol, 4 in 3036943_AL2X6
  -1 * AL2X6-al2me5  -1 * 5.808497415564489  1 * AL2X6-alme2  1 * -0.37596587467123754  1 * AL2X6-alme3  1 * 0.1087073203525506
Top 4 AI: 4.186023638700135 kcal/mol, 3 in 3036943_AL2X6
  -1 * AL2X6-al2me4  -1 * 3.43409188935766  2 * AL2X6-alme2  2 * -0.37596587467123754
Top 5 AI: 3.571476377779618 kcal/mol, 2 in 3036943_AL2X6
  -1 * AL2X6-al2cl6  -1 * -1.0316311912611127  2 * AL2X6-alcl3  2 * -2.3015537845203653
Top 1 DFT: 9.084031574253459 kcal/mol
Top 2 DFT: 7.0848077459668275 kcal/mol
Top 3 DFT: 5.3300173038151115 kcal/mol
Top 4 DFT: 5.070575412944891 kcal/mol
Top 5 DFT: 4.9637361988425255 kcal/mol
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Top 1 AI: 9.615009685163386 kcal/mol, 9 in 3036943_HEAVYSB11
  2 * HEAVYSB11-cl  2 * 0.3177842336590402  -1 * HEAVYSB11-cl2  -1 * -8.979441217845306
Top 2 AI: 7.917366590118036 kcal/mol, 6 in 3036943_HEAVYSB11
  2 * HEAVYSB11-pme2  2 * -2.97890443156939  -1 * HEAVYSB11-p2me4  -1 * 1.9595577269792557
Top 3 AI: 7.0735363299027085 kcal/mol, 10 in 3036943_HEAVYSB11
  2 * HEAVYSB11-br  2 * 0.002556967083364725  -1 * HEAVYSB11-br2  -1 * -7.068422395735979
Top 4 AI: 5.164152127690613 kcal/mol, 7 in 3036943_HEAVYSB11
  2 * HEAVYSB11-asme2  2 * -5.1110981474630535  -1 * HEAVYSB11-as2me4  -1 * -5.058044167235494
Top 5 AI: 4.665122918842826 kcal/mol, 3 in 3036943_HEAVYSB11
  2 * HEAVYSB11-sh  2 * -0.11393352362210862  -1 * HEAVYSB11-h2s2  -1 * -4.892989966087043
Top 1 DFT: 10.68985605717171 kcal/mol
Top 2 DFT: 9.494120202027261 kcal/mol
Top 3 DFT: 7.114256684028078 kcal/mol
Top 4 DFT: 6.325384678319097 kcal/mol
Top 5 DFT: 1.569642293266952 kcal/mol
Warning: NBPRC-K_F not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_Cl not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: NBPRC-ch not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: NBPRC-ch not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_F not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: NBPRC-K_Cl not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Top 1 AI: 10.152050388060161 kcal/mol, 3 in 3036943_NBPRC
  -2 * NBPRC-nh2-bh2  -2 * 1.6707477978998213  1 * NBPRC-cbut  1 * 13.493545983859804
Top 2 AI: 7.466172514068603 kcal/mol, 0 in 3036943_NBPRC
  -1 * NBPRC-nh3  -1 * 0.06345894689002307  -1 * NBPRC-bh3  -1 * 0.030617264477768913  1 * NBPRC-nh3-bh3  1 * 7.560248725436395
Top 3 AI: 6.9745506750186905 kcal/mol, 8 in 3036943_NBPRC
  1 * NBPRC-BF3PMe3  1 * -9.901793527824339  -1 * NBPRC-BF3  -1 * -10.85150347580202  -1 * NBPRC-PMe3  -1 * 1.8496081703342497
Top 4 AI: 6.143186520668678 kcal/mol, 5 in 3036943_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * 1.6707477978998213  1 * NBPRC-ch
Top 5 AI: 5.980832498818131 kcal/mol, 1 in 3036943_NBPRC
  -1 * NBPRC-nh3-bh3  -1 * 7.560248725436395  1 * NBPRC-nh2-bh2  1 * 1.6707477978998213  1 * NBPRC-h2  1 * -0.09133157128155744
Top 1 DFT: 4.25873367569875 kcal/mol
Top 2 DFT: 3.4078239038353786 kcal/mol
Top 3 DFT: 2.2723810925637054 kcal/mol
Top 4 DFT: 1.4810449850338046 kcal/mol
Top 5 DFT: 1.0150121501906142 kcal/mol
Top 1 AI: 18.97707875557535 kcal/mol, 2 in 3036943_ALK8
  -1 * ALK8-li4_me4  -1 * 14.331920184267801  4 * ALK8-li_me  4 * -1.1612896428268868
Top 2 AI: 15.798990003066137 kcal/mol, 1 in 3036943_ALK8
  -1 * ALK8-na8  -1 * 11.439001356484368  4 * ALK8-na2  4 * -1.0899971616454422
Top 3 AI: 10.066403216864273 kcal/mol, 0 in 3036943_ALK8
  -1 * ALK8-li8  -1 * 26.49528900403675  4 * ALK8-li2  4 * 4.107221446793119
Top 4 AI: 3.610623296634003 kcal/mol, 3 in 3036943_ALK8
  -1 * ALK8-li3_me  -1 * 6.556555100600235  1 * ALK8-li_me  1 * -1.1612896428268868  1 * ALK8-li2  1 * 4.107221446793119
Top 5 AI: 3.4037736525933724 kcal/mol, 6 in 3036943_ALK8
  -1 * ALK8-li2_ch2n_2  -1 * -7.376229668472661  2 * ALK8-li_ch2n  2 * -5.3900016605330165
Top 1 DFT: 13.423444515326992 kcal/mol
Top 2 DFT: 13.339023275213549 kcal/mol
Top 3 DFT: 3.2870388831361197 kcal/mol
Top 4 DFT: 1.8348026665917132 kcal/mol
Top 5 DFT: 1.3258451606470771 kcal/mol
Warning: RC21-2p2 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-2e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-5p not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-pr not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7p3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-4e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3p3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-9p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-2p3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-1p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-5e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-8p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3int1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-1p3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-2p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-4p not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-9e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3int3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7p5 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-8e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-10p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-10e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6p3 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-1e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3int2 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6int not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6p1 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-1e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-1e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-2e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-2e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-3e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-4e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-5e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-6e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-7e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-8e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-9e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: RC21-10e not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-118 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-11 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-113 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-32 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-82 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-58 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-30 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-21 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-47 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-39 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-23 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-18 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-52 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file
Warning: G2RC-57 not found in ccdft_cc-pVDZ_atom-1-3036943_gmtkn-cc-pVDZ data file

/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

MAE

data_path    3036943                                                       \
Disp type         AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1        6.118434  18.203799  6.459284  18.914367  5.991956  18.232302
sub2       11.078233   7.778315  7.385627  11.988613   6.70284   7.600269
sub3             NaN        NaN       NaN        NaN       NaN        NaN
sub4             NaN        NaN       NaN        NaN       NaN        NaN
sub5        0.978262   0.574513  0.409574    0.54405  0.386263   0.565887

data_path             1424849                       ...                       \
Disp type Processed        AI        DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1         8 / 18  2.002477  13.710857  2.341161  ...  1.840461  13.713797
sub2          0 / 7  5.510109   6.612164  9.257621  ...  6.192242   6.757732
sub3          0 / 7  2.617318   6.261376  3.548881  ...  3.228945   6.934991
sub4         0 / 11   1.93524   3.272197  2.924356  ...  2.900361   4.988172
sub5          0 / 8  1.626727   1.321288   1.52729  ...  1.545785   0.872793

data_path             1513512                                             \
Disp type Processed        AI        DFT    AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1           DONE  6.282354  13.717062   6.868466  14.265974  6.365582
sub2           DONE  7.536765   6.612828  11.817093   9.131704  8.930029
sub3           DONE  4.620451    6.26131   5.733397   7.356016  5.317836
sub4           DONE   2.38953   3.272965   3.818374   5.029019  3.790518
sub5           DONE  1.250183   1.322771   0.717525   0.928201  0.665034

data_path
Disp type DFT_D3ZERO Processed
sub1       13.720054      DONE
sub2        6.760778      DONE
sub3        6.935442      DONE
sub4        4.986451      DONE
sub5        0.872943      DONE

[5 rows x 21 columns]

wtmad_1

data_path    3036943                                                      \
Disp type         AI        DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1        5.264198   6.676977  4.441266  6.613591  4.480294   6.300322
sub2       25.373279  24.561859  4.058777   4.88558  8.833039   8.581265
sub3             NaN        NaN       NaN       NaN       NaN        NaN
sub4             NaN        NaN       NaN       NaN       NaN        NaN
sub5        9.782615   5.745127  4.095739  5.440497  3.862631   5.658872
summary          NaN        NaN       NaN       NaN       NaN        NaN

data_path              1424849                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1         8 / 18   3.239113   7.420922   2.966668  ...   2.651677
sub2          0 / 7  13.142366   12.53052  11.927684  ...  11.524607
sub3          0 / 7   4.832263   6.984991   5.854163  ...   5.522858
sub4         0 / 11  11.556831  11.029773  13.901938  ...  12.876599
sub5          0 / 8  15.335367  11.571826  14.145431  ...  14.544885
summary          --  48.105939  49.538032  48.795883  ...  47.120625

data_path                         1513512                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        7.102094      DONE   5.917804   7.427913   6.173631   7.422353
sub2       10.005295      DONE   9.677109  12.530346   7.731942   9.967392
sub3        7.521852      DONE   5.362819   6.982875   6.557344   8.149361
sub4       13.798614      DONE  10.472747  11.046974  12.507724  14.856703
sub5        7.523212      DONE  10.880025  11.599184   6.460544   8.076713
summary    45.951067        --  42.310504  49.587291  39.431184  48.472523

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        5.786012   7.109349      DONE
sub2        7.407743  10.004803      DONE
sub3        5.935941   7.519994      DONE
sub4       11.478243  13.779798      DONE
sub5        5.881129   7.508553      DONE
summary    36.489069  45.922496        --

[6 rows x 21 columns]

wtmad_2

data_path    3036943                                                        \
Disp type         AI        DFT    AI_D3BJ  DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        14.00995  26.992259  13.326963  27.45632  13.062257  26.722526
sub2         6.06036   5.873226   0.956717  1.144589   2.103308   2.040891
sub3             0.0        0.0        0.0       0.0        0.0        0.0
sub4             0.0        0.0        0.0       0.0        0.0        0.0
sub5        1.552508   0.911756   0.649997  0.863411   0.613002   0.898067
summary    21.622818   33.77724  14.933677  29.46432  15.778567  29.661483

data_path              1424849                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1         8 / 18   1.438234   4.040696   1.379994  ...   1.263846
sub2          0 / 7   3.339073   3.635331   2.970755  ...   2.735086
sub3          0 / 7   1.303233   2.611064    1.66299  ...   1.549133
sub4         0 / 11   4.683102   4.159493   6.811273  ...   6.578153
sub5          0 / 8   6.331811    4.66236    6.30221  ...   6.387196
summary          --  17.095452  19.108945  19.127222  ...  18.513414

data_path                         1513512                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        3.989769      DONE   2.668675   4.045306   2.808633   4.115977
sub2        2.545688      DONE   3.206768   3.637148   2.047904   2.377001
sub3        2.873647      DONE   1.989474   2.610843    2.42163   3.039958
sub4         6.62018      DONE   4.130245    4.16366   6.081695   6.850967
sub5         3.19725      DONE   4.368745   4.670544   2.805652    3.50597
summary    19.226535        --  16.363907  19.127501  16.165515  19.889873

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        2.675278   3.994343      DONE
sub2        2.176739   2.547486      DONE
sub3        2.256968   2.873547      DONE
sub4        5.851345   6.614613      DONE
sub5        2.496356   3.192324      DONE
summary    15.456686  19.222314        --

[6 rows x 21 columns]

Summary of Subset
MAE

data_path    3036943                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       6.849464  29.111712   8.159832  30.739374   7.086307  29.426911
G21EA       2.581223   9.754522   2.575859   9.751745   2.592166   9.757546
G21IP       1.938484   8.953334    1.94495   8.946699   1.941726     8.9519
DIPCS10     4.985363  12.310852    4.96582  12.334099    4.96276  12.264655
PA26        2.360893   2.222399    2.61935   1.834736   2.489014   1.987376
SIE4x4     18.489931  21.908516  18.919228  22.337814  18.921342  22.339928
ALKBDE10   11.415343  18.125246  12.103946  18.838948  11.425615  18.135588
YBDE18      5.891732   7.984356   4.727342   7.507393   4.930792   7.560119
AL2X6       4.917457   5.659145   2.368365   1.332003    1.38317   1.829895
HEAVYSB11   5.957114   5.391476   5.287455   8.010474   4.527058   5.984154
NBPRC       4.906963   1.640573   3.525889   3.024418   3.587284   2.174489
ALK8        7.397188   4.400063   2.018111   3.174803   4.748123   2.559066
RC21               0          0          0          0          0          0
G2RC               0          0          0          0          0          0
BH76RC             0          0          0          0          0          0
FH51               0          0          0          0          0          0
TAUT15             0          0          0          0          0          0
DC13               0          0          0          0          0          0
MB16_43    21.441555  12.767682  18.652963  30.855364  15.182943  17.701997
DARC               0          0          0          0          0          0
RSE43              0          0          0          0          0          0
BSR36        4.86024   4.784695   0.625226   0.668562   1.614778   1.539233
CDIE20             0          0          0          0          0          0
ISO34              0          0          0          0          0          0
PArel              0          0          0          0          0          0
BH76               0          0          0          0          0          0
BHPERI             0          0          0          0          0          0
BHDIV10            0          0          0          0          0          0
INV24              0          0          0          0          0          0
BHROT27            0          0          0          0          0          0
PX13               0          0          0          0          0          0
WCPT18             0          0          0          0          0          0
RG18               0          0          0          0          0          0
ADIM6              0          0          0          0          0          0
S22                0          0          0          0          0          0
S66                0          0          0          0          0          0
WATER27            0          0          0          0          0          0
CARBHB12           0          0          0          0          0          0
PNICO23            0          0          0          0          0          0
HAL59              0          0          0          0          0          0
AHB21              0          0          0          0          0          0
CHB6               0          0          0          0          0          0
IL16               0          0          0          0          0          0
IDISP              0          0          0          0          0          0
ICONF              0          0          0          0          0          0
ACONF              0          0          0          0          0          0
Amino20x4   0.978262   0.574513   0.409574    0.54405   0.386263   0.565887
PCONF21            0          0          0          0          0          0
MCONF              0          0          0          0          0          0
SCONF              0          0          0          0          0          0
BUT14DIOL          0          0          0          0          0          0

data_path               1424849                        ...             \
Disp type  Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11      137 / 140   1.028249  29.506863   2.441523  ...   1.248828
G21EA           DONE   0.816732   9.754522   0.812414  ...   0.823677
G21IP           DONE   0.694714   8.953334    0.70284  ...   0.685192
DIPCS10         DONE   2.042735  12.310852   2.034436  ...   2.049052
PA26         22 / 26   3.009087   2.200766   2.998221  ...   2.951891
SIE4x4          DONE   3.430805  21.908516   3.716252  ...   3.729847
ALKBDE10        DONE   0.959132  18.125246   1.307356  ...    0.94979
YBDE18       17 / 18   5.939045   8.145393   3.828518  ...   4.255001
AL2X6           DONE   6.140013   5.659145   2.086328  ...    2.63339
HEAVYSB11       DONE   2.024005   5.391476   3.570429  ...   1.845095
NBPRC         9 / 12   3.058861    2.23255   2.325813  ...   2.192134
ALK8            DONE   4.403777   4.400063   3.075723  ...   2.009981
RC21          0 / 21   2.456062   4.820926   2.009509  ...   1.816792
G2RC          0 / 25   1.887093   5.917203    2.60955  ...   2.145182
BH76RC        0 / 30    0.85212   3.484561   1.035153  ...    0.96494
FH51          0 / 51   2.464205   3.703657   2.323411  ...   2.136612
TAUT15        0 / 15   1.702465    2.16453   1.631979  ...   1.578771
DC13          0 / 13   6.170057  13.090861   7.562068  ...   5.746533
MB16_43       9 / 43   13.39941  15.461604  35.416173  ...  21.115024
DARC          0 / 14   7.823359   10.75415   2.327124  ...   3.060175
RSE43         0 / 43    3.11738     3.1576   2.896011  ...   2.755026
BSR36        15 / 36    4.98276    8.40118   3.343187  ...   2.368872
CDIE20        0 / 20   1.450234   1.599507   1.483496  ...   1.479584
ISO34         0 / 34   2.020035   2.001743   1.659329  ...   1.708557
PArel         0 / 20   3.015433   1.743933   2.882746  ...   2.907704
BH76          0 / 76   2.803583   9.107946   3.232992  ...   3.093517
BHPERI        0 / 26   2.657111   3.268992    6.88257  ...   5.491745
BHDIV10       0 / 10   4.741552   6.277706   5.390696  ...    4.85035
INV24         0 / 24   3.393792   2.697333   3.863218  ...   3.631489
BHROT27       0 / 27   1.713103   0.853379   1.734055  ...   1.763036
PX13          0 / 13   1.059156  11.042023   1.291815  ...   1.212867
WCPT18        0 / 18   2.039614   7.967151   2.977303  ...   2.749679
RG18          0 / 18    0.30936   0.230018   0.765676  ...   0.819514
ADIM6          0 / 6   3.598266   3.059029   2.516398  ...   2.777618
S22           0 / 22   2.728845   2.291252   3.309309  ...   3.196728
S66           0 / 66   2.326488   1.894709    1.79261  ...   1.834235
WATER27       0 / 27    3.02651  16.299413   8.262183  ...   9.177355
CARBHB12      0 / 12   0.484944   1.632408   1.161335  ...   1.030009
PNICO23       0 / 23   0.840943   0.776429   2.313413  ...    1.44661
HAL59         0 / 31   2.035403   1.649786   2.945249  ...   2.562614
AHB21         0 / 21   1.666768   2.453821   2.321702  ...   2.212706
CHB6           0 / 4   1.766454    1.80532   1.334639  ...   1.432927
IL16          0 / 16   1.467889   1.021067   3.988457  ...   4.059287
IDISP          0 / 6  13.356085  13.125475   5.787398  ...   6.653317
ICONF         0 / 17   0.946016   0.413804    0.81078  ...   0.905493
ACONF         0 / 15   3.016487   0.546621   2.340276  ...   2.444544
Amino20x4     8 / 80   1.243276   0.656235   1.235374  ...   1.240646
PCONF21       0 / 18    2.09681   3.214782    2.27087  ...   2.451983
MCONF         0 / 51   1.596087    1.95602   1.874388  ...   1.854668
SCONF         0 / 17   1.154998   0.512352   1.080344  ...   1.029236
BUT14DIOL     0 / 64   0.879011   0.645099   1.125573  ...   1.044006

data_path                         1513512                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11      29.861054      DONE   8.912932  29.506078  10.371244  31.210968
G21EA       9.757546      DONE   2.564896   9.754833   2.561594   9.752056
G21IP         8.9519      DONE   2.386778   8.953264   2.393298   8.946628
DIPCS10    12.264655      DONE   4.016426  12.311021   3.996413  12.334267
PA26         2.00824      DONE   2.509054   2.201636   2.809443   1.901211
SIE4x4     22.339928      DONE  19.060598  21.908495  19.489895  22.337792
ALKBDE10   18.135588      DONE  12.834948  18.116813   13.54865  18.830516
YBDE18      7.472761      DONE   6.229871   8.147657   5.103758    7.26749
AL2X6       1.829895      DONE   1.916657   5.657149   5.462636   1.330963
HEAVYSB11   5.984154      DONE   4.770742   5.388236   6.593581   8.013345
NBPRC       2.274234      DONE   3.669712   2.230608   2.476637    2.54398
ALK8        2.559066      DONE   6.048862   4.392627   3.098441   3.183152
RC21          6.0297      DONE   4.664053   4.961517   6.684956   6.810127
G2RC        6.417298      DONE   7.677862   5.917132    8.58537   6.933574
BH76RC      3.536982      DONE   3.279731   3.485362   3.389266   3.540426
FH51        3.256908      DONE   3.262527   3.706141   3.442943   3.396157
TAUT15      2.145937      DONE   1.405035   2.164503   1.440052   2.175254
DC13       11.475687      DONE  14.707148   13.09363   14.33006  12.470922
MB16_43    23.165472      DONE  22.256488  15.453583  50.913406   36.86485
DARC         5.57797      DONE   5.306109  10.749101   2.481735    3.43032
RSE43        2.74911      DONE   2.373794   3.156151   2.140418   2.914826
BSR36       3.079317      DONE   9.542035   8.418212   2.188723   1.224292
CDIE20      1.347484      DONE   1.138114   1.598478   0.835289   1.335515
ISO34       1.647042      DONE   1.623868   2.001743   1.275672   1.577125
PArel       1.645025      DONE   1.392302   1.745172   1.332906   1.735011
BH76        9.676053      DONE   6.839808   9.108903   7.602416   9.890156
BHPERI        6.4139      DONE   2.393671   3.269267   6.807975   7.806334
BHDIV10     6.535109      DONE   4.856895   6.276167   5.996852   7.447415
INV24       2.228547      DONE   2.758492   2.694221   2.764818   2.346504
BHROT27      0.78352      DONE   0.900358   0.851983   0.907826   0.857457
PX13       11.219857      DONE   7.029398  11.044222   7.813386   11.82821
WCPT18      8.744304      DONE   4.657887    7.96751   5.837702   9.152344
RG18        0.709552      DONE   0.264077   0.230148   0.631463   0.655579
ADIM6       2.390824      DONE    3.20211   3.074906   1.947175   2.074379
S22         2.291758      DONE   2.549198   2.292182   1.876449   2.402001
S66         2.101976      DONE   1.989056   1.896952   1.680986   2.055246
WATER27    26.402884      DONE   9.389889  16.299413  18.581524  25.491048
CARBHB12    2.841777      DONE   0.769567   1.633524   2.070602    2.97422
PNICO23     1.726817      DONE   0.805198   0.775722   2.559277   2.603153
HAL59       2.247276      DONE    1.55448   1.649326   2.385952    2.62945
AHB21       3.294519      DONE   1.347543   2.453773   2.214282   3.464336
CHB6        2.309161      DONE   1.507904   1.803629     1.6901   3.036435
IL16        4.409963      DONE   0.689251   1.017646   3.033894   4.335711
IDISP       5.245746      DONE  13.131153  13.141197   3.047996   4.407339
ICONF       0.493337      DONE   0.500565    0.41335    0.67976   0.464855
ACONF       0.274429      DONE   0.505225   0.567241   0.472147   0.410131
Amino20x4   0.576975      DONE   0.668801   0.655899   0.563968   0.644029
PCONF21     1.099663      DONE   3.002198   3.214782    0.83205   1.178453
MCONF       0.711618      DONE   2.142772   1.949561   0.675319   0.746058
SCONF       1.317952      DONE    0.28121   0.514191   0.939365   1.435301
BUT14DIOL    1.02002      DONE   0.290133   0.650204   0.701027   1.141809

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
W4_11       9.214856   29.86027      DONE
G21EA       2.571788   9.757857      DONE
G21IP       2.389928   8.951829      DONE
DIPCS10     3.999516  12.264823      DONE
PA26        2.642708   2.009318      DONE
SIE4x4     19.492009  22.339906      DONE
ALKBDE10    12.84529  18.127155      DONE
YBDE18      5.247099   7.475024      DONE
AL2X6       3.483718   1.827899      DONE
HEAVYSB11   4.567261   5.987025      DONE
NBPRC       2.718006   2.276088      DONE
ALK8         3.50235   2.554507      DONE
RC21        6.048642   6.169201      DONE
G2RC         8.07384   6.419741      DONE
BH76RC      3.328641   3.537585      DONE
FH51        3.345771   3.258629      DONE
TAUT15      1.366175   2.145706      DONE
DC13       13.437354  11.471982      DONE
MB16_43    35.698138  23.169246      DONE
DARC        1.125373   5.572921      DONE
RSE43       1.973055   2.747661      DONE
BSR36       4.220172   3.096349      DONE
CDIE20      0.834091   1.346455      DONE
ISO34        1.29209   1.647042      DONE
PArel        1.35753   1.645923      DONE
BH76        7.394191    9.67701      DONE
BHPERI       5.41715   6.415509      DONE
BHDIV10      5.10293    6.53357      DONE
INV24       2.634085   2.228457      DONE
BHROT27     0.832769   0.781869      DONE
PX13        7.207232  11.222056      DONE
WCPT18      5.468315   8.744663      DONE
RG18        0.685301   0.709417      DONE
ADIM6       2.247743   2.374947      DONE
S22         1.765279   2.290832      DONE
S66         1.724401   2.098661      DONE
WATER27     19.49336  26.402884      DONE
CARBHB12    1.939275   2.842893      DONE
PNICO23     1.682048   1.725924      DONE
HAL59       2.003316   2.246814      DONE
AHB21       2.132835   3.294471      DONE
CHB6         1.39439    2.30747      DONE
IL16        3.104725   4.406542      DONE
IDISP       4.124779   5.230025      DONE
ICONF       0.575008   0.493186      DONE
ACONF       0.317627   0.253809      DONE
Amino20x4   0.487973   0.574269      DONE
PCONF21     0.857901   1.099663      DONE
MCONF       0.633868   0.717392      DONE
SCONF        0.82446   1.320396      DONE
BUT14DIOL    0.59559   1.025126      DONE

[51 rows x 21 columns]

In [5]:
16.363907 / 19.127501, 12.60223 / 15.936448, 14.245033 / 17.35668

(0.8555172471301924, 0.7907803545683455, 0.8207233756686185)