In [1]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 0
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate_hkqai_done").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict_ccpvdz"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if "modified_dft_d3bj" in data.columns:
            data_dft_d3bj = data["modified_dft_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3bj = data_d3bj
        if "modified_dft_d3zero" in data.columns:
            data_dft_d3zero = data["modified_dft_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3zero = data_d3zero
        if "modified_ai_d3bj" in data.columns:
            data_ai_d3bj = data["modified_ai_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3bj = data_d3bj
        if "modified_ai_d3zero" in data.columns:
            data_ai_d3zero = data["modified_ai_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    print(atomic_energy_cc, i_reaction["reference"])
                    atomic_energy_cc = i_reaction["reference"]
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_ai = np.argsort(data_subset[name_subset]["ai"])[
                    ::-1
                ][:5]
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ][:5]
                for i in range(len(argsort_atomic_energy_ai)):
                    i_reaction_name = data_subset[name_subset]["name"][
                        argsort_atomic_energy_ai[i]
                    ]
                    i_reaction = json_data[f"reaction-{i_subset}"][i_reaction_name]
                    print(
                        f"Top {i+1} AI: {data_subset[name_subset]['ai'][argsort_atomic_energy_ai[i]]} kcal/mol, {i_reaction_name} in {name_subset}",
                    )
                    systems_list = i_reaction["systems"]
                    stoichiometry_list = i_reaction["stoichiometry"]
                    for j in range(len(systems_list)):
                        mole_name = (
                            systems_list[j]
                            if i_subset == "BH76RC"
                            else f"{i_subset}-{systems_list[j]}"
                        )
                        stoichiometry = int(stoichiometry_list[j])
                        if mole_name in json_data:
                            if isinstance(json_data[mole_name], str):
                                mole_name = json_data[mole_name]
                        print(f"  {stoichiometry} * {mole_name}", end="")
                        col = np.where(data_name == mole_name)[0]
                        if col.size == 1:
                            error_energy_ai = data_scf[col[0]] - data_cc[col[0]]
                            print(f"  {stoichiometry} * {error_energy_ai}", end="")
                    print()

                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["ai"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["ai"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {data_path_name}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

    wtmad_1_subset.loc["summary", (data_path_name, "Processed")] = "--"
    wtmad_2_subset.loc["summary", (data_path_name, "Processed")] = "--"
    for d3_name in ["", "_d3bj", "_d3zero"]:
        wtmad_1_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_1_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        for name_set in full_subset_dict.keys():
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]

print("Summary")
display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset_ele.to_csv(f"../validate_hkqai_done/df_summary_subset_ele_{date}.csv")
df_summary_subset.to_csv(f"../validate_hkqai_done/summary_subset_{date}.csv")
mean_subset.to_csv(f"../validate_hkqai_done/mean_subset_{date}.csv")
wtmad_1_subset.to_csv(f"../validate_hkqai_done/wtmad_1_subset_{date}.csv")
wtmad_2_subset.to_csv(f"../validate_hkqai_done/wtmad_2_subset_{date}.csv")
# save summary to excel with date
df_summary_subset_ele.to_excel(f"../validate_hkqai_done/df_summary_subset_ele_{date}.xlsx")
df_summary_subset.to_excel(f"../validate_hkqai_done/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate_hkqai_done/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate_hkqai_done/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate_hkqai_done/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
103.45767788233127 109.493
197.87474320132537 213.169
67.7890541336356 73.57
301.7467616007382 324.945
264.30226880356827 281.287
78.83721184493066 84.995
177.19211774472035 190.745
66.19061508512556 73.921
492.3781024508485 535.885
286.8025965786612 307.87
394.25825746381474 420.42
566.5643705795687 607.023
340.5786669225199 382.753
218.0213781856794 242.267
666.5164644713718 713.08
940.5028523511942 1007.909
Warning: 15 in 1424849_W4_11 has a large CC energy: 1007.909 kcal/mol
164.31614701852425 181.456
74.9817887194668 84.221
166.15324029093608 183.913
77.9978403703426 87.731
665.7382671656451 721.502
530.9323428577784 582.301
387.86547605063174 422.959
798.0293574686789 861.578
265.7823781808104 298.018
746.5917383465116 811.241
430.9585935350008 474.629
521.6135155617778 564.095
469.62903003021006 513.501
97.68035093485378 107.499
159.49529398107018 182.591
70.88252791147994 83.096
434.5276205401135 482.276
373.77507352331304 410.973
207.5764702942979 232.974
125.78342166014772 141.64
408.5184302926275 446.081
93.69320042856003 107.208
645.2001664434977 705.605
622.1461601906087 677.864
644.4442473496204 704.1
474.6865497987019 577.78
425.02986077821697 470.973
523.0812227489507 573.892
592.3821211846991 651.526
395.44282890548686 437.668
364.4221086654288 430.967
270.5178973983857 309.099
325.52107332139906 359.934
382.87911858415464 438.281
395.725080665273 439.441
140.7651894832452 163.78
731.6236870346659 804.017
365.8863112488781 405.525
340.6253538694291 374.658
307.3699078396894 343.749
162.4157070639194 182.517
204.68108480831143 225.274
288.8905431652039 322.477
269.198590732296 312.651
284.18552454959183 317.647
106.62337512522936 122.618
481.94353282218265 533.462
114.47294797041832 142.71
451.09347136386543 501.899
296.18328155704705 336.249
571.9777297105703 635.101
361.63770977806877 403.743
210.8124147118598 248.059
426.1689155989152 478.76
353.2329720391181 398.472
277.08716267571435 313.418
261.53601144375716 298.203
233.87773041652423 266.163
250.17993806830782 279.422
235.99583794592763 259.727
396.95072211302806 456.072
372.5995969479409 420.636
357.50976986835036 410.066
231.10913910751697 269.089
252.42577707274177 296.534
379.7093395084349 434.737
247.2536278818734 291.135
225.27880953995918 258.782
347.35298587259604 390.141
334.49806895708025 386.087
357.85437104447385 410.029
114.34704667295591 132.721
133.00776232903905 165.128
134.97415255522355 166.229
434.61423169729824 502.037
193.77785714174388 228.485
186.69799392495503 224.864
292.2970671202638 335.747
154.93752886389848 193.052
242.7738302105863 285.447
146.0499753265176 175.533
307.61612612878986 364.971
299.07446298896417 350.149
171.6952135218744 205.89
130.7137083410271 158.653
260.76406682610104 312.219
259.5760142468207 312.649
235.21897672716295 280.778
267.2922711520223 331.785
145.8446902356809 172.218
148.83809141609527 181.35
226.78749878387316 346.943
144.00877982727252 177.357
81.96595572016668 105.815
175.18821088015102 260.621
125.80121217873238 152.745
90.60165159546887 126.465
216.8633135423006 270.849
184.90752151838387 233.089
76.91421675292077 104.251
196.38822922471445 290.578
38.79547573567834 59.75
99.13696514129697 120.824
22.11346669078921 39.042
183.855191745708 233.297
135.38612079116865 208.781
82.03831409546547 117.593
39.33997497775272 62.8
178.94796568188758 227.882
37.02871662550024 65.447
108.64201313373633 168.364
61.97433667568839 101.457
148.7264346879674 234.348
34.03758634097903 53.075
113.51214936282486 147.023
44.58144210505998 128.12
58.63257303526916 93.78
50.13450295237635 67.459
91.72653194019222 134.721
87.23797055176692 126.385
96.79474578030931 152.369
93.8012964882073 147.428
69.99087224205141 105.239
-2.084101479191304 2.669
2.3606765124204685 29.2
-22.74137921671354 33.7
19.62185181023233 78.4
16.638233546807896 32.1
-17.239664660213748 17.3
16.964803471346386 48.0
56.91499975131592 83.5
0.8769436639304331 27.9
-15.807303788362333 13.4
-28.458146719742217 1.2
-44.99861716482701 8.3
-31.793254336436803 16.8
-15.3947548100914 41.7
13.90307032020064 29.3
10.577740641165292 25.1
17.813674557051854 31.4
-7.109995343460469 23.5
2.5932301623979583 28.8
25.195919922494795 54.2
-26.443786939795245 9.5
-30.223614010435995 -0.2
65.39676022579806 89.5
0.5339677982556168 24.9
18.626282668788917 38.0
45.936298766639084 54.7
313.3019279972386 314.9
123.25100174284944 123.3
214.2024720987447 214.9
185.50237661557367 190.4
253.0980128923875 259.6
327.4242995132299 335.3
296.2427352147497 313.8
385.2822848305368 401.7
114.39537121495232 118.5
173.53351447444584 176.3
134.05986441214918 138.0
182.98762731734314 188.0
236.0932927740505 241.9
222.31091392444796 239.0
285.0344170331373 299.1
291.3918614476024 296.339
219.98989069536765 235.69
283.0468394752461 300.917
272.5172629683002 292.648
351.90065484631486 371.311
248.70597023214214 255.387
228.0280249104544 234.107
219.51022365421522 226.367
218.45729858492268 227.822
225.417502778786 239.3
282.01092556270305 294.459
251.3601413588476 264.585
233.12707006531127 243.709
314.1945943458122 322.986
350.35604821275047 359.365
270.104549247204 277.727
241.1483214245527 242.854
210.1664813599782 215.737
260.703432053444 265.083
285.4622802733211 291.699
254.1644252379192 261.153
512.988715306652 529.2
660.0930003615867 667.1
638.7531667341536 655.8
612.3597411422961 626.9
753.0557642683561 776.5
733.3263710421888 747.6
713.0408907497767 733.0
634.1259366368467 649.6
513.2633817447349 522.1
631.4456416715329 634.8
171.07957391102536 167.2
197.85095157932665 192.9
214.0837223022245 209.2
223.94259436559514 219.2
220.23364171144203 211.9
180.58708242182183 171.4
160.6877454275309 157.4
157.1979607179819 156.9
194.9208129097824 192.8
178.72311203030404 174.3
141.55399180715904 137.8
105.62826681866431 106.2
126.12688581476687 120.8
197.24830939083768 191.9
196.13282849444658 190.9
224.99612896400504 218.2
206.89314115489833 200.4
214.81132548494497 210.2
191.40151548048016 188.3
185.64244732877705 181.9
227.95873934216797 221.3
227.13035202363972 219.6
201.3909862941946 192.9
215.97132305201376 210.7
242.51728880754672 236.0
244.15432332406635 235.1
63.37251396025664 64.4
56.94162704792393 58.9
45.64604986096293 48.7
34.50038781668002 38.3
53.071758472146485 56.9
43.49347195224618 46.9
28.738282325882665 31.3
17.281310228210714 19.1
36.051034228134085 35.9
24.972192156797973 25.9
10.315573885658523 13.4
0.08366747575928457 4.9
40.97513549416908 39.7
29.1769796165172 29.1
14.680219840403879 16.9
5.644841673158226 9.3
116.4405689091509 138.7
76.77795528128627 106.6
57.21556741733366 96.2
125.78438767154876 142.1
121.68362467933912 139.2
63.989182149663975 82.5
29.556841399920813 62.2
30.37601203485974 56.7
44.92724179071229 65.2
47.05107629934355 57.17
70.58581512744786 91.14
14.029307460856216 20.96
16.805467736270657 36.4
30.405667018443637 38.99
30.754253953553416 51.74
7.54380816626508 12.31
36.356922528593714 53.73
34.65284457406233 32.58
20.884114788404986 28.87
39.75912118807173 42.11
31.581463619881106 42.81
41.30178701540717 52.28
55.92674971008455 76.37
35.651165891562414 44.8
39.882070749128616 60.11
57.127693033726246 66.59
56.94791995626656 78.0
34.35712907073321 38.5
60.4335912221577 51.6
27.598288372159004 32.5
35.609609787818044 38.4
27.273332296230365 31.2
18.21387416194193 23.1
68.3026060378179 73.82
50.707772818685044 67.85
45.832846568431705 58.37
49.237641107989475 61.85
43.68931851303205 52.18
38.43368311598897 59.65
36.53713600570336 53.17
-33.792402985767694 -32.1
1.833096950546178 -0.2
39.65082765939428 37.6
-19.686439162513125 -19.5
-44.36512896050135 -48.9
-47.68285860365722 -46.1
-20.071147613984067 -25.2
44.31841211447511 40.4
-13.259094716166146 -15.2
20.476931327766692 18.5
-24.294345419679303 -31.2
19.65371775462893 17.6
73.46954343028483 86.47
50.767523624934256 53.15
136.35981809288205 131.13
33.19521937960599 34.51
46.91091195309491 47.42
67.23699480288269 66.28
62.11523076679441 56.55
28.35022310182103 25.3
21.551569021423347 23.43
24.533528688487422 26.66
22.362634850738687 24.74
55.15717650712031 59.44
57.658213536659844 57.93
36.801087157131406 36.56
19.325530514819548 17.91
16.817455014039297 16.8
49.04162216297118 49.85
43.364126353684696 45.16
19.707387487913365 22.24
-3.4555473218206316 -6.72
23.95756392992189 21.21
20.6174360497389 22.03
26.052831743334536 28.12
1.0662819630597369 -0.73
50.50055065454217 50.66
24.438550770340953 30.38
48.94374535444513 49.73
23.530286877023173 32.81
124.91641149130737 126.56
-23.23018389895151 -2.23
-0.31154960770800244 -2.26
-7.98707241617376 -2.18
-7.643045576638542 -4.1
-7.378334794184639 -7.1
-16.690478918491863 -10.7
-19.29966168628016 -19.47
-31.819901191600366 -26.97
-18.706155653111637 -27.3
-37.672137120272964 -27.15
10.882930254330859 -24.89
-25.539446764305467 -29.46
-35.12303537745902 -32.71
-43.83011712798907 -36.32
-27.813303065588116 -39.43
-54.70624560548458 -48.52
-52.6048655506238 -49.2
-94.16879849680117 -61.67
-55.572206000812 -65.15
-67.35408623807598 -68.9
-80.6717972735496 -81.21
-104.27826737203577 -109.11
-126.1484881274373 -135.4
-158.2693689056905 -154.04
-198.7895008015039 -216.11
-70.70527747826418 -64.91
-24.777322617406753 -26.32
-104.01133193718852 -103.28
-61.71578701538965 -52.64
-61.600522870139685 -32.16
-44.01981997129042 -26.12
-23.171177066265955 -20.32
-50.68764951231424 -36.71
6.980071807556669 3.69
-14.156610999329132 -19.55
-40.44780613459443 -40.02
-27.10638884101354 -26.56
-15.517636002405197 -15.06
-5.788470511382911 -1.9
-10.404441769099265 -16.39
-3.992683881299797 -3.11
-6.4117578877958294 -13.28
-7.702259865152882 -10.32
-9.781154392720055 -5.01
-9.351984838911449 -16.84
-22.32429042963753 -32.22
13.773280498444365 5.44
-22.194361328234663 -21.74
-9.780596617143601 -2.32
-15.30645017043571 -13.26
3.992126105702482 0.42
-18.87433104563752 -13.12
-417.81181181190914 -9.56
-1.6497249737512902 -6.52
1.290501977349777 -2.96
-141.33352378208656 -150.81
-131.5224298950052 -144.38
-84.7474774140137 -89.35
-54.50817141718289 -82.55
-77.62634936423274 -78.51
-75.22528630369925 -66.96
-60.543676267552655 -63.89
-54.615140549925854 -58.53
-52.71600785701594 -56.64
-25.618658076171414 -52.85
-56.08131741677062 -52.6
-49.58488737407606 -46.72
-47.264058680302696 -44.82
-45.77092113086837 -43.67
-42.956024291866925 -42.89
-39.23716301243985 -37.08
-44.739489438099554 -34.93
-36.88968249061145 -32.47
-34.26779769969289 -32.1
-34.46350041072583 -31.22
-28.951130578818265 -29.98
-26.438858343841275 -25.84
-19.934285870025633 -23.47
-25.663390054687625 -22.45
-20.054872602282558 -20.27
-20.1184948773589 -19.72
-19.989651794661768 -19.34
-8.506633673343458 -19.45
-11.085070490604267 -17.39
-23.615577273914823 -16.98
-15.938468769862084 -16.14
-15.935726409807103 -14.3
-12.680712218454573 -13.14
-15.123401663120603 -11.68
-8.278255570607143 -10.7
-11.138188506447477 -9.39
-4.182594925223384 -8.53
-14.431158146820962 -6.63
-8.440485074388562 -6.65
-3.451479454379296 -6.45
-2.8132666988676647 -5.11
0.3389663673588075 -3.25
-1.9149754674872383 -2.64
-2.327190892159706 -2.48
-2.1514032845880138 -2.11
-4.786024113709573 -1.47
-1.4931375494343229 -1.15
-0.5557061818544753 -0.86
3.1671059855871135 -0.43
1.6933957500732504 -0.41
3.3510224685742287 -0.18
0.5555414959962945 4.3
1.904503563331673 6.56
-4.251910745806526 -5.44
1.1432803390198387 5.25
16.510615119390422 13.03
1.2418254199728835 0.93
1.8347114832722582 0.74
0.8530597716453485 1.45
-0.935850354610011 -0.17
-0.3856253152480349 -0.87
4.037478886602912 2.85
2.8352412210952025 2.15
0.31250686329440214 0.55
3.213350671576336 0.95
1.9854888165718876 -0.45
-1.1188644832291175 -1.0
-21.842206635163166 -7.7
-16.847440047567943 -15.2
-19.53829106950434 -18.8
-28.475618258060422 -22.9
-27.396348876063712 -25.7
-40.3833581279614 -38.9
-55.057773674911004 -92.0
-50.543036930961534 -106.0
106.07256267499179 109.92
-68.60685206632479 -65.3
-61.76667381709558 -58.7
173.60438507748768 152.6
103.45767788233127 109.493
197.87474320132537 213.169
67.7890541336356 73.57
301.7467616007382 324.945
264.30226880356827 281.287
78.83721184493066 84.995
177.19211774472035 190.745
66.19061508512556 73.921
492.3781024508485 535.885
286.8025965786612 307.87
394.25825746381474 420.42
566.5643705795687 607.023
340.5786669225199 382.753
218.0213781856794 242.267
666.5164644713718 713.08
940.5028523511942 1007.909
Warning: 15 in 1513512_W4_11 has a large CC energy: 1007.909 kcal/mol
164.31614701852425 181.456
74.9817887194668 84.221
166.15324029093608 183.913
77.9978403703426 87.731
665.7382671656451 721.502
530.9323428577784 582.301
387.86547605063174 422.959
798.0293574686789 861.578
265.7823781808104 298.018
746.5917383465116 811.241
430.9585935350008 474.629
521.6135155617778 564.095
469.62903003021006 513.501
97.68035093485378 107.499
159.49529398107018 182.591
70.88252791147994 83.096
434.5276205401135 482.276
373.77507352331304 410.973
207.5764702942979 232.974
125.78342166014772 141.64
408.5184302926275 446.081
93.69320042856003 107.208
645.2001664434977 705.605
622.1461601906087 677.864
644.4442473496204 704.1
474.6865497987019 577.78
425.02986077821697 470.973
523.0812227489507 573.892
592.3821211846991 651.526
395.44282890548686 437.668
364.4221086654288 430.967
270.5178973983857 309.099
325.52107332139906 359.934
382.87911858415464 438.281
395.725080665273 439.441
140.7651894832452 163.78
731.6236870346659 804.017
365.8863112488781 405.525
340.6253538694291 374.658
307.3699078396894 343.749
162.4157070639194 182.517
204.68108480831143 225.274
288.8905431652039 322.477
269.198590732296 312.651
284.18552454959183 317.647
106.62337512522936 122.618
481.94353282218265 533.462
114.47294797041832 142.71
451.09347136386543 501.899
296.18328155704705 336.249
571.9777297105703 635.101
361.63770977806877 403.743
210.8124147118598 248.059
426.1689155989152 478.76
353.2329720391181 398.472
277.08716267571435 313.418
261.53601144375716 298.203
233.87773041652423 266.163
250.17993806830782 279.422
235.99583794592763 259.727
396.95072211302806 456.072
372.5995969479409 420.636
357.50976986835036 410.066
231.10913910751697 269.089
252.42577707274177 296.534
379.7093395084349 434.737
247.2536278818734 291.135
225.27880953995918 258.782
347.35298587259604 390.141
334.49806895708025 386.087
357.85437104447385 410.029
114.34704667295591 132.721
133.00776232903905 165.128
134.97415255522355 166.229
434.61423169729824 502.037
193.77785714174388 228.485
186.69799392495503 224.864
292.2970671202638 335.747
154.93752886389848 193.052
242.7738302105863 285.447
146.0499753265176 175.533
307.61612612878986 364.971
299.07446298896417 350.149
171.6952135218744 205.89
130.7137083410271 158.653
260.76406682610104 312.219
259.5760142468207 312.649
235.21897672716295 280.778
267.2922711520223 331.785
145.8446902356809 172.218
148.83809141609527 181.35
226.78749878387316 346.943
144.00877982727252 177.357
81.96595572016668 105.815
175.18821088015102 260.621
125.80121217873238 152.745
90.60165159546887 126.465
216.8633135423006 270.849
184.90752151838387 233.089
76.91421675292077 104.251
196.38822922471445 290.578
38.79547573567834 59.75
99.13696514129697 120.824
22.11346669078921 39.042
183.855191745708 233.297
135.38612079116865 208.781
82.03831409546547 117.593
39.33997497775272 62.8
178.94796568188758 227.882
37.02871662550024 65.447
108.64201313373633 168.364
61.97433667568839 101.457
148.7264346879674 234.348
34.03758634097903 53.075
113.51214936282486 147.023
44.58144210505998 128.12
58.63257303526916 93.78
50.13450295237635 67.459
91.72653194019222 134.721
87.23797055176692 126.385
96.79474578030931 152.369
93.8012964882073 147.428
69.99087224205141 105.239
-2.084101479191304 2.669
2.3606765124204685 29.2
-22.74137921671354 33.7
19.62185181023233 78.4
16.638233546807896 32.1
-17.239664660213748 17.3
16.964803471346386 48.0
56.91499975131592 83.5
0.8769436639304331 27.9
-15.807303788362333 13.4
-28.458146719742217 1.2
-44.99861716482701 8.3
-31.793254336436803 16.8
-15.3947548100914 41.7
13.90307032020064 29.3
10.577740641165292 25.1
17.813674557051854 31.4
-7.109995343460469 23.5
2.5932301623979583 28.8
25.195919922494795 54.2
-26.443786939795245 9.5
-30.223614010435995 -0.2
65.39676022579806 89.5
0.5339677982556168 24.9
18.626282668788917 38.0
45.936298766639084 54.7
313.3019279972386 314.9
123.25100174284944 123.3
214.2024720987447 214.9
185.50237661557367 190.4
253.0980128923875 259.6
327.4242995132299 335.3
296.2427352147497 313.8
385.2822848305368 401.7
114.39537121495232 118.5
173.53351447444584 176.3
134.05986441214918 138.0
182.98762731734314 188.0
236.0932927740505 241.9
222.31091392444796 239.0
285.0344170331373 299.1
291.3918614476024 296.339
219.98989069536765 235.69
283.0468394752461 300.917
272.5172629683002 292.648
351.90065484631486 371.311
248.70597023214214 255.387
228.0280249104544 234.107
219.51022365421522 226.367
218.45729858492268 227.822
225.417502778786 239.3
282.01092556270305 294.459
251.3601413588476 264.585
233.12707006531127 243.709
314.1945943458122 322.986
350.35604821275047 359.365
270.104549247204 277.727
241.1483214245527 242.854
210.1664813599782 215.737
260.703432053444 265.083
285.4622802733211 291.699
254.1644252379192 261.153
512.988715306652 529.2
660.0930003615867 667.1
638.7531667341536 655.8
612.3597411422961 626.9
753.0557642683561 776.5
733.3263710421888 747.6
713.0408907497767 733.0
634.1259366368467 649.6
513.2633817447349 522.1
631.4456416715329 634.8
171.07957391102536 167.2
197.85095157932665 192.9
214.0837223022245 209.2
223.94259436559514 219.2
220.23364171144203 211.9
180.58708242182183 171.4
160.6877454275309 157.4
157.1979607179819 156.9
194.9208129097824 192.8
178.72311203030404 174.3
141.55399180715904 137.8
105.62826681866431 106.2
126.12688581476687 120.8
197.24830939083768 191.9
196.13282849444658 190.9
224.99612896400504 218.2
206.89314115489833 200.4
214.81132548494497 210.2
191.40151548048016 188.3
185.64244732877705 181.9
227.95873934216797 221.3
227.13035202363972 219.6
201.3909862941946 192.9
215.97132305201376 210.7
242.51728880754672 236.0
244.15432332406635 235.1
63.37251396025664 64.4
56.94162704792393 58.9
45.64604986096293 48.7
34.50038781668002 38.3
53.071758472146485 56.9
43.49347195224618 46.9
28.738282325882665 31.3
17.281310228210714 19.1
36.051034228134085 35.9
24.972192156797973 25.9
10.315573885658523 13.4
0.08366747575928457 4.9
40.97513549416908 39.7
29.1769796165172 29.1
14.680219840403879 16.9
5.644841673158226 9.3
116.4405689091509 138.7
76.77795528128627 106.6
57.21556741733366 96.2
125.78438767154876 142.1
121.68362467933912 139.2
63.989182149663975 82.5
29.556841399920813 62.2
30.37601203485974 56.7
44.92724179071229 65.2
47.05107629934355 57.17
70.58581512744786 91.14
14.029307460856216 20.96
16.805467736270657 36.4
30.405667018443637 38.99
30.754253953553416 51.74
7.54380816626508 12.31
36.356922528593714 53.73
34.65284457406233 32.58
20.884114788404986 28.87
39.75912118807173 42.11
31.581463619881106 42.81
41.30178701540717 52.28
55.92674971008455 76.37
35.651165891562414 44.8
39.882070749128616 60.11
57.127693033726246 66.59
56.94791995626656 78.0
34.35712907073321 38.5
60.4335912221577 51.6
27.598288372159004 32.5
35.609609787818044 38.4
27.273332296230365 31.2
18.21387416194193 23.1
68.3026060378179 73.82
50.707772818685044 67.85
45.832846568431705 58.37
49.237641107989475 61.85
43.68931851303205 52.18
38.43368311598897 59.65
36.53713600570336 53.17
-33.792402985767694 -32.1
1.833096950546178 -0.2
39.65082765939428 37.6
-19.686439162513125 -19.5
-44.36512896050135 -48.9
-47.68285860365722 -46.1
-20.071147613984067 -25.2
44.31841211447511 40.4
-13.259094716166146 -15.2
20.476931327766692 18.5
-24.294345419679303 -31.2
19.65371775462893 17.6
73.46954343028483 86.47
50.767523624934256 53.15
136.35981809288205 131.13
33.19521937960599 34.51
46.91091195309491 47.42
67.23699480288269 66.28
62.11523076679441 56.55
28.35022310182103 25.3
21.551569021423347 23.43
24.533528688487422 26.66
22.362634850738687 24.74
55.15717650712031 59.44

data_path       1424849                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary         0.32847      0.352175      0.031172       0.03176
W4_11          0.128193      0.146661      0.023594      0.021439
G21EA          0.079752      0.090296      0.012511      0.012762
G21IP          0.081996      0.086805      0.005995      0.006154
DIPCS10        0.101593      0.107438      0.005017      0.003622
PA26           0.268845        0.2982      0.034744      0.038429
SIE4x4         0.071736      0.093996      0.003569      0.001311
ALKBDE10       0.098409       0.10564      0.065934      0.061711
YBDE18         0.257196      0.276239      0.041119      0.041601
AL2X6          0.395256      0.396501      0.002764      0.002336
HEAVYSB11      0.288568      0.278481      0.011631      0.009043
NBPRC          0.237834      0.252724      0.032958      0.032482
ALK8           0.202733      0.187227      0.040614      0.040223
RC21           0.244294      0.258984      0.071539      0.082447
G2RC           0.163856      0.181463      0.015502      0.015617
BH76RC          0.12608       0.14036      0.055976      0.057338
FH51           0.342554      0.346443      0.024006      0.026834
TAUT15         0.369822      0.413544      0.067899      0.069453
DC13           0.390599      0.397856      0.020702      0.019322
MB16_43        0.500446      0.536587      0.084707      0.086338
DARC           0.426179      0.443789      0.014191      0.019082
RSE43          0.209548      0.233351      0.034582      0.033645
BSR36          0.534747      0.495778      0.004311      0.001683
CDIE20         0.370491       0.36033      0.039229      0.043548
ISO34           0.29061      0.298776      0.025594      0.026941
PArel          0.522926      0.599811      0.074776      0.079046
BH76            0.12608       0.14036      0.055976      0.057338
BHPERI         0.329315      0.326909      0.031284      0.029987
BHDIV10        0.342553      0.361694      0.049657      0.049067
INV24          0.778226      0.784024      0.038296      0.027518
BHROT27        0.289291      0.303021      0.021441      0.018507
PX13           0.215428      0.278637      0.012669       0.01315
WCPT18         0.197421      0.224154      0.060305      0.057861
RG18           0.204128      0.206046        0.0023      0.002641
ADIM6          0.480426      0.434301      0.000826       0.00024
S22            0.385426      0.405222      0.025222      0.024365
S66            0.331414      0.347655      0.022744      0.025355
WATER27        0.393804      0.547345       0.02721      0.033217
CARBHB12       0.176663      0.195377      0.033396      0.036954
PNICO23        0.208847      0.233577        0.0258      0.023517
HAL59          0.399949      0.412527      0.042605      0.036969
AHB21          0.108228      0.129997      0.032458      0.031459
CHB6           0.162305       0.16005      0.019153      0.019259
IL16           0.290156      0.335812      0.049496       0.05021
IDISP           0.89541      0.816401      0.002265      0.000619
ICONF          0.464768      0.533359      0.023171      0.022986
ACONF          0.384884      0.355398      0.003603      0.001781
Amino20x4      0.723524      0.806256       0.02953      0.037327
PCONF21         1.05244      1.184712      0.058859      0.077448
MCONF          0.933391      0.987572      0.038508      0.045477
SCONF          0.606237      0.725383      0.033587      0.024507
BUT14DIOL      0.338723      0.380054      0.025886       0.02199

data_path       1513512                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.322465      0.353225       0.03193       0.03176
W4_11          0.175284      0.148743       0.02206      0.021439
G21EA          0.236845      0.109529      0.011775      0.012762
G21IP          0.203623      0.102473      0.005944      0.006154
DIPCS10         0.09766      0.107454      0.003775      0.003622
PA26            0.25334      0.298218       0.03784      0.038429
SIE4x4         0.066672         0.094      0.001765      0.001311
ALKBDE10       0.182915      0.105669      0.066398      0.061711
YBDE18         0.253422      0.276224      0.045093      0.041601
AL2X6          0.405011       0.39636      0.001176      0.002336
HEAVYSB11      0.360122      0.278584      0.013089      0.009043
NBPRC           0.22909      0.252691      0.034451      0.032482
ALK8           0.217408      0.187231      0.034057      0.040223
RC21           0.295227      0.258996      0.086264      0.082447
G2RC           0.150104      0.181458      0.015757      0.015617
BH76RC           0.1463      0.140369       0.05898      0.057338
FH51           0.319164      0.346464       0.02731      0.026834
TAUT15         0.350471      0.413574      0.069962      0.069453
DC13           0.383288      0.397878      0.018574      0.019322
MB16_43        0.518531      0.536502      0.094792      0.086338
DARC           0.395505      0.443827      0.022334      0.019082
RSE43          0.195703      0.233363      0.033632      0.033645
BSR36          0.495655      0.495755      0.001133      0.001683
CDIE20         0.360308      0.360334      0.040943      0.043548
ISO34          0.271749      0.298766      0.025747      0.026941
PArel          0.469842      0.599826      0.078076      0.079046
BH76             0.1463      0.140369       0.05898      0.057338
BHPERI         0.315621      0.326923      0.031502      0.029987
BHDIV10        0.335963       0.36167      0.048037      0.049067
INV24          0.751564      0.784023      0.031474      0.027518
BHROT27        0.274318      0.303042      0.019701      0.018507
PX13           0.168176      0.278622      0.011859       0.01315
WCPT18         0.185586      0.224175      0.063803      0.057861
RG18           0.161305      0.205868      0.001977      0.002641
ADIM6          0.438285      0.433935      0.000125       0.00024
S22            0.358342      0.405269      0.023643      0.024365
S66            0.306882      0.347674      0.025266      0.025355
WATER27        0.311289      0.547381      0.028807      0.033217
CARBHB12        0.16907      0.195383      0.032772      0.036954
PNICO23        0.206764      0.233505      0.021276      0.023517
HAL59          0.385954      0.412781      0.038852      0.036969
AHB21          0.090137      0.130018      0.028776      0.031459
CHB6           0.150839      0.160096      0.014523      0.019259
IL16           0.260229      0.335826      0.046176       0.05021
IDISP          0.821087      0.816236      0.000556      0.000619
ICONF          0.485563       0.53321      0.021268      0.022986
ACONF          0.356304      0.355414      0.001912      0.001781
Amino20x4      0.671796      0.806302      0.038339      0.037327
PCONF21        0.969335      1.184777      0.079074      0.077448
MCONF          0.875182      0.987576      0.050452      0.045477
SCONF          0.527465      0.725367      0.021338      0.024507
BUT14DIOL      0.300657      0.380059       0.01603       0.02199

data_path        206726                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.316487       0.35243      0.032183      0.031706
W4_11            0.1671      0.148743      0.022541      0.021439
G21EA          0.191182      0.109529      0.011794      0.012762
G21IP          0.158778      0.102473      0.006126      0.006154
DIPCS10        0.094298      0.107454      0.002996      0.003622
PA26           0.254553      0.298218      0.036894      0.038429
SIE4x4         0.070633         0.094      0.002077      0.001311
ALKBDE10       0.218523      0.105669      0.065757      0.061711
YBDE18         0.239775      0.276224      0.045339      0.041601
AL2X6          0.362824       0.39636      0.001743      0.002336
HEAVYSB11       0.31079      0.278584      0.014684      0.009043
NBPRC          0.220769      0.252691      0.034622      0.032482
ALK8           0.210799      0.187231      0.036618      0.040223
RC21           0.261873      0.258996      0.084785      0.082447
G2RC           0.146688      0.181458      0.015576      0.015617
BH76RC         0.155174      0.140369      0.058568      0.057338
FH51           0.312509      0.346464       0.02615      0.026834
TAUT15         0.356718      0.413574      0.068925      0.069453
DC13            0.36573      0.397878      0.019594      0.019322
MB16_43        0.494716      0.536502      0.091377      0.086338
DARC            0.39586      0.443827      0.018461      0.019082
RSE43          0.193267      0.233363      0.034222      0.033645
BSR36          0.474422      0.495755      0.001537      0.001683
CDIE20         0.342773      0.360334      0.043181      0.043548
ISO34          0.265069      0.298766      0.026345      0.026941
PArel          0.493547      0.599826      0.078448      0.079046
BH76           0.155174      0.140369      0.058568      0.057338
BHPERI         0.304046      0.326923      0.030904      0.029987
BHDIV10        0.325425       0.36167      0.048614      0.049067
INV24          0.732215      0.784023      0.034713      0.027518
BHROT27        0.267022      0.303042      0.020445      0.018507
PX13           0.186648      0.278622      0.013214       0.01315
WCPT18         0.190053      0.224175      0.064089      0.057861
RG18           0.156693      0.205868      0.002144      0.002641
ADIM6          0.410864      0.433935      0.000087       0.00024
S22            0.357561      0.405269      0.024003      0.024365
S66            0.303952      0.347674       0.02474      0.025355
WATER27        0.366916      0.547381      0.031115      0.033217
CARBHB12       0.165507      0.195383      0.033438      0.036954
PNICO23        0.200543      0.233505      0.020764      0.023517
HAL59          0.384106      0.412781      0.040182      0.036969
AHB21          0.095548      0.130018      0.030811      0.031459
CHB6           0.147636      0.160096      0.016293      0.019259
IL16           0.264496      0.335826      0.049104       0.05021
IDISP          0.788399      0.816236      0.000974      0.000619
ICONF          0.480557       0.53321      0.023869      0.022986
ACONF          0.335886      0.355414      0.001744      0.001781
Amino20x4        0.6818      0.806302      0.036482      0.037327
PCONF21        0.993103      1.176517      0.073327      0.075738
MCONF          0.867894      0.987576      0.046747      0.045477
SCONF          0.554243      0.725367      0.031645      0.024507
BUT14DIOL      0.304479      0.380059      0.023771       0.02199

data_path       1428227                                            \
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.274686      0.353225      0.032812       0.03176
W4_11          0.154267      0.148743       0.02325      0.021439
G21EA          0.230568      0.109529      0.012397      0.012762
G21IP          0.167749      0.102473      0.006406      0.006154
DIPCS10        0.083987      0.107454       0.00244      0.003622
PA26           0.219291      0.298218      0.036426      0.038429
SIE4x4         0.064461         0.094      0.001999      0.001311
ALKBDE10       0.183963      0.105669      0.064876      0.061711
YBDE18         0.206502      0.276224      0.046499      0.041601
AL2X6          0.315005       0.39636       0.00186      0.002336
HEAVYSB11      0.270753      0.278584      0.014563      0.009043
NBPRC          0.186171      0.252691       0.03671      0.032482
ALK8           0.198394      0.187231      0.038359      0.040223
RC21            0.23505      0.258996      0.084804      0.082447
G2RC           0.124002      0.181458      0.015848      0.015617
BH76RC         0.131713      0.140369      0.059738      0.057338
FH51           0.260636      0.346464      0.025589      0.026834
TAUT15         0.304413      0.413574      0.067804      0.069453
DC13           0.306954      0.397878      0.020799      0.019322
MB16_43        0.440434      0.536502      0.090907      0.086338
DARC           0.333375      0.443827      0.015349      0.019082
RSE43          0.165468      0.233363      0.035271      0.033645
BSR36          0.395367      0.495755      0.001589      0.001683
CDIE20         0.283166      0.360334      0.043195      0.043548
ISO34          0.223018      0.298766      0.027289      0.026941
PArel          0.430784      0.599826      0.079526      0.079046
BH76           0.131713      0.140369      0.059738      0.057338
BHPERI         0.253614      0.326923      0.030627      0.029987
BHDIV10        0.271375       0.36167      0.049734      0.049067
INV24          0.616417      0.784023      0.037286      0.027518
BHROT27        0.224039      0.303042       0.02085      0.018507
PX13           0.180746      0.278622       0.01418       0.01315
WCPT18         0.163249      0.224175      0.063897      0.057861
RG18           0.133107      0.205868      0.002226      0.002641
ADIM6          0.339826      0.433935      0.000314       0.00024
S22            0.302584      0.405269      0.023769      0.024365
S66            0.256456      0.347674       0.02449      0.025355
WATER27        0.363907      0.547381       0.03342      0.033217
CARBHB12        0.13919      0.195383      0.033001      0.036954
PNICO23        0.172346      0.233505      0.022065      0.023517
HAL59          0.322549      0.412781      0.039677      0.036969
AHB21          0.081451      0.130018      0.033444      0.031459
CHB6           0.127612      0.160096      0.017508      0.019259
IL16           0.228859      0.335826       0.05296       0.05021
IDISP          0.651276      0.816236      0.000565      0.000619
ICONF          0.407688       0.53321      0.025059      0.022986
ACONF          0.276745      0.355414      0.001668      0.001781
Amino20x4      0.588484      0.806302      0.035895      0.037327
PCONF21        0.862849      1.184777      0.073273      0.077448
MCONF          0.738518      0.987576      0.045276      0.045477
SCONF          0.495965      0.725367       0.03816      0.024507
BUT14DIOL      0.264565      0.380059      0.029646       0.02199

data_path       3036943
Ele type  error_scf_ele error_dft_ele error_scf_dip error_dft_dip
summary        0.272361      0.353225      0.032258       0.03176
W4_11          0.161587      0.148743      0.022614      0.021439
G21EA          0.240177      0.109529      0.011709      0.012762
G21IP          0.172763      0.102473      0.006416      0.006154
DIPCS10        0.084361      0.107454        0.0028      0.003622
PA26             0.2151      0.298218      0.037656      0.038429
SIE4x4         0.058532         0.094      0.001729      0.001311
ALKBDE10        0.20704      0.105669      0.065603      0.061711
YBDE18         0.211432      0.276224      0.045758      0.041601
AL2X6          0.346008       0.39636      0.001437      0.002336
HEAVYSB11      0.336374      0.278584      0.012044      0.009043
NBPRC          0.186838      0.252691      0.036355      0.032482
ALK8           0.198121      0.187231      0.035923      0.040223
RC21           0.258775      0.258996      0.086091      0.082447
G2RC           0.128582      0.181458      0.015909      0.015617
BH76RC         0.123042      0.140369      0.058968      0.057338
FH51           0.257048      0.346464      0.026653      0.026834
TAUT15         0.294034      0.413574       0.06958      0.069453
DC13           0.316467      0.397878      0.019958      0.019322
MB16_43        0.452557      0.536502      0.093626      0.086338
DARC           0.327058      0.443827      0.019769      0.019082
RSE43          0.163501      0.233363      0.034588      0.033645
BSR36          0.394158      0.495755      0.001368      0.001683
CDIE20         0.286508      0.360334      0.042411      0.043548
ISO34          0.219719      0.298766      0.026503      0.026941
PArel          0.408186      0.599826      0.079765      0.079046
BH76           0.123042      0.140369      0.058968      0.057338
BHPERI         0.254995      0.326923      0.031686      0.029987
BHDIV10        0.275189       0.36167      0.049554      0.049067
INV24          0.621036      0.784023      0.032306      0.027518
BHROT27         0.22539      0.303042      0.019566      0.018507
PX13           0.164134      0.278622      0.012696       0.01315
WCPT18         0.159023      0.224175      0.062524      0.057861
RG18           0.138059      0.205868      0.001946      0.002641
ADIM6          0.340269      0.433935      0.000132       0.00024
S22            0.296958      0.405269      0.023691      0.024365
S66            0.251784      0.347674      0.024129      0.025355
WATER27        0.320629      0.547381      0.031619      0.033217
CARBHB12       0.141083      0.195383        0.0334      0.036954
PNICO23         0.17403      0.233505       0.02296      0.023517
HAL59          0.329072      0.412781      0.038054      0.036969
AHB21          0.077947      0.130018      0.031191      0.031459
CHB6           0.127645      0.160096      0.016397      0.019259
IL16           0.221024      0.335826       0.05056       0.05021
IDISP          0.652341      0.816236      0.000533      0.000619
ICONF          0.412438       0.53321      0.023287      0.022986
ACONF          0.277876      0.355414      0.001569      0.001781
Amino20x4      0.561279      0.806302      0.036696      0.037327
PCONF21        0.814801      1.184777      0.076052      0.077448
MCONF          0.726722      0.987576      0.048579      0.045477
SCONF          0.453376      0.725367       0.02528      0.024507
BUT14DIOL      0.250299      0.380059      0.020757       0.02199

MAE

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1       19.257894   9.561783  19.003664   9.285475  19.001926   9.339163
sub2        17.43575  17.941953  15.308423  15.070735   14.42948  14.694369
sub3        3.579974   5.232716   3.500591   5.229833   3.536558   5.240787
sub4        5.767958    7.73056   5.768147   7.837984   6.029571   8.125751
sub5        1.877407    1.63367   1.784048   1.215567   1.828415   1.260364

data_path              1513512                        ...    1428227  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE  17.132365   9.561783  16.843939  ...  18.897742
sub2           DONE  14.708169  17.941917  11.756054  ...  17.406645
sub3           DONE   3.884964   5.232716   3.871375  ...   4.339606
sub4           DONE   6.767833    7.73056   6.825807  ...   6.950488
sub5           DONE   1.537359    1.63367   1.091891  ...   1.427438

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        9.242701      DONE  18.138858   9.561783  17.739346   9.285406
sub2       12.824076      DONE  20.759914  17.941917  17.407069  15.070004
sub3         5.39491      DONE   4.394932   5.232716   4.194984   5.229844
sub4        8.966458      DONE   7.589782    7.73056   7.655925   7.838035
sub5        1.444903      DONE   1.608105    1.63367   1.167015   1.215535

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1       17.835187   9.339154      DONE
sub2       17.292773   14.69417      DONE
sub3        4.190525   5.240792      DONE
sub4        7.935859   8.125779      DONE
sub5        1.203425   1.260358      DONE

[5 rows x 35 columns]

wtmad_1

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1         9.04957    8.07025   8.723117   7.669073   8.643578   7.645286
sub2       10.373674    9.55389    9.58728   8.328621   9.429804   8.192154
sub3        5.589269    5.26824   5.511509   5.231204    5.58283   5.202779
sub4       16.212132  15.433344  11.448574   10.51843  11.386519  11.046215
sub5       16.809623  13.864114   16.57373  10.474968  17.341207  11.075081
summary    58.034268  52.189838  51.844211  42.222296  52.383938  43.161514

data_path              1513512                        ...    1428227  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE   8.356141    8.07025   7.968809  ...   9.594935
sub2           DONE   8.294925    9.55386   7.070922  ...   9.809317
sub3           DONE   3.892173    5.26824   3.880119  ...   5.069737
sub4           DONE  14.911936  15.433344   9.097337  ...   7.681217
sub5           DONE  13.017061  13.864114   9.665924  ...   13.02307
summary          --  48.472236  52.189807  37.683111  ...  45.178276

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        7.419066      DONE   9.237687    8.07025   8.672857   7.668977
sub2        7.363037      DONE   9.462007    9.55386   7.990014   8.328335
sub3        5.337975      DONE   4.762185    5.26824   4.501345   5.231209
sub4       12.271066      DONE  15.262996  15.433344   9.168287  10.517844
sub5       13.286521      DONE  13.873863  13.864114  10.288167  10.474792
summary    45.677664        --   52.59874  52.189807  40.620669  42.221158

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        8.622622   7.645266      DONE
sub2        8.014716   8.192048      DONE
sub3        4.434353   5.202781      DONE
sub4        9.707163   11.04597      DONE
sub5       10.853381  11.075089      DONE
summary    41.632235  43.161155        --

[6 rows x 35 columns]

wtmad_2

data_path    1424849                                                        \
Disp type         AI       DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        6.277319  5.178214   6.172154   5.078621   6.164673   5.079784
sub2        3.651251  3.877689   3.242347   3.272638   3.123791   3.196425
sub3        2.106216  2.614724   2.063461   2.616758   2.085172   2.626665
sub4        6.367586  6.373283   4.862385   4.749006   4.850364   4.934288
sub5        8.814703  6.885461   8.927999   5.505604   9.303028   5.735238
summary    27.217075  24.92937  25.268346  21.222626  25.527028    21.5724

data_path              1513512                        ...    1428227  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE    5.94125   5.178214   5.866193  ...   6.560451
sub2           DONE   3.561736   3.877663   2.940609  ...    3.25987
sub3           DONE   1.980558   2.614724   1.969746  ...    2.16422
sub4           DONE   6.171102   6.373283   4.261619  ...   3.854685
sub5           DONE   6.413561   6.885461   4.959104  ...   6.412078
summary          --  24.068207  24.929344  19.997271  ...  22.251304

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        5.034329      DONE   6.238372   5.178214   6.061484   5.078599
sub2        2.768723      DONE   3.731224   3.877663   3.037659   3.272491
sub3        2.712063      DONE   2.260037   2.614724   2.161454   2.616764
sub4        5.657324      DONE   6.361915   6.373283   4.359116     4.7488
sub5        7.087473      DONE   6.706495   6.885461   5.172812   5.505572
summary    23.259912        --  25.298042  24.929344  20.792525  21.222225

data_path
Disp type AI_D3ZERO DFT_D3ZERO Processed
sub1       6.034555   5.079779      DONE
sub2       3.014919   3.196361      DONE
sub3       2.159593   2.626668      DONE
sub4       4.578321   4.934221      DONE
sub5       5.380061   5.735267      DONE
summary    21.16745  21.572295        --

[6 rows x 35 columns]

Summary of Subset
MAE

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11      39.203149  10.586851  38.853509  10.151262  38.979171   10.36342
G21EA      30.220527  21.305991  30.220361  21.305565  30.218268  21.312705
G21IP       8.904852   4.048451   8.906119   4.050199   8.907709   4.051561
DIPCS10    15.645142   5.523671  15.642432   5.520994  15.670327   5.542695
PA26        5.547839   4.345868   5.734141   4.560076   5.766502   4.551628
SIE4x4      2.211917  19.742582   2.344023  19.931231   2.441618  19.995962
ALKBDE10   24.646299   7.329434  24.542879   7.226645  24.639264   7.322383
YBDE18     17.630289  11.624199  16.612456  10.271846  16.195151  10.131819
AL2X6       8.563034   8.882512   7.106967   6.977665   6.724394   6.882542
HEAVYSB11   13.67463   9.234585  12.807459   8.064498  12.613713   8.085818
NBPRC       4.818544   3.439714     4.2556   2.450943   3.931592   2.304782
ALK8        6.646991   5.808698   5.861682   4.687731   5.453268   4.528804
RC21         3.96282   3.461899   3.375288   4.132064   3.184984   4.320594
G2RC        7.470471   9.046991   7.521257   9.158742   7.542723   9.175369
BH76RC     19.743386  19.296993  19.769568   19.33919  19.808283  19.373516
FH51        4.914566   5.989218   4.693241   5.778463   4.710783    5.71526
TAUT15      2.047229   1.296414   2.056397   1.293938   2.107852   1.297826
DC13       13.168067  11.283548   12.51633   9.855071  12.284805    9.62655
MB16_43    70.165924  69.184937  62.479214  59.061723  58.869199   57.48081
DARC        6.458438   9.156028   4.510171   6.415948   3.932408   6.158905
RSE43       2.192437     2.1819   2.124583   2.076916   2.001252   1.920009
BSR36       7.722201  11.536749   5.448674   8.305676    5.06645   8.366058
CDIE20      1.389784    1.30392   1.382773   1.210818   1.403786   1.121308
ISO34       2.600893   2.542523   2.498489   2.371063   2.408512   2.308607
PArel       3.272731   2.150234   3.245339    2.11164   3.267522   2.163034
BH76        5.081367   8.001229   5.039622   8.263441   5.077368   8.336214
BHPERI       2.31662   2.267963   1.772904   1.473761   1.804448   1.476689
BHDIV10     2.804841   3.632748   2.755641   3.770441   2.683666   3.713918
INV24       3.496892   2.365007   3.596044   1.874413   3.568984   1.786513
BHROT27      2.02935   0.460483   2.033646   0.457262   2.061739   0.452308
PX13        2.207445   9.108108   2.039994   9.347137   2.153157    9.19119
WCPT18      2.924216   6.897796   3.039895   7.316616   3.174801   7.391851
RG18        0.718153   0.639009   0.530815     0.4001   0.473066   0.375029
ADIM6       5.078231   4.538994   2.512195   1.504767   2.325509   1.475628
S22          3.25348    2.96243   2.400718   1.818909   2.450278   1.921899
S66         2.719507   2.650196    1.70671   1.613102   1.701413   1.728748
WATER27    26.776433  44.026732  30.374405  48.436778  32.080143  49.886845
CARBHB12    1.107515   1.225261    0.93317   1.720435   0.849189   1.838808
PNICO23     1.247076   1.360456   0.989045    1.11031    1.09178   1.251345
HAL59        2.16396   1.760779   1.907658    1.44248   1.998212   1.549255
AHB21       6.674573   8.209303   6.876886   8.591839   7.042015   8.737606
CHB6        5.328572   4.975051   5.327903   5.211979   5.140394   5.355778
IL16        7.734363   8.085039   8.889882   9.542067   9.668163  10.191702
IDISP      14.868039  14.656005  10.125663   8.360211   9.397027   8.255014
ICONF       0.939276   0.436156   0.899487   0.401956    0.84748   0.496735
ACONF       3.231744   0.870997   2.996062   0.444413   2.945497   0.414074
Amino20x4   1.327476   0.667886    1.30662   0.588023   1.325975   0.630334
PCONF21     1.393949   1.543614   1.871713   0.774716   2.345268   0.892306
MCONF        1.39839   1.627101   1.178519   0.355213   1.229222   0.400263
SCONF       1.872296   2.585236   2.059643   2.886978   2.282729   3.109879
BUT14DIOL   1.797762     1.8947   1.934374   2.092655   1.957091   2.090972

data_path              1513512                        ...    1428227  \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11          DONE  31.746268  10.586851  31.222326  ...  36.497734
G21EA          DONE  29.301594  21.305991  29.301452  ...  29.915815
G21IP          DONE   10.11137   4.048451   10.11332  ...   9.257032
DIPCS10        DONE  16.424501   5.523671  16.419526  ...  15.911524
PA26           DONE   6.875101   4.345868   7.140102  ...   5.990763
SIE4x4         DONE  16.852721  19.742582  17.054686  ...  16.516065
ALKBDE10       DONE  13.185359   7.329434  13.069952  ...   19.09311
YBDE18         DONE  13.820948  11.624199  12.493726  ...   15.33316
AL2X6          DONE   4.731746   8.882512   2.666276  ...   8.663242
HEAVYSB11      DONE  10.645184   9.234585   9.363369  ...   8.587563
NBPRC          DONE   5.352028   3.439714   4.056245  ...   5.163514
ALK8           DONE   8.102949   5.808698   6.851216  ...   6.113501
RC21           DONE   3.057812   3.461899   3.657592  ...   4.505824
G2RC           DONE   7.952702   9.046991   8.201393  ...  10.294364
BH76RC         DONE  19.355525  19.296993  19.412797  ...  19.141948
FH51           DONE   5.727293   5.989218   5.675632  ...   5.153155
TAUT15         DONE   0.875614   1.296414   0.943637  ...   2.052713
DC13           DONE   8.919642  11.283548   7.471282  ...  14.118532
MB16_43        DONE  54.832709  69.184937  44.292718  ...  70.790381
DARC           DONE   4.358444   9.156028   2.196937  ...   8.844231
RSE43          DONE   1.717782     2.1819   1.630825  ...   1.484108
BSR36          DONE  12.914255  11.536538   9.458357  ...   7.132184
CDIE20         DONE   0.970932    1.30392    0.85857  ...   0.805209
ISO34          DONE   1.997863   2.542523   1.851216  ...   2.461353
PArel          DONE   2.188354   2.150234   2.134414  ...   3.361222
BH76           DONE   5.922339   8.001229    6.12313  ...   5.277559
BHPERI         DONE   2.170312   2.267963   1.289184  ...   4.089614
BHDIV10        DONE   2.310487   3.632748   2.640132  ...   4.073214
INV24          DONE   2.857125   2.365007   2.447942  ...   5.432499
BHROT27        DONE   0.463495   0.460483    0.45894  ...   0.751112
PX13           DONE    5.06662   9.108108   5.330408  ...   4.161553
WCPT18         DONE   4.283373   6.897796   4.740637  ...   4.942601
RG18           DONE   0.700851   0.639009   0.415244  ...   0.323015
ADIM6          DONE   4.742051   4.538994   1.557116  ...   0.341558
S22            DONE   2.934532    2.96243   1.586312  ...   1.457888
S66            DONE   2.593402   2.650196   1.408507  ...   1.387701
WATER27        DONE  37.419702  44.026732   42.15435  ...  42.247404
CARBHB12       DONE   0.817391   1.225261   0.958295  ...   0.951429
PNICO23        DONE   1.184973   1.360456   0.921903  ...   1.202401
HAL59          DONE   1.774763   1.760779   1.403155  ...   0.883862
AHB21          DONE   7.002713   8.209303   7.417177  ...   7.161423
CHB6           DONE    5.13126   4.975051   5.100949  ...   6.486975
IL16           DONE   6.757143   8.085039     8.3183  ...   11.41698
IDISP          DONE  14.569792  14.656005   7.869856  ...   8.259001
ICONF          DONE   0.448983   0.436156   0.468699  ...   0.891858
ACONF          DONE   0.995228   0.870997   0.536139  ...   0.285265
Amino20x4      DONE   0.743373   0.667886   0.583808  ...    0.61408
PCONF21        DONE   1.477625   1.543614   0.846878  ...   1.573988
MCONF          DONE   1.736673   1.627101   0.402755  ...   1.171272
SCONF          DONE   2.130031   2.585236   2.467438  ...   3.132433
BUT14DIOL      DONE   1.424756     1.8947   1.640035  ...   1.923661

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11      10.256536      DONE  34.415077  10.586851  33.844964  10.151144
G21EA      21.315596      DONE  28.962199  21.305991  28.962079  21.305565
G21IP        4.05323      DONE   9.529019   4.048451   9.531145   4.050199
DIPCS10     5.556586      DONE  16.481006   5.523671    16.4754   5.520993
PA26        4.683908      DONE   6.717763   4.345868   6.995094   4.560123
SIE4x4     20.173993      DONE  16.323996  19.742582  16.538067  19.931267
ALKBDE10    7.319739      DONE  14.757686   7.329434  14.630131   7.226613
YBDE18      9.444002      DONE  15.313892  11.624199  13.884726  10.271525
AL2X6       5.608575      DONE   7.798052   8.882512   5.583912   6.977239
HEAVYSB11   7.465703      DONE  12.432549   9.234585  11.045819   8.064204
NBPRC       1.829803      DONE   6.522037   3.439714   5.222796   2.450766
ALK8        3.878489      DONE   8.818751   5.808698   7.443432   4.687396
RC21         4.81048      DONE   3.304558   3.461899   3.434897   4.132208
G2RC        9.273589      DONE   8.074109   9.046991   8.158827   9.158781
BH76RC     19.413114      DONE  19.539952  19.296993  19.576901  19.339198
FH51        5.641316      DONE   5.296232   5.989218    4.86415   5.778426
TAUT15      1.274044      DONE   1.301403   1.296414   1.243818    1.29394
DC13        8.761089      DONE  12.687957  11.283548   10.80996   9.854712
MB16_43    51.053617      DONE  83.176654  69.184937  71.316559   59.05909
DARC        4.245588      DONE  11.003814   9.156028   7.572477   6.415361
RSE43        1.77444      DONE   1.709309     2.1819   1.617139   2.076896
BSR36       6.214675      DONE  11.561878  11.536538   7.901199   8.304863
CDIE20      1.047213      DONE   1.210025    1.30392   1.106607   1.210796
ISO34       2.183769      DONE   2.247553   2.542523     2.0457    2.37102
PArel        2.15453      DONE   1.929358   2.150234   1.859586   2.111633
BH76        8.530846      DONE   5.889439   8.001229   6.086175   8.263501
BHPERI      2.110186      DONE    5.26577   2.267963   3.302502   1.473645
BHDIV10     3.741546      DONE   3.134586   3.632748   2.954936   3.770481
INV24       1.451305      DONE   3.409584   2.365007   2.860737   1.874314
BHROT27     0.457442      DONE   0.673959   0.460483   0.663097   0.457261
PX13        9.285942      DONE   4.679444   9.108108   4.966369   9.347203
WCPT18      7.671577      DONE   4.216887   6.897796    4.70773   7.316713
RG18        0.410255      DONE   0.688193   0.639009   0.386792   0.400053
ADIM6       0.910858      DONE   4.823284   4.538994   1.505646   1.504356
S22         2.416839      DONE   2.974107    2.96243   1.509354   1.818753
S66         2.314019      DONE   2.648896   2.650196   1.434985   1.612988
WATER27    54.287559      DONE  44.153026  44.026732  49.140279   48.43752
CARBHB12    2.315971      DONE   0.837242   1.225261   1.046056   1.720536
PNICO23     1.267681      DONE   1.401335   1.360456   1.078705   1.110271
HAL59       1.752045      DONE   1.639404   1.760779   1.239873   1.442473
AHB21       9.050001      DONE   7.352848   8.209303   7.796733   8.591924
CHB6        5.478892      DONE   5.295341   4.975051   5.255817   5.212068
IL16       11.473934      DONE   7.048687   8.085039   8.704591   9.542346
IDISP       4.249502      DONE  16.207441  14.656005    9.14309   8.359123
ICONF       0.536715      DONE   0.397144   0.436156   0.385554   0.401952
ACONF       0.065911      DONE   1.132038   0.870997   0.643486   0.444326
Amino20x4   0.705373      DONE   0.793819   0.667886     0.6437    0.58802
PCONF21     2.203882      DONE   1.635033   1.543614   0.728337   0.774755
MCONF       1.018851      DONE   1.649602   1.627101    0.45717   0.355108
SCONF       3.394533      DONE   2.442466   2.585236   2.798669   2.887059
BUT14DIOL   2.279001      DONE   1.428245     1.8947   1.659308   2.092702

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
W4_11      34.162306   10.36341      DONE
G21EA      28.959653  21.312706      DONE
G21IP       9.532291   4.051561      DONE
DIPCS10    16.510042   5.542696      DONE
PA26        6.971877   4.551639      DONE
SIE4x4     16.597106  19.995976      DONE
ALKBDE10   14.750227   7.322383      DONE
YBDE18     13.890781  10.131759      DONE
AL2X6       5.651583   6.882439      DONE
HEAVYSB11   11.20496   8.085762      DONE
NBPRC       5.213644   2.304739      DONE
ALK8        7.443623   4.528744      DONE
RC21        3.478746   4.320638      DONE
G2RC        8.157274   9.175377      DONE
BH76RC     19.603206  19.373519      DONE
FH51        4.787565   5.715248      DONE
TAUT15      1.111007   1.297824      DONE
DC13       10.916319   9.626477      DONE
MB16_43    70.719383  57.480253      DONE
DARC        7.630691   6.158752      DONE
RSE43       1.480512   1.919997      DONE
BSR36       8.117737   8.365649      DONE
CDIE20      1.016014   1.121299      DONE
ISO34       2.006697   2.308598      DONE
PArel       1.963529   2.163033      DONE
BH76        6.158749   8.336229      DONE
BHPERI      3.154206   1.476691      DONE
BHDIV10     2.894198    3.71392      DONE
INV24       2.847189   1.786483      DONE
BHROT27     0.642616   0.452308      DONE
PX13        4.763413    9.19119      DONE
WCPT18       4.79656   7.391874      DONE
RG18        0.377177   0.375016      DONE
ADIM6       1.493905   1.475431      DONE
S22         1.639456    1.92184      DONE
S66         1.557621   1.728707      DONE
WATER27    50.561515  49.887195      DONE
CARBHB12    1.125654   1.838845      DONE
PNICO23     1.243885   1.251342      DONE
HAL59       1.341281   1.549253      DONE
AHB21       7.917183   8.737631      DONE
CHB6        5.084724   5.355792      DONE
IL16        9.309436  10.191812      DONE
IDISP       9.280843   8.254636      DONE
ICONF       0.362862   0.496741      DONE
ACONF       0.631953   0.414044      DONE
Amino20x4   0.659857   0.630339      DONE
PCONF21     0.970758   0.892365      DONE
MCONF        0.48449   0.400228      DONE
SCONF       3.001002   3.109906      DONE
BUT14DIOL   1.643699   2.090985      DONE

[51 rows x 35 columns]

In [1]:
i_reaction

NameError: name 'i_reaction' is not defined