In [2]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate_hkqai").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict_ccpvdz"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if "modified_dft_d3bj" in data.columns:
            data_dft_d3bj = data["modified_dft_d3bj"].to_numpy() * 627.5094733748099
            # data_dft_d3bj = data_d3bj
        else:
            data_dft_d3bj = data_d3bj
        if "modified_dft_d3zero" in data.columns:
            data_dft_d3zero = data["modified_dft_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3zero = data_d3zero

        if "modified_ai_d3bj" in data.columns:
            data_ai_d3bj = data["modified_ai_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3bj = data_d3bj
        if "modified_ai_d3zero" in data.columns:
            data_ai_d3zero = data["modified_ai_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_ai = np.argsort(data_subset[name_subset]["ai"])[
                    ::-1
                ][:5]
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ][:5]
                for i in range(len(argsort_atomic_energy_ai)):
                    i_reaction_name = data_subset[name_subset]["name"][
                        argsort_atomic_energy_ai[i]
                    ]
                    i_reaction = json_data[f"reaction-{i_subset}"][i_reaction_name]
                    print(
                        f"Top {i+1} AI: {data_subset[name_subset]['ai'][argsort_atomic_energy_ai[i]]} kcal/mol, {i_reaction_name} in {name_subset}",
                    )
                    systems_list = i_reaction["systems"]
                    stoichiometry_list = i_reaction["stoichiometry"]
                    for j in range(len(systems_list)):
                        mole_name = (
                            systems_list[j]
                            if i_subset == "BH76RC"
                            else f"{i_subset}-{systems_list[j]}"
                        )
                        stoichiometry = int(stoichiometry_list[j])
                        if mole_name in json_data:
                            if isinstance(json_data[mole_name], str):
                                mole_name = json_data[mole_name]
                        print(f"  {stoichiometry} * {mole_name}", end="")
                        col = np.where(data_name == mole_name)[0]
                        if col.size == 1:
                            error_energy_ai = data_scf[col[0]] - data_cc[col[0]]
                            print(f"  {stoichiometry} * {error_energy_ai}", end="")
                    print()

                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["ai"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["ai"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {data_path_name}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

# print("Summary")
# display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# # save summary to csv with date
# df_summary_subset_ele.to_csv(f"../validate/df_summary_subset_ele_{date}.csv")
# df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
# mean_subset.to_csv(f"../validate/mean_subset_{date}.csv")
# wtmad_1_subset.to_csv(f"../validate/wtmad_1_subset_{date}.csv")
# wtmad_2_subset.to_csv(f"../validate/wtmad_2_subset_{date}.csv")
# # save summary to excel with date
# df_summary_subset_ele.to_excel(f"../validate/df_summary_subset_ele_{date}.xlsx")
# df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")
# mean_subset.to_excel(f"../validate/mean_subset_{date}.xlsx")
# wtmad_1_subset.to_excel(f"../validate/wtmad_1_subset_{date}.xlsx")
# wtmad_2_subset.to_excel(f"../validate/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
Top 1 AI: 34.233055776202036 kcal/mol, 11 in 4192002_W4_11
  -1 * W4_11-b2h6  -1 * 10.695407580642495  2 * W4_11-b  2 * -0.022044754356102203  6 * W4_11-h  6 * -3.915593114474518
Top 2 AI: 33.56038100627484 kcal/mol, 131 in 4192002_W4_11
  -1 * W4_11-oclo  -1 * -33.21436206129147  2 * W4_11-o  2 * -0.048638512183970306  1 * W4_11-cl  1 * 0.4432959693367593
Top 3 AI: 32.95333680184558 kcal/mol, 107 in 4192002_W4_11
  -1 * W4_11-so3  -1 * -34.15919210616266  1 * W4_11-s  1 * -1.0599397677578963  3 * W4_11-o  3 * -0.048638512183970306
Top 4 AI: 30.548958831859636 kcal/mol, 136 in 4192002_W4_11
  -1 * W4_11-foof  -1 * -29.62172775104409  2 * W4_11-f  2 * 0.512254052591743  2 * W4_11-o  2 * -0.048638512183970306
Top 5 AI: 28.770819377125008 kcal/mol, 133 in 4192002_W4_11
  -1 * W4_11-b2  -1 * 28.726729868412804  2 * W4_11-b  2 * -0.022044754356102203
Top 1 DFT: 64.94188301078975 kcal/mol
Top 2 DFT: 64.82774996492662 kcal/mol
Top 3 DFT: 58.786665937819635 kcal/mol
Top 4 DFT: 55.62329130060971 kcal/mol
Top 5 DFT: 55.14181469601294 kcal/mol
Top 1 AI: 8.171066423485172 kcal/mol, 20 in 4192002_G21EA
  1 * G21EA-EA_21n  1 * -3.5698540063749533  -1 * G21EA-EA_21  -1 * -11.740920429860125
Top 2 AI: 2.8581798295490444 kcal/mol, 24 in 4192002_G21EA
  1 * G21EA-EA_25n  1 * -5.795896918163635  -1 * G21EA-EA_25  -1 * -8.65407674771268
Top 3 AI: 2.140416194597492 kcal/mol, 19 in 4192002_G21EA
  1 * G21EA-EA_20n  1 * -8.97472170398396  -1 * G21EA-EA_20  -1 * -11.115137898581452
Top 4 AI: 2.094123193528503 kcal/mol, 23 in 4192002_G21EA
  1 * G21EA-EA_24n  1 * -9.589558984851465  -1 * G21EA-EA_24  -1 * -11.683682178379968
Top 5 AI: 2.0693354823451955 kcal/mol, 14 in 4192002_G21EA
  1 * G21EA-EA_15n  1 * -0.10268240817822516  -1 * G21EA-EA_15  -1 * -2.1720178905234206
Top 1 DFT: 17.922119285416557 kcal/mol
Top 2 DFT: 14.542179432406556 kcal/mol
Top 3 DFT: 13.795776374754496 kcal/mol
Top 4 DFT: 13.585515154067252 kcal/mol
Top 5 DFT: 13.248639462894062 kcal/mol
Top 1 AI: 13.473203138564713 kcal/mol, 30 in 4192002_G21IP
  1 * G21IP-IP_75  1 * 4.4543074414687  -1 * G21IP-37  -1 * -9.018895697096013
Top 2 AI: 7.247384939226322 kcal/mol, 34 in 4192002_G21IP
  1 * G21IP-IP_79  1 * -13.929160589643288  -1 * G21IP-51  -1 * -6.6817756504169665
Top 3 AI: 7.05655992073298 kcal/mol, 26 in 4192002_G21IP
  1 * G21IP-IP_71  1 * -4.5203748669082415  -1 * G21IP-25  -1 * 2.536185053824738
Top 4 AI: 5.4549287256086245 kcal/mol, 33 in 4192002_G21IP
  1 * G21IP-IP_78  1 * -11.292475020280108  -1 * G21IP-45  -1 * -5.837546294671483
Top 5 AI: 4.80946242545906 kcal/mol, 28 in 4192002_G21IP
  1 * G21IP-IP_73  1 * -6.744253215612844  -1 * G21IP-30  -1 * -1.9347907901537837
Top 1 DFT: 24.652048565418227 kcal/mol
Top 2 DFT: 19.50703940328094 kcal/mol
Top 3 DFT: 16.821335594599077 kcal/mol
Top 4 DFT: 16.4504761478438 kcal/mol
Top 5 DFT: 16.230148226983147 kcal/mol
Top 1 AI: 15.460189500307024 kcal/mol, 2 in 4192002_DIPCS10
  -1 * DIPCS10-c2h4  -1 * 2.010804618621478  1 * DIPCS10-c2h4_2+  1 * -13.449384881685546
Top 2 AI: 6.012228251958732 kcal/mol, 0 in 4192002_DIPCS10
  -1 * DIPCS10-c4h4  -1 * -5.4484415124316  1 * DIPCS10-c4h4_2+  1 * -11.460669764390332
Top 3 AI: 2.7711736716446467 kcal/mol, 3 in 4192002_DIPCS10
  -1 * DIPCS10-n2h2  -1 * -2.3746847840520786  1 * DIPCS10-n2h2_2+  1 * 0.39648888759256806
Top 4 AI: 1.582735774019966 kcal/mol, 5 in 4192002_DIPCS10
  -1 * DIPCS10-ch2o  -1 * -1.1501957799337106  1 * DIPCS10-ch2o_2+  1 * 0.4325399940862553
Top 5 AI: 1.1418906886829063 kcal/mol, 1 in 4192002_DIPCS10
  -1 * DIPCS10-c2h6  -1 * -4.918523450229259  1 * DIPCS10-c2h6_2+  1 * -6.060414138912165
Top 1 DFT: 21.238722962967586 kcal/mol
Top 2 DFT: 18.410172816045815 kcal/mol
Top 3 DFT: 17.180242111804546 kcal/mol
Top 4 DFT: 16.016684862523107 kcal/mol
Top 5 DFT: 13.03569706963026 kcal/mol
Top 1 AI: 7.4664896390168 kcal/mol, 21 in 4192002_PA26
  1 * PA26-phosphapyrrol  1 * -15.165877843566705  -1 * PA26-phosphapyrrolp  -1 * -7.699388204549905
Top 2 AI: 5.576031286356738 kcal/mol, 15 in 4192002_PA26
  1 * PA26-gly  1 * -18.998761300521437  -1 * PA26-glyp  -1 * -13.4227300141647
Top 3 AI: 4.993233620785759 kcal/mol, 13 in 4192002_PA26
  1 * PA26-ethanol  1 * -6.700793729367433  -1 * PA26-ethanolp  -1 * -1.7075601085816743
Top 4 AI: 4.96596057061106 kcal/mol, 20 in 4192002_PA26
  1 * PA26-cys  1 * -21.156662919791415  -1 * PA26-cysp  -1 * -16.190702349180356
Top 5 AI: 4.5017280730680795 kcal/mol, 6 in 4192002_PA26
  1 * PA26-c2h2  1 * 2.5225297954457346  -1 * PA26-c2h2p  -1 * -1.979198277622345
Top 1 DFT: 5.496021041501081 kcal/mol
Top 2 DFT: 3.952208415896166 kcal/mol
Top 3 DFT: 3.843404227809515 kcal/mol
Top 4 DFT: 3.7666994354804046 kcal/mol
Top 5 DFT: 3.7500070057285484 kcal/mol
Top 1 AI: 38.60453798495928 kcal/mol, 7 in 4192002_SIE4x4
  1 * SIE4x4-he  1 * 0.13400364049243763  1 * SIE4x4-he+  1 * -0.047795356385222476  -1 * SIE4x4-he2+_1.75  -1 * -38.518329700852064
Top 2 AI: 37.30055192341388 kcal/mol, 15 in 4192002_SIE4x4
  1 * SIE4x4-h2o  1 * -0.002486345387296751  1 * SIE4x4-h2o+  1 * 0.30784362356644124  -1 * SIE4x4-h2o2+_1.75  -1 * -36.99519464523473
Top 3 AI: 32.2132681289213 kcal/mol, 6 in 4192002_SIE4x4
  1 * SIE4x4-he  1 * 0.13400364049243763  1 * SIE4x4-he+  1 * -0.047795356385222476  -1 * SIE4x4-he2+_1.5  -1 * -32.127059844814084
Top 4 AI: 31.90019662224222 kcal/mol, 14 in 4192002_SIE4x4
  1 * SIE4x4-h2o  1 * -0.002486345387296751  1 * SIE4x4-h2o+  1 * 0.30784362356644124  -1 * SIE4x4-h2o2+_1.5  -1 * -31.594839344063075
Top 5 AI: 26.470854646977386 kcal/mol, 11 in 4192002_SIE4x4
  1 * SIE4x4-nh3  1 * -0.28398965445376234  1 * SIE4x4-nh3+  1 * -0.10635923962399829  -1 * SIE4x4-nh32+_1.75  -1 * -26.861203541062423
Top 1 DFT: 42.48945061229006 kcal/mol
Top 2 DFT: 36.3825565542179 kcal/mol
Top 3 DFT: 34.02966520233895 kcal/mol
Top 4 DFT: 29.669328280849186 kcal/mol
Top 5 DFT: 29.26023051775701 kcal/mol
Warning: ALKBDE10-kf not found in data json, ERROR
Top 1 AI: 48.886625298713625 kcal/mol, 2 in 4192002_ALKBDE10
  -1 * ALKBDE10-cao  -1 * -49.09148696163902  1 * ALKBDE10-ca  1 * -0.2574877658043988  1 * ALKBDE10-o  1 * 0.052626102879003156
Top 2 AI: 18.5573229095462 kcal/mol, 1 in 4192002_ALKBDE10
  -1 * ALKBDE10-beo  -1 * -18.51310414764157  1 * ALKBDE10-be  1 * -0.008407340972553357  1 * ALKBDE10-o  1 * 0.052626102879003156
Top 3 AI: 15.747957727442554 kcal/mol, 7 in 4192002_ALKBDE10
  -1 * ALKBDE10-mgo  -1 * -15.742837702855468  1 * ALKBDE10-mg  1 * -0.04750607829191722  1 * ALKBDE10-o  1 * 0.052626102879003156
Top 4 AI: 11.581285355161526 kcal/mol, 0 in 4192002_ALKBDE10
  -1 * ALKBDE10-bef  -1 * -11.345795969245955  1 * ALKBDE10-be  1 * -0.008407340972553357  1 * ALKBDE10-f  1 * 0.24389672688266728
Top 5 AI: 9.810460359913122 kcal/mol, 9 in 4192002_ALKBDE10
  -1 * ALKBDE10-nao  -1 * -9.728318798006512  1 * ALKBDE10-na  1 * 0.029515459027606994  1 * ALKBDE10-o  1 * 0.052626102879003156
Top 1 DFT: 42.20618001303956 kcal/mol
Top 2 DFT: 26.422307972352428 kcal/mol
Top 3 DFT: 19.54640414734604 kcal/mol
Top 4 DFT: 16.150239486240025 kcal/mol
Top 5 DFT: 15.581684817676432 kcal/mol
Top 1 AI: 27.089816761515976 kcal/mol, 10 in 4192002_YBDE18
  -1 * YBDE18-nme3-cbh22  -1 * 10.024448920739815  1 * YBDE18-nme3  1 * -5.159948184518726  1 * YBDE18-cbh22  1 * -11.905419656257436
Top 2 AI: 15.356523660309904 kcal/mol, 16 in 4192002_YBDE18
  -1 * YBDE18-pme3-cbh22  -1 * -7.26779409131268  1 * YBDE18-pme3  1 * -10.718898095365148  1 * YBDE18-cbh22  1 * -11.905419656257436
Top 3 AI: 11.31673021271854 kcal/mol, 4 in 4192002_YBDE18
  -1 * YBDE18-me2s-cbh22  -1 * -5.353665632661432  1 * YBDE18-me2s  1 * -4.764976189122535  1 * YBDE18-cbh22  1 * -11.905419656257436
Top 4 AI: 11.303539518088655 kcal/mol, 11 in 4192002_YBDE18
  -1 * YBDE18-nme3-ch2  -1 * 5.591403744620038  1 * YBDE18-nme3  1 * -5.159948184518726  1 * YBDE18-ch2  1 * -0.5521875889498915
Top 5 AI: 10.888587093802926 kcal/mol, 12 in 4192002_YBDE18
  -1 * YBDE18-pf3-cbh22  -1 * -29.081412714673206  1 * YBDE18-pf3  1 * -28.064580152218696  1 * YBDE18-cbh22  1 * -11.905419656257436
Top 1 DFT: 16.44728826175924 kcal/mol
Top 2 DFT: 12.740130906568083 kcal/mol
Top 3 DFT: 10.883027330586629 kcal/mol
Top 4 DFT: 10.488881110526563 kcal/mol
Top 5 DFT: 10.40475183620947 kcal/mol
Top 1 AI: 5.116179389413446 kcal/mol, 1 in 4192002_AL2X6
  -1 * AL2X6-al2f6  -1 * -28.85581202758476  2 * AL2X6-alf3  2 * -16.985995708499104
Top 2 AI: 4.917499433038756 kcal/mol, 5 in 4192002_AL2X6
  -1 * AL2X6-al2me6  -1 * -14.637233202462085  2 * AL2X6-alme3  2 * -9.77736631775042
Top 3 AI: 3.0240788821247406 kcal/mol, 4 in 4192002_AL2X6
  -1 * AL2X6-al2me5  -1 * -13.663670422509313  1 * AL2X6-alme2  1 * -6.910382986883633  1 * AL2X6-alme3  1 * -9.77736631775042
Top 4 AI: 1.2639633192447945 kcal/mol, 3 in 4192002_AL2X6
  -1 * AL2X6-al2me4  -1 * -12.556802654522471  2 * AL2X6-alme2  2 * -6.910382986883633
Top 5 AI: 0.726138221565634 kcal/mol, 0 in 4192002_AL2X6
  -1 * AL2X6-al2h6  -1 * -0.9405667927931063  2 * AL2X6-alh3  2 * -0.10721428561373614
Top 1 DFT: 9.084031574253459 kcal/mol
Top 2 DFT: 7.0848077459668275 kcal/mol
Top 3 DFT: 5.3300173038151115 kcal/mol
Top 4 DFT: 5.070575412944891 kcal/mol
Top 5 DFT: 4.9637361988425255 kcal/mol
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Top 1 AI: 9.66242031659931 kcal/mol, 10 in 4192002_HEAVYSB11
  2 * HEAVYSB11-br  2 * 0.0026890262961387634  -1 * HEAVYSB11-br2  -1 * -9.657042264007032
Top 2 AI: 8.87300589401275 kcal/mol, 4 in 4192002_HEAVYSB11
  2 * HEAVYSB11-seh  2 * -0.5074136063922197  -1 * HEAVYSB11-h2se2  -1 * -9.887833106797189
Top 3 AI: 6.567417899495922 kcal/mol, 9 in 4192002_HEAVYSB11
  2 * HEAVYSB11-cl  2 * 0.4432563533191569  -1 * HEAVYSB11-cl2  -1 * -5.680905192857608
Top 4 AI: 5.45264328509802 kcal/mol, 3 in 4192002_HEAVYSB11
  2 * HEAVYSB11-sh  2 * -1.1053401649114676  -1 * HEAVYSB11-h2s2  -1 * -7.663323614920955
Top 5 AI: 3.4238247514003888 kcal/mol, 6 in 4192002_HEAVYSB11
  2 * HEAVYSB11-pme2  2 * -11.347167792264372  -1 * HEAVYSB11-p2me4  -1 * -19.270510833128355
Top 1 DFT: 10.68985605717171 kcal/mol
Top 2 DFT: 9.494120202027261 kcal/mol
Top 3 DFT: 7.114256684028078 kcal/mol
Top 4 DFT: 6.325384678319097 kcal/mol
Top 5 DFT: 1.569642293266952 kcal/mol
Top 1 AI: 11.166173819161486 kcal/mol, 10 in 4192002_NBPRC
  1 * NBPRC-BCl3PMe3  1 * -2.5224326997995377  -1 * NBPRC-BCl3  -1 * -2.3471621450735256  -1 * NBPRC-PMe3  -1 * -11.341444373887498
Top 2 AI: 8.897053901164327 kcal/mol, 5 in 4192002_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * -1.2586424243127112  1 * NBPRC-ch  1 * 5.121126628248021
Top 3 AI: 6.543003621769117 kcal/mol, 9 in 4192002_NBPRC
  1 * NBPRC-K_F  1 * -16.50934029655764  -1 * NBPRC-BF3PMe3  -1 * -26.031682466098573  -1 * NBPRC-H2  -1 * 2.9793385477718175
Top 4 AI: 6.523895134712802 kcal/mol, 3 in 4192002_NBPRC
  -2 * NBPRC-nh2-bh2  -2 * -1.2586424243127112  1 * NBPRC-cbut  1 * 4.00661028608738
Top 5 AI: 6.43747518237285 kcal/mol, 2 in 4192002_NBPRC
  -1 * NBPRC-nh2-bh2  -1 * -1.2586424243127112  1 * NBPRC-nh-bh  1 * 2.1809341788612073  1 * NBPRC-h2  1 * 2.9978985791989317
Top 1 DFT: 8.843319919425994 kcal/mol
Top 2 DFT: 4.25873367569875 kcal/mol
Top 3 DFT: 3.4078239038353786 kcal/mol
Top 4 DFT: 2.532460168497778 kcal/mol
Top 5 DFT: 2.2723810925637054 kcal/mol
Top 1 AI: 20.51011089934036 kcal/mol, 1 in 4192002_ALK8
  -1 * ALK8-na8  -1 * 24.60157099144999  4 * ALK8-na2  4 * 1.022865023027407
Top 2 AI: 12.042245613702107 kcal/mol, 2 in 4192002_ALK8
  -1 * ALK8-li4_me4  -1 * -4.627951320639113  4 * ALK8-li_me  4 * -4.167549233585305
Top 3 AI: 6.659940354900755 kcal/mol, 5 in 4192002_ALK8
  -1 * ALK8-li5_ch  -1 * -16.685053773224354  1 * ALK8-li4_c  1 * -10.878216111683287  1 * ALK8-li_h  1 * 0.8531026933596877
Top 4 AI: 5.698436286198557 kcal/mol, 0 in 4192002_ALK8
  -1 * ALK8-li8  -1 * 17.794977119025134  4 * ALK8-li2  4 * 3.024135208206644
Top 5 AI: 3.4844377767585684 kcal/mol, 6 in 4192002_ALK8
  -1 * ALK8-li2_ch2n_2  -1 * -15.178284429915948  2 * ALK8-li_ch2n  2 * -9.331361103337258
Top 1 DFT: 13.423444515326992 kcal/mol
Top 2 DFT: 13.339023275213549 kcal/mol
Top 3 DFT: 3.2870388831361197 kcal/mol
Top 4 DFT: 1.8348026665917132 kcal/mol
Top 5 DFT: 1.3258451606470771 kcal/mol
Top 1 AI: 16.05803418490541 kcal/mol, 17 in 4192002_RC21
  -1 * RC21-7e  -1 * -23.405987196572823  1 * RC21-7p5  1 * -8.653914028720465  1 * RC21-7p6  1 * 1.3059610170530505
Top 2 AI: 15.393690014010645 kcal/mol, 18 in 4192002_RC21
  -1 * RC21-8e  -1 * -10.513817400322296  1 * RC21-8p1  1 * 2.4790734828275163  1 * RC21-ethylene  1 * 2.4007991308608325
Top 3 AI: 13.397736266961147 kcal/mol, 15 in 4192002_RC21
  -1 * RC21-7e  -1 * -23.405987196572823  1 * RC21-7p1  1 * -9.983213640080066  1 * RC21-7p2  1 * -0.02503728953161044
Top 4 AI: 8.435471006239823 kcal/mol, 3 in 4192002_RC21
  -1 * RC21-2e  -1 * -9.383944800851168  1 * RC21-2p2  1 * -5.097639017141773  1 * RC21-2p3  1 * 4.149165222530428
Top 5 AI: 8.403721689101076 kcal/mol, 6 in 4192002_RC21
  -1 * RC21-3e  -1 * 1.8948272993147839  1 * RC21-3int2  1 * -6.508894389786292
Top 1 DFT: 14.185896344562934 kcal/mol
Top 2 DFT: 11.848156853782712 kcal/mol
Top 3 DFT: 9.843254908562812 kcal/mol
Top 4 DFT: 8.613347860442445 kcal/mol
Top 5 DFT: 7.032865641926037 kcal/mol
Top 1 AI: 17.044138431621832 kcal/mol, 17 in 4192002_G2RC
  -1 * G2RC-56  -1 * -26.409403913188726  -3 * G2RC-1  -3 * 2.979022792445221  1 * G2RC-21  1 * -0.35359958282788284  2 * G2RC-13  2 * -0.037298760675184894
Top 2 AI: 16.14390469249338 kcal/mol, 24 in 4192002_G2RC
  -1 * G2RC-23  -1 * 3.1027722644848836  -1 * G2RC-39  -1 * -5.9456785651127575  2 * G2RC-24  2 * -9.493405496556079
Top 3 AI: 15.280440424830886 kcal/mol, 12 in 4192002_G2RC
  -1 * G2RC-25  -1 * 2.517592730881006  -1 * G2RC-26  -1 * 2.5236650434089825  1 * G2RC-88  1 * -10.239182650548173
Top 4 AI: 14.585982393349695 kcal/mol, 0 in 4192002_G2RC
  -1 * G2RC-118  -1 * -20.149598958087154  1 * G2RC-117  1 * -5.526317804062273  1 * G2RC-13  1 * -0.037298760675184894
Top 5 AI: 14.276499416861043 kcal/mol, 20 in 4192002_G2RC
  -1 * G2RC-68  -1 * -16.487268005847  -1 * G2RC-1  -1 * 2.979022792445221  1 * G2RC-34  1 * 0.8055529641278554  1 * G2RC-13  1 * -0.037298760675184894
Top 1 DFT: 16.861372091829253 kcal/mol
Top 2 DFT: 13.550974861325813 kcal/mol
Top 3 DFT: 11.457349740527434 kcal/mol
Top 4 DFT: 10.800692827404418 kcal/mol
Top 5 DFT: 10.432011227676412 kcal/mol
Top 1 AI: 22.674393171531847 kcal/mol, BH76RC_1 in 4192002_BH76RC
  -1 * BH76-h  -1 * -3.915593114875776  -1 * BH76-n2o  -1 * -16.51744807459181  1 * BH76-oh  1 * 1.3200685217307182  1 * BH76-n2  1 * 0.9212834603240481
Top 2 AI: 11.03634861089813 kcal/mol, BH76RC_12 in 4192002_BH76RC
  -1 * BH76-ch3  -1 * -0.29212859247490996  -1 * BH76-c2h4  -1 * 2.4942653621692443  1 * BH76-c3h7  1 * -8.83421184119652
Top 3 AI: 10.372612350503914 kcal/mol, BH76RC_8 in 4192002_BH76RC
  -1 * BH76-hoch3fcomp2  -1 * -8.586821762786712  1 * BH76-hoch3fcomp1  1 * -18.959434113290627
Top 4 AI: 9.325158093168284 kcal/mol, BH76RC_3 in 4192002_BH76RC
  -1 * BH76-h  -1 * -3.915593114875776  -1 * BH76-f2  -1 * -5.913823035400128  1 * BH76-hf  1 * -0.701695151750755  1 * BH76-f  1 * 0.19743709463364212
Top 5 AI: 8.626180154446047 kcal/mol, BH76RC_6 in 4192002_BH76RC
  -1 * BH76-fch3clcomp1  -1 * -12.623320045531727  1 * BH76-fch3clcomp2  1 * -3.9971398910856806
Top 1 DFT: 16.943700659729075 kcal/mol
Top 2 DFT: 11.4192808540829 kcal/mol
Top 3 DFT: 9.908463760002633 kcal/mol
Top 4 DFT: 9.5446835977491 kcal/mol
Top 5 DFT: 7.421772861736827 kcal/mol
Top 1 AI: 26.68590135560953 kcal/mol, 5 in 4192002_FH51
  -1 * FH51-toluene  -1 * -4.981566329719499  -3 * FH51-H2  -3 * 3.044895688097654  1 * FH51-methylcyclohexane  1 * -22.53278062105528
Top 2 AI: 16.76563122239895 kcal/mol, 38 in 4192002_FH51
  1 * FH51-pentadiene  1 * -4.263269145201775  1 * FH51-ethene  1 * 1.5046779404874542  -1 * FH51-ax-methylcyclohexene  -1 * -19.524222427105997
Top 3 AI: 12.399107055243803 kcal/mol, 24 in 4192002_FH51
  -1 * FH51-methylpyridine  -1 * -7.542914406192722  -1 * FH51-H2  -1 * 3.044895688097654  1 * FH51-dimethylpyrrole  1 * -16.897125773335574
Top 4 AI: 11.97134014533367 kcal/mol, 26 in 4192002_FH51
  -1 * FH51-C3H7CN  -1 * -8.562186431809096  -1 * FH51-H2O  -1 * -0.31006608591997065  1 * FH51-C3H7CONH2  1 * -20.843592663062736
Top 5 AI: 11.20131625252543 kcal/mol, 49 in 4192002_FH51
  -1 * FH51-n-nonane  -1 * -28.42571827606298  1 * FH51-tetramethylpentane  1 * -17.22440202353755
Top 1 DFT: 14.376499545731349 kcal/mol
Top 2 DFT: 11.10615688978578 kcal/mol
Top 3 DFT: 10.966376306983875 kcal/mol
Top 4 DFT: 9.751064423559 kcal/mol
Top 5 DFT: 9.64041400255519 kcal/mol
Top 1 AI: 10.292027522082208 kcal/mol, 1 in 4192002_TAUT15
  -1 * TAUT15-2a  -1 * -16.85645559549448  1 * TAUT15-2b  1 * -6.564428073412273
Top 2 AI: 7.502294927689945 kcal/mol, 0 in 4192002_TAUT15
  -1 * TAUT15-1a  -1 * -19.029298558074515  1 * TAUT15-1b  1 * -11.52700363038457
Top 3 AI: 6.868454286683118 kcal/mol, 3 in 4192002_TAUT15
  -1 * TAUT15-3a  -1 * -15.719182973407442  1 * TAUT15-3c  1 * -8.850728686724324
Top 4 AI: 5.084938458807301 kcal/mol, 7 in 4192002_TAUT15
  -1 * TAUT15-5a  -1 * -20.373502734670183  1 * TAUT15-5c  1 * -25.458441193477483
Top 5 AI: 4.522724309354089 kcal/mol, 14 in 4192002_TAUT15
  -1 * TAUT15-10a  -1 * -8.805873779812828  1 * TAUT15-10b  1 * -13.328598089166917
Top 1 DFT: 7.5247652156685945 kcal/mol
Top 2 DFT: 6.618434203410288 kcal/mol
Top 3 DFT: 6.082770755718229 kcal/mol
Top 4 DFT: 3.889858042122796 kcal/mol
Top 5 DFT: 1.8469628894818015 kcal/mol
Top 1 AI: 52.285535492774216 kcal/mol, 7 in 4192002_DC13
  1 * DC13-be4  1 * -52.3191648566426  -4 * DC13-be  -4 * -0.008407340967096388
Top 2 AI: 47.33859369775746 kcal/mol, 9 in 4192002_DC13
  -1 * DC13-ISO_C8H8_1  -1 * 2.810415976069635  1 * DC13-ISO_C8H8_41  1 * -44.528177721687825
Top 3 AI: 36.039685111434665 kcal/mol, 4 in 4192002_DC13
  1 * DC13-ISO_E35  1 * -40.06392120860983  -1 * DC13-ISO_P35  -1 * -4.024236097175162
Top 4 AI: 22.518458964535967 kcal/mol, 5 in 4192002_DC13
  -1 * DC13-carbooxo2  -1 * -55.86388649686705  1 * DC13-carbooxo1  1 * -33.34542753233109
Top 5 AI: 19.039599809562787 kcal/mol, 1 in 4192002_DC13
  -1 * DC13-c20cage  -1 * -71.39537836657837  1 * DC13-c20bowl  1 * -52.35577855701558
Top 1 DFT: 37.447079584468156 kcal/mol
Top 2 DFT: 34.20446150796488 kcal/mol
Top 3 DFT: 19.887267829326447 kcal/mol
Top 4 DFT: 18.6525409417809 kcal/mol
Top 5 DFT: 11.921989963244414 kcal/mol
Top 1 AI: 42.67340337204223 kcal/mol, 136 in 1513512_W4_11
  -1 * W4_11-foof  -1 * -42.42863818787737  2 * W4_11-f  2 * 0.01452538870216813  2 * W4_11-o  2 * 0.10785720338026294
Top 2 AI: 33.313599174958654 kcal/mol, 116 in 1513512_W4_11
  -1 * W4_11-p4  -1 * -36.21119966742117  4 * W4_11-p  4 * -0.724400123115629
Top 3 AI: 32.14222127138055 kcal/mol, 41 in 1513512_W4_11
  -1 * W4_11-sif4  -1 * -31.815485039027408  1 * W4_11-si  1 * 0.268634677544469  4 * W4_11-f  4 * 0.01452538870216813
Top 4 AI: 31.444142822001595 kcal/mol, 131 in 1513512_W4_11
  -1 * W4_11-oclo  -1 * -31.287230808578897  2 * W4_11-o  2 * 0.10785720338026294  1 * W4_11-cl  1 * -0.05880239332327619
Top 5 AI: 27.658037785979104 kcal/mol, 134 in 1513512_W4_11
  -1 * W4_11-fo2  -1 * -27.42779799050186  1 * W4_11-f  1 * 0.01452538870216813  2 * W4_11-o  2 * 0.10785720338026294
Top 1 DFT: 64.94237074931152 kcal/mol
Top 2 DFT: 64.82739106187364 kcal/mol
Top 3 DFT: 58.7869441981602 kcal/mol
Top 4 DFT: 55.61715956105036 kcal/mol
Top 5 DFT: 55.142266292670456 kcal/mol
Top 1 AI: 9.665314415993635 kcal/mol, 23 in 1513512_G21EA
  1 * G21EA-EA_24n  1 * -1.4497629219549708  -1 * G21EA-EA_24  -1 * -11.115077337948605
Top 2 AI: 7.491658211423783 kcal/mol, 19 in 1513512_G21EA
  1 * G21EA-EA_20n  1 * -5.942427998306812  -1 * G21EA-EA_20  -1 * -13.434086209730594
Top 3 AI: 7.256941262050532 kcal/mol, 22 in 1513512_G21EA

data_path   4192002                                                       \
Disp type        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       7.397052  13.710737  7.705655  14.259581  7.454815  13.713677
sub2       7.949106   6.617683  11.14734   9.133989  8.647369   6.763003
sub3       5.404118   6.261376  6.312986   7.355579  5.999373   6.934991
sub4       3.857649   3.272197  4.840664    5.03074  4.815184   4.988172
sub5       1.653929   1.320811  1.187383   0.927486  1.103389   0.872124

data_path             1513512                        ...                       \
Disp type Processed        AI        DFT    AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1           DONE  6.282354  13.717062   6.868466  ...  6.365582  13.720054
sub2           DONE  7.536765   6.612828  11.817093  ...  8.930029   6.760778
sub3           DONE  4.620451    6.26131   5.733397  ...  5.317836   6.935442
sub4           DONE   2.38953   3.272965   3.818374  ...  3.790518   4.986451
sub5           DONE  1.250183   1.322771   0.717525  ...  0.665034   0.872943

data_path             4190857                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1           DONE  5.878346  13.710809  6.034077  14.259652  5.683363
sub2           DONE  8.342449   6.615367  7.457728   9.134314  6.206933
sub3           DONE  4.084904   6.261376  4.909066   7.355579  4.528621
sub4           DONE  1.841768   3.272197  2.317571    5.03074  2.296708
sub5           DONE  1.494092   1.320947  0.552164   0.927497  0.591902

data_path
Disp type DFT_D3ZERO Processed
sub1       13.713748      DONE
sub2        6.763238      DONE
sub3        6.934991      DONE
sub4        4.988172      DONE
sub5        0.872207      DONE

[5 rows x 21 columns]

wtmad_1

data_path    4192002                                                        \
Disp type         AI        DFT    AI_D3BJ  DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        8.026571   7.420931   8.407886  7.414587   7.954307   7.102103
sub2       14.039316  12.535436  13.432814  9.971579  13.081751  10.010194
sub3        6.665281   6.984991    7.67756  8.150912   7.244838   7.521852
sub4       13.029252  11.029773  11.229165  14.87552  10.254653  13.798614
sub5       14.524759  11.569831  10.209795  8.089137   9.674365   7.520409

data_path              1513512                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE   5.917804   7.427913   6.173631  ...   5.786012
sub2           DONE   9.677109  12.530346   7.731942  ...   7.407743
sub3           DONE   5.362819   6.982875   6.557344  ...   5.935941
sub4           DONE  10.472747  11.046974  12.507724  ...  11.478243
sub5           DONE  10.880025  11.599184   6.460544  ...   5.881129

data_path                         4190857                                 \
Disp type DFT_D3ZERO Processed         AI        DFT   AI_D3BJ  DFT_D3BJ
sub1        7.109349      DONE   6.332236    7.42093  5.740168  7.414586
sub2       10.004803      DONE  12.258863  12.533853  9.365034  9.970671
sub3        7.519994      DONE   4.930522   6.984991  5.759201  8.150912
sub4       13.779798      DONE  11.161453  11.029773  9.252237  14.87552
sub5        7.508553      DONE  13.595049    11.5704  4.671735  8.089186

data_path
Disp type AI_D3ZERO DFT_D3ZERO Processed
sub1       5.713986   7.102103      DONE
sub2       9.645465  10.008789      DONE
sub3        5.21121   7.521852      DONE
sub4       8.236251  13.798614      DONE
sub5       5.203513   7.520755      DONE

[5 rows x 21 columns]

wtmad_2

data_path   4192002                                                     \
Disp type        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       3.730481  4.040696  3.896445  4.111446  3.771451   3.989769
sub2       4.652822  3.640223  3.680039  2.379436  3.810301   2.550573
sub3       2.204726  2.611064  2.567649  3.040013  2.451917   2.873647
sub4       5.074244  4.159493  5.673725  6.856534  5.451359    6.62018
sub5       6.127489   4.65963  4.404013  3.507041  4.142926   3.193414

data_path             1513512                      ...                       \
Disp type Processed        AI       DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1           DONE  2.668675  4.045306  2.808633  ...  2.675278   3.994343
sub2           DONE  3.206768  3.637148  2.047904  ...  2.176739   2.547486
sub3           DONE  1.989474  2.610843   2.42163  ...  2.256968   2.873547
sub4           DONE  4.130245   4.16366  6.081695  ...  5.851345   6.614613
sub5           DONE  4.368745  4.670544  2.805652  ...  2.496356   3.192324

data_path             4190857                                          \
Disp type Processed        AI       DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO
sub1           DONE  2.896385  4.040699  2.747327  4.111449  2.718933
sub2           DONE  4.263586  3.638673  2.879648   2.37847  3.129725
sub3           DONE  1.749779  2.611064  2.078028  3.040013  1.921636
sub4           DONE  4.368593  4.159493  4.530199  6.856534   4.30781
sub5           DONE  4.982498  4.660409  2.000387  3.507108   2.04441

data_path
Disp type DFT_D3ZERO Processed
sub1        3.989772      DONE
sub2        2.549091      DONE
sub3        2.873647      DONE
sub4         6.62018      DONE
sub5        3.193887      DONE

[5 rows x 21 columns]

Summary of Subset
MAE

data_path    4192002                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       10.66333  29.506381  10.833318  31.211271  10.623928  29.860573
G21EA       1.368797   9.754713   1.365484   9.751936    1.37575   9.757737
G21IP       1.887165   8.953509    1.89351   8.946874   1.890371   8.952075
DIPCS10      2.76982  12.310852   2.750274  12.334099   2.747213  12.264655
PA26        2.130008   2.200766   2.232988   1.900152   2.112959    2.00824
SIE4x4     19.372674  21.908516  19.724808  22.337814   19.80166  22.339928
ALKBDE10   14.584296  18.125246  15.272899  18.838948  14.594568  18.135588
YBDE18       7.88327   8.145393   6.566602   7.265227   6.804269   7.472761
AL2X6       2.528306   5.659145    4.67199   1.332003   2.693071   1.829895
HEAVYSB11   5.352169   5.391476    8.05375   8.010474    6.02743   5.984154
NBPRC       5.194536    2.23255   2.793279   2.544088   2.964373   2.274234
ALK8        6.517239   4.400063   3.987358   3.174803   3.855053   2.559066
RC21        5.089529   4.820926   6.467859   6.671006   5.915758     6.0297
G2RC        7.969402   5.917203   8.800259   6.933515   8.369664   6.417298
BH76RC      4.928623   3.484561   5.072159   3.539828    4.95332   3.536982
FH51        5.458383   3.703657   6.406194    3.39478   6.225212   3.256908
TAUT15      3.766778    2.16453   3.818437   2.175485   3.743546   2.145937
DC13       18.818245  13.090861  22.203919  12.474047  20.424495  11.475687
MB16_43    16.865727  15.459572  36.669437  36.862016  23.734956  23.162234
DARC        8.553153   10.75415  16.274083    3.43411  13.729333    5.57797
RSE43       3.379095     3.1576   3.152551   2.916276   2.998074    2.74911
BSR36      12.979174   8.435801   5.625862    1.23793   7.657312   3.113938
CDIE20      1.185442   1.599507   0.842494   1.336544   0.850532   1.347484
ISO34       4.039369   2.001743   3.886036   1.577125   3.840333   1.647042
PArel       2.537158   1.743933   2.462631   1.733749   2.548572   1.645025
BH76        6.017022   9.107946   6.562533     9.8892   6.442369   9.676053
BHPERI      6.450168   3.268992  11.044106   7.804724   9.639775     6.4139
BHDIV10     5.348389   6.277706    6.20967   7.448955   5.445819   6.535109
INV24       4.730775   2.697333   3.681237   2.346995   4.009396   2.228547
BHROT27     0.852886   0.853379   0.869294   0.858852   0.864225    0.78352
PX13        9.424224  11.042023  10.208212   11.82601   9.602058  11.219857
WCPT18      6.157524   7.967151   7.344225   9.151986   6.932203   8.744304
RG18        0.291302   0.230018   0.622562   0.655714   0.676401   0.709552
ADIM6       3.770998   3.059029   1.378287   2.090256   1.678855   2.390824
S22         2.960235   2.291252   1.468083   2.402928   1.371008   2.291758
S66         2.430561   1.894709   1.238997   2.058561   1.284896   2.101976
WATER27    17.253654  16.299413   26.44529  25.491048  27.357125  26.402884
CARBHB12    1.021393   1.632408   1.984726   2.973103   1.853399   2.841777
PNICO23     0.904183   0.776429   2.195519   2.604046    1.31829   1.726817
HAL59       1.944712   1.649786   2.274223   2.629912   1.904915   2.247276
AHB21        3.63609   2.453821   4.619029   3.464384   4.449164   3.294519
CHB6        4.487423    1.80532   4.134877   3.038126   4.233166   2.309161
IL16        2.390561   1.021067   4.984156   4.339132   5.054987   4.409963
IDISP      10.362743  13.125475   6.074243   4.423061   5.139912   5.245746
ICONF       0.628185   0.413804   0.521771   0.464652   0.602117   0.493337
ACONF       0.548606   0.546621   0.459131   0.430751   0.334257   0.274429
Amino20x4   1.032519   0.654639   0.901487   0.644234   0.836632   0.574733
PCONF21     3.473282   3.214782   1.152402   1.178453   1.218123   1.099663
MCONF        2.70061    1.95602   0.928197   0.741352   0.862973   0.711618
SCONF       1.308606   0.512352    2.22169   1.432857   2.106785   1.317952
BUT14DIOL   0.891725   0.645099   1.375735   1.136703   1.264612    1.02002

data_path              1513512                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11          DONE   8.912932  29.506078  10.371244  ...   9.214856
G21EA          DONE   2.564896   9.754833   2.561594  ...   2.571788
G21IP          DONE   2.386778   8.953264   2.393298  ...   2.389928
DIPCS10        DONE   4.016426  12.311021   3.996413  ...   3.999516
PA26           DONE   2.509054   2.201636   2.809443  ...   2.642708
SIE4x4         DONE  19.060598  21.908495  19.489895  ...  19.492009
ALKBDE10       DONE  12.834948  18.116813   13.54865  ...   12.84529
YBDE18         DONE   6.229871   8.147657   5.103758  ...   5.247099
AL2X6          DONE   1.916657   5.657149   5.462636  ...   3.483718
HEAVYSB11      DONE   4.770742   5.388236   6.593581  ...   4.567261
NBPRC          DONE   3.669712   2.230608   2.476637  ...   2.718006
ALK8           DONE   6.048862   4.392627   3.098441  ...    3.50235
RC21           DONE   4.664053   4.961517   6.684956  ...   6.048642
G2RC           DONE   7.677862   5.917132    8.58537  ...    8.07384
BH76RC         DONE   3.279731   3.485362   3.389266  ...   3.328641
FH51           DONE   3.262527   3.706141   3.442943  ...   3.345771
TAUT15         DONE   1.405035   2.164503   1.440052  ...   1.366175
DC13           DONE  14.707148   13.09363   14.33006  ...  13.437354
MB16_43        DONE  22.256488  15.453583  50.913406  ...  35.698138
DARC           DONE   5.306109  10.749101   2.481735  ...   1.125373
RSE43          DONE   2.373794   3.156151   2.140418  ...   1.973055
BSR36          DONE   9.542035   8.418212   2.188723  ...   4.220172
CDIE20         DONE   1.138114   1.598478   0.835289  ...   0.834091
ISO34          DONE   1.623868   2.001743   1.275672  ...    1.29209
PArel          DONE   1.392302   1.745172   1.332906  ...    1.35753
BH76           DONE   6.839808   9.108903   7.602416  ...   7.394191
BHPERI         DONE   2.393671   3.269267   6.807975  ...    5.41715
BHDIV10        DONE   4.856895   6.276167   5.996852  ...    5.10293
INV24          DONE   2.758492   2.694221   2.764818  ...   2.634085
BHROT27        DONE   0.900358   0.851983   0.907826  ...   0.832769
PX13           DONE   7.029398  11.044222   7.813386  ...   7.207232
WCPT18         DONE   4.657887    7.96751   5.837702  ...   5.468315
RG18           DONE   0.264077   0.230148   0.631463  ...   0.685301
ADIM6          DONE    3.20211   3.074906   1.947175  ...   2.247743
S22            DONE   2.549198   2.292182   1.876449  ...   1.765279
S66            DONE   1.989056   1.896952   1.680986  ...   1.724401
WATER27        DONE   9.389889  16.299413  18.581524  ...   19.49336
CARBHB12       DONE   0.769567   1.633524   2.070602  ...   1.939275
PNICO23        DONE   0.805198   0.775722   2.559277  ...   1.682048
HAL59          DONE    1.55448   1.649326   2.385952  ...   2.003316
AHB21          DONE   1.347543   2.453773   2.214282  ...   2.132835
CHB6           DONE   1.507904   1.803629     1.6901  ...    1.39439
IL16           DONE   0.689251   1.017646   3.033894  ...   3.104725
IDISP          DONE  13.131153  13.141197   3.047996  ...   4.124779
ICONF          DONE   0.500565    0.41335    0.67976  ...   0.575008
ACONF          DONE   0.505225   0.567241   0.472147  ...   0.317627
Amino20x4      DONE   0.668801   0.655899   0.563968  ...   0.487973
PCONF21        DONE   3.002198   3.214782    0.83205  ...   0.857901
MCONF          DONE   2.142772   1.949561   0.675319  ...   0.633868
SCONF          DONE    0.28121   0.514191   0.939365  ...    0.82446
BUT14DIOL      DONE   0.290133   0.650204   0.701027  ...    0.59559

data_path                         4190857                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11       29.86027      DONE   7.550798  29.506665   8.934006  31.211555
G21EA       9.757857      DONE   1.711269   9.754663   1.708564   9.751886
G21IP       8.951829      DONE   2.550915   8.953296   2.557253    8.94666
DIPCS10    12.264823      DONE   6.273613  12.311131   6.258881  12.334377
PA26        2.009318      DONE   3.605722   2.200766   4.200466   1.900152
SIE4x4     22.339906      DONE  20.173028  21.908516  20.602325  22.337814
ALKBDE10   18.127155      DONE   8.902005  18.125246   9.590608  18.838948
YBDE18      7.475024      DONE   5.933368   8.145393   4.569985   7.265227
AL2X6       1.827899      DONE   6.181334   5.659145   1.831383   1.332003
HEAVYSB11   5.987025      DONE   4.749555   5.391476   5.679351   8.010474
NBPRC       2.276088      DONE     4.9164    2.23255   3.013631   2.544088
ALK8        2.554507      DONE   6.616179   4.400063   2.646402   3.174803
RC21        6.169201      DONE   4.100054   4.820926   5.069438   6.671006
G2RC        6.419741      DONE   6.128987   5.917203   6.551209   6.933515
BH76RC      3.537585      DONE   2.449106   3.484561   2.333343   3.539828
FH51        3.258629      DONE   4.177508   3.703657   3.122524    3.39478
TAUT15      2.145706      DONE    2.45399    2.16453   2.491192   2.175485
DC13       11.471982      DONE  11.403446  13.090861    9.49728  12.474047
MB16_43    23.169246      DONE   18.68265  15.457354  23.743491   36.86956
DARC        5.572921      DONE  13.348619   10.75415   5.627689    3.43411
RSE43       2.747661      DONE   2.396741     3.1576   2.156379   2.916276
BSR36       3.096349      DONE  14.514193   8.424939    7.16088   1.230819
CDIE20      1.346455      DONE   1.421845   1.599507   1.154213   1.336544
ISO34       1.647042      DONE   2.246307   2.001743   1.818504   1.577125
PArel       1.645923      DONE    1.56488   1.743933   1.546789   1.733749
BH76         9.67701      DONE   5.674759   9.107946   6.451724     9.8892
BHPERI      6.415509      DONE   2.336375   3.268992    5.13515   7.804724
BHDIV10      6.53357      DONE   3.717542   6.277706   4.311655   7.448955
INV24       2.228457      DONE   2.912957   2.697333   2.514939   2.346995
BHROT27     0.781869      DONE   0.853725   0.853379   0.859734   0.858852
PX13       11.222056      DONE    6.74376  11.042023   7.527748   11.82601
WCPT18      8.744663      DONE   4.591009   7.967151   5.775844   9.151986
RG18        0.709417      DONE   0.282955   0.230018   0.528977   0.655714
ADIM6       2.374947      DONE   3.399418   3.059029   1.769733   2.090256
S22         2.290832      DONE   3.091727   2.291252   1.068819   2.402928
S66         2.098661      DONE   2.398152   1.894709   1.093938   2.058561
WATER27    26.402884      DONE   2.164455  16.299413   10.86161  25.491048
CARBHB12    2.842893      DONE   0.723698   1.632408   1.848179   2.973103
PNICO23     1.725924      DONE    0.78019   0.776429    1.87894   2.604046
HAL59       2.246814      DONE   1.351353   1.649786   1.627911   2.629912
AHB21       3.294471      DONE   1.183552   2.453821   1.283149   3.464384
CHB6         2.30747      DONE   0.818446    1.80532   1.164292   3.038126
IL16        4.406542      DONE   2.826198   1.021067   0.760215   4.339132
IDISP       5.230025      DONE  16.838365  13.125475   5.500384   4.423061
ICONF       0.493186      DONE   0.510195   0.413804   0.396783   0.464652
ACONF       0.253809      DONE   0.990238   0.546621   0.484622   0.430751
Amino20x4   0.574269      DONE   0.637764   0.655095   0.435546   0.644273
PCONF21     1.099663      DONE   3.139995   3.214782    0.60959   1.178453
MCONF       0.717392      DONE   2.431729    1.95602   0.517603   0.741352
SCONF       1.320396      DONE   1.075863   0.512352   0.400347   1.432857
BUT14DIOL   1.025126      DONE   0.406419   0.645099   0.342858   1.136703

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
W4_11         7.7959  29.860857      DONE
G21EA       1.717819   9.757687      DONE
G21IP       2.554465   8.951861      DONE
DIPCS10     6.306532  12.264933      DONE
PA26        3.962178    2.00824      DONE
SIE4x4     20.604439  22.339928      DONE
ALKBDE10    8.912277  18.135588      DONE
YBDE18      4.919947   7.472761      DONE
AL2X6        2.43879   1.829895      DONE
HEAVYSB11   3.718193   5.984154      DONE
NBPRC       3.726127   2.274234      DONE
ALK8        3.967115   2.559066      DONE
RC21        4.872813     6.0297      DONE
G2RC        6.263019   6.417298      DONE
BH76RC       2.36072   3.536982      DONE
FH51        3.165912   3.256908      DONE
TAUT15      2.460292   2.145937      DONE
DC13        9.519743  11.475687      DONE
MB16_43    15.187126  23.172471      DONE
DARC        8.172439    5.57797      DONE
RSE43        1.99471    2.74911      DONE
BSR36        9.19233   3.103076      DONE
CDIE20      1.165153   1.347484      DONE
ISO34       1.935109   1.647042      DONE
PArel       1.510103   1.645025      DONE
BH76        6.240629   9.676053      DONE
BHPERI      3.744325     6.4139      DONE
BHDIV10      3.82634   6.535109      DONE
INV24       2.536246   2.228547      DONE
BHROT27     0.784117    0.78352      DONE
PX13        6.921594  11.219857      DONE
WCPT18      5.368162   8.744304      DONE
RG18        0.582816   0.709552      DONE
ADIM6       2.050435   2.390824      DONE
S22         1.006439   2.291758      DONE
S66         1.137353   2.101976      DONE
WATER27    11.773446  26.402884      DONE
CARBHB12    1.716852   2.841777      DONE
PNICO23     1.001711   1.726817      DONE
HAL59       1.253226   2.247276      DONE
AHB21       1.255892   3.294519      DONE
CHB6        0.591027   2.309161      DONE
IL16        0.861906   4.409963      DONE
IDISP       7.631686   5.245746      DONE
ICONF       0.562598   0.493337      DONE
ACONF       0.503102   0.274429      DONE
Amino20x4   0.418306    0.57501      DONE
PCONF21     0.715875   1.099663      DONE
MCONF       0.454896   0.711618      DONE
SCONF       0.457281   1.317952      DONE
BUT14DIOL   0.287583    1.02002      DONE

[51 rows x 21 columns]