In [2]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
with open("/home/chenzihao/workspace/cc2cc_test5/cc2cc/utils/gmtkn-def2.json") as f:
    json_data = json.load(f)

basis_args = "def2-TZVPD"
print(basis_args)

dft_type_list = ["scf_ene", "scf_d3bj_ene"]
data = pd.read_csv(
    "/home/chenzihao/workspace/cc2cc_test5/validate_hkqai/ccdft_def2-TZVPD_atom-1-1679342_gmtkn-def2.csv"
)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]

for name_set, subset_list_ in full_subset_dict.items():
    full_subset_dict[name_set] = np.sort(subset_list_)
data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for dft_type in dft_type_list:
        if dft_type in data.columns:
            data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
            data_dft = data[dft_type].to_numpy() * 627.5094733748099
        else:
            data_name = []
            for i_subset in subset_list_:
                if i_subset == "BH76RC":
                    data_name.append(json_data["molecule_BH76"])
                else:
                    data_name.append(json_data[f"molecule_{i_subset}"])
            data_name = np.concatenate(data_name)
            data_dft = np.zeros_like(data_name, dtype=float)

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft_name": [],
                "dft": [],
                "cc": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    # if verbose > 0:
                    #     print(f"Warning: {i_molecule_name} not found in data file")
                    continue

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        # if verbose > 0:
                        #     print(f"Warning: {mole_name} not found in json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                    else:
                        finished = False
                        # if verbose > 0:
                        #     print(f"Warning: {mole_name} not found in data csv file")
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft_name"].append(i_reaction_name)
                    for i in range(len(systems_list)):
                        data_subset[name_subset]["dft_name"][
                            -1
                        ] = f"{data_subset[name_subset]["dft_name"][-1]}-{systems_list[i]}"

                    atomic_energy_cc = i_reaction["reference"]
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ]
                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} with name {data_subset[name_subset]["dft_name"][argsort_atomic_energy_dft[i]]} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

header = dft_type_list + ["Processed"]

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

for dft_type in dft_type_list:
    mean_absolute_deviation_list = []

    for name_set, subset_list_ in full_subset_dict.items():
        subset_dft = []
        wtmad_1_dft = []
        wtmad_2_dft = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"

            if len(data_subset[name_subset]["dft"]) == 0:
                df_summary_subset.loc[i_subset, dft_type] = 0
                df_summary_subset.loc[i_subset, "Processed"] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                df_summary_subset.loc[i_subset, dft_type] = np.mean(
                    data_subset[name_subset]["dft"]
                )
                df_summary_subset.loc[i_subset, "Processed"] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["dft"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["dft"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['dft'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                subset_dft = np.append(subset_dft, data_subset[name_subset]["dft"])
                wtmad_1_dft = np.append(
                    wtmad_1_dft,
                    wtmad_1 * np.mean(data_subset[name_subset]["dft"]),
                )
                wtmad_2_dft = np.append(
                    wtmad_2_dft,
                    data_subset[name_subset]["dft"]
                    / np.mean(data_subset[name_subset]["cc"]),
                )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["dft"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)

        mean_subset.loc[name_set, dft_type] = np.mean(subset_dft)
        wtmad_1_subset.loc[name_set, dft_type] = np.mean(wtmad_1_dft)
        wtmad_2_subset.loc[name_set, dft_type] = np.sum(wtmad_2_dft)
        mean_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = 56.84 / len(mean_absolute_deviation_list)
    print(
        f"Mean absolute deviation for {dft_type}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        wtmad_2_subset.loc[name_set, dft_type] = (
            mean_absolute_deviation * wtmad_2_subset.loc[name_set, dft_type]
        )

    wtmad_1_subset.loc["summary", "Processed"] = "--"
    wtmad_2_subset.loc["summary", "Processed"] = "--"
    wtmad_1_subset.loc["summary", dft_type] = 0
    wtmad_2_subset.loc["summary", dft_type] = 0
    for name_set in full_subset_dict.keys():
        wtmad_1_subset.loc["summary", dft_type] += wtmad_1_subset.loc[
            name_set, dft_type
        ]
        wtmad_2_subset.loc["summary", dft_type] += wtmad_2_subset.loc[
            name_set, dft_type
        ]

print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to excel with date
df_summary_subset.to_excel(f"../validate_hkqai/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate_hkqai/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate_hkqai/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate_hkqai/wtmad_2_subset_{date}.xlsx")

def2-TZVPD
Top 1 with name 5-al2me6-alme3 DFT: 5.31837773686275 kcal/mol
Top 2 with name 4-al2me5-alme2-alme3 DFT: 3.70506898749154 kcal/mol
Top 3 with name 1-al2f6-alf3 DFT: 3.5393704901449397 kcal/mol
Top 4 with name 3-al2me4-alme2 DFT: 0.9957893619779483 kcal/mol
Top 5 with name 2-al2cl6-alcl3 DFT: 0.7178096454590559 kcal/mol
Top 6 with name 0-al2h6-alh3 DFT: 0.3802605289965868 kcal/mol
Top 1 with name 1-na8-na2 DFT: 19.718534740130416 kcal/mol
Top 2 with name 0-li8-li2 DFT: 17.28441572926269 kcal/mol
Top 3 with name 5-li5_ch-li4_c-li_h DFT: 3.5008350275154214 kcal/mol
Top 4 with name 3-li3_me-li_me-li2 DFT: 2.6901613514253384 kcal/mol
Top 5 with name 2-li4_me4-li_me DFT: 2.470510285648629 kcal/mol
Top 6 with name 7-na+-li_na_h2-li+-na2_h2 DFT: 1.481008917896542 kcal/mol
Top 7 with name 6-li2_ch2n_2-li_ch2n DFT: 0.36847404720610655 kcal/mol
Top 8 with name 4-li2_ch4-li_me-li_h DFT: 0.2798004152701452 kcal/mol
Top 1 with name 8-mgs-mg-s DFT: 9.271880338742633 kcal/mol
Top 2 with name 7-mgo-mg-o DFT: 8.49468604504655 kcal/mol
Top 3 with name 0-bef-be-f DFT: 7.81062633810069 kcal/mol
Top 4 with name 1-beo-be-o DFT: 7.2427535862385355 kcal/mol
Top 5 with name 3-hf-h-f DFT: 5.592363692283101 kcal/mol
Top 6 with name 9-nao-na-o DFT: 4.113320584964825 kcal/mol
Top 7 with name 4-kf-k-f DFT: 3.3684083761691 kcal/mol
Top 8 with name 5-lif-li-f DFT: 2.8043342337070385 kcal/mol
Top 9 with name 2-cao-ca-o DFT: 1.6419373133510788 kcal/mol
Top 10 with name 6-lio-li-o DFT: 0.7460932462854544 kcal/mol
Top 1 with name BH76RC_1-BH76-h-BH76-n2o-BH76-oh-BH76-n2 DFT: 7.9061659334803664 kcal/mol
Top 2 with name BH76RC_9-BH76-h-BH76-n2-BH76-hn2 DFT: 5.344693278600461 kcal/mol
Top 3 with name BH76RC_4-BH76-ch3-BH76-clf-BH76-ch3f-BH76-cl DFT: 4.402136518314947 kcal/mol
Top 4 with name BH76RC_10-BH76-h-BH76-co-BH76-hco DFT: 4.26318586958514 kcal/mol
Top 5 with name BH76RC_3-BH76-h-BH76-f2-BH76-hf-BH76-f DFT: 4.1231477483391075 kcal/mol
Top 6 with name BH76RC_2-BH76-h-BH76-ch3f-BH76-hf-BH76-ch3 DFT: 2.4229241057076436 kcal/mol
Top 7 with name BH76RC_22-BH76-O-BH76-CH4-BH76-oh-BH76-ch3 DFT: 2.344236738898471 kcal/mol
Top 8 with name BH76RC_17-BH76-oh-BH76-CH4-BH76-H2O-BH76-ch3 DFT: 2.2984754628171498 kcal/mol
Top 9 with name BH76RC_21-BH76-f-BH76-H2-BH76-hf-BH76-h DFT: 2.270120596455371 kcal/mol
Top 10 with name BH76RC_24-BH76-h-BH76-oh-BH76-H2-BH76-O DFT: 1.9434420415051865 kcal/mol
Top 11 with name BH76RC_25-BH76-h-BH76-H2S-BH76-H2-BH76-HS DFT: 1.9345391681510957 kcal/mol
Top 12 with name BH76RC_15-BH76-oh-BH76-H2-BH76-H2O-BH76-h DFT: 1.8876807654181817 kcal/mol
Top 13 with name BH76RC_27-BH76-NH2-BH76-ch3-BH76-NH-BH76-CH4 DFT: 1.7647780436954061 kcal/mol
Top 14 with name BH76RC_20-BH76-oh-BH76-C2H6-BH76-H2O-BH76-c2h5 DFT: 1.6859657133716972 kcal/mol
Top 15 with name BH76RC_30-BH76-NH2-BH76-CH4-BH76-NH3-BH76-ch3 DFT: 1.665873503418843 kcal/mol
Top 16 with name BH76RC_26-BH76-O-BH76-hcl-BH76-oh-BH76-cl DFT: 1.4200646200170741 kcal/mol
Top 17 with name BH76RC_28-BH76-NH2-BH76-c2h5-BH76-NH-BH76-C2H6 DFT: 1.1522682942717797 kcal/mol
Top 18 with name BH76RC_29-BH76-C2H6-BH76-NH2-BH76-c2h5-BH76-NH3 DFT: 1.0533637539879415 kcal/mol
Top 19 with name BH76RC_19-BH76-hcl-BH76-ch3-BH76-cl-BH76-CH4 DFT: 0.9341721189396051 kcal/mol
Top 20 with name BH76RC_11-BH76-h-BH76-c2h4-BH76-c2h5 DFT: 0.9280804878039604 kcal/mol
Top 21 with name BH76RC_5-BH76-f--BH76-ch3cl-BH76-cl--BH76-ch3f DFT: 0.8749345079885131 kcal/mol
Top 22 with name BH76RC_23-BH76-h-BH76-PH3-BH76-H2-BH76-PH2 DFT: 0.7307929497526509 kcal/mol
Top 23 with name BH76RC_13-BH76-hnc-BH76-hcn DFT: 0.6524709189712308 kcal/mol
Top 24 with name BH76RC_18-BH76-oh-BH76-NH3-BH76-H2O-BH76-NH2 DFT: 0.6326019594055836 kcal/mol
Top 25 with name BH76RC_14-BH76-h-BH76-hcl-BH76-H2-BH76-cl DFT: 0.5233774215099403 kcal/mol
Top 26 with name BH76RC_8-BH76-hoch3fcomp2-BH76-hoch3fcomp1 DFT: 0.4902465000841758 kcal/mol
Top 27 with name BH76RC_7-BH76-oh--BH76-ch3f-BH76-ch3oh-BH76-f- DFT: 0.44533739941136474 kcal/mol
Top 28 with name BH76RC_16-BH76-ch3-BH76-H2-BH76-CH4-BH76-h DFT: 0.41079469739896934 kcal/mol
Top 29 with name BH76RC_12-BH76-ch3-BH76-c2h4-BH76-c3h7 DFT: 0.060412275883717115 kcal/mol
Top 30 with name BH76RC_6-BH76-fch3clcomp1-BH76-fch3clcomp2 DFT: 0.029774682533460606 kcal/mol
Top 1 with name 8-s2-s8 DFT: 40.60260656103492 kcal/mol
Top 2 with name 1-c20cage-c20bowl DFT: 30.35026509956224 kcal/mol
Top 3 with name 12-C6Cl6-HCL-C6H6-CL2 DFT: 19.547129325009877 kcal/mol
Top 4 with name 3-tmethen-omcb DFT: 18.85631368525792 kcal/mol
Top 5 with name 4-ISO_E35-ISO_P35 DFT: 12.20602605442982 kcal/mol
Top 6 with name 9-ISO_C8H8_1-ISO_C8H8_41 DFT: 11.096876886744283 kcal/mol
Top 7 with name 2-heptatriyne-heptahexaene DFT: 8.868806253088405 kcal/mol
Top 8 with name 5-carbooxo2-carbooxo1 DFT: 7.99664284910541 kcal/mol
Top 9 with name 6-ethen-ch2n2-13dip DFT: 5.64000891111791 kcal/mol
Top 10 with name 11-o3-c2h4-o3_c2h4_add DFT: 2.5842253365728567 kcal/mol
Top 11 with name 7-be4-be DFT: 1.4825983167611412 kcal/mol
Top 12 with name 0-ISO_E36-ISO_P36 DFT: 0.8566434996610042 kcal/mol
Top 13 with name 10-o3-c2h2-o3_c2h2_add DFT: 0.022373220726152 kcal/mol
Top 1 with name 2-c2h4-c2h4_2+ DFT: 15.864272893367115 kcal/mol
Top 2 with name 0-c4h4-c4h4_2+ DFT: 11.103168304677865 kcal/mol
Top 3 with name 7-ph3-ph3_2+ DFT: 8.121308936935407 kcal/mol
Top 4 with name 4-nh3-nh3_2+ DFT: 7.639902911971149 kcal/mol
Top 5 with name 6-h2s-h2s_2+ DFT: 7.477537133410806 kcal/mol
Top 6 with name 1-c2h6-c2h6_2+ DFT: 5.204206948606611 kcal/mol
Top 7 with name 8-mg-mg_2+ DFT: 4.137078646855684 kcal/mol
Top 8 with name 9-be-be_2+ DFT: 2.073604366175232 kcal/mol
Top 9 with name 5-ch2o-ch2o_2+ DFT: 1.7881202779041132 kcal/mol
Top 10 with name 3-n2h2-n2h2_2+ DFT: 0.7778253431985149 kcal/mol
Top 1 with name 3-C4H9SO2H-H2O2-C4H9SO3H-H2O DFT: 9.018817940032747 kcal/mol
Top 2 with name 38-pentadiene-ethene-ax-methylcyclohexene DFT: 8.814185695571359 kcal/mol
Top 3 with name 31-H2C-C5-CH2-heptatriyne DFT: 8.125680879643188 kcal/mol
Top 4 with name 35-C3H7CHCO-H2CO-propyloxirane-CO DFT: 7.624663305483992 kcal/mol
Top 5 with name 0-C6H12O-H2O2-ethyl-g-butyrolactone-H2O DFT: 7.387983908646277 kcal/mol
Top 6 with name 4-trans-2-pentene-H2O2-pentanediol DFT: 6.347808663811307 kcal/mol
Top 7 with name 1-C4H9NH2-H2O2-C4H9NO2-H2O DFT: 6.055800242635883 kcal/mol
Top 8 with name 7-C2H5O_2-C2H4OH_2 DFT: 5.8971784022881195 kcal/mol
Top 9 with name 2-C4H9CHO-H2O2-C4H9CO2H-H2O DFT: 5.133540774857096 kcal/mol
Top 10 with name 36-pentanol-CO-HCO2C5H11 DFT: 5.127339525932912 kcal/mol
Top 11 with name 5-toluene-H2-methylcyclohexane DFT: 4.676978237149299 kcal/mol
Top 12 with name 8-3-hexene-H2O2-diethyloxirane-H2O DFT: 3.73259368498897 kcal/mol
Top 13 with name 19-trans-2-pentene-Cl2-C2H5CClCHCH3-HCl DFT: 3.6789682098594483 kcal/mol
Top 14 with name 10-ax-methylcyclohexene-eq-methylcyclohexene DFT: 3.675531368417431 kcal/mol
Top 15 with name 16-1-pentyne-H2O-C4H9CHO DFT: 3.6559742740576624 kcal/mol
Top 16 with name 25-C4H9NCO-NH3-C4H9NHCONH2 DFT: 3.6143609243433445 kcal/mol
Top 17 with name 23-dimethyloxirane-H2O-butanediol DFT: 3.534852345171384 kcal/mol
Top 18 with name 9-S_C2H5_2-H2O2-OS_C2H5_2-H2O DFT: 3.4798212901965613 kcal/mol
Top 19 with name 27-propylfuran-H2S-propylthiophene-H2O DFT: 3.437739882541063 kcal/mol
Top 20 with name 42-n-hexane-neo-hexane DFT: 3.34366802442004 kcal/mol
Top 21 with name 30-C3H7CO2C2H3-ethyl-g-butyrolactone DFT: 3.341998284028378 kcal/mol
Top 22 with name 24-methylpyridine-H2-dimethylpyrrole DFT: 3.231761442449642 kcal/mol
Top 23 with name 22-C4H9CHO-H2-pentanol DFT: 2.8177571677067306 kcal/mol
Top 24 with name 20-2-pentyne-HCl-C2H5CClCHCH3 DFT: 2.781111160719302 kcal/mol
Top 25 with name 45-toluene-H2-methylcyclohexa-1,3-diene DFT: 2.4371070454060098 kcal/mol
Top 26 with name 39-hexandione-methyl-d-valerolactone DFT: 2.41971095725894 kcal/mol
Top 27 with name 34-methylfuran-NH3-methylpyrrole-H2O DFT: 2.3567805672748356 kcal/mol
Top 28 with name 37-C3H7S_2-H2-C3H7SH DFT: 2.322140399836935 kcal/mol
Top 29 with name 40-C2H5CO2H-methanol-C2H5CO2CH3-H2O DFT: 2.1560245495123675 kcal/mol
Top 30 with name 29-C3H7NCO-H2O-C3H7NH2-CO2 DFT: 2.0978575106378408 kcal/mol
Top 31 with name 18-eq-methylcyclohexene-H2-methylcyclohexane DFT: 1.8594830290181577 kcal/mol
Top 32 with name 32-methylpyrazole-methylimidazole DFT: 1.8517596972093457 kcal/mol
Top 33 with name 28-diethylamine-CO-HCON_C2H5_2 DFT: 1.8065550963650452 kcal/mol
Top 34 with name 21-1-pentene-ethene-Heptene DFT: 1.6962820486549752 kcal/mol
Top 35 with name 6-pentanol-H2O2-C4H9CHO-H2O DFT: 1.6859624503419042 kcal/mol
Top 36 with name 26-C3H7CN-H2O-C3H7CONH2 DFT: 1.3967362273507753 kcal/mol
Top 37 with name 48-C2H5CO2H-NH3-C2H5CONH2-H2O DFT: 1.0872913541676825 kcal/mol
Top 38 with name 13-2-pentyne-H2-cis-2-pentene DFT: 0.951397767626915 kcal/mol
Top 39 with name 47-3-methylpentane-dimethylbutane DFT: 0.9355011861620005 kcal/mol
Top 40 with name 50-C3H7CO2H-NH3-C3H7CONH2-H2O DFT: 0.828952983719937 kcal/mol
Top 41 with name 41-C4H9ONO-C4H9NO2 DFT: 0.82310130391852 kcal/mol
Top 42 with name 11-hexyne-H2-1-hexene DFT: 0.7891604911722254 kcal/mol
Top 43 with name 14-2-pentyne-HCN-C2H5CCNCHCH3 DFT: 0.6850223553925758 kcal/mol
Top 44 with name 12-2-pentyne-H2-trans-2-pentene DFT: 0.589917229205021 kcal/mol
Top 45 with name 44-1-pentene-trans-2-pentene DFT: 0.48189501494984155 kcal/mol
Top 46 with name 46-cis-2-pentene-trans-2-pentene DFT: 0.36148053842189265 kcal/mol
Top 47 with name 33-1-pentene-H2O-pentanol DFT: 0.3487999432324429 kcal/mol
Top 48 with name 15-1-hexene-H2-n-hexane DFT: 0.24146146197570317 kcal/mol
Top 49 with name 43-methylcyclohexa-1,4-diene-methylcyclohexa-1,3-diene DFT: 0.12967407646239737 kcal/mol
Top 1 with name 4-EA_p-EA_p- DFT: 11.979403586487752 kcal/mol
Top 2 with name 16-EA_17n-EA_17 DFT: 9.397721860586898 kcal/mol
Top 3 with name 10-EA_11n-EA_11 DFT: 9.285680315519858 kcal/mol
Top 4 with name 17-EA_18n-EA_18 DFT: 8.846736200136366 kcal/mol
Top 5 with name 0-EA_c-EA_c- DFT: 7.504379409801185 kcal/mol
Top 6 with name 11-EA_12n-EA_12 DFT: 7.2450846369218205 kcal/mol
Top 7 with name 24-EA_25n-EA_25 DFT: 7.051730512711217 kcal/mol
Top 8 with name 9-EA_10n-EA_10 DFT: 6.79379218065078 kcal/mol
Top 9 with name 3-EA_si-EA_si- DFT: 6.385260747041322 kcal/mol
Top 10 with name 23-EA_24n-EA_24 DFT: 6.117387352220248 kcal/mol
Top 11 with name 7-EA_8n-EA_8 DFT: 5.775246914376474 kcal/mol
Top 12 with name 8-EA_9n-EA_9 DFT: 5.764676327724738 kcal/mol
Top 13 with name 18-EA_19n-EA_19 DFT: 5.032327315118167 kcal/mol
Top 14 with name 13-EA_14n-EA_14 DFT: 4.736964659806109 kcal/mol
Top 15 with name 5-EA_s-EA_s- DFT: 4.313995964213973 kcal/mol
Top 16 with name 1-EA_o-EA_o- DFT: 4.2015492644088255 kcal/mol
Top 17 with name 12-EA_13n-EA_13 DFT: 3.6916495084617083 kcal/mol
Top 18 with name 15-EA_16n-EA_16 DFT: 3.4290020220563733 kcal/mol
Top 19 with name 2-EA_f-EA_f- DFT: 3.302231834050332 kcal/mol
Top 20 with name 22-EA_23n-EA_23 DFT: 3.2385190182598294 kcal/mol
Top 21 with name 6-EA_cl-EA_cl- DFT: 3.2174571008072235 kcal/mol
Top 22 with name 20-EA_21n-EA_21 DFT: 2.9145788792491656 kcal/mol
Top 23 with name 19-EA_20n-EA_20 DFT: 1.0865249797934666 kcal/mol
Top 24 with name 21-EA_22n-EA_22 DFT: 0.8878521379447193 kcal/mol
Top 25 with name 14-EA_15n-EA_15 DFT: 0.10015266845002913 kcal/mol
Top 1 with name 33-IP_78-45 DFT: 17.498316611412008 kcal/mol
Top 2 with name 26-IP_71-25 DFT: 9.001063560798627 kcal/mol
Top 3 with name 27-IP_72-26 DFT: 8.305678591442472 kcal/mol
Top 4 with name 15-IP_59-8 DFT: 7.173667844261274 kcal/mol
Top 5 with name 30-IP_75-37 DFT: 6.742099169247808 kcal/mol
Top 6 with name 23-IP_67-20 DFT: 6.357669827513632 kcal/mol
Top 7 with name 25-IP_70-22 DFT: 5.971616217136386 kcal/mol
Top 8 with name 6-o+-o DFT: 5.6525481501637955 kcal/mol
Top 9 with name 20-IP_64-18 DFT: 5.598829645180842 kcal/mol
Top 10 with name 13-s+-s DFT: 5.524661532748723 kcal/mol
Top 11 with name 34-IP_79-51 DFT: 5.321113409335737 kcal/mol
Top 12 with name 14-cl+-cl DFT: 5.153463075542845 kcal/mol
Top 13 with name 7-f+-f DFT: 5.070386552691332 kcal/mol
Top 14 with name 28-IP_73-30 DFT: 4.407415046585015 kcal/mol
Top 15 with name 19-IP_63-14 DFT: 4.132804312719884 kcal/mol
Top 16 with name 18-IP_62-13 DFT: 3.943469080629143 kcal/mol
Top 17 with name 29-IP_74-34 DFT: 3.764215634718994 kcal/mol
Top 18 with name 16-IP_60-11 DFT: 3.1913719412963815 kcal/mol
Top 19 with name 32-IP_77-44 DFT: 3.11690258027474 kcal/mol
Top 20 with name 21-IP_65-IP_n65 DFT: 2.312237926245899 kcal/mol
Top 21 with name 35-IP_80-48 DFT: 2.14250674518712 kcal/mol
Top 22 with name 9-mg+-mg DFT: 2.058869287965365 kcal/mol
Top 23 with name 24-IP_68-137 DFT: 1.6693464235984834 kcal/mol
Top 24 with name 17-IP_61-12 DFT: 1.659051911998688 kcal/mol
Top 25 with name 5-n+-n DFT: 1.527598093748395 kcal/mol
Top 26 with name 4-c+-c DFT: 1.3706613183254603 kcal/mol
Top 27 with name 0-h DFT: 1.3450181056977044 kcal/mol
Top 28 with name 31-IP_76-43 DFT: 1.1526505376598664 kcal/mol
Top 29 with name 8-na+-na DFT: 1.0008511261257809 kcal/mol
Top 30 with name 2-be+-be DFT: 0.9225666025999146 kcal/mol
Top 31 with name 11-si+-si DFT: 0.9129440636315849 kcal/mol
Top 32 with name 12-p+-p DFT: 0.8285483675776106 kcal/mol
Top 33 with name 10-al+-al DFT: 0.8023334499739576 kcal/mol
Top 34 with name 1-li+-li DFT: 0.7121481894893833 kcal/mol
Top 35 with name 22-IP_66-19 DFT: 0.6932142410676363 kcal/mol
Top 36 with name 3-b+-b DFT: 0.686507799333782 kcal/mol
Top 1 with name 10-67-61-66-62 DFT: 18.98881936083548 kcal/mol
Top 2 with name 9-58-59-57-60 DFT: 10.722804767568597 kcal/mol
Top 3 with name 20-68-1-34-13 DFT: 9.7137580030912 kcal/mol
Top 4 with name 8-39-45-51 DFT: 7.254024924058466 kcal/mol
Top 5 with name 19-73-1-39-13 DFT: 6.85059929930722 kcal/mol
Top 6 with name 4-30-13-40-1 DFT: 6.486709762165697 kcal/mol
Top 7 with name 22-1-39-14 DFT: 6.057796309998963 kcal/mol
Top 8 with name 23-25-94 DFT: 4.929894770038089 kcal/mol
Top 9 with name 15-8-45-97-22 DFT: 4.716462427033115 kcal/mol
Top 10 with name 7-25-14-121 DFT: 4.545788028918906 kcal/mol
Top 11 with name 2-113-30-8 DFT: 3.789341589995893 kcal/mol
Top 12 with name 0-118-117-13 DFT: 3.7826037891831947 kcal/mol
Top 13 with name 14-34-1-11 DFT: 3.0613162657612705 kcal/mol
Top 14 with name 21-26-6-82 DFT: 2.910794754206435 kcal/mol
Top 15 with name 16-25-1-26 DFT: 2.8495704873464973 kcal/mol
Top 16 with name 17-56-1-21-13 DFT: 2.3132133819325844 kcal/mol
Top 17 with name 18-30-1-13-8 DFT: 2.263368895548041 kcal/mol
Top 18 with name 6-100-13-106 DFT: 1.9254250442329806 kcal/mol
Top 19 with name 1-40-1-104 DFT: 1.889717816962511 kcal/mol
Top 20 with name 11-32-1-33 DFT: 1.316422923025094 kcal/mol
Top 21 with name 12-25-26-88 DFT: 0.41755402835493527 kcal/mol
Top 22 with name 5-128-13-126-22 DFT: 0.15971582971979004 kcal/mol
Top 23 with name 24-23-39-24 DFT: 0.0740175365202731 kcal/mol
Top 24 with name 3-52-1-18 DFT: 0.04813476438866893 kcal/mol
Top 25 with name 13-47-1-18-13 DFT: 0.013931191897135875 kcal/mol
Top 1 with name 6-pme2-p2me4 DFT: 12.045881449617447 kcal/mol
Top 2 with name 7-asme2-as2me4 DFT: 11.662527984306216 kcal/mol
Top 3 with name 4-seh-h2se2 DFT: 8.343533224314449 kcal/mol
Top 4 with name 2-pbme3-pb2me6 DFT: 7.833781514449512 kcal/mol
Top 5 with name 8-sbme2-sb2me4 DFT: 6.947079117430839 kcal/mol
Top 6 with name 3-sh-h2s2 DFT: 6.216458305448754 kcal/mol
Top 7 with name 0-geh3-ge2h6 DFT: 5.540448557753109 kcal/mol
Top 8 with name 5-teme-te2me2 DFT: 5.505511762308885 kcal/mol
Top 9 with name 1-snme3-sn2me6 DFT: 5.008049537786285 kcal/mol
Top 10 with name 9-cl-cl2 DFT: 2.8018753049895153 kcal/mol
Top 11 with name 10-br-br2 DFT: 1.6541594635508972 kcal/mol
Top 1 with name 5-nh2-bh2-ch DFT: 18.3985712508671 kcal/mol
Top 2 with name 3-nh2-bh2-cbut DFT: 10.823107759933919 kcal/mol
Top 3 with name 10-BCl3PMe3-BCl3-PMe3 DFT: 10.64453620671993 kcal/mol
Top 4 with name 0-nh3-bh3-nh3-bh3 DFT: 7.718612039310393 kcal/mol
Top 5 with name 6-BH3PH3-BH3-PH3 DFT: 7.057252748508471 kcal/mol
Top 6 with name 8-BF3PMe3-BF3-PMe3 DFT: 6.206108464498538 kcal/mol
Top 7 with name 4-nh2-bh2-bz-h2 DFT: 5.5025918955278925 kcal/mol
Top 8 with name 1-nh3-bh3-nh2-bh2-h2 DFT: 3.244909124792616 kcal/mol
Top 9 with name 11-K_Cl-BCl3PMe3-H2 DFT: 3.1333400477777573 kcal/mol
Top 10 with name 7-K_H-BH3PH3-H2 DFT: 2.321228128916708 kcal/mol
Top 11 with name 2-nh2-bh2-nh-bh-h2 DFT: 1.2106549798857245 kcal/mol
Top 12 with name 9-K_F-BF3PMe3-H2 DFT: 0.6874990440899182 kcal/mol
Top 1 with name 3-p8-p8p DFT: 8.659036615031084 kcal/mol
Top 2 with name 2-p6-p6p DFT: 7.088671791873651 kcal/mol
Top 3 with name 1-p4-p4p DFT: 5.160252397612197 kcal/mol
Top 4 with name 10-hcl-hclp DFT: 4.474109660822421 kcal/mol
Top 5 with name 22-A-Ap DFT: 4.210883055895096 kcal/mol
Top 6 with name 16-phenol-phenolp DFT: 3.2306673103826995 kcal/mol
Top 7 with name 21-phosphapyrrol-phosphapyrrolp DFT: 3.2016733289696333 kcal/mol
Top 8 with name 17-ass-assp DFT: 2.8979477100772897 kcal/mol
Top 9 with name 24-G-Gp DFT: 2.890730694984086 kcal/mol
Top 10 with name 18-ch2s-ch2sp DFT: 2.8442350053693986 kcal/mol
Top 11 with name 12-c2f6-c2f6p DFT: 2.4964726212085253 kcal/mol
Top 12 with name 9-h2s-h2sp DFT: 2.229105093417445 kcal/mol
Top 13 with name 8-ph3-ph3p DFT: 2.0224954537872577 kcal/mol
Top 14 with name 6-c2h2-c2h2p DFT: 1.9688218024035393 kcal/mol
Top 15 with name 0-p2-p2p DFT: 1.341711644829786 kcal/mol
Top 16 with name 13-ethanol-ethanolp DFT: 1.2430350443522968 kcal/mol
Top 17 with name 25-C-Cp DFT: 1.1908788441855052 kcal/mol
Top 18 with name 5-h2o-h2op DFT: 1.0492834143718994 kcal/mol
Top 19 with name 15-gly-glyp DFT: 0.9267350631300246 kcal/mol
Top 20 with name 23-T-Tp DFT: 0.8472749723703714 kcal/mol
Top 21 with name 4-nh3-nh3p DFT: 0.5919597669912093 kcal/mol
Top 22 with name 19-si2h6-si2h6p DFT: 0.4457518142531569 kcal/mol
Top 23 with name 11-h2-h2p DFT: 0.39114110897862986 kcal/mol
Top 24 with name 7-sih4-sih4p DFT: 0.24079557939549545 kcal/mol
Top 25 with name 20-cys-cysp DFT: 0.20067448414630462 kcal/mol
Top 26 with name 14-ch3cooh-ch3coohp DFT: 0.07727233424665769 kcal/mol
Top 1 with name 15-7e-7p1-7p2 DFT: 4.657026103629033 kcal/mol
Top 2 with name 17-7e-7p5-7p6 DFT: 4.296182895062085 kcal/mol
Top 3 with name 2-2e-2p1-me DFT: 4.292901366528678 kcal/mol
Top 4 with name 18-8e-8p1-ethylene DFT: 3.8857128248023187 kcal/mol
Top 5 with name 0-1e-1p1-me DFT: 3.2709162368594846 kcal/mol
Top 6 with name 13-6e-6p3-me DFT: 3.258403294613089 kcal/mol
Top 7 with name 7-3e-3int3 DFT: 2.752346939797281 kcal/mol
Top 8 with name 3-2e-2p2-2p3 DFT: 2.5218008843463053 kcal/mol
Top 9 with name 11-6e-6int DFT: 2.455298404091736 kcal/mol
Top 10 with name 10-5e-5p-me DFT: 2.0861307864818066 kcal/mol
Top 11 with name 14-6e-1p2-pr DFT: 1.720004531390149 kcal/mol
Top 12 with name 8-3e-3p2-3p3 DFT: 1.5568982136843275 kcal/mol
Top 13 with name 1-1e-1p2-1p3 DFT: 1.3417716766160446 kcal/mol
Top 14 with name 9-4e-4p-me DFT: 0.9987031748316042 kcal/mol
Top 15 with name 19-9e-9p1-9p2 DFT: 0.9701550653675781 kcal/mol
Top 16 with name 20-10e-10p1-10p2 DFT: 0.9658160565909952 kcal/mol
Top 17 with name 12-6e-6p1-ethylene DFT: 0.7833512824299405 kcal/mol
Top 18 with name 16-7e-7p3-7p4 DFT: 0.7278455868473941 kcal/mol
Top 19 with name 5-3e-3int1 DFT: 0.3988939604046777 kcal/mol
Top 20 with name 6-3e-3int2 DFT: 0.3451625558699014 kcal/mol
Top 21 with name 4-3e-3p1-3p2 DFT: 0.2109590702621702 kcal/mol
Top 1 with name 7-he-he+-he2+_1.75 DFT: 42.928688765260084 kcal/mol
Top 2 with name 6-he-he+-he2+_1.5 DFT: 35.696397302145854 kcal/mol
Top 3 with name 5-he-he+-he2+_1.25 DFT: 27.908915321918904 kcal/mol
Top 4 with name 15-h2o-h2o+-h2o2+_1.75 DFT: 26.50620916803309 kcal/mol
Top 5 with name 14-h2o-h2o+-h2o2+_1.5 DFT: 22.32276419462287 kcal/mol
Top 6 with name 11-nh3-nh3+-nh32+_1.75 DFT: 21.97337733770255 kcal/mol
Top 7 with name 4-he-he+-he2+_1.0 DFT: 21.89470393700558 kcal/mol
Top 8 with name 13-h2o-h2o+-h2o2+_1.25 DFT: 17.855467921492526 kcal/mol

        scf_ene scf_d3bj_ene Processed
sub1   7.698257     6.846569   17 / 18
sub2  11.603007     4.286499     1 / 9
sub3    3.80233     4.583619     1 / 7
sub4   2.873248     0.664807    1 / 12
sub5   1.322934     0.568765     0 / 9

wtmad_1

           scf_ene scf_d3bj_ene Processed
sub1      5.117596     4.440814   17 / 18
sub2        7.4072      3.35696     1 / 9
sub3       3.80233     4.583619     1 / 7
sub4     28.732483      6.64807    1 / 12
sub5     14.823218     5.740454     0 / 9
summary  59.882826    24.769918        --

wtmad_2

           scf_ene scf_d3bj_ene Processed
sub1      3.669966     3.342886   17 / 18
sub2       2.19484     0.671535     1 / 9
sub3      1.173408     1.414515     1 / 7
sub4      2.621843     0.606637    1 / 12
sub5      1.876088     0.917135     0 / 9
summary  11.536143     6.952708        --

Summary of Subset
MAE

             scf_ene scf_d3bj_ene Processed
AL2X6       2.442779     4.355891      DONE
ALK8        5.974218     5.355165      DONE
ALKBDE10     5.10864     4.646737      DONE
BH76RC      1.886535     2.029058      DONE
DC13       12.316194     7.576728      DONE
DIPCS10     6.418703     6.403969      DONE
FH51        3.079106     2.406724   49 / 51
G21EA       5.291996     5.287058      DONE
G21IP       3.825676      3.83182      DONE
G2RC        4.283271     5.106553      DONE
HEAVYSB11    6.68721     2.321667      DONE
NBPRC       6.412368     3.310686      DONE
PA26        2.381601     2.792602      DONE
RC21        2.071251     3.446428      DONE
SIE4x4     18.283906    18.713203      DONE
TAUT15      1.333721     1.379498      DONE
W4_11      14.370496    12.731396      DONE
YBDE18      6.840173     3.189867      DONE
BSR36       9.981292     2.627794      DONE
C60ISO             0            0     0 / 9
CDIE20             0            0    0 / 20
DARC          8.5205      1.56308   13 / 14
ISO34              0            0    0 / 34
ISOL24      3.841749     2.747042   12 / 24
MB16_43     73.08108    37.277565    4 / 43
PArel              0            0    0 / 20
RSE43       0.738435     0.611913    5 / 43
BH76         3.80233     4.583619      DONE
BHDIV10            0            0    0 / 10
BHPERI             0            0    0 / 26
BHROT27            0            0    0 / 27
INV24              0            0    0 / 24
PX13               0            0    0 / 13
WCPT18             0            0    0 / 18
ADIM6              0            0     0 / 6
AHB21              0            0    0 / 21
CARBHB12           0            0    0 / 12
CHB6               0            0     0 / 6
HAL59              0            0    0 / 59
HEAVY28            0            0    0 / 28
IL16               0            0    0 / 16
PNICO23            0            0    0 / 23
RG18               0            0    0 / 18
S22                0            0    0 / 22
S66         2.873248     0.664807      DONE
WATER27            0            0    0 / 27
ACONF              0            0    0 / 15
Amino20x4   0.636343     0.546018   41 / 80
BUT14DIOL          0            0    0 / 64
ICONF              0            0    0 / 17
IDISP              0            0     0 / 6
MCONF         2.3283     0.602073   28 / 51
PCONF21            0            0    0 / 18
SCONF              0            0    0 / 17
UPU23              0            0    0 / 23