In [2]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
with open("/home/chenzihao/workspace/cc2cc_test5/cc2cc/utils/gmtkn-def2.json") as f:
    json_data = json.load(f)

basis_args = "cc-pVTZ"
# basis_args = "def2-TZVPD"
print(basis_args)

dft_type_list = ["cc_ene", "b3lyp_ene", "b3lyp-d3bj_ene"]
data = pd.read_csv(
    f"/home/chenzihao/workspace/cc2cc_test5/validate_hkqai/ccdft_{basis_args}__gmtkn-def2.csv"
)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]

for name_set, subset_list_ in full_subset_dict.items():
    full_subset_dict[name_set] = np.sort(subset_list_)
data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for dft_type in dft_type_list:
        if dft_type in data.columns:
            data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
            data_dft = data[dft_type].to_numpy() * 627.5094733748099
        else:
            data_name = []
            for i_subset in subset_list_:
                if i_subset == "BH76RC":
                    data_name.append(json_data["molecule_BH76"])
                else:
                    data_name.append(json_data[f"molecule_{i_subset}"])
            data_name = np.concatenate(data_name)
            data_dft = np.zeros_like(data_name, dtype=float)

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "cc": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(f"Warning: {i_molecule_name} not found in data file")
                    continue

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data csv file")
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    atomic_energy_cc = i_reaction["reference"]
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ]
                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} with name {data_subset[name_subset]["name"][argsort_atomic_energy_dft[i]]} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

header = dft_type_list + ["Processed"]

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

for dft_type in dft_type_list:
    mean_absolute_deviation_list = []

    for name_set, subset_list_ in full_subset_dict.items():
        subset_dft = []
        wtmad_1_dft = []
        wtmad_2_dft = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"

            if len(data_subset[name_subset]["dft"]) == 0:
                df_summary_subset.loc[i_subset, dft_type] = 0
                df_summary_subset.loc[i_subset, "Processed"] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                df_summary_subset.loc[i_subset, dft_type] = np.mean(
                    data_subset[name_subset]["dft"]
                )
                df_summary_subset.loc[i_subset, "Processed"] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["dft"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["dft"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['dft'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                subset_dft = np.append(subset_dft, data_subset[name_subset]["dft"])
                wtmad_1_dft = np.append(
                    wtmad_1_dft,
                    wtmad_1 * np.mean(data_subset[name_subset]["dft"]),
                )
                wtmad_2_dft = np.append(
                    wtmad_2_dft,
                    data_subset[name_subset]["dft"]
                    / np.mean(data_subset[name_subset]["cc"]),
                )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["dft"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)

        mean_subset.loc[name_set, dft_type] = np.mean(subset_dft)
        wtmad_1_subset.loc[name_set, dft_type] = np.mean(wtmad_1_dft)
        wtmad_2_subset.loc[name_set, dft_type] = np.sum(wtmad_2_dft)
        mean_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = 56.84 / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {dft_type}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        wtmad_2_subset.loc[name_set, dft_type] = (
            mean_absolute_deviation * wtmad_2_subset.loc[name_set, dft_type]
        )

    wtmad_1_subset.loc["summary", "Processed"] = "--"
    wtmad_2_subset.loc["summary", "Processed"] = "--"
    wtmad_1_subset.loc["summary", dft_type] = 0
    wtmad_2_subset.loc["summary", dft_type] = 0
    for name_set in full_subset_dict.keys():
        wtmad_1_subset.loc["summary", dft_type] += wtmad_1_subset.loc[
            name_set, dft_type
        ]
        wtmad_2_subset.loc["summary", dft_type] += wtmad_2_subset.loc[
            name_set, dft_type
        ]

print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# # save summary to csv with date
# df_summary_subset_ele.to_csv(f"../validate_hkqai_done/df_summary_subset_ele_{date}.csv")
# df_summary_subset.to_csv(f"../validate_hkqai_done/summary_subset_{date}.csv")
# mean_subset.to_csv(f"../validate_hkqai_done/mean_subset_{date}.csv")
# wtmad_1_subset.to_csv(f"../validate_hkqai_done/wtmad_1_subset_{date}.csv")
# wtmad_2_subset.to_csv(f"../validate_hkqai_done/wtmad_2_subset_{date}.csv")
# # save summary to excel with date
# df_summary_subset_ele.to_excel(
#     f"../validate_hkqai_done/df_summary_subset_ele_{date}.xlsx"
# )
# df_summary_subset.to_excel(f"../validate_hkqai_done/summary_subset_{date}.xlsx")
# mean_subset.to_excel(f"../validate_hkqai_done/mean_subset_{date}.xlsx")
# wtmad_1_subset.to_excel(f"../validate_hkqai_done/wtmad_1_subset_{date}.xlsx")
# wtmad_2_subset.to_excel(f"../validate_hkqai_done/wtmad_2_subset_{date}.xlsx")

cc-pVTZ
Top 1 with name 1 DFT: 51.6 kcal/mol
Top 2 with name 0 DFT: 38.5 kcal/mol
Top 3 with name 3 DFT: 38.4 kcal/mol
Top 4 with name 2 DFT: 32.5 kcal/mol
Top 5 with name 4 DFT: 31.2 kcal/mol
Top 6 with name 5 DFT: 23.1 kcal/mol
Top 1 with name 2 DFT: 131.13 kcal/mol
Top 2 with name 0 DFT: 86.47 kcal/mol
Top 3 with name 5 DFT: 66.28 kcal/mol
Top 4 with name 6 DFT: 56.55 kcal/mol
Top 5 with name 1 DFT: 53.15 kcal/mol
Top 6 with name 4 DFT: 47.42 kcal/mol
Top 7 with name 3 DFT: 34.51 kcal/mol
Top 8 with name 7 DFT: 25.3 kcal/mol
Top 1 with name 3 DFT: 142.1 kcal/mol
Top 2 with name 5 DFT: 139.2 kcal/mol
Top 3 with name 0 DFT: 138.7 kcal/mol
Top 4 with name 4 DFT: 117.5 kcal/mol
Top 5 with name 1 DFT: 106.6 kcal/mol
Top 6 with name 2 DFT: 96.2 kcal/mol
Top 7 with name 6 DFT: 82.5 kcal/mol
Top 8 with name 9 DFT: 65.2 kcal/mol
Top 9 with name 7 DFT: 62.2 kcal/mol
Top 10 with name 8 DFT: 56.7 kcal/mol
Top 1 with name BH76RC_3 DFT: 103.28 kcal/mol
Top 2 with name BH76RC_1 DFT: 64.91 kcal/mol
Top 3 with name BH76RC_4 DFT: 52.64 kcal/mol
Top 4 with name BH76RC_11 DFT: 40.02 kcal/mol
Top 5 with name BH76RC_8 DFT: 36.71 kcal/mol
Top 6 with name BH76RC_21 DFT: 32.22 kcal/mol
Top 7 with name BH76RC_5 DFT: 32.16 kcal/mol
Top 8 with name BH76RC_12 DFT: 26.56 kcal/mol
Top 9 with name BH76RC_2 DFT: 26.32 kcal/mol
Top 10 with name BH76RC_6 DFT: 26.12 kcal/mol
Top 11 with name BH76RC_23 DFT: 21.74 kcal/mol
Top 12 with name BH76RC_7 DFT: 20.32 kcal/mol
Top 13 with name BH76RC_10 DFT: 19.55 kcal/mol
Top 14 with name BH76RC_20 DFT: 16.84 kcal/mol
Top 15 with name BH76RC_15 DFT: 16.39 kcal/mol
Top 16 with name BH76RC_13 DFT: 15.06 kcal/mol
Top 17 with name BH76RC_17 DFT: 13.28 kcal/mol
Top 18 with name BH76RC_25 DFT: 13.26 kcal/mol
Top 19 with name BH76RC_27 DFT: 13.12 kcal/mol
Top 20 with name BH76RC_18 DFT: 10.32 kcal/mol
Top 21 with name BH76RC_28 DFT: 9.56 kcal/mol
Top 22 with name BH76RC_29 DFT: 6.52 kcal/mol
Top 23 with name BH76RC_22 DFT: 5.44 kcal/mol
Top 24 with name BH76RC_19 DFT: 5.01 kcal/mol
Top 25 with name BH76RC_9 DFT: 3.69 kcal/mol
Top 26 with name BH76RC_16 DFT: 3.11 kcal/mol
Top 27 with name BH76RC_30 DFT: 2.96 kcal/mol
Top 28 with name BH76RC_24 DFT: 2.32 kcal/mol
Top 29 with name BH76RC_14 DFT: 1.9 kcal/mol
Top 30 with name BH76RC_26 DFT: 0.42 kcal/mol
Top 1 with name 12 DFT: 152.6 kcal/mol
Top 2 with name 9 DFT: 109.92 kcal/mol
Top 3 with name 8 DFT: 106.0 kcal/mol
Top 4 with name 7 DFT: 92.0 kcal/mol
Top 5 with name 10 DFT: 65.3 kcal/mol
Top 6 with name 11 DFT: 58.7 kcal/mol
Top 7 with name 6 DFT: 38.9 kcal/mol
Top 8 with name 5 DFT: 25.7 kcal/mol
Top 9 with name 4 DFT: 22.9 kcal/mol
Top 10 with name 3 DFT: 18.8 kcal/mol
Top 11 with name 2 DFT: 15.2 kcal/mol
Top 12 with name 1 DFT: 7.7 kcal/mol
Top 13 with name 0 DFT: 1.0 kcal/mol
Top 1 with name 4 DFT: 776.5 kcal/mol
Top 2 with name 5 DFT: 747.6 kcal/mol
Top 3 with name 6 DFT: 733.0 kcal/mol
Top 4 with name 1 DFT: 667.1 kcal/mol
Top 5 with name 2 DFT: 655.8 kcal/mol
Top 6 with name 7 DFT: 649.6 kcal/mol
Top 7 with name 9 DFT: 634.8 kcal/mol
Top 8 with name 3 DFT: 626.9 kcal/mol
Top 9 with name 0 DFT: 529.2 kcal/mol
Top 10 with name 8 DFT: 522.1 kcal/mol
Top 1 with name 0 DFT: 150.81 kcal/mol
Top 2 with name 1 DFT: 144.38 kcal/mol
Top 3 with name 2 DFT: 89.35 kcal/mol
Top 4 with name 3 DFT: 82.55 kcal/mol
Top 5 with name 4 DFT: 78.51 kcal/mol
Top 6 with name 5 DFT: 66.96 kcal/mol
Top 7 with name 6 DFT: 63.89 kcal/mol
Top 8 with name 7 DFT: 58.53 kcal/mol
Top 9 with name 8 DFT: 56.64 kcal/mol
Top 10 with name 9 DFT: 52.85 kcal/mol
Top 11 with name 10 DFT: 52.6 kcal/mol
Top 12 with name 11 DFT: 46.72 kcal/mol
Top 13 with name 12 DFT: 44.82 kcal/mol
Top 14 with name 13 DFT: 43.67 kcal/mol
Top 15 with name 14 DFT: 42.89 kcal/mol
Top 16 with name 15 DFT: 37.08 kcal/mol
Top 17 with name 16 DFT: 34.93 kcal/mol
Top 18 with name 17 DFT: 32.47 kcal/mol
Top 19 with name 18 DFT: 32.1 kcal/mol
Top 20 with name 19 DFT: 31.22 kcal/mol
Top 21 with name 20 DFT: 29.98 kcal/mol
Top 22 with name 21 DFT: 25.84 kcal/mol
Top 23 with name 22 DFT: 23.47 kcal/mol
Top 24 with name 23 DFT: 22.45 kcal/mol
Top 25 with name 24 DFT: 20.27 kcal/mol
Top 26 with name 25 DFT: 19.72 kcal/mol
Top 27 with name 27 DFT: 19.45 kcal/mol
Top 28 with name 26 DFT: 19.34 kcal/mol
Top 29 with name 28 DFT: 17.39 kcal/mol
Top 30 with name 29 DFT: 16.98 kcal/mol
Top 31 with name 30 DFT: 16.14 kcal/mol
Top 32 with name 31 DFT: 14.3 kcal/mol
Top 33 with name 32 DFT: 13.14 kcal/mol
Top 34 with name 33 DFT: 11.68 kcal/mol
Top 35 with name 34 DFT: 10.7 kcal/mol
Top 36 with name 35 DFT: 9.39 kcal/mol
Top 37 with name 36 DFT: 8.53 kcal/mol
Top 38 with name 38 DFT: 6.65 kcal/mol
Top 39 with name 37 DFT: 6.63 kcal/mol
Top 40 with name 39 DFT: 6.45 kcal/mol
Top 41 with name 40 DFT: 5.11 kcal/mol
Top 42 with name 41 DFT: 3.25 kcal/mol
Top 43 with name 42 DFT: 2.64 kcal/mol
Top 44 with name 43 DFT: 2.48 kcal/mol
Top 45 with name 44 DFT: 2.11 kcal/mol
Top 46 with name 45 DFT: 1.47 kcal/mol
Top 47 with name 46 DFT: 1.15 kcal/mol
Top 48 with name 47 DFT: 0.86 kcal/mol
Top 49 with name 48 DFT: 0.43 kcal/mol
Top 50 with name 49 DFT: 0.41 kcal/mol
Top 51 with name 50 DFT: 0.18 kcal/mol
Top 1 with name 21 DFT: 89.5 kcal/mol
Top 2 with name 6 DFT: 83.5 kcal/mol
Top 3 with name 2 DFT: 78.4 kcal/mol
Top 4 with name 24 DFT: 54.7 kcal/mol
Top 5 with name 18 DFT: 54.2 kcal/mol
Top 6 with name 5 DFT: 48.0 kcal/mol
Top 7 with name 12 DFT: 41.7 kcal/mol
Top 8 with name 23 DFT: 38.0 kcal/mol
Top 9 with name 1 DFT: 33.7 kcal/mol
Top 10 with name 3 DFT: 32.1 kcal/mol
Top 11 with name 15 DFT: 31.4 kcal/mol
Top 12 with name 13 DFT: 29.3 kcal/mol
Top 13 with name 0 DFT: 29.2 kcal/mol
Top 14 with name 17 DFT: 28.8 kcal/mol
Top 15 with name 7 DFT: 27.9 kcal/mol
Top 16 with name 14 DFT: 25.1 kcal/mol
Top 17 with name 22 DFT: 24.9 kcal/mol
Top 18 with name 16 DFT: 23.5 kcal/mol
Top 19 with name 4 DFT: 17.3 kcal/mol
Top 20 with name 11 DFT: 16.8 kcal/mol
Top 21 with name 8 DFT: 13.4 kcal/mol
Top 22 with name 19 DFT: 9.5 kcal/mol
Top 23 with name 10 DFT: 8.3 kcal/mol
Top 24 with name 9 DFT: 1.2 kcal/mol
Top 25 with name 20 DFT: 0.2 kcal/mol
Top 1 with name 7 DFT: 401.7 kcal/mol
Top 2 with name 19 DFT: 371.311 kcal/mol
Top 3 with name 29 DFT: 359.365 kcal/mol
Top 4 with name 5 DFT: 335.3 kcal/mol
Top 5 with name 28 DFT: 322.986 kcal/mol
Top 6 with name 0 DFT: 314.9 kcal/mol
Top 7 with name 6 DFT: 313.8 kcal/mol
Top 8 with name 17 DFT: 300.917 kcal/mol
Top 9 with name 14 DFT: 299.1 kcal/mol
Top 10 with name 15 DFT: 296.339 kcal/mol
Top 11 with name 25 DFT: 294.459 kcal/mol
Top 12 with name 18 DFT: 292.648 kcal/mol
Top 13 with name 34 DFT: 291.699 kcal/mol
Top 14 with name 30 DFT: 277.727 kcal/mol
Top 15 with name 33 DFT: 265.083 kcal/mol
Top 16 with name 26 DFT: 264.585 kcal/mol
Top 17 with name 35 DFT: 261.153 kcal/mol
Top 18 with name 4 DFT: 259.6 kcal/mol
Top 19 with name 20 DFT: 255.387 kcal/mol
Top 20 with name 27 DFT: 243.709 kcal/mol
Top 21 with name 31 DFT: 242.854 kcal/mol
Top 22 with name 12 DFT: 241.9 kcal/mol
Top 23 with name 24 DFT: 239.3 kcal/mol
Top 24 with name 13 DFT: 239.0 kcal/mol
Top 25 with name 16 DFT: 235.69 kcal/mol
Top 26 with name 21 DFT: 234.107 kcal/mol
Top 27 with name 23 DFT: 227.822 kcal/mol
Top 28 with name 22 DFT: 226.367 kcal/mol
Top 29 with name 32 DFT: 215.737 kcal/mol
Top 30 with name 2 DFT: 214.9 kcal/mol
Top 31 with name 3 DFT: 190.4 kcal/mol
Top 32 with name 11 DFT: 188.0 kcal/mol
Top 33 with name 9 DFT: 176.3 kcal/mol
Top 34 with name 10 DFT: 138.0 kcal/mol
Top 35 with name 1 DFT: 123.3 kcal/mol
Top 36 with name 8 DFT: 118.5 kcal/mol
Top 1 with name 24 DFT: 216.11 kcal/mol
Top 2 with name 23 DFT: 154.04 kcal/mol
Top 3 with name 22 DFT: 135.4 kcal/mol
Top 4 with name 21 DFT: 109.11 kcal/mol
Top 5 with name 20 DFT: 81.21 kcal/mol
Top 6 with name 19 DFT: 68.9 kcal/mol
Top 7 with name 18 DFT: 65.15 kcal/mol
Top 8 with name 17 DFT: 61.67 kcal/mol
Top 9 with name 16 DFT: 49.2 kcal/mol
Top 10 with name 15 DFT: 48.52 kcal/mol
Top 11 with name 14 DFT: 39.43 kcal/mol
Top 12 with name 13 DFT: 36.32 kcal/mol
Top 13 with name 12 DFT: 32.71 kcal/mol
Top 14 with name 11 DFT: 29.46 kcal/mol
Top 15 with name 8 DFT: 27.3 kcal/mol
Top 16 with name 9 DFT: 27.15 kcal/mol
Top 17 with name 7 DFT: 26.97 kcal/mol
Top 18 with name 10 DFT: 24.89 kcal/mol
Top 19 with name 6 DFT: 19.47 kcal/mol
Top 20 with name 5 DFT: 10.7 kcal/mol
Top 21 with name 4 DFT: 7.1 kcal/mol
Top 22 with name 3 DFT: 4.1 kcal/mol
Top 23 with name 1 DFT: 2.26 kcal/mol
Top 24 with name 0 DFT: 2.23 kcal/mol
Top 25 with name 2 DFT: 2.18 kcal/mol
Top 1 with name 0 DFT: 73.82 kcal/mol
Top 2 with name 3 DFT: 67.85 kcal/mol
Top 3 with name 6 DFT: 61.85 kcal/mol
Top 4 with name 1 DFT: 61.74 kcal/mol
Top 5 with name 9 DFT: 59.65 kcal/mol
Top 6 with name 4 DFT: 58.37 kcal/mol
Top 7 with name 10 DFT: 53.17 kcal/mol
Top 8 with name 2 DFT: 52.92 kcal/mol
Top 9 with name 5 DFT: 52.91 kcal/mol
Top 10 with name 7 DFT: 52.18 kcal/mol
Top 11 with name 8 DFT: 43.79 kcal/mol
Top 1 with name 4 DFT: 48.9 kcal/mol
Top 2 with name 5 DFT: 46.1 kcal/mol
Top 3 with name 7 DFT: 40.4 kcal/mol
Top 4 with name 2 DFT: 37.6 kcal/mol
Top 5 with name 0 DFT: 32.1 kcal/mol
Top 6 with name 10 DFT: 31.2 kcal/mol
Top 7 with name 6 DFT: 25.2 kcal/mol
Top 8 with name 3 DFT: 19.5 kcal/mol
Top 9 with name 9 DFT: 18.5 kcal/mol
Top 10 with name 11 DFT: 17.6 kcal/mol
Top 11 with name 8 DFT: 15.2 kcal/mol
Top 12 with name 1 DFT: 0.2 kcal/mol
Top 1 with name 24 DFT: 236.0 kcal/mol
Top 2 with name 25 DFT: 235.1 kcal/mol
Top 3 with name 20 DFT: 221.3 kcal/mol
Top 4 with name 21 DFT: 219.6 kcal/mol
Top 5 with name 3 DFT: 219.2 kcal/mol
Top 6 with name 15 DFT: 218.2 kcal/mol
Top 7 with name 4 DFT: 211.9 kcal/mol
Top 8 with name 23 DFT: 210.7 kcal/mol
Top 9 with name 17 DFT: 210.2 kcal/mol
Top 10 with name 2 DFT: 209.2 kcal/mol
Top 11 with name 16 DFT: 200.4 kcal/mol
Top 12 with name 1 DFT: 192.9 kcal/mol
Top 13 with name 22 DFT: 192.9 kcal/mol
Top 14 with name 8 DFT: 192.8 kcal/mol
Top 15 with name 13 DFT: 191.9 kcal/mol
Top 16 with name 14 DFT: 190.9 kcal/mol
Top 17 with name 18 DFT: 188.3 kcal/mol
Top 18 with name 19 DFT: 181.9 kcal/mol
Top 19 with name 9 DFT: 174.3 kcal/mol
Top 20 with name 5 DFT: 171.4 kcal/mol
Top 21 with name 0 DFT: 167.2 kcal/mol
Top 22 with name 6 DFT: 157.4 kcal/mol
Top 23 with name 7 DFT: 156.9 kcal/mol
Top 24 with name 10 DFT: 137.8 kcal/mol
Top 25 with name 12 DFT: 120.8 kcal/mol
Top 26 with name 11 DFT: 106.2 kcal/mol
Top 1 with name 20 DFT: 126.56 kcal/mol
Top 2 with name 3 DFT: 59.44 kcal/mol
Top 3 with name 4 DFT: 57.93 kcal/mol
Top 4 with name 16 DFT: 50.66 kcal/mol
Top 5 with name 8 DFT: 49.85 kcal/mol
Top 6 with name 18 DFT: 49.73 kcal/mol
Top 7 with name 9 DFT: 45.16 kcal/mol
Top 8 with name 5 DFT: 36.56 kcal/mol
Top 9 with name 19 DFT: 32.81 kcal/mol
Top 10 with name 17 DFT: 30.38 kcal/mol
Top 11 with name 14 DFT: 28.12 kcal/mol
Top 12 with name 1 DFT: 26.66 kcal/mol
Top 13 with name 2 DFT: 24.74 kcal/mol
Top 14 with name 0 DFT: 23.43 kcal/mol
Top 15 with name 10 DFT: 22.24 kcal/mol
Top 16 with name 13 DFT: 22.03 kcal/mol
Top 17 with name 12 DFT: 21.21 kcal/mol
Top 18 with name 6 DFT: 17.91 kcal/mol
Top 19 with name 7 DFT: 16.8 kcal/mol
Top 20 with name 11 DFT: 6.72 kcal/mol
Top 21 with name 15 DFT: 0.73 kcal/mol
Top 1 with name 0 DFT: 64.4 kcal/mol
Top 2 with name 1 DFT: 58.9 kcal/mol
Top 3 with name 4 DFT: 56.9 kcal/mol
Top 4 with name 2 DFT: 48.7 kcal/mol
Top 5 with name 5 DFT: 46.9 kcal/mol
Top 6 with name 12 DFT: 39.7 kcal/mol
Top 7 with name 3 DFT: 38.3 kcal/mol
Top 8 with name 8 DFT: 35.9 kcal/mol
Top 9 with name 6 DFT: 31.3 kcal/mol
Top 10 with name 13 DFT: 29.1 kcal/mol
Top 11 with name 9 DFT: 25.9 kcal/mol
Top 12 with name 7 DFT: 19.1 kcal/mol
Top 13 with name 14 DFT: 16.9 kcal/mol
Top 14 with name 10 DFT: 13.4 kcal/mol
Top 15 with name 15 DFT: 9.3 kcal/mol
Top 16 with name 11 DFT: 4.9 kcal/mol
Top 1 with name 4 DFT: 13.03 kcal/mol
Top 2 with name 1 DFT: 6.56 kcal/mol
Top 3 with name 2 DFT: 5.44 kcal/mol
Top 4 with name 3 DFT: 5.25 kcal/mol
Top 5 with name 0 DFT: 4.3 kcal/mol
Top 6 with name 10 DFT: 2.85 kcal/mol
Top 7 with name 11 DFT: 2.15 kcal/mol
Top 8 with name 7 DFT: 1.45 kcal/mol
Top 9 with name 13 DFT: 0.95 kcal/mol
Top 10 with name 5 DFT: 0.93 kcal/mol
Top 11 with name 9 DFT: 0.87 kcal/mol
Top 12 with name 6 DFT: 0.74 kcal/mol
Top 13 with name 12 DFT: 0.55 kcal/mol
Top 14 with name 14 DFT: 0.45 kcal/mol
Top 15 with name 8 DFT: 0.17 kcal/mol
Warning: 15 in cc_ene_W4_11 has a large CC energy: 1007.909 kcal/mol
Top 1 with name 15 DFT: 1007.909 kcal/mol
Top 2 with name 23 DFT: 861.578 kcal/mol
Top 3 with name 25 DFT: 811.241 kcal/mol
Top 4 with name 52 DFT: 804.017 kcal/mol
Top 5 with name 20 DFT: 721.502 kcal/mol
Top 6 with name 14 DFT: 713.08 kcal/mol
Top 7 with name 38 DFT: 705.605 kcal/mol
Top 8 with name 40 DFT: 704.1 kcal/mol
Top 9 with name 39 DFT: 677.864 kcal/mol
Top 10 with name 44 DFT: 651.526 kcal/mol
Top 11 with name 66 DFT: 635.101 kcal/mol
Top 12 with name 11 DFT: 607.023 kcal/mol
Top 13 with name 21 DFT: 582.301 kcal/mol
Top 14 with name 41 DFT: 577.78 kcal/mol
Top 15 with name 43 DFT: 573.892 kcal/mol
Top 16 with name 27 DFT: 564.095 kcal/mol
Top 17 with name 8 DFT: 535.885 kcal/mol
Top 18 with name 62 DFT: 533.462 kcal/mol
Top 19 with name 28 DFT: 513.501 kcal/mol
Top 20 with name 90 DFT: 502.037 kcal/mol
Top 21 with name 64 DFT: 501.899 kcal/mol
Top 22 with name 32 DFT: 482.276 kcal/mol
Top 23 with name 69 DFT: 478.76 kcal/mol
Top 24 with name 26 DFT: 474.629 kcal/mol
Top 25 with name 42 DFT: 470.973 kcal/mol
Top 26 with name 76 DFT: 456.072 kcal/mol
Top 27 with name 36 DFT: 446.081 kcal/mol
Top 28 with name 50 DFT: 439.441 kcal/mol
Top 29 with name 49 DFT: 438.281 kcal/mol
Top 30 with name 45 DFT: 437.668 kcal/mol
Top 31 with name 81 DFT: 434.737 kcal/mol
Top 32 with name 46 DFT: 430.967 kcal/mol
Top 33 with name 22 DFT: 422.959 kcal/mol
Top 34 with name 77 DFT: 420.636 kcal/mol
Top 35 with name 10 DFT: 420.42 kcal/mol
Top 36 with name 33 DFT: 410.973 kcal/mol
Top 37 with name 78 DFT: 410.066 kcal/mol
Top 38 with name 86 DFT: 410.029 kcal/mol
Top 39 with name 53 DFT: 405.525 kcal/mol
Top 40 with name 67 DFT: 403.743 kcal/mol
Top 41 with name 70 DFT: 398.472 kcal/mol
Top 42 with name 84 DFT: 390.141 kcal/mol
Top 43 with name 85 DFT: 386.087 kcal/mol
Top 44 with name 12 DFT: 382.753 kcal/mol
Top 45 with name 54 DFT: 374.658 kcal/mol
Top 46 with name 97 DFT: 364.971 kcal/mol
Top 47 with name 48 DFT: 359.934 kcal/mol
Top 48 with name 98 DFT: 350.149 kcal/mol
Top 49 with name 107 DFT: 346.943 kcal/mol
Top 50 with name 55 DFT: 343.749 kcal/mol
Top 51 with name 65 DFT: 336.249 kcal/mol
Top 52 with name 93 DFT: 335.747 kcal/mol
Top 53 with name 104 DFT: 331.785 kcal/mol
Top 54 with name 3 DFT: 324.945 kcal/mol
Top 55 with name 58 DFT: 322.477 kcal/mol
Top 56 with name 60 DFT: 317.647 kcal/mol
Top 57 with name 71 DFT: 313.418 kcal/mol
Top 58 with name 59 DFT: 312.651 kcal/mol
Top 59 with name 102 DFT: 312.649 kcal/mol
Top 60 with name 101 DFT: 312.219 kcal/mol
Top 61 with name 47 DFT: 309.099 kcal/mol
Top 62 with name 9 DFT: 307.87 kcal/mol
Top 63 with name 72 DFT: 298.203 kcal/mol
Top 64 with name 24 DFT: 298.018 kcal/mol
Top 65 with name 80 DFT: 296.534 kcal/mol
Top 66 with name 82 DFT: 291.135 kcal/mol
Top 67 with name 116 DFT: 290.578 kcal/mol
Top 68 with name 95 DFT: 285.447 kcal/mol
Top 69 with name 4 DFT: 281.287 kcal/mol
Top 70 with name 103 DFT: 280.778 kcal/mol
Top 71 with name 74 DFT: 279.422 kcal/mol
Top 72 with name 113 DFT: 270.849 kcal/mol
Top 73 with name 79 DFT: 269.089 kcal/mol
Top 74 with name 73 DFT: 266.163 kcal/mol
Top 75 with name 110 DFT: 260.621 kcal/mol
Top 76 with name 75 DFT: 259.727 kcal/mol
Top 77 with name 83 DFT: 258.782 kcal/mol
Top 78 with name 68 DFT: 248.059 kcal/mol
Top 79 with name 13 DFT: 242.267 kcal/mol
Top 80 with name 128 DFT: 234.348 kcal/mol
Top 81 with name 120 DFT: 233.297 kcal/mol
Top 82 with name 114 DFT: 233.089 kcal/mol
Top 83 with name 34 DFT: 232.974 kcal/mol
Top 84 with name 91 DFT: 228.485 kcal/mol
Top 85 with name 124 DFT: 227.882 kcal/mol
Top 86 with name 57 DFT: 225.274 kcal/mol
Top 87 with name 92 DFT: 224.864 kcal/mol
Top 88 with name 1 DFT: 213.169 kcal/mol
Top 89 with name 121 DFT: 208.781 kcal/mol
Top 90 with name 99 DFT: 205.89 kcal/mol
Top 91 with name 94 DFT: 193.052 kcal/mol
Top 92 with name 6 DFT: 190.745 kcal/mol
Top 93 with name 18 DFT: 183.913 kcal/mol
Top 94 with name 30 DFT: 182.591 kcal/mol
Top 95 with name 56 DFT: 182.517 kcal/mol
Top 96 with name 16 DFT: 181.456 kcal/mol
Top 97 with name 106 DFT: 181.35 kcal/mol
Top 98 with name 108 DFT: 177.357 kcal/mol
Top 99 with name 96 DFT: 175.533 kcal/mol
Top 100 with name 105 DFT: 172.218 kcal/mol
Top 101 with name 126 DFT: 168.364 kcal/mol
Top 102 with name 89 DFT: 166.229 kcal/mol
Top 103 with name 88 DFT: 165.128 kcal/mol
Top 104 with name 51 DFT: 163.78 kcal/mol
Top 105 with name 100 DFT: 158.653 kcal/mol
Top 106 with name 111 DFT: 152.745 kcal/mol
Top 107 with name 136 DFT: 152.369 kcal/mol
Top 108 with name 137 DFT: 147.428 kcal/mol
Top 109 with name 130 DFT: 147.023 kcal/mol
Top 110 with name 63 DFT: 142.71 kcal/mol
Top 111 with name 35 DFT: 141.64 kcal/mol
Top 112 with name 134 DFT: 134.721 kcal/mol
Top 113 with name 87 DFT: 132.721 kcal/mol
Top 114 with name 131 DFT: 128.12 kcal/mol
Top 115 with name 112 DFT: 126.465 kcal/mol
Top 116 with name 135 DFT: 126.385 kcal/mol
Top 117 with name 61 DFT: 122.618 kcal/mol
Top 118 with name 118 DFT: 120.824 kcal/mol
Top 119 with name 122 DFT: 117.593 kcal/mol
Top 120 with name 0 DFT: 109.493 kcal/mol
Top 121 with name 29 DFT: 107.499 kcal/mol
Top 122 with name 37 DFT: 107.208 kcal/mol
Top 123 with name 109 DFT: 105.815 kcal/mol
Top 124 with name 138 DFT: 105.239 kcal/mol
Top 125 with name 115 DFT: 104.251 kcal/mol
Top 126 with name 127 DFT: 101.457 kcal/mol
Top 127 with name 132 DFT: 93.78 kcal/mol
Top 128 with name 19 DFT: 87.731 kcal/mol
Top 129 with name 5 DFT: 84.995 kcal/mol
Top 130 with name 17 DFT: 84.221 kcal/mol
Top 131 with name 31 DFT: 83.096 kcal/mol
Top 132 with name 7 DFT: 73.921 kcal/mol
Top 133 with name 2 DFT: 73.57 kcal/mol
Top 134 with name 133 DFT: 67.459 kcal/mol
Top 135 with name 125 DFT: 65.447 kcal/mol
Top 136 with name 123 DFT: 62.8 kcal/mol
Top 137 with name 117 DFT: 59.75 kcal/mol
Top 138 with name 129 DFT: 53.075 kcal/mol
Top 139 with name 119 DFT: 39.042 kcal/mol
Top 140 with name 139 DFT: 2.669 kcal/mol
Top 1 with name 1 DFT: 91.14 kcal/mol
Top 2 with name 17 DFT: 78.0 kcal/mol
Top 3 with name 13 DFT: 76.37 kcal/mol
Top 4 with name 16 DFT: 66.59 kcal/mol
Top 5 with name 15 DFT: 60.11 kcal/mol
Top 6 with name 0 DFT: 57.17 kcal/mol
Top 7 with name 7 DFT: 53.73 kcal/mol
Top 8 with name 12 DFT: 52.28 kcal/mol
Top 9 with name 5 DFT: 51.74 kcal/mol
Top 10 with name 14 DFT: 44.8 kcal/mol
Top 11 with name 11 DFT: 42.81 kcal/mol
Top 12 with name 10 DFT: 42.11 kcal/mol
Top 13 with name 4 DFT: 38.99 kcal/mol
Top 14 with name 3 DFT: 36.4 kcal/mol
Top 15 with name 8 DFT: 32.58 kcal/mol
Top 16 with name 9 DFT: 28.87 kcal/mol
Top 17 with name 2 DFT: 20.96 kcal/mol
Top 18 with name 6 DFT: 12.31 kcal/mol
Warning: AL2X6-alcl3 not found in data file
Warning: AL2X6-al2f6 not found in data file
Warning: AL2X6-alh3 not found in data file
Warning: AL2X6-alme2 not found in data file
Warning: AL2X6-al2h6 not found in data file
Warning: AL2X6-al2cl6 not found in data file
Warning: AL2X6-al2me5 not found in data file
Warning: AL2X6-al2me4 not found in data file
Warning: AL2X6-alme3 not found in data file
Warning: AL2X6-al2me6 not found in data file
Warning: AL2X6-alf3 not found in data file
Warning: AL2X6-al2h6 not found in data csv file
Warning: AL2X6-al2f6 not found in data csv file
Warning: AL2X6-al2cl6 not found in data csv file
Warning: AL2X6-al2me4 not found in data csv file
Warning: AL2X6-al2me5 not found in data csv file
Warning: AL2X6-al2me6 not found in data csv file
Warning: ALK8-li5_ch not found in data file
Warning: ALK8-na2 not found in data file

/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

          cc_ene b3lyp_ene b3lyp-d3bj_ene Processed
sub1  155.762918   5.03683       4.627682    3 / 18
sub2   97.057338  36.89058      15.174867     1 / 9
sub3   22.721031       NaN            NaN     0 / 7
sub4   18.410852  1.385127       1.236351    0 / 12
sub5    3.557344  0.741932       0.290605     0 / 9

wtmad_1

             cc_ene  b3lyp_ene b3lyp-d3bj_ene Processed
sub1      37.583104    2.84512       2.828378    3 / 18
sub2      26.253228   7.972577       2.910386     1 / 9
sub3       35.39219        NaN            NaN     0 / 7
sub4        33.0659  13.851267       12.36351    0 / 12
sub5      31.862853   9.556913       3.221594     0 / 9
summary  164.157275        NaN            NaN        --

wtmad_2

            cc_ene b3lyp_ene b3lyp-d3bj_ene Processed
sub1        17.864  1.620095        1.57518    3 / 18
sub2      9.177488   4.50525        1.57478     1 / 9
sub3      7.326884       0.0            0.0     0 / 7
sub4     11.481302  1.406328       1.255275    0 / 12
sub5     10.990326  1.210652       0.499207     0 / 9
summary      56.84  8.742324       4.904443        --

Summary of Subset
MAE

               cc_ene  b3lyp_ene b3lyp-d3bj_ene Processed
AL2X6       35.883333          0              0     0 / 6
ALK8         62.60125          0              0     0 / 8
ALKBDE10       100.69          0              0    0 / 10
BH76RC      21.391667          0              0    0 / 30
DC13        54.978462          0              0    0 / 13
DIPCS10        654.26   3.794038       3.781285    9 / 10
FH51         31.01098          0              0    0 / 51
G21EA          33.624  10.168724      10.163771      DONE
G21IP      257.609583   3.806944       3.813164      DONE
G2RC          51.2632          0              0    0 / 25
HEAVYSB11   58.022727          0              0    0 / 11
NBPRC       27.708333          0              0    0 / 12
PA26       189.053846          0              0    0 / 26
RC21        35.698571          0              0    0 / 21
SIE4x4         33.725          0              0    0 / 16
TAUT15          3.046          0              0    0 / 15
W4_11      306.914464   4.516571       3.902954      DONE
YBDE18      49.275556          0              0    0 / 18
BSR36       16.196944  10.208393       3.399603   33 / 36
C60ISO      98.252222          0              0     0 / 9
CDIE20          4.055          0              0    0 / 20
DARC        32.471429          0              0    0 / 14
ISO34           14.57          0              0    0 / 34
ISOL24       21.91875          0              0    0 / 24
MB16_43    468.393795  57.367607      24.211697      DONE
PArel          4.6305          0              0    0 / 20
RSE43        7.602326          0              0    0 / 43
BH76        18.614474          0              0    0 / 76
BHDIV10        45.333          0              0    0 / 10
BHPERI      20.873077          0              0    0 / 26
BHROT27      6.272963          0              0    0 / 27
INV24       31.845833          0              0    0 / 24
PX13        33.361538          0              0    0 / 13
WCPT18      34.987778          0              0    0 / 18
ADIM6        3.358333          0              0     0 / 6
AHB21        22.48619          0              0    0 / 21
CARBHB12     6.035333          0              0    0 / 12
CHB6           26.785          0              0     0 / 6
HAL59        4.592203          0              0    0 / 59
HEAVY28      1.241429          0              0    0 / 28
IL16          109.045          0              0    0 / 16
PNICO23      4.273478          0              0    0 / 23
RG18             0.58          0              0    0 / 18
S22          7.302364          0              0    0 / 22
S66           5.46697   1.385127       1.236351   39 / 66
WATER27     81.140111          0              0    0 / 27
ACONF        1.834133          0              0    0 / 15
Amino20x4    2.438687   0.485421        0.25274   24 / 80
BUT14DIOL    2.799688          0              0    0 / 64
ICONF        3.266471          0              0    0 / 17
IDISP       14.223333          0              0     0 / 6
MCONF         4.97098   1.425961       0.391578    9 / 51
PCONF21      1.621667          0              0    0 / 18
SCONF             4.6          0              0    0 / 17
UPU23        5.722609          0              0    0 / 23

In [2]:
mean_absolute_deviation_list

[]