In [7]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
with open(
    "/home/chenzihao/workspace/cc2cc_test5/jupyter-notebook/new_dataset/gmtkn-def2.json"
) as f:
    json_data = json.load(f)

dft_type_list = ["b3lyp_ene", "b3lyp-d3bj_ene"]
data = pd.read_csv(
    "/home/chenzihao/workspace/cc2cc_test5/validate_hkqai/ccdft_def2-TZVPD__gmtkn-def2.csv"
)

basis_args = "def2-TZVPD"
print(basis_args)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for dft_type in dft_type_list:
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data[dft_type].to_numpy() * 627.5094733748099

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "cc": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(f"Warning: {i_molecule_name} not found in data file")
                    continue

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data csv file")
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    atomic_energy_cc = i_reaction["reference"]
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ]
                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} with name {data_subset[name_subset]["name"][argsort_atomic_energy_dft[i]]} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

header = dft_type_list + ["Processed"]

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

for dft_type in dft_type_list:
    mean_absolute_deviation_list = []

    for name_set, subset_list_ in full_subset_dict.items():
        subset_dft = []
        wtmad_1_dft = []
        wtmad_2_dft = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"

            if len(data_subset[name_subset]["dft"]) == 0:
                df_summary_subset.loc[i_subset, dft_type] = 0
                df_summary_subset.loc[i_subset, "Processed"] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                df_summary_subset.loc[i_subset, dft_type] = np.mean(
                    data_subset[name_subset]["dft"]
                )
                df_summary_subset.loc[i_subset, "Processed"] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["dft"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["dft"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['dft'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                subset_dft = np.append(subset_dft, data_subset[name_subset]["dft"])
                wtmad_1_dft = np.append(
                    wtmad_1_dft,
                    wtmad_1 * np.mean(data_subset[name_subset]["dft"]),
                )
                wtmad_2_dft = np.append(
                    wtmad_2_dft,
                    data_subset[name_subset]["dft"]
                    / np.mean(data_subset[name_subset]["cc"]),
                )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["dft"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)

        mean_subset.loc[name_set, dft_type] = np.mean(subset_dft)
        wtmad_1_subset.loc[name_set, dft_type] = np.mean(wtmad_1_dft)
        wtmad_2_subset.loc[name_set, dft_type] = np.sum(wtmad_2_dft)
        mean_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {dft_type}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        wtmad_2_subset.loc[name_set, dft_type] = (
            mean_absolute_deviation * wtmad_2_subset.loc[name_set, dft_type]
        )

    wtmad_1_subset.loc["summary", "Processed"] = "--"
    wtmad_2_subset.loc["summary", "Processed"] = "--"
    wtmad_1_subset.loc["summary", dft_type] = 0
    wtmad_2_subset.loc["summary", dft_type] = 0
    for name_set in full_subset_dict.keys():
        wtmad_1_subset.loc["summary", dft_type] += wtmad_1_subset.loc[
            name_set, dft_type
        ]
        wtmad_2_subset.loc["summary", dft_type] += wtmad_2_subset.loc[
            name_set, dft_type
        ]

print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# # save summary to csv with date
# df_summary_subset_ele.to_csv(f"../validate_hkqai_done/df_summary_subset_ele_{date}.csv")
# df_summary_subset.to_csv(f"../validate_hkqai_done/summary_subset_{date}.csv")
# mean_subset.to_csv(f"../validate_hkqai_done/mean_subset_{date}.csv")
# wtmad_1_subset.to_csv(f"../validate_hkqai_done/wtmad_1_subset_{date}.csv")
# wtmad_2_subset.to_csv(f"../validate_hkqai_done/wtmad_2_subset_{date}.csv")
# # save summary to excel with date
# df_summary_subset_ele.to_excel(
#     f"../validate_hkqai_done/df_summary_subset_ele_{date}.xlsx"
# )
# df_summary_subset.to_excel(f"../validate_hkqai_done/summary_subset_{date}.xlsx")
# mean_subset.to_excel(f"../validate_hkqai_done/mean_subset_{date}.xlsx")
# wtmad_1_subset.to_excel(f"../validate_hkqai_done/wtmad_1_subset_{date}.xlsx")
# wtmad_2_subset.to_excel(f"../validate_hkqai_done/wtmad_2_subset_{date}.xlsx")

def2-TZVPD
Warning: 15 in b3lyp_ene_W4_11 has a large CC energy: 1007.909 kcal/mol
Top 1 with name 130 DFT: 27.611040291833746 kcal/mol
Top 2 with name 41 DFT: 23.57685816803246 kcal/mol
Top 3 with name 59 DFT: 18.465193503116268 kcal/mol
Top 4 with name 46 DFT: 16.66766832751034 kcal/mol
Top 5 with name 107 DFT: 15.832422816137068 kcal/mol
Top 6 with name 128 DFT: 14.61009749176634 kcal/mol
Top 7 with name 138 DFT: 13.297855736038827 kcal/mol
Top 8 with name 69 DFT: 11.406077101526307 kcal/mol
Top 9 with name 110 DFT: 10.347673006909531 kcal/mol
Top 10 with name 116 DFT: 10.09249907268395 kcal/mol
Top 11 with name 104 DFT: 9.494733162737077 kcal/mol
Top 12 with name 121 DFT: 8.97286860715127 kcal/mol
Top 13 with name 126 DFT: 8.6950050329892 kcal/mol
Top 14 with name 42 DFT: 7.896587854456868 kcal/mol
Top 15 with name 137 DFT: 7.588451093484878 kcal/mol
Top 16 with name 133 DFT: 7.502828200650754 kcal/mol
Top 17 with name 52 DFT: 7.398278573773268 kcal/mol
Top 18 with name 92 DFT: 7.265498392404112 kcal/mol
Top 19 with name 25 DFT: 6.318844065279563 kcal/mol
Top 20 with name 108 DFT: 6.066708797512575 kcal/mol
Top 21 with name 47 DFT: 5.981111170445558 kcal/mol
Top 22 with name 105 DFT: 5.940713660885336 kcal/mol
Top 23 with name 15 DFT: 5.940200654218074 kcal/mol
Top 24 with name 77 DFT: 5.8344546620806454 kcal/mol
Top 25 with name 94 DFT: 5.682163696674564 kcal/mol
Top 26 with name 12 DFT: 5.633922168835227 kcal/mol
Top 27 with name 86 DFT: 5.41127710517344 kcal/mol
Top 28 with name 127 DFT: 5.320951588653429 kcal/mol
Top 29 with name 109 DFT: 5.318986072709379 kcal/mol
Top 30 with name 61 DFT: 5.285767882056064 kcal/mol
Top 31 with name 57 DFT: 5.268409085600638 kcal/mol
Top 32 with name 8 DFT: 5.225985320785185 kcal/mol
Top 33 with name 66 DFT: 5.225460192086871 kcal/mol
Top 34 with name 113 DFT: 4.810971175227849 kcal/mol
Top 35 with name 75 DFT: 4.801851547564297 kcal/mol
Top 36 with name 44 DFT: 4.792024344445622 kcal/mol
Top 37 with name 51 DFT: 4.686919912551531 kcal/mol
Top 38 with name 124 DFT: 4.611729423251347 kcal/mol
Top 39 with name 64 DFT: 4.597158369278418 kcal/mol
Top 40 with name 55 DFT: 4.486221829112537 kcal/mol
Top 41 with name 31 DFT: 4.466884363246322 kcal/mol
Top 42 with name 76 DFT: 4.408330251908978 kcal/mol
Top 43 with name 30 DFT: 4.3676576296398935 kcal/mol
Top 44 with name 117 DFT: 4.338699675980024 kcal/mol
Top 45 with name 89 DFT: 4.3224525904595055 kcal/mol
Top 46 with name 26 DFT: 4.3186985074165705 kcal/mol
Top 47 with name 65 DFT: 4.229258184227547 kcal/mol
Top 48 with name 20 DFT: 4.097138864526187 kcal/mol
Top 49 with name 23 DFT: 4.095734898341789 kcal/mol
Top 50 with name 38 DFT: 4.002598258064609 kcal/mol
Top 51 with name 73 DFT: 3.9396448509622815 kcal/mol
Top 52 with name 45 DFT: 3.9233306772267724 kcal/mol
Top 53 with name 79 DFT: 3.8530097216499257 kcal/mol
Top 54 with name 103 DFT: 3.8307202103985674 kcal/mol
Top 55 with name 32 DFT: 3.811296333500934 kcal/mol
Top 56 with name 83 DFT: 3.804160333406628 kcal/mol
Top 57 with name 97 DFT: 3.7729293657395147 kcal/mol
Top 58 with name 80 DFT: 3.7408904758336803 kcal/mol
Top 59 with name 82 DFT: 3.7384341303352357 kcal/mol
Top 60 with name 34 DFT: 3.662401784340375 kcal/mol
Top 61 with name 49 DFT: 3.6323773220673843 kcal/mol
Top 62 with name 131 DFT: 3.6244222529977606 kcal/mol
Top 63 with name 33 DFT: 3.495592246270519 kcal/mol
Top 64 with name 28 DFT: 3.401511663943211 kcal/mol
Top 65 with name 39 DFT: 3.3958577365883684 kcal/mol
Top 66 with name 35 DFT: 3.3658788926410352 kcal/mol
Top 67 with name 67 DFT: 3.350334882826189 kcal/mol
Top 68 with name 4 DFT: 3.2588737194602686 kcal/mol
Top 69 with name 85 DFT: 3.1802368574722095 kcal/mol
Top 70 with name 53 DFT: 3.0891923022728633 kcal/mol
Top 71 with name 70 DFT: 3.0639423485951056 kcal/mol
Top 72 with name 56 DFT: 2.933704120398204 kcal/mol
Top 73 with name 84 DFT: 2.8033090566281658 kcal/mol
Top 74 with name 93 DFT: 2.7463075693783026 kcal/mol
Top 75 with name 29 DFT: 2.741228096816684 kcal/mol
Top 76 with name 118 DFT: 2.6714347654565955 kcal/mol
Top 77 with name 43 DFT: 2.642470183498858 kcal/mol
Top 78 with name 14 DFT: 2.602043035627844 kcal/mol
Top 79 with name 58 DFT: 2.5972851126897467 kcal/mol
Top 80 with name 95 DFT: 2.574807978504282 kcal/mol
Top 81 with name 123 DFT: 2.5339672884554574 kcal/mol
Top 82 with name 60 DFT: 2.4851093670930027 kcal/mol
Top 83 with name 81 DFT: 2.4469912789024306 kcal/mol
Top 84 with name 100 DFT: 2.42313574854208 kcal/mol
Top 85 with name 119 DFT: 2.4137452327400695 kcal/mol
Top 86 with name 18 DFT: 2.2314709450870396 kcal/mol
Top 87 with name 13 DFT: 2.22708577176644 kcal/mol
Top 88 with name 106 DFT: 2.221084951410006 kcal/mol
Top 89 with name 129 DFT: 2.1270977685388033 kcal/mol
Top 90 with name 111 DFT: 2.0611907413939434 kcal/mol
Top 91 with name 63 DFT: 2.0189620959071988 kcal/mol
Top 92 with name 88 DFT: 1.8910382562323207 kcal/mol
Top 93 with name 78 DFT: 1.782234172997562 kcal/mol
Top 94 with name 11 DFT: 1.7456927336251056 kcal/mol
Top 95 with name 54 DFT: 1.738045356349744 kcal/mol
Top 96 with name 27 DFT: 1.683791258689098 kcal/mol
Top 97 with name 22 DFT: 1.542259733270214 kcal/mol
Top 98 with name 9 DFT: 1.4484867919152293 kcal/mol
Top 99 with name 122 DFT: 1.4426497767628206 kcal/mol
Top 100 with name 24 DFT: 1.441786744795479 kcal/mol
Top 101 with name 50 DFT: 1.3828437458639087 kcal/mol
Top 102 with name 139 DFT: 1.326513583675347 kcal/mol
Top 103 with name 3 DFT: 1.2830622195741057 kcal/mol
Top 104 with name 5 DFT: 1.2417716930435745 kcal/mol
Top 105 with name 96 DFT: 1.2344470592464916 kcal/mol
Top 106 with name 16 DFT: 1.0877893975381028 kcal/mol
Top 107 with name 6 DFT: 1.0115550514238976 kcal/mol
Top 108 with name 17 DFT: 1.0012628462064868 kcal/mol
Top 109 with name 90 DFT: 0.9897481217961399 kcal/mol
Top 110 with name 134 DFT: 0.9561979237528249 kcal/mol
Top 111 with name 7 DFT: 0.936098858398438 kcal/mol
Top 112 with name 115 DFT: 0.8855799096743624 kcal/mol
Top 113 with name 91 DFT: 0.8429418681922698 kcal/mol
Top 114 with name 87 DFT: 0.7676120341980095 kcal/mol
Top 115 with name 132 DFT: 0.7227378048640105 kcal/mol
Top 116 with name 1 DFT: 0.7105899885630436 kcal/mol
Top 117 with name 48 DFT: 0.6945693103785402 kcal/mol
Top 118 with name 68 DFT: 0.6440084710352778 kcal/mol
Top 119 with name 2 DFT: 0.5934342903980792 kcal/mol
Top 120 with name 136 DFT: 0.5920440816468329 kcal/mol
Top 121 with name 40 DFT: 0.5822607713336083 kcal/mol
Top 122 with name 72 DFT: 0.5795083488933415 kcal/mol
Top 123 with name 36 DFT: 0.5645667172193498 kcal/mol
Top 124 with name 0 DFT: 0.5562926509338126 kcal/mol
Top 125 with name 71 DFT: 0.5511928987274359 kcal/mol
Top 126 with name 135 DFT: 0.5422768063383359 kcal/mol
Top 127 with name 101 DFT: 0.5346341481808281 kcal/mol
Top 128 with name 74 DFT: 0.5174281965578302 kcal/mol
Top 129 with name 98 DFT: 0.45150393379299203 kcal/mol
Top 130 with name 125 DFT: 0.44125064744014253 kcal/mol
Top 131 with name 62 DFT: 0.4010208324573341 kcal/mol
Top 132 with name 21 DFT: 0.36487253580378365 kcal/mol
Top 133 with name 114 DFT: 0.32164161405665936 kcal/mol
Top 134 with name 19 DFT: 0.29845719161653506 kcal/mol
Top 135 with name 10 DFT: 0.29523479548100795 kcal/mol
Top 136 with name 102 DFT: 0.25392905612045524 kcal/mol
Top 137 with name 120 DFT: 0.2373272041645862 kcal/mol
Top 138 with name 112 DFT: 0.21817869253195 kcal/mol
Top 139 with name 37 DFT: 0.20333321913605573 kcal/mol
Top 140 with name 99 DFT: 0.13031402873514253 kcal/mol
Top 1 with name 24 DFT: 9.904605866945346 kcal/mol
Top 2 with name 3 DFT: 6.930933471675964 kcal/mol
Top 3 with name 17 DFT: 5.440032400318888 kcal/mol
Top 4 with name 16 DFT: 5.070773703919258 kcal/mol
Top 5 with name 1 DFT: 5.049622271316181 kcal/mol
Top 6 with name 0 DFT: 4.686041389231104 kcal/mol
Top 7 with name 13 DFT: 4.615256846370176 kcal/mol
Top 8 with name 20 DFT: 4.4624646871408915 kcal/mol
Top 9 with name 11 DFT: 4.002130484598457 kcal/mol
Top 10 with name 4 DFT: 3.8773998088261585 kcal/mol
Top 11 with name 9 DFT: 3.8096223570093573 kcal/mol
Top 12 with name 10 DFT: 3.5156274029111962 kcal/mol
Top 13 with name 2 DFT: 3.1035703690009484 kcal/mol
Top 14 with name 21 DFT: 2.8670772582190693 kcal/mol
Top 15 with name 5 DFT: 2.8280708657985087 kcal/mol
Top 16 with name 19 DFT: 2.381995580319199 kcal/mol
Top 17 with name 7 DFT: 1.5823678388500397 kcal/mol
Top 18 with name 14 DFT: 1.4780141944298535 kcal/mol
Top 19 with name 6 DFT: 1.3128084019990638 kcal/mol
Top 20 with name 15 DFT: 1.2693794942519148 kcal/mol
Top 21 with name 12 DFT: 0.9350290512709734 kcal/mol
Top 22 with name 22 DFT: 0.6584193373506437 kcal/mol
Top 23 with name 18 DFT: 0.3451152852678234 kcal/mol
Top 24 with name 23 DFT: 0.2579652455751784 kcal/mol
Top 25 with name 8 DFT: 0.023578944534529356 kcal/mol
Top 1 with name 6 DFT: 11.994420880600217 kcal/mol
Top 2 with name 30 DFT: 11.198511143243081 kcal/mol
Top 3 with name 3 DFT: 11.102902316262401 kcal/mol
Top 4 with name 7 DFT: 6.982573409343615 kcal/mol
Top 5 with name 4 DFT: 6.447041530651745 kcal/mol
Top 6 with name 1 DFT: 6.440403341381355 kcal/mol
Top 7 with name 8 DFT: 6.208424147014739 kcal/mol
Top 8 with name 17 DFT: 6.081605592802077 kcal/mol
Top 9 with name 29 DFT: 5.663181566347475 kcal/mol
Top 10 with name 31 DFT: 5.138980756331222 kcal/mol
Top 11 with name 27 DFT: 5.1102450101799946 kcal/mol
Top 12 with name 26 DFT: 4.970480125660231 kcal/mol
Top 13 with name 2 DFT: 4.860140306924592 kcal/mol
Top 14 with name 13 DFT: 4.428926967637381 kcal/mol
Top 15 with name 32 DFT: 4.297626231354201 kcal/mol
Top 16 with name 28 DFT: 3.6267041144209315 kcal/mol
Top 17 with name 15 DFT: 3.5597075491787677 kcal/mol
Top 18 with name 33 DFT: 2.868790243069668 kcal/mol
Top 19 with name 5 DFT: 2.5966764246942944 kcal/mol
Top 20 with name 12 DFT: 2.438028145092545 kcal/mol
Top 21 with name 14 DFT: 2.386614036257356 kcal/mol
Top 22 with name 22 DFT: 2.384600739371507 kcal/mol
Top 23 with name 9 DFT: 2.256199966333213 kcal/mol
Top 24 with name 24 DFT: 2.1697309563343765 kcal/mol
Top 25 with name 35 DFT: 2.059066391541137 kcal/mol
Top 26 with name 20 DFT: 1.9388323962751315 kcal/mol
Top 27 with name 34 DFT: 1.2290121661857825 kcal/mol
Top 28 with name 23 DFT: 1.083152361956195 kcal/mol
Top 29 with name 11 DFT: 0.8646865375631023 kcal/mol
Top 30 with name 10 DFT: 0.6780062147590797 kcal/mol
Top 31 with name 18 DFT: 0.5908398662348873 kcal/mol
Top 32 with name 19 DFT: 0.5423262584897088 kcal/mol
Top 33 with name 25 DFT: 0.4064120821687425 kcal/mol
Top 34 with name 21 DFT: 0.30247581487125785 kcal/mol
Top 35 with name 0 DFT: 0.20653267110810702 kcal/mol
Top 36 with name 16 DFT: 0.09483055792719597 kcal/mol
Top 1 with name 8 DFT: 12.610150163475168 kcal/mol
Top 2 with name 0 DFT: 6.853675324196274 kcal/mol
Top 3 with name 3 DFT: 6.546693096630065 kcal/mol
Top 4 with name 2 DFT: 5.569567090785085 kcal/mol
Top 5 with name 5 DFT: 4.602507019319432 kcal/mol
Top 6 with name 9 DFT: 4.311729069869443 kcal/mol
Top 7 with name 4 DFT: 2.0495517814852064 kcal/mol
Top 8 with name 6 DFT: 0.9798427875794005 kcal/mol
Top 9 with name 1 DFT: 0.3803614108197735 kcal/mol
Top 10 with name 7 DFT: 0.204125245416094 kcal/mol
Top 1 with name 3 DFT: 8.364119006594422 kcal/mol
Top 2 with name 2 DFT: 7.039676197437814 kcal/mol
Top 3 with name 1 DFT: 5.540360867796693 kcal/mol
Top 4 with name 21 DFT: 3.902054159820551 kcal/mol
Top 5 with name 19 DFT: 3.333203445328394 kcal/mol
Top 6 with name 16 DFT: 3.139571484929178 kcal/mol
Top 7 with name 17 DFT: 2.475518245669093 kcal/mol
Top 8 with name 12 DFT: 2.2872699422761826 kcal/mol
Top 9 with name 24 DFT: 2.1134930378757417 kcal/mol
Top 10 with name 22 DFT: 1.8446241328143458 kcal/mol
Top 11 with name 11 DFT: 1.5583528780876605 kcal/mol
Top 12 with name 25 DFT: 1.3009520827676226 kcal/mol
Top 13 with name 18 DFT: 1.235141620377533 kcal/mol
Top 14 with name 5 DFT: 1.083484594308544 kcal/mol
Top 15 with name 0 DFT: 1.0314606251166083 kcal/mol
Top 16 with name 6 DFT: 0.9897481098465448 kcal/mol
Top 17 with name 4 DFT: 0.9388240020765863 kcal/mol
Top 18 with name 23 DFT: 0.8703064805129657 kcal/mol
Top 19 with name 13 DFT: 0.6781550064828537 kcal/mol
Top 20 with name 15 DFT: 0.6363286628213132 kcal/mol
Top 21 with name 7 DFT: 0.583953170361923 kcal/mol
Top 22 with name 9 DFT: 0.542819142650103 kcal/mol
Top 23 with name 20 DFT: 0.3435778650571706 kcal/mol
Top 24 with name 14 DFT: 0.3169484471087287 kcal/mol
Top 25 with name 8 DFT: 0.3097306966548672 kcal/mol
Top 26 with name 10 DFT: 0.0761921745608447 kcal/mol
Top 1 with name 7 DFT: 40.15733931362174 kcal/mol
Top 2 with name 6 DFT: 33.56978964504124 kcal/mol
Top 3 with name 5 DFT: 26.41469875289122 kcal/mol
Top 4 with name 15 DFT: 25.90598320060526 kcal/mol
Top 5 with name 14 DFT: 21.68370324150019 kcal/mol
Top 6 with name 11 DFT: 20.513234967156315 kcal/mol
Top 7 with name 4 DFT: 19.384005983327462 kcal/mol
Top 8 with name 10 DFT: 16.388850540659043 kcal/mol
Top 9 with name 13 DFT: 16.205864043635664 kcal/mol
Top 10 with name 3 DFT: 12.369587686665184 kcal/mol
Top 11 with name 9 DFT: 11.559479355005898 kcal/mol
Top 12 with name 12 DFT: 9.594859869725767 kcal/mol
Top 13 with name 2 DFT: 8.895709386909957 kcal/mol
Top 14 with name 8 DFT: 6.134713744695183 kcal/mol
Top 15 with name 1 DFT: 5.749405327474484 kcal/mol
Top 16 with name 0 DFT: 2.7989611513385455 kcal/mol
Top 1 with name 7 DFT: 10.282103619628472 kcal/mol
Top 2 with name 8 DFT: 10.121912064659412 kcal/mol
Top 3 with name 3 DFT: 3.8224094315824857 kcal/mol
Top 4 with name 4 DFT: 3.7145810987931327 kcal/mol
Top 5 with name 5 DFT: 3.4680243861250233 kcal/mol
Top 6 with name 9 DFT: 2.627488775560053 kcal/mol
Top 7 with name 2 DFT: 1.9228126216301433 kcal/mol
Top 8 with name 1 DFT: 1.4065043556314833 kcal/mol
Top 9 with name 6 DFT: 1.235276871419046 kcal/mol
Top 10 with name 0 DFT: 0.7736369716105287 kcal/mol
Top 1 with name 10 DFT: 17.6906903490884 kcal/mol
Top 2 with name 12 DFT: 15.90333042859973 kcal/mol
Top 3 with name 16 DFT: 15.810574438033512 kcal/mol
Top 4 with name 4 DFT: 13.914437037305326 kcal/mol
Top 5 with name 0 DFT: 12.19176925125241 kcal/mol
Top 6 with name 14 DFT: 11.999637068071749 kcal/mol
Top 7 with name 2 DFT: 9.979780447895756 kcal/mol
Top 8 with name 8 DFT: 9.357945662950513 kcal/mol
Top 9 with name 11 DFT: 7.759930556831534 kcal/mol
Top 10 with name 13 DFT: 7.229900498486245 kcal/mol
Top 11 with name 17 DFT: 5.991935567129985 kcal/mol
Top 12 with name 6 DFT: 5.133506611413905 kcal/mol
Top 13 with name 5 DFT: 4.139005399100135 kcal/mol
Top 14 with name 1 DFT: 3.809941610030947 kcal/mol
Top 15 with name 15 DFT: 3.6606961890641827 kcal/mol
Top 16 with name 9 DFT: 1.9000685218462614 kcal/mol
Top 17 with name 7 DFT: 1.5933303227025348 kcal/mol
Top 18 with name 3 DFT: 1.4477796831837608 kcal/mol
Top 1 with name 5 DFT: 13.322228016122246 kcal/mol
Top 2 with name 2 DFT: 10.349332842277363 kcal/mol
Top 3 with name 4 DFT: 10.240575084858573 kcal/mol
Top 4 with name 3 DFT: 7.298820923059246 kcal/mol
Top 5 with name 1 DFT: 7.274165495322087 kcal/mol
Top 6 with name 0 DFT: 5.072378771146759 kcal/mol
Top 1 with name 6 DFT: 12.776013809628786 kcal/mol
Top 2 with name 2 DFT: 12.122632617438214 kcal/mol
Top 3 with name 7 DFT: 10.142856465484947 kcal/mol
Top 4 with name 1 DFT: 8.620897851719057 kcal/mol
Top 5 with name 8 DFT: 7.907011128400917 kcal/mol
Top 6 with name 5 DFT: 6.377994398670268 kcal/mol
Top 7 with name 3 DFT: 6.116569025930943 kcal/mol
Top 8 with name 0 DFT: 5.718120705503964 kcal/mol
Top 9 with name 4 DFT: 5.290392406638709 kcal/mol
Top 10 with name 9 DFT: 4.375408333120866 kcal/mol
Top 11 with name 10 DFT: 4.353494594413789 kcal/mol
Top 1 with name 5 DFT: 17.42804954380845 kcal/mol
Top 2 with name 10 DFT: 10.336989625461865 kcal/mol
Top 3 with name 3 DFT: 8.850079075666144 kcal/mol
Top 4 with name 4 DFT: 6.682410854602857 kcal/mol
Top 5 with name 8 DFT: 3.2477422663825557 kcal/mol
Top 6 with name 0 DFT: 3.204297288191448 kcal/mol
Top 7 with name 6 DFT: 2.7556008393177756 kcal/mol
Top 8 with name 1 DFT: 2.4048873357995033 kcal/mol
Top 9 with name 11 DFT: 1.9367682807412407 kcal/mol
Top 10 with name 9 DFT: 1.0817554017147586 kcal/mol
Top 11 with name 2 DFT: 0.45760465933526717 kcal/mol
Top 12 with name 7 DFT: 0.23738547379937103 kcal/mol
Top 1 with name 1 DFT: 16.030955320899373 kcal/mol
Top 2 with name 0 DFT: 13.904082304163893 kcal/mol
Top 3 with name 2 DFT: 11.266498185194791 kcal/mol
Top 4 with name 3 DFT: 3.0014237140237654 kcal/mol
Top 5 with name 4 DFT: 2.0449301435609613 kcal/mol
Top 6 with name 6 DFT: 0.8457417821744428 kcal/mol
Top 7 with name 7 DFT: 0.7380740393244203 kcal/mol
Top 8 with name 5 DFT: 0.24465513687547968 kcal/mol
Top 1 with name 18 DFT: 9.821198651462034 kcal/mol
Top 2 with name 11 DFT: 3.5822220974066292 kcal/mol
Top 3 with name 12 DFT: 3.044489796812705 kcal/mol
Top 4 with name 6 DFT: 3.0347135089721995 kcal/mol
Top 5 with name 7 DFT: 2.948289494216443 kcal/mol
Top 6 with name 20 DFT: 2.9393600009303213 kcal/mol
Top 7 with name 2 DFT: 2.874342778353604 kcal/mol
Top 8 with name 17 DFT: 2.360086491590774 kcal/mol
Top 9 with name 9 DFT: 2.2421543477068155 kcal/mol
Top 10 with name 10 DFT: 1.8320451810088692 kcal/mol
Top 11 with name 16 DFT: 1.795480446813741 kcal/mol
Top 12 with name 15 DFT: 1.786415608880343 kcal/mol
Top 13 with name 0 DFT: 1.2955927139776762 kcal/mol
Top 14 with name 13 DFT: 1.2827572384255461 kcal/mol
Top 15 with name 8 DFT: 0.8276529523660443 kcal/mol
Top 16 with name 4 DFT: 0.6392131560379042 kcal/mol
Top 17 with name 5 DFT: 0.4489878604921955 kcal/mol
Top 18 with name 19 DFT: 0.37880930382874567 kcal/mol
Top 19 with name 14 DFT: 0.3761293745727734 kcal/mol
Top 20 with name 3 DFT: 0.2562168538739229 kcal/mol
Top 21 with name 1 DFT: 0.10702199736610041 kcal/mol
Top 1 with name 20 DFT: 8.186653628953493 kcal/mol
Top 2 with name 4 DFT: 5.961470240043491 kcal/mol
Top 3 with name 19 DFT: 5.908605605195049 kcal/mol
Top 4 with name 15 DFT: 5.83342506327201 kcal/mol
Top 5 with name 10 DFT: 5.7778937261179095 kcal/mol
Top 6 with name 22 DFT: 5.515879373304784 kcal/mol
Top 7 with name 12 DFT: 4.425469481699984 kcal/mol
Top 8 with name 7 DFT: 3.4638240416691417 kcal/mol
Top 9 with name 21 DFT: 3.42308990807156 kcal/mol
Top 10 with name 3 DFT: 2.502257566992194 kcal/mol
Top 11 with name 11 DFT: 2.3531160274660223 kcal/mol
Top 12 with name 1 DFT: 2.3141517484234644 kcal/mol
Top 13 with name 9 DFT: 1.9926308186491966 kcal/mol
Top 14 with name 6 DFT: 1.904815518356628 kcal/mol
Top 15 with name 24 DFT: 1.6556980518938644 kcal/mol
Top 16 with name 2 DFT: 1.5776321879017634 kcal/mol
Top 17 with name 17 DFT: 1.2603199910244456 kcal/mol
Top 18 with name 23 DFT: 1.1779684969433504 kcal/mol
Top 19 with name 8 DFT: 1.1082965435227372 kcal/mol
Top 20 with name 18 DFT: 0.7959833287226559 kcal/mol
Top 21 with name 13 DFT: 0.7774159697804137 kcal/mol
Top 22 with name 16 DFT: 0.6811987063600071 kcal/mol
Top 23 with name 0 DFT: 0.4726969945663586 kcal/mol
Top 24 with name 14 DFT: 0.0737296899239297 kcal/mol
Top 25 with name 5 DFT: 0.000335742649621551 kcal/mol
Top 1 with name BH76RC_9 DFT: 6.404341526923817 kcal/mol
Top 2 with name BH76RC_10 DFT: 5.442962969467043 kcal/mol
Top 3 with name BH76RC_15 DFT: 4.527494332530537 kcal/mol
Top 4 with name BH76RC_21 DFT: 4.0007340155073905 kcal/mol
Top 5 with name BH76RC_1 DFT: 3.860432244833788 kcal/mol
Top 6 with name BH76RC_14 DFT: 3.397912337293383 kcal/mol
Top 7 with name BH76RC_25 DFT: 3.140342107313918 kcal/mol
Top 8 with name BH76RC_26 DFT: 3.0660769976256415 kcal/mol
Top 9 with name BH76RC_12 DFT: 3.003613738083512 kcal/mol
Top 10 with name BH76RC_28 DFT: 2.7442456244339706 kcal/mol
Top 11 with name BH76RC_16 DFT: 2.353763601580781 kcal/mol
Top 12 with name BH76RC_23 DFT: 2.2978629943006688 kcal/mol
Top 13 with name BH76RC_17 DFT: 2.173730730949755 kcal/mol
Top 14 with name BH76RC_22 DFT: 2.031928261903377 kcal/mol
Top 15 with name BH76RC_11 DFT: 1.8006507317299807 kcal/mol
Top 16 with name BH76RC_3 DFT: 1.7578753559367044 kcal/mol

      b3lyp_ene b3lyp-d3bj_ene Processed
sub1   4.562869       3.707215      DONE
sub2  15.625329       7.261946     7 / 9
sub3   3.212841       3.249051     6 / 7
sub4   2.419527         0.8884      DONE
sub5   1.638705       0.315302     3 / 9

wtmad_1

         b3lyp_ene b3lyp-d3bj_ene Processed
sub1      5.297991       3.891416      DONE
sub2      8.238651       5.301846     7 / 9
sub3      3.333248       3.284615     6 / 7
sub4     15.178475       3.094262      DONE
sub5     11.446032       2.513874     3 / 9
summary  43.494396      18.086013        --

wtmad_2

         b3lyp_ene b3lyp-d3bj_ene Processed
sub1      2.529777       2.087674      DONE
sub2       3.93566         2.3377     7 / 9
sub3      1.694074       1.706235     6 / 7
sub4      8.487102       1.908139      DONE
sub5      3.494829       0.678168     3 / 9
summary  20.141442       8.717916        --

Summary of Subset
MAE

           b3lyp_ene b3lyp-d3bj_ene Processed
W4_11        3.94796       3.269621      DONE
G21EA       3.216316       3.210707      DONE
G21IP       3.755797       3.761985      DONE
DIPCS10      4.41082       4.392293      DONE
PA26         2.02061       2.458886      DONE
SIE4x4     17.332887      17.762184      DONE
ALKBDE10    3.937475        3.67966      DONE
YBDE18      8.306348       4.576729      DONE
AL2X6        8.92625       2.589699      DONE
HEAVYSB11   7.618308       3.026647      DONE
NBPRC       4.885298       1.831183      DONE
ALK8        6.009545       2.603275      DONE
RC21        2.089199       2.716653      DONE
G2RC        2.765782       3.013725      DONE
BH76RC       2.07279       2.054048      DONE
FH51        3.947587       2.656844      DONE
TAUT15      1.187497       1.230635      DONE
DC13       14.511302       9.941195      DONE
MB16_43    59.906849      26.654322      DONE
DARC       14.920644       7.199735      DONE
RSE43       1.984407       1.743045      DONE
BSR36      11.201854       3.848356      DONE
CDIE20      1.299675       1.036096      DONE
ISO34       2.324915       1.815044      DONE
ISOL24      5.732272        3.97303   12 / 24
C60ISO             0              0     0 / 9
PArel       1.075768       1.080917      DONE
BH76        4.464158       5.248077      DONE
BHPERI      4.180251       1.263153      DONE
BHDIV10     2.736699       3.220899      DONE
INV24          1.711       0.967279   18 / 24
BHROT27     0.410569       0.419731      DONE
PX13        4.725531       5.509516      DONE
WCPT18      1.409402       2.586069      DONE
RG18        0.789227       0.116072      DONE
ADIM6       4.968723       0.187215      DONE
S22         3.700617       0.372939      DONE
S66         3.173422       0.321915      DONE
HEAVY28     1.275698       0.364093      DONE
WATER27     4.937123       5.021605      DONE
CARBHB12     0.64769       0.913685      DONE
PNICO23     1.701481       0.552682      DONE
HAL59       1.685904       0.665397      DONE
AHB21       0.800861       0.559851      DONE
CHB6         1.03038       1.063153      DONE
IL16        3.891341       0.660111      DONE
IDISP      16.129367       3.873294     5 / 6
ICONF       0.576403       0.280006      DONE
ACONF        0.95258       0.052464      DONE
Amino20x4   0.592487       0.175201   72 / 80
PCONF21            0              0    0 / 18
MCONF       2.458995        0.24105      DONE
SCONF       0.674218       0.372274   11 / 17
UPU23              0              0    0 / 23
BUT14DIOL          0              0    0 / 64