In [7]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
data_set = "gmtkn-cc-pVDZ"

data_path_list = sorted(
    list(Path("../validate_hkqai_done").glob(f"*gmtkn*.csv")),
    key=lambda p: p.stat().st_ctime,
)

basis_args = "cc-pVDZ"
print(basis_args)

with open(f"new_dataset/{data_set}.json") as f:
    json_data = json.load(f)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict_ccpvdz"]
    # full_subset_dict = json.load(f)["full_subset_dict_test"]

data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for data_path in data_path_list:
        data = pd.read_csv(data_path)
        data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
        data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
        data_dft = data["dft_ene"].to_numpy() * 627.5094733748099
        data_scf = data["scf_ene"].to_numpy() * 627.5094733748099
        data_cc = data["cc_ene"].to_numpy() * 627.5094733748099

        data_error_scf_ele = data["error_scf_ele"].to_numpy()
        data_error_dft_ele = data["error_dft_ele"].to_numpy()
        data_error_scf_dip = data["error_scf_dip"].to_numpy()
        data_error_dft_dip = data["error_dft_dip"].to_numpy()
        data_subset[f"{data_path_name}_summary"] = {
            "error_scf_ele": data_error_scf_ele,
            "error_dft_ele": data_error_dft_ele,
            "error_scf_dip": data_error_scf_dip,
            "error_dft_dip": data_error_dft_dip,
        }

        if "delta_d3bj" in data.columns:
            data_d3bj = data["delta_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_d3bj = np.zeros_like(data_dft)
        if "delta_d3zero" in data.columns:
            data_d3zero = data["delta_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_d3zero = np.zeros_like(data_dft)

        if "modified_dft_d3bj" in data.columns:
            data_dft_d3bj = data["modified_dft_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3bj = data_d3bj
        if "modified_dft_d3zero" in data.columns:
            data_dft_d3zero = data["modified_dft_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_dft_d3zero = data_d3zero
        if "modified_ai_d3bj" in data.columns:
            data_ai_d3bj = data["modified_ai_d3bj"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3bj = data_d3bj
        if "modified_ai_d3zero" in data.columns:
            data_ai_d3zero = data["modified_ai_d3zero"].to_numpy() * 627.5094733748099
        else:
            data_ai_d3zero = data_d3zero

        del data_d3bj, data_d3zero

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft": [],
                "dft_d3bj": [],
                "dft_d3zero": [],
                "ai": [],
                "ai_d3bj": [],
                "ai_d3zero": [],
                "cc": [],
                "error_scf_ele": [],
                "error_dft_ele": [],
                "error_scf_dip": [],
                "error_dft_dip": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    if verbose > 0:
                        print(
                            f"Warning: {i_molecule_name} not found in {data_path.stem} data file"
                        )
                    continue
                data_subset[name_subset]["error_scf_ele"].append(
                    data_error_scf_ele[col[0]]
                )
                data_subset[name_subset]["error_dft_ele"].append(
                    data_error_dft_ele[col[0]]
                )
                data_subset[name_subset]["error_scf_dip"].append(
                    data_error_scf_dip[col[0]]
                )
                data_subset[name_subset]["error_dft_dip"].append(
                    data_error_dft_dip[col[0]]
                )

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                atomic_energy_dft_d3bj = 0
                atomic_energy_dft_d3zero = 0
                atomic_energy_ai = 0
                atomic_energy_ai_d3bj = 0
                atomic_energy_ai_d3zero = 0
                atomic_energy_cc = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        if verbose > 0:
                            print(f"Warning: {mole_name} not found in data json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                        atomic_energy_dft_d3bj += data_dft_d3bj[col[0]] * stoichiometry
                        atomic_energy_dft_d3zero += (
                            data_dft_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_ai += data_scf[col[0]] * stoichiometry
                        atomic_energy_ai_d3bj += data_ai_d3bj[col[0]] * stoichiometry
                        atomic_energy_ai_d3zero += (
                            data_ai_d3zero[col[0]] * stoichiometry
                        )
                        atomic_energy_cc += data_cc[col[0]] * stoichiometry
                    else:
                        finished = False
                        if verbose > 0:
                            print(
                                f"Warning: {mole_name} not found in {data_path.stem} data file"
                            )
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["dft_d3bj"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3bj
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["dft_d3zero"].append(
                        abs(
                            atomic_energy_dft
                            + atomic_energy_dft_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["ai"].append(
                        abs(atomic_energy_ai - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3bj"].append(
                        abs(atomic_energy_ai + atomic_energy_ai_d3bj - atomic_energy_cc)
                    )
                    data_subset[name_subset]["ai_d3zero"].append(
                        abs(
                            atomic_energy_ai
                            + atomic_energy_ai_d3zero
                            - atomic_energy_cc
                        )
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_ai = np.argsort(data_subset[name_subset]["ai"])[
                    ::-1
                ][:5]
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ][:5]
                for i in range(len(argsort_atomic_energy_ai)):
                    i_reaction_name = data_subset[name_subset]["name"][
                        argsort_atomic_energy_ai[i]
                    ]
                    i_reaction = json_data[f"reaction-{i_subset}"][i_reaction_name]
                    print(
                        f"Top {i+1} AI: {data_subset[name_subset]['ai'][argsort_atomic_energy_ai[i]]} kcal/mol, {i_reaction_name} in {name_subset}",
                    )
                    systems_list = i_reaction["systems"]
                    stoichiometry_list = i_reaction["stoichiometry"]
                    for j in range(len(systems_list)):
                        mole_name = (
                            systems_list[j]
                            if i_subset == "BH76RC"
                            else f"{i_subset}-{systems_list[j]}"
                        )
                        stoichiometry = int(stoichiometry_list[j])
                        if mole_name in json_data:
                            if isinstance(json_data[mole_name], str):
                                mole_name = json_data[mole_name]
                        print(f"  {stoichiometry} * {mole_name}", end="")
                        col = np.where(data_name == mole_name)[0]
                        if col.size == 1:
                            error_energy_ai = data_scf[col[0]] - data_cc[col[0]]
                            print(f"  {stoichiometry} * {error_energy_ai}", end="")
                    print()

                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

data_path_name_list = [
    data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    for data_path in data_path_list
]
header = pd.MultiIndex.from_product(
    [
        data_path_name_list,
        [
            "AI",
            "DFT",
            "AI_D3BJ",
            "DFT_D3BJ",
            "AI_D3ZERO",
            "DFT_D3ZERO",
            "Processed",
        ],
    ],
    names=["data_path", "Disp type"],
)

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

df_summary_subset_ele = pd.DataFrame(
    columns=pd.MultiIndex.from_product(
        [
            data_path_name_list,
            [
                "error_scf_ele",
                "error_dft_ele",
                "error_scf_dip",
                "error_dft_dip",
            ],
        ],
        names=["data_path", "Ele type"],
    )
)

for data_path in data_path_list:
    mean_absolute_deviation_list = []
    data_path_name = data_path.stem.split("_atom-1-")[1].split("_gmtkn")[0]
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_ele")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_ele"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_scf_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_scf_dip"]
    )
    df_summary_subset_ele.loc["summary", (data_path_name, "error_dft_dip")] = np.mean(
        data_subset[f"{data_path_name}_summary"]["error_dft_dip"]
    )

    for name_set, subset_list_ in full_subset_dict.items():
        subset_ai = {}
        wtmad_1_ai = {}
        wtmad_2_ai = {}
        subset_dft = {}
        wtmad_1_dft = {}
        wtmad_2_dft = {}

        for d3_name in ["", "_d3bj", "_d3zero"]:
            subset_ai[d3_name] = []
            wtmad_1_ai[d3_name] = []
            wtmad_2_ai[d3_name] = []
            subset_dft[d3_name] = []
            wtmad_1_dft[d3_name] = []
            wtmad_2_dft[d3_name] = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{data_path_name}_{i_subset}"
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_ele")] = (
                np.mean(data_subset[name_subset]["error_scf_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_ele")] = (
                np.mean(data_subset[name_subset]["error_dft_ele"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_scf_dip")] = (
                np.mean(data_subset[name_subset]["error_scf_dip"])
            )
            df_summary_subset_ele.loc[i_subset, (data_path_name, "error_dft_dip")] = (
                np.mean(data_subset[name_subset]["error_dft_dip"])
            )

            if len(data_subset[name_subset]["ai"]) == 0:
                for col_name in [
                    "AI",
                    "DFT",
                    "AI_D3BJ",
                    "DFT_D3BJ",
                    "AI_D3ZERO",
                    "DFT_D3ZERO",
                ]:
                    df_summary_subset.loc[i_subset, (data_path_name, col_name)] = 0
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                for d3_name in ["", "_d3bj", "_d3zero"]:
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"AI{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"ai{d3_name}"])
                    df_summary_subset.loc[
                        i_subset, (data_path_name, f"DFT{d3_name.upper()}")
                    ] = np.mean(data_subset[name_subset][f"dft{d3_name}"])
                df_summary_subset.loc[i_subset, (data_path_name, "Processed")] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["ai"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["ai"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['ai'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                for d3_name in ["", "_d3bj", "_d3zero"]:
                    subset_ai[d3_name] = np.append(
                        subset_ai[d3_name], data_subset[name_subset][f"ai{d3_name}"]
                    )
                    subset_dft[d3_name] = np.append(
                        subset_dft[d3_name], data_subset[name_subset][f"dft{d3_name}"]
                    )
                    wtmad_1_ai[d3_name] = np.append(
                        wtmad_1_ai[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"ai{d3_name}"]),
                    )
                    wtmad_1_dft[d3_name] = np.append(
                        wtmad_1_dft[d3_name],
                        wtmad_1 * np.mean(data_subset[name_subset][f"dft{d3_name}"]),
                    )
                    wtmad_2_ai[d3_name] = np.append(
                        wtmad_2_ai[d3_name],
                        data_subset[name_subset][f"ai{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                    wtmad_2_dft[d3_name] = np.append(
                        wtmad_2_dft[d3_name],
                        data_subset[name_subset][f"dft{d3_name}"]
                        / np.mean(data_subset[name_subset]["cc"]),
                    )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["ai"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)
        for d3_name in ["", "_d3bj", "_d3zero"]:
            mean_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(subset_ai[d3_name])
            )
            mean_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(subset_dft[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.mean(wtmad_1_ai[d3_name])
            )
            wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.mean(wtmad_1_dft[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                np.sum(wtmad_2_ai[d3_name])
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                np.sum(wtmad_2_dft[d3_name])
            )
        mean_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, (data_path_name, "Processed")] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = np.mean(mean_absolute_deviation_list) / len(
        mean_absolute_deviation_list
    )
    print(
        f"Mean absolute deviation for {data_path_name}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        for d3_name in ["", "_d3bj", "_d3zero"]:
            wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            )
            wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")] = (
                mean_absolute_deviation
                * wtmad_2_subset.loc[
                    name_set, (data_path_name, f"DFT{d3_name.upper()}")
                ]
            )

    wtmad_1_subset.loc["summary", (data_path_name, "Processed")] = "--"
    wtmad_2_subset.loc["summary", (data_path_name, "Processed")] = "--"
    for d3_name in ["", "_d3bj", "_d3zero"]:
        wtmad_1_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_1_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"AI{d3_name.upper()}")] = 0
        wtmad_2_subset.loc["summary", (data_path_name, f"DFT{d3_name.upper()}")] = 0
        for name_set in full_subset_dict.keys():
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_1_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_1_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"AI{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"AI{d3_name.upper()}")]
            wtmad_2_subset.loc[
                "summary", (data_path_name, f"DFT{d3_name.upper()}")
            ] += wtmad_2_subset.loc[name_set, (data_path_name, f"DFT{d3_name.upper()}")]

# print("Summary")
# display(df_summary_subset_ele)
print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to csv with date
df_summary_subset_ele.to_csv(f"../validate/df_summary_subset_ele_{date}.csv")
df_summary_subset.to_csv(f"../validate/summary_subset_{date}.csv")
mean_subset.to_csv(f"../validate/mean_subset_{date}.csv")
wtmad_1_subset.to_csv(f"../validate/wtmad_1_subset_{date}.csv")
wtmad_2_subset.to_csv(f"../validate/wtmad_2_subset_{date}.csv")
# save summary to excel with date
df_summary_subset_ele.to_excel(f"../validate/df_summary_subset_ele_{date}.xlsx")
df_summary_subset.to_excel(f"../validate/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate/wtmad_2_subset_{date}.xlsx")

cc-pVDZ
Top 1 AI: 12.609903921023943 kcal/mol, 116 in 1424849_W4_11
  -1 * W4_11-p4  -1 * -13.835936387768015  4 * W4_11-p  4 * -0.3065081166860182
Top 2 AI: 5.341987040214008 kcal/mol, 136 in 1424849_W4_11
  -1 * W4_11-foof  -1 * -4.328057378443191  2 * W4_11-f  2 * 0.6256503599724965  2 * W4_11-o  2 * -0.11868552908708807
Top 3 AI: 5.219463497924153 kcal/mol, 46 in 1424849_W4_11
  -1 * W4_11-alf3  -1 * -3.2680325650726445  1 * W4_11-al  1 * 0.07447985294857062  3 * W4_11-f  3 * 0.6256503599724965
Top 4 AI: 4.821493316645501 kcal/mol, 135 in 1424849_W4_11
  -1 * W4_11-cloo  -1 * -4.751233361486811  1 * W4_11-cl  1 * 0.30763101333286613  2 * W4_11-o  2 * -0.11868552908708807
Top 5 AI: 4.2865408250218024 kcal/mol, 63 in 1424849_W4_11
  -1 * W4_11-sif  -1 * -3.7919159706216305  1 * W4_11-si  1 * -0.13102550557232462  1 * W4_11-f  1 * 0.6256503599724965
Top 1 DFT: 64.9391765203327 kcal/mol
Top 2 DFT: 64.82811637483246 kcal/mol
Top 3 DFT: 58.7866408124537 kcal/mol
Top 4 DFT: 55.610892266675364 kcal/mol
Top 5 DFT: 55.13918598267037 kcal/mol
Top 1 AI: 7.49201939390332 kcal/mol, 20 in 1424849_G21EA
  1 * G21EA-EA_21n  1 * -0.5402685518347425  -1 * G21EA-EA_21  -1 * -8.032287945738062
Top 2 AI: 1.6797678372531664 kcal/mol, 22 in 1424849_G21EA
  1 * G21EA-EA_23n  1 * -0.09462860008352436  -1 * G21EA-EA_23  -1 * -1.7743964373366907
Top 3 AI: 1.3357985674811061 kcal/mol, 19 in 1424849_G21EA
  1 * G21EA-EA_20n  1 * -0.39129666016378906  -1 * G21EA-EA_20  -1 * 0.9445019073173171
Top 4 AI: 1.2738022370067483 kcal/mol, 8 in 1424849_G21EA
  1 * G21EA-EA_9n  1 * -0.17406531150481896  -1 * G21EA-EA_9  -1 * -1.4478675485115673
Top 5 AI: 1.1117870431626216 kcal/mol, 24 in 1424849_G21EA
  1 * G21EA-EA_25n  1 * 0.7681434685364366  -1 * G21EA-EA_25  -1 * -0.343643574626185
Top 1 DFT: 17.922119285416557 kcal/mol
Top 2 DFT: 14.542179432406556 kcal/mol
Top 3 DFT: 13.792081636143848 kcal/mol
Top 4 DFT: 13.585563076587277 kcal/mol
Top 5 DFT: 13.248573637160007 kcal/mol
Top 1 AI: 4.192199363344116 kcal/mol, 20 in 1424849_G21IP
  1 * G21IP-IP_64  1 * -1.9147681299073156  -1 * G21IP-18  -1 * 2.2774312334368005
Top 2 AI: 2.842535861534998 kcal/mol, 25 in 1424849_G21IP
  1 * G21IP-IP_70  1 * 2.2912037747446448  -1 * G21IP-22  -1 * -0.5513320867903531
Top 3 AI: 2.214247952398182 kcal/mol, 1 in 1424849_G21IP
  1 * G21IP-li+  1 * 1.0381241644026886  -1 * G21IP-li  -1 * -1.1761237879954933
Top 4 AI: 1.5648051777970977 kcal/mol, 27 in 1424849_G21IP
  1 * G21IP-IP_72  1 * -1.602356972420239  -1 * G21IP-26  -1 * -0.03755179462314118
Top 5 AI: 1.4983439797069877 kcal/mol, 35 in 1424849_G21IP
  1 * G21IP-IP_80  1 * 0.12246092985151336  -1 * G21IP-48  -1 * -1.3758830498554744
Top 1 DFT: 24.652048565418227 kcal/mol
Top 2 DFT: 19.50703940328094 kcal/mol
Top 3 DFT: 16.821335594599077 kcal/mol
Top 4 DFT: 16.4504761478438 kcal/mol
Top 5 DFT: 16.230253286354127 kcal/mol
Top 1 AI: 13.011239236511756 kcal/mol, 0 in 1424849_DIPCS10
  -1 * DIPCS10-c4h4  -1 * 4.986917996298871  1 * DIPCS10-c4h4_2+  1 * -8.024321240212885
Top 2 AI: 4.60629111668095 kcal/mol, 3 in 1424849_DIPCS10
  -1 * DIPCS10-n2h2  -1 * 4.445577510428848  1 * DIPCS10-n2h2_2+  1 * -0.16071360625210218
Top 3 AI: 1.2518831721245078 kcal/mol, 1 in 1424849_DIPCS10
  -1 * DIPCS10-c2h6  -1 * -0.8114082642496214  1 * DIPCS10-c2h6_2+  1 * 0.4404749078748864
Top 4 AI: 0.6984853867543279 kcal/mol, 2 in 1424849_DIPCS10
  -1 * DIPCS10-c2h4  -1 * -0.007542564373579808  1 * DIPCS10-c2h4_2+  1 * -0.7060279511279077
Top 5 AI: 0.4374527729814872 kcal/mol, 6 in 1424849_DIPCS10
  -1 * DIPCS10-h2s  -1 * -0.32372897141613066  1 * DIPCS10-h2s_2+  1 * 0.11372380156535655
Top 1 DFT: 21.238722962967586 kcal/mol
Top 2 DFT: 18.410172816045815 kcal/mol
Top 3 DFT: 17.180242111804546 kcal/mol
Top 4 DFT: 16.016684862523107 kcal/mol
Top 5 DFT: 13.03569706963026 kcal/mol
Top 1 AI: 11.632347433187533 kcal/mol, 12 in 1424849_PA26
  1 * PA26-c2f6  1 * -0.9294062241679057  -1 * PA26-c2f6p  -1 * -12.561753657355439
Top 2 AI: 6.585291430470534 kcal/mol, 3 in 1424849_PA26
  1 * PA26-p8  1 * -2.8362062554224394  -1 * PA26-p8p  -1 * -9.421497685892973
Top 3 AI: 6.281163186999038 kcal/mol, 15 in 1424849_PA26
  1 * PA26-gly  1 * -1.2317279376729857  -1 * PA26-glyp  -1 * 5.049435249326052
Top 4 AI: 6.280898495329893 kcal/mol, 1 in 1424849_PA26
  1 * PA26-p4  1 * 0.5498058937810129  -1 * PA26-p4p  -1 * -5.73109260154888
Top 5 AI: 6.022427202151448 kcal/mol, 4 in 1424849_PA26
  1 * PA26-nh3  1 * -0.13298793267313158  -1 * PA26-nh3p  -1 * 5.889439269478316
Top 1 DFT: 5.496021041501081 kcal/mol
Top 2 DFT: 3.952208415896166 kcal/mol
Top 3 DFT: 3.843404227809515 kcal/mol
Top 4 DFT: 3.7666994354804046 kcal/mol
Top 5 DFT: 3.7500070057285484 kcal/mol
Top 1 AI: 8.179945183015661 kcal/mol, 11 in 1424849_SIE4x4
  1 * SIE4x4-nh3  1 * -0.42297215241706  1 * SIE4x4-nh3+  1 * -0.43809660836996045  -1 * SIE4x4-nh32+_1.75  -1 * -9.041013943802682
Top 2 AI: 8.164314597747932 kcal/mol, 3 in 1424849_SIE4x4
  1 * SIE4x4-h  1 * 0.05522922269778974  -1 * SIE4x4-h2+_1.75  -1 * -8.109085375050142
Top 3 AI: 7.508551642065868 kcal/mol, 15 in 1424849_SIE4x4
  1 * SIE4x4-h2o  1 * -0.5000765549193602  1 * SIE4x4-h2o+  1 * -0.4621521750232205  -1 * SIE4x4-h2o2+_1.75  -1 * -8.470780372008448
Top 4 AI: 5.74040256185981 kcal/mol, 10 in 1424849_SIE4x4
  1 * SIE4x4-nh3  1 * -0.42297215241706  1 * SIE4x4-nh3+  1 * -0.43809660836996045  -1 * SIE4x4-nh32+_1.5  -1 * -6.60147132264683
Top 5 AI: 5.432473135719192 kcal/mol, 14 in 1424849_SIE4x4
  1 * SIE4x4-h2o  1 * -0.5000765549193602  1 * SIE4x4-h2o+  1 * -0.4621521750232205  -1 * SIE4x4-h2o2+_1.5  -1 * -6.394701865661773
Top 1 DFT: 42.48945061229006 kcal/mol
Top 2 DFT: 36.3825565542179 kcal/mol
Top 3 DFT: 34.02966520233895 kcal/mol
Top 4 DFT: 29.669328280849186 kcal/mol
Top 5 DFT: 29.26023051775701 kcal/mol
Warning: ALKBDE10-kf not found in data json, ERROR
Top 1 AI: 3.5931618843824253 kcal/mol, 2 in 1424849_ALKBDE10
  -1 * ALKBDE10-cao  -1 * -4.225235932972282  1 * ALKBDE10-ca  1 * -0.1940410149982199  1 * ALKBDE10-o  1 * -0.4380330335916369
Top 2 AI: 1.6851680263571325 kcal/mol, 9 in 1424849_ALKBDE10
  -1 * ALKBDE10-nao  -1 * 1.245474494935479  1 * ALKBDE10-na  1 * -0.0016604978300165385  1 * ALKBDE10-o  1 * -0.4380330335916369
Top 3 AI: 1.1388922457408626 kcal/mol, 1 in 1424849_ALKBDE10
  -1 * ALKBDE10-beo  -1 * -1.551834514226357  1 * ALKBDE10-be  1 * 0.0250907651061425  1 * ALKBDE10-o  1 * -0.4380330335916369
Top 4 AI: 0.900990189598815 kcal/mol, 6 in 1424849_ALKBDE10
  -1 * ALKBDE10-lio  -1 * -0.7131666319764918  1 * ALKBDE10-li  1 * -1.1761237879773034  1 * ALKBDE10-o  1 * -0.4380330335916369
Top 5 AI: 0.5287845291895792 kcal/mol, 3 in 1424849_ALKBDE10
  -1 * ALKBDE10-hf  -1 * 0.399809805683617  1 * ALKBDE10-h  1 * 0.05522922269767605  1 * ALKBDE10-f  1 * -0.18420394619897706
Top 1 DFT: 42.20618001303956 kcal/mol
Top 2 DFT: 26.422307972352428 kcal/mol
Top 3 DFT: 19.54640414734604 kcal/mol
Top 4 DFT: 16.150239486240025 kcal/mol
Top 5 DFT: 15.581684817676432 kcal/mol
Top 1 AI: 17.956644504272845 kcal/mol, 10 in 1424849_YBDE18
  -1 * YBDE18-nme3-cbh22  -1 * 8.76483919157181  1 * YBDE18-nme3  1 * 2.494217516781646  1 * YBDE18-cbh22  1 * -11.686022829482681
Top 2 AI: 13.952189418123453 kcal/mol, 4 in 1424849_YBDE18
  -1 * YBDE18-me2s-cbh22  -1 * 2.525485541555099  1 * YBDE18-me2s  1 * 0.2593189529143274  1 * YBDE18-cbh22  1 * -11.686022829482681
Top 3 AI: 12.433364505690406 kcal/mol, 16 in 1424849_YBDE18
  -1 * YBDE18-pme3-cbh22  -1 * 2.2007937313173898  1 * YBDE18-pme3  1 * 1.4534520551096648  1 * YBDE18-cbh22  1 * -11.686022829482681
Top 4 AI: 10.242876734046149 kcal/mol, 0 in 1424849_YBDE18
  -1 * YBDE18-f2s-cbh22  -1 * -8.987277443113271  1 * YBDE18-f2s  1 * -7.544131347676739  1 * YBDE18-cbh22  1 * -11.686022829482681
Top 5 AI: 9.91436033345235 kcal/mol, 12 in 1424849_YBDE18
  -1 * YBDE18-pf3-cbh22  -1 * -9.045221398642752  1 * YBDE18-pf3  1 * -7.273558902612422  1 * YBDE18-cbh22  1 * -11.686022829482681
Top 1 DFT: 16.44728826175924 kcal/mol
Top 2 DFT: 12.740130906568083 kcal/mol
Top 3 DFT: 10.883027330586629 kcal/mol
Top 4 DFT: 10.488881110526563 kcal/mol
Top 5 DFT: 10.40475183620947 kcal/mol
Top 1 AI: 8.067653083940968 kcal/mol, 2 in 1424849_AL2X6
  -1 * AL2X6-al2cl6  -1 * 8.374734565615654  2 * AL2X6-alcl3  2 * 0.15354074083734304
Top 2 AI: 7.471616765251383 kcal/mol, 1 in 1424849_AL2X6
  -1 * AL2X6-al2f6  -1 * 0.8225600435398519  2 * AL2X6-alf3  2 * -3.3245283608557656
Top 3 AI: 7.343571939010872 kcal/mol, 4 in 1424849_AL2X6
  -1 * AL2X6-al2me5  -1 * 6.86388280056417  1 * AL2X6-alme2  1 * -1.1836469503468834  1 * AL2X6-alme3  1 * 0.7039578119001817
Top 4 AI: 6.699005018279422 kcal/mol, 5 in 1424849_AL2X6
  -1 * AL2X6-al2me6  -1 * 8.106920642079785  2 * AL2X6-alme3  2 * 0.7039578119001817
Top 5 AI: 6.63455681828782 kcal/mol, 3 in 1424849_AL2X6
  -1 * AL2X6-al2me4  -1 * 4.267262917594053  2 * AL2X6-alme2  2 * -1.1836469503468834
Top 1 DFT: 9.084031574253459 kcal/mol
Top 2 DFT: 7.0848077459668275 kcal/mol
Top 3 DFT: 5.3300173038151115 kcal/mol
Top 4 DFT: 5.070575412944891 kcal/mol
Top 5 DFT: 4.9637361988425255 kcal/mol
Warning: HEAVYSB11-snme3 not found in data json, ERROR
Warning: HEAVYSB11-pbme3 not found in data json, ERROR
Warning: HEAVYSB11-teme not found in data json, ERROR
Warning: HEAVYSB11-sbme2 not found in data json, ERROR
Top 1 AI: 5.75657530000899 kcal/mol, 6 in 1424849_HEAVYSB11
  2 * HEAVYSB11-pme2  2 * -1.2019594826851971  -1 * HEAVYSB11-p2me4  -1 * 3.3526563346385956
Top 2 AI: 5.610538036562502 kcal/mol, 9 in 1424849_HEAVYSB11
  2 * HEAVYSB11-cl  2 * 0.2219614171772264  -1 * HEAVYSB11-cl2  -1 * -5.16661520220805
Top 3 AI: 1.0372299998998642 kcal/mol, 7 in 1424849_HEAVYSB11
  2 * HEAVYSB11-asme2  2 * -1.0196587890386581  -1 * HEAVYSB11-as2me4  -1 * -1.002087578177452
Top 4 AI: 0.9772255774587393 kcal/mol, 0 in 1424849_HEAVYSB11
  2 * HEAVYSB11-geh3  2 * -0.922918267082423  -1 * HEAVYSB11-ge2h6  -1 * -0.8686109567061067
Top 5 AI: 0.3714285076712258 kcal/mol, 3 in 1424849_HEAVYSB11
  2 * HEAVYSB11-sh  2 * -0.4419116753851995  -1 * HEAVYSB11-h2s2  -1 * -1.2552518584416248
Top 1 DFT: 10.68985605717171 kcal/mol
Top 2 DFT: 9.494120202027261 kcal/mol
Top 3 DFT: 7.114256684028078 kcal/mol
Top 4 DFT: 6.325384678319097 kcal/mol
Top 5 DFT: 1.569642293266952 kcal/mol
Top 1 AI: 9.315482142061228 kcal/mol, 5 in 1424849_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * -0.6257461566565325  1 * NBPRC-ch  1 * 7.438243672106182
Top 2 AI: 7.636239194078371 kcal/mol, 10 in 1424849_NBPRC
  1 * NBPRC-BCl3PMe3  1 * 4.34182446799241  -1 * NBPRC-BCl3  -1 * -4.5550408971030265  -1 * NBPRC-PMe3  -1 * 1.2606261710170656
Top 3 AI: 5.836323817318771 kcal/mol, 8 in 1424849_NBPRC
  1 * NBPRC-BF3PMe3  1 * -6.1832620548666455  -1 * NBPRC-BF3  -1 * -1.60756440856494  -1 * NBPRC-PMe3  -1 * 1.2606261710170656
Top 4 AI: 5.2119485977164 kcal/mol, 3 in 1424849_NBPRC
  -2 * NBPRC-nh2-bh2  -2 * -0.6257461566565325  1 * NBPRC-cbut  1 * 3.9604562844033353
Top 5 AI: 3.7569015825838505 kcal/mol, 4 in 1424849_NBPRC
  -3 * NBPRC-nh2-bh2  -3 * -0.6257461566565325  1 * NBPRC-bz  1 * 1.4031934527738485  3 * NBPRC-h2  3 * 0.15882321995172788
Top 1 DFT: 8.843319919425994 kcal/mol
Top 2 DFT: 4.25873367569875 kcal/mol
Top 3 DFT: 3.4078239038353786 kcal/mol
Top 4 DFT: 2.532460168497778 kcal/mol
Top 5 DFT: 2.2723810925637054 kcal/mol
Top 1 AI: 13.044069080497138 kcal/mol, 1 in 1424849_ALK8
  -1 * ALK8-na8  -1 * 13.954185288399458  4 * ALK8-na2  4 * 0.22752905197557993
Top 2 AI: 11.870058785367291 kcal/mol, 2 in 1424849_ALK8
  -1 * ALK8-li4_me4  -1 * 7.233050062946859  4 * ALK8-li_me  4 * -1.1592521806051082
Top 3 AI: 3.481810020719422 kcal/mol, 0 in 1424849_ALK8
  -1 * ALK8-li8  -1 * 5.874364224080637  4 * ALK8-li2  4 * 0.5981385508403037
Top 4 AI: 2.0963395667804434 kcal/mol, 5 in 1424849_ALK8
  -1 * ALK8-li5_ch  -1 * -9.989718298704247  1 * ALK8-li4_c  1 * -6.8041883276746375  1 * ALK8-li_h  1 * -1.089190404249166
Top 5 AI: 1.8018620726070367 kcal/mol, 6 in 1424849_ALK8
  -1 * ALK8-li2_ch2n_2  -1 * -5.295821466948837  2 * ALK8-li_ch2n  2 * -3.548841769777937
Top 1 DFT: 13.423444515326992 kcal/mol
Top 2 DFT: 13.339023275213549 kcal/mol
Top 3 DFT: 3.2870388831361197 kcal/mol
Top 4 DFT: 1.8348026665917132 kcal/mol
Top 5 DFT: 1.3258451606470771 kcal/mol
Top 1 AI: 7.804180996492505 kcal/mol, 20 in 1424849_RC21
  -1 * RC21-10e  -1 * -0.6043241154402494  1 * RC21-10p1  1 * -8.038832320467918  1 * RC21-10p2  1 * -0.36967279146483634
Top 2 AI: 6.651165923918597 kcal/mol, 3 in 1424849_RC21
  -1 * RC21-2e  -1 * 2.5394617409911007  1 * RC21-2p2  1 * -3.2577468493400374  1 * RC21-2p3  1 * -0.8539573335874593
Top 3 AI: 4.563972460164223 kcal/mol, 7 in 1424849_RC21
  -1 * RC21-3e  -1 * -3.491647837596247  1 * RC21-3int3  1 * -8.05562029776047
Top 4 AI: 4.066219467124029 kcal/mol, 15 in 1424849_RC21
  -1 * RC21-7e  -1 * -2.8928721645788755  1 * RC21-7p1  1 * -6.575975243758876  1 * RC21-7p2  1 * -0.38311638794402825
Top 5 AI: 4.015800832300329 kcal/mol, 4 in 1424849_RC21
  -1 * RC21-3e  -1 * -3.491647837596247  1 * RC21-3p1  1 * -7.562677892594365  1 * RC21-3p2  1 * 0.05522922269778974
Top 1 DFT: 14.185896344562934 kcal/mol
Top 2 DFT: 11.848156853782712 kcal/mol
Top 3 DFT: 9.843254908562812 kcal/mol
Top 4 DFT: 8.613347860442445 kcal/mol
Top 5 DFT: 7.032865641926037 kcal/mol
Top 1 AI: 12.807629294453363 kcal/mol, 0 in 1424849_G2RC
  -1 * G2RC-118  -1 * -1.2543781104614027  1 * G2RC-117  1 * 12.015353402064648  1 * G2RC-13  1 * -0.4621022180726868
Top 2 AI: 6.159344337880611 kcal/mol, 9 in 1424849_G2RC
  -1 * G2RC-58  -1 * -4.624411534634419  -1 * G2RC-59  -1 * -3.387370614975225  1 * G2RC-57  1 * -1.6075559127493761  1 * G2RC-60  1 * -0.24488189886324108
Top 3 AI: 4.1927976191509515 kcal/mol, 3 in 1424849_G2RC
  -1 * G2RC-52  -1 * 0.18058456404833123  -1 * G2RC-1  -1 * 0.18177151582847273  2 * G2RC-18  2 * 2.2775768495048396
Top 4 AI: 3.687676800880581 kcal/mol, 10 in 1424849_G2RC
  -1 * G2RC-67  -1 * -3.858445713063702  -1 * G2RC-61  -1 * -1.294665065011941  1 * G2RC-66  1 * -2.9287824314669706  1 * G2RC-62  1 * 1.4633484543301165
Top 5 AI: 2.4240117664812715 kcal/mol, 18 in 1424849_G2RC
  -1 * G2RC-30  -1 * -0.30618490479537286  -3 * G2RC-1  -3 * 0.18177151582847273  1 * G2RC-13  1 * -0.4621022180726868  1 * G2RC-8  1 * -1.7227799057145603
Top 1 DFT: 16.861372091829253 kcal/mol
Top 2 DFT: 13.550974861325813 kcal/mol
Top 3 DFT: 11.457349740527434 kcal/mol
Top 4 DFT: 10.800692827404418 kcal/mol
Top 5 DFT: 10.432011227676412 kcal/mol
Top 1 AI: 2.351305730015156 kcal/mol, BH76RC_27 in 1424849_BH76RC
  -1 * BH76-NH2  -1 * -0.4143704167800024  -1 * BH76-ch3  -1 * -0.12456163157185074  1 * BH76-NH  1 * -1.163183092365216  1 * BH76-CH4  1 * -1.727054686001793
Top 2 AI: 1.9971823122396017 kcal/mol, BH76RC_22 in 1424849_BH76RC
  -1 * BH76-O  -1 * -0.655313191084133  -1 * BH76-CH4  -1 * -1.727054686001793  1 * BH76-oh  1 * -0.26062393327447353  1 * BH76-ch3  1 * -0.12456163157185074
Top 3 AI: 1.9958700972856604 kcal/mol, BH76RC_2 in 1424849_BH76RC
  -1 * BH76-h  -1 * 0.05522922269784658  -1 * BH76-ch3f  -1 * -2.054774440082838  1 * BH76-hf  1 * 0.12088651146768825  1 * BH76-ch3  1 * -0.12456163157185074
Top 4 AI: 1.8813349445263157 kcal/mol, BH76RC_1 in 1424849_BH76RC
  -1 * BH76-h  -1 * 0.05522922269784658  -1 * BH76-n2o  -1 * -2.011880009784363  1 * BH76-oh  1 * -0.26062393327447353  1 * BH76-n2  1 * 0.18530809070216492
Top 5 AI: 1.8082797052484239 kcal/mol, BH76RC_30 in 1424849_BH76RC
  -1 * BH76-NH2  -1 * -0.4143704167800024  -1 * BH76-CH4  -1 * -1.727054686001793  1 * BH76-NH3  1 * -0.2085837659687968  1 * BH76-ch3  1 * -0.12456163157185074
Top 1 DFT: 16.943700659729075 kcal/mol
Top 2 DFT: 11.4192808540829 kcal/mol
Top 3 DFT: 9.908463760002633 kcal/mol
Top 4 DFT: 9.5446835977491 kcal/mol
Top 5 DFT: 7.421772861736827 kcal/mol
Top 1 AI: 11.384949486906407 kcal/mol, 31 in 1424849_FH51
  -1 * FH51-H2C-C5-CH2  -1 * -18.314417980698636  1 * FH51-heptatriyne  1 * -6.929468493792228
Top 2 AI: 8.784551896096673 kcal/mol, 49 in 1424849_FH51
  -1 * FH51-n-nonane  -1 * 9.325105747091584  1 * FH51-tetramethylpentane  1 * 18.109657643188257
Top 3 AI: 7.289441557426471 kcal/mol, 38 in 1424849_FH51
  1 * FH51-pentadiene  1 * 0.6736922028067056  1 * FH51-ethene  1 * -0.1974217099705129  -1 * FH51-ax-methylcyclohexene  -1 * 7.765712050255388
Top 4 AI: 7.165030918084085 kcal/mol, 5 in 1424849_FH51
  -1 * FH51-toluene  -1 * -0.27144056736142375  -3 * FH51-H2  -3 * 0.19244744610512043  1 * FH51-methylcyclohexane  1 * 7.470932689029723
Top 5 AI: 6.488772344542667 kcal/mol, 21 in 1424849_FH51
  -1 * FH51-1-pentene  -1 * 2.9775264920608606  -1 * FH51-ethene  -1 * -0.1974217099705129  1 * FH51-Heptene  1 * 9.268877126654843
Top 1 DFT: 14.376499545731349 kcal/mol
Top 2 DFT: 11.10615688978578 kcal/mol
Top 3 DFT: 10.966376306983875 kcal/mol
Top 4 DFT: 9.751064423559 kcal/mol
Top 5 DFT: 9.64041400255519 kcal/mol
Top 1 AI: 5.480142251646612 kcal/mol, 14 in 1424849_TAUT15
  -1 * TAUT15-10a  -1 * -4.874422913300805  1 * TAUT15-10b  1 * 0.605719338345807
Top 2 AI: 4.511525593494298 kcal/mol, 0 in 1424849_TAUT15
  -1 * TAUT15-1a  -1 * -3.414652399980696  1 * TAUT15-1b  1 * 1.096873193513602
Top 3 AI: 3.9130094844149426 kcal/mol, 2 in 1424849_TAUT15
  -1 * TAUT15-3a  -1 * -0.22851199022261426  1 * TAUT15-3b  1 * -4.141521474637557
Top 4 AI: 1.939598721161019 kcal/mol, 13 in 1424849_TAUT15
  -1 * TAUT15-9a  -1 * -1.6955989124253392  1 * TAUT15-9b  1 * 0.24399980873567984
Top 5 AI: 1.6064334915427025 kcal/mol, 6 in 1424849_TAUT15
  -1 * TAUT15-5a  -1 * -3.246505590999732  1 * TAUT15-5b  1 * -4.852939082542434
Top 1 DFT: 7.5247652156685945 kcal/mol
Top 2 DFT: 6.618434203410288 kcal/mol
Top 3 DFT: 6.082770755718229 kcal/mol
Top 4 DFT: 3.889858042122796 kcal/mol
Top 5 DFT: 1.8469628894818015 kcal/mol
Top 1 AI: 14.363085532735568 kcal/mol, 3 in 1424849_DC13
  -2 * DC13-tmethen  -2 * 4.221809613256482  1 * DC13-omcb  1 * 22.806704759248532
Top 2 AI: 14.009644481120631 kcal/mol, 8 in 1424849_DC13
  -4 * DC13-s2  -4 * -0.9940886896220036  1 * DC13-s8  1 * -17.985999239608645
Top 3 AI: 13.047931595618138 kcal/mol, 2 in 1424849_DC13
  1 * DC13-heptatriyne  1 * -8.58112359943334  -1 * DC13-heptahexaene  -1 * -21.629055195051478
Top 4 AI: 12.809457940980792 kcal/mol, 4 in 1424849_DC13
  1 * DC13-ISO_E35  1 * 18.05205850454513  -1 * DC13-ISO_P35  -1 * 5.242600563564338
Top 5 AI: 10.154472930531483 kcal/mol, 6 in 1424849_DC13
  -1 * DC13-ethen  -1 * -0.03755799642385682  -1 * DC13-ch2n2  -1 * -5.947396966352244  1 * DC13-13dip  1 * 4.169517967762658
Top 1 DFT: 37.447079584468156 kcal/mol
Top 2 DFT: 34.20446150796488 kcal/mol
Top 3 DFT: 19.887267829326447 kcal/mol
Top 4 DFT: 18.6525409417809 kcal/mol
Top 5 DFT: 11.921989963244414 kcal/mol
Top 1 AI: 42.67340337204223 kcal/mol, 136 in 1513512_W4_11
  -1 * W4_11-foof  -1 * -42.42863818787737  2 * W4_11-f  2 * 0.01452538870216813  2 * W4_11-o  2 * 0.10785720338026294
Top 2 AI: 33.313599174958654 kcal/mol, 116 in 1513512_W4_11
  -1 * W4_11-p4  -1 * -36.21119966742117  4 * W4_11-p  4 * -0.724400123115629
Top 3 AI: 32.14222127138055 kcal/mol, 41 in 1513512_W4_11
  -1 * W4_11-sif4  -1 * -31.815485039027408  1 * W4_11-si  1 * 0.268634677544469  4 * W4_11-f  4 * 0.01452538870216813
Top 4 AI: 31.444142822001595 kcal/mol, 131 in 1513512_W4_11
  -1 * W4_11-oclo  -1 * -31.287230808578897  2 * W4_11-o  2 * 0.10785720338026294  1 * W4_11-cl  1 * -0.05880239332327619
Top 5 AI: 27.658037785979104 kcal/mol, 134 in 1513512_W4_11
  -1 * W4_11-fo2  -1 * -27.42779799050186  1 * W4_11-f  1 * 0.01452538870216813  2 * W4_11-o  2 * 0.10785720338026294
Top 1 DFT: 64.94237074931152 kcal/mol
Top 2 DFT: 64.82739106187364 kcal/mol
Top 3 DFT: 58.7869441981602 kcal/mol
Top 4 DFT: 55.61715956105036 kcal/mol
Top 5 DFT: 55.142266292670456 kcal/mol
Top 1 AI: 9.665314415993635 kcal/mol, 23 in 1513512_G21EA
  1 * G21EA-EA_24n  1 * -1.4497629219549708  -1 * G21EA-EA_24  -1 * -11.115077337948605
Top 2 AI: 7.491658211423783 kcal/mol, 19 in 1513512_G21EA
  1 * G21EA-EA_20n  1 * -5.942427998306812  -1 * G21EA-EA_20  -1 * -13.434086209730594

data_path   1424849                                                      \
Disp type        AI        DFT   AI_D3BJ  DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1       2.002477  13.710857  1.935526   13.7889  1.859815  13.685393
sub2       5.510109   6.612164  5.412513  6.359139  5.458901   6.408048
sub3       2.617318   6.261376  2.816465  6.625846  2.938387   6.678362
sub4        1.93524   3.272197  1.474342  3.440323  1.710948   3.742517
sub5       1.626727   1.321288  1.369759  0.815469  1.357554   0.809664

data_path             1513512                       ...                       \
Disp type Processed        AI        DFT   AI_D3BJ  ... AI_D3ZERO DFT_D3ZERO
sub1           DONE  6.282354  13.717062  6.368076  ...  6.285388  13.691463
sub2           DONE  7.536765   6.612828  8.231324  ...  8.368537     6.4095
sub3           DONE  4.620451    6.26131  5.023311  ...   5.06199   6.678171
sub4           DONE   2.38953   3.272965  2.422374  ...  2.681673   3.740626
sub5           DONE  1.250183   1.322771  0.678013  ...  0.664039   0.810875

data_path             3036943                                            \
Disp type Processed        AI        DFT   AI_D3BJ   DFT_D3BJ AI_D3ZERO
sub1           DONE  5.772845  13.710857  5.904607  14.259701  5.573973
sub2           DONE  7.919127   6.612128     6.749   9.130035  5.957076
sub3           DONE  4.636265   6.261376  5.246788   7.355579  4.851987
sub4           DONE   3.14773   3.272197  4.543588    5.03074  4.521658
sub5           DONE  1.175371   1.177766  0.751182   0.957237  0.718836

data_path
Disp type DFT_D3ZERO Processed
sub1       13.713797      DONE
sub2        6.757695      DONE
sub3        6.934991      DONE
sub4        4.988172      DONE
sub5        0.899379     7 / 8

[5 rows x 21 columns]

wtmad_1

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
sub1        3.239113   7.420922   2.966428   7.224551   2.815004   7.166359
sub2       13.142366   12.53052  12.443324  11.377537  12.073631  10.891896
sub3        4.832263   6.984991   5.052323    7.34316   5.207324    7.32152
sub4       11.556831  11.029773   7.478943   7.022789   7.675787   7.720437
sub5       15.335367  11.571826  12.722907   6.873743  12.540889   6.757453
summary    48.105939  49.538032  40.663925   39.84178  40.312635  39.857666

data_path              1513512                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE   5.917804   7.427913   5.782796  ...   5.728434
sub2           DONE   9.677109  12.530346   8.502999  ...   8.154213
sub3           DONE   5.362819   6.982875   5.766257  ...   5.725648
sub4           DONE  10.472747  11.046974   5.704214  ...   6.148839
sub5           DONE  10.880025  11.599184   5.605527  ...   5.429641
summary          --  42.310504  49.587291  31.361794  ...  31.186775

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        7.173561      DONE   6.543701   7.420922   5.841371   7.414578
sub2       10.893999      DONE  11.307039  12.530489   8.468475   9.968131
sub3        7.319476      DONE   5.546066   6.984991   6.136313   8.150912
sub4        7.745878      DONE  10.448711  11.029773  12.102006   14.87552
sub5        6.782008      DONE  11.006618  10.752409   6.506317   7.954853
summary    39.914922        --  44.852136  48.718585  39.054481  48.363993

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        5.796977   7.102094      DONE
sub2        8.608195  10.005264      DONE
sub3        5.571336   7.521852      DONE
sub4       11.099232  13.798614      DONE
sub5        6.133091   7.451573     7 / 8
summary    37.208831  45.879399        --

[6 rows x 21 columns]

wtmad_2

data_path    1424849                                                        \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ AI_D3ZERO DFT_D3ZERO
sub1        1.438234   4.040696   1.347877   4.009887  1.298132   3.993215
sub2        3.339073   3.635331    3.00695   3.050633  2.887856   2.955369
sub3        1.303233   2.611064   1.379492   2.754823  1.432794   2.775157
sub4        4.683102   4.159493   3.352776   3.139343  3.830024   3.673649
sub5        6.331811    4.66236   5.509119   2.969375  5.489474   2.874701
summary    17.095452  19.108945  14.596213  15.924061  14.93828   16.27209

data_path              1513512                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
sub1           DONE   2.668675   4.045306   2.649786  ...   2.637463
sub2           DONE   3.206768   3.637148   2.603922  ...   2.543548
sub3           DONE   1.989474   2.610843   2.145594  ...       2.16
sub4           DONE   4.130245    4.16366   2.770651  ...   3.198557
sub5           DONE   4.368745   4.670544   2.432243  ...   2.292671
summary          --  16.363907  19.127501  12.602197  ...  12.832239

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
sub1        3.997743      DONE   3.026285   4.281128   2.858798   4.356088
sub2        2.958326      DONE   3.572836   3.851611    2.11247   2.517388
sub3        2.774852      DONE   2.164366   2.766429   2.424001   3.220901
sub4        3.673564      DONE   4.359528   4.406994   6.311912   7.264515
sub5        2.878168      DONE   4.106082   4.093191   2.599534   3.419076
summary    16.282653        --  17.229098  19.399353  16.306715  20.777968

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
sub1        2.797576   4.227171      DONE
sub2        2.349116   2.697132      DONE
sub3        2.251778   3.044636      DONE
sub4        6.067582   7.014098      DONE
sub5        2.397851   3.104579     7 / 8
summary    15.863904  20.087616        --

[6 rows x 21 columns]

Summary of Subset
MAE

data_path    1424849                                                         \
Disp type         AI        DFT    AI_D3BJ   DFT_D3BJ  AI_D3ZERO DFT_D3ZERO
W4_11       1.028249  29.506863   1.223261  29.989789   1.151098  29.747048
G21EA       0.816732   9.754522   0.816599    9.75468   0.820867   9.756932
G21IP       0.694714   8.953334    0.69616   8.951545    0.68818   8.952599
DIPCS10     2.042735  12.310852   2.039936   12.31518   2.045245  12.283687
PA26        3.009087   2.200766   2.985201   2.058032   2.957953   2.055317
SIE4x4      3.430805  21.908516   3.542007  22.097166   3.562974  22.161897
ALKBDE10    0.959132  18.125246   0.989582  18.277559   0.952777  18.132767
YBDE18      5.939045   8.145393   5.216198   7.828353   4.841699   7.695204
AL2X6       6.140013   5.659145   4.464174   3.449937   3.988804   3.300348
HEAVYSB11   2.024005   5.391476   1.791244   5.463331   1.721678   5.379671
NBPRC       3.058861    2.23255   2.703933   1.870626   2.562871   2.028757
ALK8        4.403777   4.400063   3.334795   3.350254   2.788735   2.953216
RC21        2.456062   4.820926   1.923738    5.39421    1.82928   5.525602
G2RC        1.887093   5.917203   1.969408   6.249306   1.995017   6.227185
BH76RC       0.85212   3.484561   0.891385    3.50012   0.922322   3.516546
FH51        2.464205   3.703657   2.169993   3.443826   2.129573   3.347368
TAUT15      1.702465    2.16453    1.66463   2.155289   1.600571   2.170609
DC13        6.170057  13.090861   6.241887  12.478213   5.863507  11.959009
MB16_43     13.39941  15.461604  15.297752  18.175348  16.246698  18.708523
DARC        7.823359   10.75415   5.637199   7.786582   4.993859   7.610198
RSE43        3.11738     3.1576   3.042746   3.052617   2.897426   2.895709
BSR36        4.98276    8.40118   3.199812   5.170108   2.849067   5.230489
CDIE20      1.450234   1.599507   1.451078   1.511089   1.479492   1.421578
ISO34       2.020035   2.001743   1.914195   1.837375   1.829508   1.772453
PArel       3.015433   1.743933   2.988405    1.73941   2.944914    1.65864
BH76        2.803583   9.107946   2.865363   9.384703   2.949706   9.471921
BHPERI      2.657111   3.268992   3.650976    4.91131   4.133776   5.201979
BHDIV10     4.741552   6.277706   4.837814   6.576988   4.819558   6.463527
INV24       3.393792   2.697333    3.50674   2.430052   3.504461   2.367796
BHROT27     1.713103   0.853379   1.717399   0.843049   1.745492   0.815488
PX13        1.059156  11.042023   1.034643  11.281052   1.127794  11.125104
WCPT18      2.039614   7.967151    2.29673    8.38753   2.461054   8.465437
RG18         0.30936   0.230018   0.307671   0.272271   0.438413   0.363283
ADIM6       3.598266   3.059029   1.159053   0.069974   1.006802   0.047161
S22         2.728845   2.291252   2.115574   1.027824   2.108266   1.185279
S66         2.326488   1.894709    1.01562   0.729648   0.940707   0.863238
WATER27      3.02651  16.299413   2.824412  20.709459   4.382597  22.096474
CARBHB12    0.484944   1.632408   0.473346   2.236748   0.556368   2.356687
PNICO23     0.840943   0.776429   0.940904   1.237735    0.98267   1.220119
HAL59       2.035403   1.649786   1.813837   1.431131   1.991528   1.687656
AHB21       1.666768   2.453821   1.835619   2.836357   1.986367   2.982124
CHB6        1.766454    1.80532   1.689088   2.042249   1.499007   2.186047
IL16        1.467889   1.021067   2.011731   2.478095   2.624917    3.12773
IDISP      13.356085  13.125475   9.748251   6.829682   9.297146   6.724485
ICONF       0.946016   0.413804   0.923008   0.398194   0.896902   0.460113
ACONF       3.016487   0.546621   2.780804   0.134491    2.73024   0.112191
Amino20x4   1.243276   0.656235   1.214437   0.533098   1.214533   0.545417
PCONF21      2.09681   3.214782   1.225373   1.470386   1.250642   1.109308
MCONF       1.596087    1.95602   1.061923   0.627382   1.086374   0.639422
SCONF       1.154998   0.512352   1.064598   0.810397    0.98711   1.033298
BUT14DIOL   0.879011   0.645099   0.933357   0.842079   0.937195   0.833764

data_path              1513512                        ...             \
Disp type Processed         AI        DFT    AI_D3BJ  ...  AI_D3ZERO
W4_11          DONE   8.912932  29.506078   9.339914  ...   9.122765
G21EA          DONE   2.564896   9.754833   2.564919  ...   2.570233
G21IP          DONE   2.386778   8.953264   2.388746  ...   2.388795
DIPCS10        DONE   4.016426  12.311021    4.01094  ...   3.999779
PA26           DONE   2.509054   2.201636    2.61059  ...   2.585335
SIE4x4         DONE  19.060598  21.908495  19.262601  ...  19.324845
ALKBDE10       DONE  12.834948  18.116813   13.00646  ...  12.842719
YBDE18         DONE   6.229871   8.147657   5.696213  ...   5.536839
AL2X6          DONE   1.916657   5.657149   2.275718  ...   2.290996
HEAVYSB11      DONE   4.770742   5.388236   4.344751  ...   4.252022
NBPRC          DONE   3.669712   2.230608   2.690143  ...   2.641647
ALK8           DONE   6.048862   4.392627   4.406227  ...   4.237825
RC21           DONE   4.664053   4.961517    5.25204  ...   5.476267
G2RC           DONE   7.677862   5.917132   8.010816  ...   7.929286
BH76RC         DONE   3.279731   3.485362   3.317796  ...   3.312617
FH51           DONE   3.262527   3.706141   3.103618  ...   3.144699
TAUT15         DONE   1.405035   2.164503   1.403612  ...   1.393841
DC13           DONE  14.707148   13.09363  14.287895  ...  13.803728
MB16_43        DONE  22.256488  15.453583  29.730651  ...  30.570332
DARC           DONE   5.306109  10.749101   2.627762  ...   2.473622
RSE43          DONE   2.373794   3.156151   2.263664  ...   2.107243
BSR36          DONE   9.542035   8.418212   6.085487  ...   6.222024
CDIE20         DONE   1.138114   1.598478   1.020152  ...    0.91279
ISO34          DONE   1.623868   2.001743    1.45501  ...   1.410148
PArel          DONE   1.392302   1.745172   1.354151  ...   1.371634
BH76           DONE   6.839808   9.108903   7.130596  ...   7.206435
BHPERI         DONE   2.393671   3.269267   4.058848  ...   4.280436
BHDIV10        DONE   4.856895   6.276167   5.186639  ...   5.030391
INV24          DONE   2.758492   2.694221   2.678556  ...   2.644791
BHROT27        DONE   0.900358   0.851983   0.890087  ...   0.860663
PX13           DONE   7.029398  11.044222   7.293258  ...   7.113316
WCPT18         DONE   4.657887    7.96751    5.11503  ...    5.19754
RG18           DONE   0.264077   0.230148    0.27333  ...   0.356841
ADIM6          DONE    3.20211   3.074906   0.083724  ...   0.052943
S22            DONE   2.549198   2.292182   0.896549  ...   0.959864
S66            DONE   1.989056   1.896952   0.601756  ...   0.670023
WATER27        DONE   9.389889  16.299413  14.076499  ...  15.449411
CARBHB12       DONE   0.769567   1.633524   1.376546  ...   1.485337
PNICO23        DONE   0.805198   0.775722   1.251776  ...   1.200508
HAL59          DONE    1.55448   1.649326   1.311235  ...   1.536919
AHB21          DONE   1.347543   2.453773    1.70875  ...   1.851066
CHB6           DONE   1.507904   1.803629    1.55138  ...   1.426055
IL16           DONE   0.689251   1.017646   1.294185  ...   1.908241
IDISP          DONE  13.131153  13.141197   6.430055  ...   6.442358
ICONF          DONE   0.500565    0.41335   0.490811  ...   0.544101
ACONF          DONE   0.505225   0.567241   0.116265  ...   0.108128
Amino20x4      DONE   0.668801   0.655899   0.487931  ...    0.47281
PCONF21        DONE   3.002198   3.214782   1.146554  ...   0.803224
MCONF          DONE   2.142772   1.949561   0.761934  ...   0.771607
SCONF          DONE    0.28121   0.514191    0.40678  ...   0.578146
BUT14DIOL      DONE   0.290133   0.650204    0.43114  ...   0.421461

data_path                         3036943                                   \
Disp type DFT_D3ZERO Processed         AI        DFT    AI_D3BJ   DFT_D3BJ
W4_11      29.745907      DONE   6.751417  29.506863   8.059916  31.211753
G21EA        9.75724      DONE   2.581223   9.754522   2.575859   9.751745
G21IP        8.95253      DONE   1.938484   8.953334    1.94495   8.946699
DIPCS10    12.283898      DONE   4.985363  12.310852    4.96582  12.334099
PA26        2.056548      DONE   2.481178   2.200766   2.803242   1.900152
SIE4x4     22.161429      DONE  18.489931  21.908516  18.919228  22.337814
ALKBDE10   18.124323      DONE  11.415343  18.125246  12.103946  18.838948
YBDE18       7.69818      DONE   6.150449   8.145393   4.621046   7.265227
AL2X6       3.302264      DONE   4.917457   5.659145   2.368365   1.332003
HEAVYSB11   5.380932      DONE   5.957114   5.391476   5.287455   8.010474
NBPRC       2.029802      DONE   5.472106    2.23255   3.618643   2.544088
ALK8        2.947479      DONE   7.397188   4.400063   2.018111   3.174803
RC21        5.663666      DONE   4.623606   4.820926   5.620144   6.671006
G2RC        6.227967      DONE   7.179177   5.917203   7.453307   6.933515
BH76RC       3.51709      DONE   3.071453   3.484561   3.095525   3.539828
FH51        3.349427      DONE   3.888296   3.703657   3.188984    3.39478
TAUT15      2.170392      DONE   1.912178    2.16453    1.82538   2.175485
DC13       11.956484      DONE  15.905857  13.090861  14.242867  12.474047
MB16_43    18.696892      DONE  22.182066  15.461604  25.812264  36.862998
DARC        7.610423      DONE  12.601936   10.75415   4.916648    3.43411
RSE43       2.894668      DONE   2.401549     3.1576   2.179161   2.916276
BSR36       5.253588      DONE   8.426309   8.400969   1.124045   1.213694
CDIE20      1.420842      DONE   1.454929   1.599507   1.162292   1.336544
ISO34       1.772736      DONE   1.949135   2.001743   1.457138   1.577125
PArel       1.659645      DONE   1.538891   1.743933   1.578573   1.733749
BH76        9.472317      DONE   6.840908   9.107946   7.620615     9.8892
BHPERI      5.200442      DONE   2.391871   3.268992   3.617896   7.804724
BHDIV10      6.46169      DONE    3.92061   6.277706    4.37726   7.448955
INV24       2.368083      DONE   3.480553   2.697333   3.106395   2.346995
BHROT27     0.814153      DONE   1.122407   0.853379   1.129875   0.858852
PX13       11.127252      DONE   6.613358  11.042023   7.397346   11.82601
WCPT18      8.465016      DONE   4.351093   7.967151   5.535927   9.151986
RG18        0.362415      DONE   0.251696   0.230018   0.620435   0.655714
ADIM6       0.081811      DONE   3.343319   3.059029   1.805966   2.090256
S22         1.186681      DONE   2.516685   2.291252   1.856861   2.402928
S66         0.861105      DONE   2.050673   1.894709   1.649492   2.058561
WATER27    22.085808      DONE  16.008082  16.299413  25.199717  25.491048
CARBHB12    2.356523      DONE   0.842403   1.632408   2.183098   2.973103
PNICO23      1.21787      DONE   0.592242   0.776429   2.267249   2.604046
HAL59       1.685489      DONE   1.397919   1.649786     2.2513   2.629912
AHB21       2.981231      DONE   1.636192   2.453821   2.607929   3.464384
CHB6        2.183829      DONE   1.653953    1.80532   1.319883   3.038126
IL16        3.120758      DONE   0.955003   1.021067   3.302781   4.339132
IDISP       6.751951      DONE  14.676912  13.125475   4.507285   4.423061
ICONF       0.459859      DONE   0.506738   0.413804   0.604105   0.464652
ACONF       0.125809      DONE   0.807662   0.546621   0.201956   0.430751
Amino20x4   0.541856      DONE   0.759824   0.656235   0.573798   0.647041
PCONF21     1.113126      DONE   3.128427   3.214782   0.675105   1.178453
MCONF        0.63646      DONE   1.391821   1.300487   0.753458   0.631118
SCONF       1.034838      DONE   0.437402   0.512352   1.275586   1.432857
BUT14DIOL   0.838464      DONE    0.30573   0.645099   0.670318   1.136703

data_path
Disp type  AI_D3ZERO DFT_D3ZERO Processed
W4_11       6.966114  29.861055      DONE
G21EA       2.592166   9.757546      DONE
G21IP       1.941726     8.9519      DONE
DIPCS10      4.96276  12.264655      DONE
PA26        2.648785    2.00824      DONE
SIE4x4     18.921342  22.339928      DONE
ALKBDE10   11.425615  18.135588      DONE
YBDE18      4.970929   7.472761      DONE
AL2X6        1.38317   1.829895      DONE
HEAVYSB11   4.527058   5.984154      DONE
NBPRC        4.23187   2.274234      DONE
ALK8        4.748123   2.559066      DONE
RC21        5.317952     6.0297      DONE
G2RC        7.220284   6.417298      DONE
BH76RC      3.053555   3.536982      DONE
FH51        3.226841   3.256908      DONE
TAUT15      1.704126   2.145937      DONE
DC13       14.033471  11.475687      DONE
MB16_43    19.630524  23.165472      DONE
DARC        7.425756    5.57797      DONE
RSE43       2.013019    2.74911      DONE
BSR36       3.104446   3.079106      DONE
CDIE20      1.158596   1.347484      DONE
ISO34       1.541408   1.647042      DONE
PArel       1.450655   1.645025      DONE
BH76        7.410716   9.676053      DONE
BHPERI      2.227072     6.4139      DONE
BHDIV10     4.006236   6.535109      DONE
INV24       2.968734   2.228547      DONE
BHROT27     1.046716    0.78352      DONE
PX13        6.791192  11.219857      DONE
WCPT18      5.128245   8.744304      DONE
RG18        0.674273   0.709552      DONE
ADIM6       2.106534   2.390824      DONE
S22         1.745691   2.291758      DONE
S66         1.692907   2.101976      DONE
WATER27    26.178239  26.402884      DONE
CARBHB12    2.051772   2.841777      DONE
PNICO23      1.39002   1.726817      DONE
HAL59       1.868664   2.247276      DONE
AHB21       2.438064   3.294519      DONE
CHB6        1.399695   2.309161      DONE
IL16        3.373612   4.409963      DONE
IDISP        5.63161   5.245746      DONE
ICONF       0.500926   0.493337      DONE
ACONF       0.134553   0.274429      DONE
Amino20x4   0.521346   0.576975      DONE
PCONF21     0.756223   1.099663      DONE
MCONF        0.69667   0.654308   10 / 51
SCONF       1.157113   1.317952      DONE
BUT14DIOL   0.576481    1.02002      DONE

[51 rows x 21 columns]

In [5]:
16.363907 / 19.127501, 12.60223 / 15.936448, 14.245033 / 17.35668

(0.8555172471301924, 0.7907803545683455, 0.8207233756686185)