In [1]:
import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np

date = datetime.now().strftime("%Y-%m-%d")

verbose = 2
with open("/home/chenzihao/workspace/cc2cc_test5/cc2cc/utils/gmtkn-def2.json") as f:
    json_data = json.load(f)

basis_args = "def2-TZVPD"
print(basis_args)

dft_type_list = ["scf_ene", "scf_d3bj_ene"]
data = pd.read_csv(
    "/home/chenzihao/workspace/cc2cc_test5/validate_hkqai/ccdft_def2-TZVPD_atom-1-1679342_gmtkn-def2.csv"
)

with open(f"./subset.json") as f:
    full_subset_dict = json.load(f)["full_subset_dict"]

for name_set, subset_list_ in full_subset_dict.items():
    full_subset_dict[name_set] = np.sort(subset_list_)
data_subset = {}

for name_set, subset_list_ in full_subset_dict.items():
    for dft_type in dft_type_list:
        if dft_type in data.columns:
            data_name = (data["name"].str.split(f"_{basis_args}").str[0]).to_numpy()
            data_dft = data[dft_type].to_numpy() * 627.5094733748099
        else:
            data_name = []
            for i_subset in subset_list_:
                if i_subset == "BH76RC":
                    data_name.append(json_data["molecule_BH76"])
                else:
                    data_name.append(json_data[f"molecule_{i_subset}"])
            data_name = np.concatenate(data_name)
            data_dft = np.zeros_like(data_name, dtype=float)

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"
            data_subset[name_subset] = {
                "name": [],
                "dft_name": [],
                "dft": [],
                "cc": [],
            }

            if i_subset == "BH76RC":
                molecular_list = json_data["molecule_BH76"]
            else:
                molecular_list = json_data[f"molecule_{i_subset}"]

            for i_molecule_name in molecular_list:
                col = np.where(data_name == i_molecule_name)[0]
                if col.size != 1:
                    # if verbose > 0:
                    #     print(f"Warning: {i_molecule_name} not found in data file")
                    continue

            reaction_dict = json_data[f"reaction-{i_subset}"]
            for i_reaction_name, i_reaction in reaction_dict.items():
                systems_list = i_reaction["systems"]
                stoichiometry_list = i_reaction["stoichiometry"]

                atomic_energy_dft = 0
                finished, exist = True, True

                for i in range(len(systems_list)):
                    mole_name = (
                        systems_list[i]
                        if i_subset == "BH76RC"
                        else f"{i_subset}-{systems_list[i]}"
                    )
                    stoichiometry = int(stoichiometry_list[i])

                    if mole_name in json_data:
                        if isinstance(json_data[mole_name], str):
                            mole_name = json_data[mole_name]
                    else:
                        finished, exist = False, False
                        # if verbose > 0:
                        #     print(f"Warning: {mole_name} not found in json, ERROR")
                        break

                    col = np.where(data_name == mole_name)[0]
                    if col.size == 1:
                        atomic_energy_dft += data_dft[col[0]] * stoichiometry
                    else:
                        finished = False
                        # if verbose > 0:
                        #     print(f"Warning: {mole_name} not found in data csv file")
                        break

                if exist:
                    data_subset[name_subset]["name"].append(i_reaction_name)
                if finished:
                    data_subset[name_subset]["dft_name"].append(i_reaction_name)
                    for i in range(len(systems_list)):
                        data_subset[name_subset]["dft_name"][
                            -1
                        ] = f"{data_subset[name_subset]["dft_name"][-1]}-{systems_list[i]}"

                    atomic_energy_cc = i_reaction["reference"]
                    data_subset[name_subset]["dft"].append(
                        abs(atomic_energy_dft - atomic_energy_cc)
                    )
                    data_subset[name_subset]["cc"].append(abs(atomic_energy_cc))
                    if np.abs(atomic_energy_cc) > 1000:
                        print(
                            f"Warning: {i_reaction_name} in {name_subset} has a large CC energy: {atomic_energy_cc} kcal/mol"
                        )

            for key, val in data_subset.items():
                for key2, val2 in val.items():
                    if isinstance(val2, list):
                        data_subset[key][key2] = np.array(val2)

            if verbose > 1:
                argsort_atomic_energy_dft = np.argsort(data_subset[name_subset]["dft"])[
                    ::-1
                ]
                for i in range(len(argsort_atomic_energy_dft)):
                    print(
                        f"Top {i+1} with name {data_subset[name_subset]["dft_name"][argsort_atomic_energy_dft[i]]} DFT: {data_subset[name_subset]['dft'][argsort_atomic_energy_dft[i]]} kcal/mol"
                    )

header = dft_type_list + ["Processed"]

df_summary_subset = pd.DataFrame(columns=header)
mean_subset = pd.DataFrame(columns=header)
wtmad_1_subset = pd.DataFrame(columns=header)
wtmad_2_subset = pd.DataFrame(columns=header)

for dft_type in dft_type_list:
    mean_absolute_deviation_list = []

    for name_set, subset_list_ in full_subset_dict.items():
        subset_dft = []
        wtmad_1_dft = []
        wtmad_2_dft = []
        processed = []

        for i_subset in subset_list_:
            name_subset = f"{dft_type}_{i_subset}"

            if len(data_subset[name_subset]["dft"]) == 0:
                df_summary_subset.loc[i_subset, dft_type] = 0
                df_summary_subset.loc[i_subset, "Processed"] = (
                    f"0 / {len(data_subset[name_subset]['name'])}"
                )
            else:
                df_summary_subset.loc[i_subset, dft_type] = np.mean(
                    data_subset[name_subset]["dft"]
                )
                df_summary_subset.loc[i_subset, "Processed"] = (
                    "DONE"
                    if (
                        (
                            len(data_subset[name_subset]["dft"])
                            == len(data_subset[name_subset]["name"])
                        )
                        and (len(data_subset[name_subset]["dft"]) != 0)
                    )
                    else f"{len(data_subset[name_subset]['dft'])} / "
                    f"{len(data_subset[name_subset]['name'])}"
                )

                if np.mean(data_subset[name_subset]["cc"]) > 75:
                    wtmad_1 = 0.1
                elif np.mean(data_subset[name_subset]["cc"]) < 7.5:
                    wtmad_1 = 10
                else:
                    wtmad_1 = 1

                subset_dft = np.append(subset_dft, data_subset[name_subset]["dft"])
                wtmad_1_dft = np.append(
                    wtmad_1_dft,
                    wtmad_1 * np.mean(data_subset[name_subset]["dft"]),
                )
                wtmad_2_dft = np.append(
                    wtmad_2_dft,
                    data_subset[name_subset]["dft"]
                    / np.mean(data_subset[name_subset]["cc"]),
                )
                mean_absolute_deviation_list = np.append(
                    mean_absolute_deviation_list,
                    data_subset[name_subset]["cc"],
                )
            if (
                len(data_subset[name_subset]["dft"])
                == len(data_subset[name_subset]["name"])
                and len(data_subset[name_subset]["name"]) > 0
            ):
                processed.append(1)
            else:
                processed.append(0)

        mean_subset.loc[name_set, dft_type] = np.mean(subset_dft)
        wtmad_1_subset.loc[name_set, dft_type] = np.mean(wtmad_1_dft)
        wtmad_2_subset.loc[name_set, dft_type] = np.sum(wtmad_2_dft)
        mean_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_1_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )
        wtmad_2_subset.loc[name_set, "Processed"] = (
            "DONE"
            if (sum(processed) == len(processed) and len(processed) != 0)
            else f"{sum(processed)} / " f"{len(processed)}"
        )

    mean_absolute_deviation = 56.84 / len(mean_absolute_deviation_list)
    print(
        f"Mean absolute deviation for {dft_type}: {mean_absolute_deviation:.4f} kcal/mol"
    )
    for name_set in full_subset_dict.keys():
        wtmad_2_subset.loc[name_set, dft_type] = (
            mean_absolute_deviation * wtmad_2_subset.loc[name_set, dft_type]
        )

    wtmad_1_subset.loc["summary", "Processed"] = "--"
    wtmad_2_subset.loc["summary", "Processed"] = "--"
    wtmad_1_subset.loc["summary", dft_type] = 0
    wtmad_2_subset.loc["summary", dft_type] = 0
    for name_set in full_subset_dict.keys():
        wtmad_1_subset.loc["summary", dft_type] += wtmad_1_subset.loc[
            name_set, dft_type
        ]
        wtmad_2_subset.loc["summary", dft_type] += wtmad_2_subset.loc[
            name_set, dft_type
        ]

print("MAE")
display(mean_subset)
print("wtmad_1")
display(wtmad_1_subset)
print("wtmad_2")
display(wtmad_2_subset)
print("Summary of Subset")
print("MAE")
display(df_summary_subset)

# save summary to excel with date
df_summary_subset.to_excel(f"../validate_hkqai_done/summary_subset_{date}.xlsx")
mean_subset.to_excel(f"../validate_hkqai_done/mean_subset_{date}.xlsx")
wtmad_1_subset.to_excel(f"../validate_hkqai_done/wtmad_1_subset_{date}.xlsx")
wtmad_2_subset.to_excel(f"../validate_hkqai_done/wtmad_2_subset_{date}.xlsx")

def2-TZVPD
Top 1 with name 5-al2me6-alme3 DFT: 5.31837773686275 kcal/mol
Top 2 with name 4-al2me5-alme2-alme3 DFT: 3.70506898749154 kcal/mol
Top 3 with name 1-al2f6-alf3 DFT: 3.5393704901449397 kcal/mol
Top 4 with name 3-al2me4-alme2 DFT: 0.9957893619779483 kcal/mol
Top 5 with name 2-al2cl6-alcl3 DFT: 0.7178096454590559 kcal/mol
Top 6 with name 0-al2h6-alh3 DFT: 0.3802605289965868 kcal/mol
Top 1 with name 8-mgs-mg-s DFT: 9.271880338742633 kcal/mol
Top 2 with name 7-mgo-mg-o DFT: 8.49468604504655 kcal/mol
Top 3 with name 0-bef-be-f DFT: 7.81062633810069 kcal/mol
Top 4 with name 1-beo-be-o DFT: 7.2427535862385355 kcal/mol
Top 5 with name 3-hf-h-f DFT: 5.592363692283101 kcal/mol
Top 6 with name 9-nao-na-o DFT: 4.113320584964825 kcal/mol
Top 7 with name 4-kf-k-f DFT: 3.3684083761691 kcal/mol
Top 8 with name 5-lif-li-f DFT: 2.8043342337070385 kcal/mol
Top 9 with name 2-cao-ca-o DFT: 1.6419373133510788 kcal/mol
Top 10 with name 6-lio-li-o DFT: 0.7460932462854544 kcal/mol
Top 1 with name 2-c2h4-c2h4_2+ DFT: 15.864272893367115 kcal/mol
Top 2 with name 0-c4h4-c4h4_2+ DFT: 11.103168304677865 kcal/mol
Top 3 with name 7-ph3-ph3_2+ DFT: 8.121308936935407 kcal/mol
Top 4 with name 4-nh3-nh3_2+ DFT: 7.639902911971149 kcal/mol
Top 5 with name 6-h2s-h2s_2+ DFT: 7.477537133410806 kcal/mol
Top 6 with name 1-c2h6-c2h6_2+ DFT: 5.204206948606611 kcal/mol
Top 7 with name 8-mg-mg_2+ DFT: 4.137078646855684 kcal/mol
Top 8 with name 9-be-be_2+ DFT: 2.073604366175232 kcal/mol
Top 9 with name 5-ch2o-ch2o_2+ DFT: 1.7881202779041132 kcal/mol
Top 10 with name 3-n2h2-n2h2_2+ DFT: 0.7778253431985149 kcal/mol
Top 1 with name 4-EA_p-EA_p- DFT: 11.979403586487752 kcal/mol
Top 2 with name 16-EA_17n-EA_17 DFT: 9.397721860586898 kcal/mol
Top 3 with name 10-EA_11n-EA_11 DFT: 9.285680315519858 kcal/mol
Top 4 with name 17-EA_18n-EA_18 DFT: 8.846736200136366 kcal/mol
Top 5 with name 0-EA_c-EA_c- DFT: 7.504379409801185 kcal/mol
Top 6 with name 11-EA_12n-EA_12 DFT: 7.2450846369218205 kcal/mol
Top 7 with name 24-EA_25n-EA_25 DFT: 7.051730512711217 kcal/mol
Top 8 with name 9-EA_10n-EA_10 DFT: 6.79379218065078 kcal/mol
Top 9 with name 3-EA_si-EA_si- DFT: 6.385260747041322 kcal/mol
Top 10 with name 23-EA_24n-EA_24 DFT: 6.117387352220248 kcal/mol
Top 11 with name 7-EA_8n-EA_8 DFT: 5.775246914376474 kcal/mol
Top 12 with name 8-EA_9n-EA_9 DFT: 5.764676327724738 kcal/mol
Top 13 with name 18-EA_19n-EA_19 DFT: 5.032327315118167 kcal/mol
Top 14 with name 13-EA_14n-EA_14 DFT: 4.736964659806109 kcal/mol
Top 15 with name 5-EA_s-EA_s- DFT: 4.313995964213973 kcal/mol
Top 16 with name 1-EA_o-EA_o- DFT: 4.2015492644088255 kcal/mol
Top 17 with name 12-EA_13n-EA_13 DFT: 3.6916495084617083 kcal/mol
Top 18 with name 15-EA_16n-EA_16 DFT: 3.4290020220563733 kcal/mol
Top 19 with name 2-EA_f-EA_f- DFT: 3.302231834050332 kcal/mol
Top 20 with name 22-EA_23n-EA_23 DFT: 3.2385190182598294 kcal/mol
Top 21 with name 6-EA_cl-EA_cl- DFT: 3.2174571008072235 kcal/mol
Top 22 with name 20-EA_21n-EA_21 DFT: 2.9145788792491656 kcal/mol
Top 23 with name 19-EA_20n-EA_20 DFT: 1.0865249797934666 kcal/mol
Top 24 with name 21-EA_22n-EA_22 DFT: 0.8878521379447193 kcal/mol
Top 25 with name 14-EA_15n-EA_15 DFT: 0.10015266845002913 kcal/mol
Top 1 with name 33-IP_78-45 DFT: 17.498316611412008 kcal/mol
Top 2 with name 26-IP_71-25 DFT: 9.001063560798627 kcal/mol
Top 3 with name 27-IP_72-26 DFT: 8.305678591442472 kcal/mol
Top 4 with name 15-IP_59-8 DFT: 7.173667844261274 kcal/mol
Top 5 with name 30-IP_75-37 DFT: 6.742099169247808 kcal/mol
Top 6 with name 23-IP_67-20 DFT: 6.357669827513632 kcal/mol
Top 7 with name 25-IP_70-22 DFT: 5.971616217136386 kcal/mol
Top 8 with name 6-o+-o DFT: 5.6525481501637955 kcal/mol
Top 9 with name 20-IP_64-18 DFT: 5.598829645180842 kcal/mol
Top 10 with name 13-s+-s DFT: 5.524661532748723 kcal/mol
Top 11 with name 34-IP_79-51 DFT: 5.321113409335737 kcal/mol
Top 12 with name 14-cl+-cl DFT: 5.153463075542845 kcal/mol
Top 13 with name 7-f+-f DFT: 5.070386552691332 kcal/mol
Top 14 with name 28-IP_73-30 DFT: 4.407415046585015 kcal/mol
Top 15 with name 19-IP_63-14 DFT: 4.132804312719884 kcal/mol
Top 16 with name 18-IP_62-13 DFT: 3.943469080629143 kcal/mol
Top 17 with name 29-IP_74-34 DFT: 3.764215634718994 kcal/mol
Top 18 with name 16-IP_60-11 DFT: 3.1913719412963815 kcal/mol
Top 19 with name 32-IP_77-44 DFT: 3.11690258027474 kcal/mol
Top 20 with name 21-IP_65-IP_n65 DFT: 2.312237926245899 kcal/mol
Top 21 with name 35-IP_80-48 DFT: 2.14250674518712 kcal/mol
Top 22 with name 9-mg+-mg DFT: 2.058869287965365 kcal/mol
Top 23 with name 24-IP_68-137 DFT: 1.6693464235984834 kcal/mol
Top 24 with name 17-IP_61-12 DFT: 1.659051911998688 kcal/mol
Top 25 with name 5-n+-n DFT: 1.527598093748395 kcal/mol
Top 26 with name 4-c+-c DFT: 1.3706613183254603 kcal/mol
Top 27 with name 0-h DFT: 1.3450181056977044 kcal/mol
Top 28 with name 31-IP_76-43 DFT: 1.1526505376598664 kcal/mol
Top 29 with name 8-na+-na DFT: 1.0008511261257809 kcal/mol
Top 30 with name 2-be+-be DFT: 0.9225666025999146 kcal/mol
Top 31 with name 11-si+-si DFT: 0.9129440636315849 kcal/mol
Top 32 with name 12-p+-p DFT: 0.8285483675776106 kcal/mol
Top 33 with name 10-al+-al DFT: 0.8023334499739576 kcal/mol
Top 34 with name 1-li+-li DFT: 0.7121481894893833 kcal/mol
Top 35 with name 22-IP_66-19 DFT: 0.6932142410676363 kcal/mol
Top 36 with name 3-b+-b DFT: 0.686507799333782 kcal/mol
Top 1 with name 6-pme2-p2me4 DFT: 12.045881449617447 kcal/mol
Top 2 with name 7-asme2-as2me4 DFT: 11.662527984306216 kcal/mol
Top 3 with name 4-seh-h2se2 DFT: 8.343533224314449 kcal/mol
Top 4 with name 2-pbme3-pb2me6 DFT: 7.833781514449512 kcal/mol
Top 5 with name 8-sbme2-sb2me4 DFT: 6.947079117430839 kcal/mol
Top 6 with name 3-sh-h2s2 DFT: 6.216458305448754 kcal/mol
Top 7 with name 0-geh3-ge2h6 DFT: 5.540448557753109 kcal/mol
Top 8 with name 5-teme-te2me2 DFT: 5.505511762308885 kcal/mol
Top 9 with name 9-cl-cl2 DFT: 2.8018753049895153 kcal/mol
Top 10 with name 10-br-br2 DFT: 1.6541594635508972 kcal/mol
Top 1 with name 0-nh3-bh3-nh3-bh3 DFT: 7.718612039310393 kcal/mol
Top 2 with name 6-BH3PH3-BH3-PH3 DFT: 7.057252748508471 kcal/mol
Top 3 with name 1-nh3-bh3-nh2-bh2-h2 DFT: 3.244909124792616 kcal/mol
Top 4 with name 7-K_H-BH3PH3-H2 DFT: 2.321228128916708 kcal/mol
Top 5 with name 2-nh2-bh2-nh-bh-h2 DFT: 1.2106549798857245 kcal/mol
Top 1 with name 3-p8-p8p DFT: 8.659036615031084 kcal/mol
Top 2 with name 2-p6-p6p DFT: 7.088671791873651 kcal/mol
Top 3 with name 1-p4-p4p DFT: 5.160252397612197 kcal/mol
Top 4 with name 10-hcl-hclp DFT: 4.474109660822421 kcal/mol
Top 5 with name 22-A-Ap DFT: 4.210883055895096 kcal/mol
Top 6 with name 16-phenol-phenolp DFT: 3.2306673103826995 kcal/mol
Top 7 with name 21-phosphapyrrol-phosphapyrrolp DFT: 3.2016733289696333 kcal/mol
Top 8 with name 17-ass-assp DFT: 2.8979477100772897 kcal/mol
Top 9 with name 24-G-Gp DFT: 2.890730694984086 kcal/mol
Top 10 with name 18-ch2s-ch2sp DFT: 2.8442350053693986 kcal/mol
Top 11 with name 12-c2f6-c2f6p DFT: 2.4964726212085253 kcal/mol
Top 12 with name 9-h2s-h2sp DFT: 2.229105093417445 kcal/mol
Top 13 with name 8-ph3-ph3p DFT: 2.0224954537872577 kcal/mol
Top 14 with name 6-c2h2-c2h2p DFT: 1.9688218024035393 kcal/mol
Top 15 with name 0-p2-p2p DFT: 1.341711644829786 kcal/mol
Top 16 with name 13-ethanol-ethanolp DFT: 1.2430350443522968 kcal/mol
Top 17 with name 25-C-Cp DFT: 1.1908788441855052 kcal/mol
Top 18 with name 5-h2o-h2op DFT: 1.0492834143718994 kcal/mol
Top 19 with name 15-gly-glyp DFT: 0.9267350631300246 kcal/mol
Top 20 with name 23-T-Tp DFT: 0.8472749723703714 kcal/mol
Top 21 with name 4-nh3-nh3p DFT: 0.5919597669912093 kcal/mol
Top 22 with name 19-si2h6-si2h6p DFT: 0.4457518142531569 kcal/mol
Top 23 with name 11-h2-h2p DFT: 0.39114110897862986 kcal/mol
Top 24 with name 7-sih4-sih4p DFT: 0.24079557939549545 kcal/mol
Top 25 with name 20-cys-cysp DFT: 0.20067448414630462 kcal/mol
Top 26 with name 14-ch3cooh-ch3coohp DFT: 0.07727233424665769 kcal/mol
Top 1 with name 7-he-he+-he2+_1.75 DFT: 42.928688765260084 kcal/mol
Top 2 with name 6-he-he+-he2+_1.5 DFT: 35.696397302145854 kcal/mol
Top 3 with name 5-he-he+-he2+_1.25 DFT: 27.908915321918904 kcal/mol
Top 4 with name 15-h2o-h2o+-h2o2+_1.75 DFT: 26.50620916803309 kcal/mol
Top 5 with name 14-h2o-h2o+-h2o2+_1.5 DFT: 22.32276419462287 kcal/mol
Top 6 with name 11-nh3-nh3+-nh32+_1.75 DFT: 21.97337733770255 kcal/mol
Top 7 with name 4-he-he+-he2+_1.0 DFT: 21.89470393700558 kcal/mol
Top 8 with name 13-h2o-h2o+-h2o2+_1.25 DFT: 17.855467921492526 kcal/mol
Top 9 with name 10-nh3-nh3+-nh32+_1.5 DFT: 17.566401658879478 kcal/mol
Top 10 with name 9-nh3-nh3+-nh32+_1.25 DFT: 12.528600557963365 kcal/mol
Top 11 with name 3-h-h2+_1.75 DFT: 11.339177864948297 kcal/mol
Top 12 with name 12-h2o-h2o+-h2o2+_1.0 DFT: 9.209102031786458 kcal/mol
Top 13 with name 2-h-h2+_1.5 DFT: 8.818163851196502 kcal/mol
Top 14 with name 8-nh3-nh3+-nh32+_1.0 DFT: 6.09668951725471 kcal/mol
Top 15 with name 1-h-h2+_1.25 DFT: 6.063203425854319 kcal/mol
Top 16 with name 0-h-h2+_1.0 DFT: 3.834627627310425 kcal/mol
Warning: 15 in scf_ene_W4_11 has a large CC energy: 1007.909 kcal/mol
Top 1 with name 116-p4-p DFT: 45.64978699236826 kcal/mol
Top 2 with name 130-c2-c DFT: 40.30859111178765 kcal/mol
Top 3 with name 41-sif4-si-f DFT: 34.15564769340676 kcal/mol
Top 4 with name 15-propane-c-h DFT: 32.0658205534163 kcal/mol
Top 5 with name 90-nccn-n-c DFT: 31.78914967224017 kcal/mol
Top 6 with name 52-acetic-c-o-h DFT: 29.961469214455065 kcal/mol
Top 7 with name 23-propene-c-h DFT: 28.988885135314376 kcal/mol
Top 8 with name 25-ethanol-c-o-h DFT: 28.266860982632807 kcal/mol
Top 9 with name 38-propyne-c-h DFT: 28.188527588003353 kcal/mol
Top 10 with name 138-bn-b-n DFT: 27.797850171291856 kcal/mol
Top 11 with name 11-b2h6-b-h DFT: 27.7689162796936 kcal/mol
Top 12 with name 133-b2-b DFT: 26.145856380198154 kcal/mol
Top 13 with name 66-glyoxal-c-o-h DFT: 25.77666085423175 kcal/mol
Top 14 with name 46-alf3-al-f DFT: 25.182619635360766 kcal/mol
Top 15 with name 40-allene-c-h DFT: 24.743409523146852 kcal/mol
Top 16 with name 107-so3-s-o DFT: 24.240890878864548 kcal/mol
Top 17 with name 44-oxirane-c-o-h DFT: 23.350071782300688 kcal/mol
Top 18 with name 39-acetaldehyde-c-o-h DFT: 23.030015901160596 kcal/mol
Top 19 with name 128-s4-c2v-s DFT: 22.869407771622775 kcal/mol
Top 20 with name 104-hnnn-h-n DFT: 22.267347541910738 kcal/mol
Top 21 with name 20-c2h5f-c-h-f DFT: 22.138036889038176 kcal/mol
Top 22 with name 76-oxirene-c-o-h DFT: 21.847326211351856 kcal/mol
Top 23 with name 14-c2h6-c-h DFT: 21.741555048127907 kcal/mol
Top 24 with name 21-ch3nh2-c-n-h DFT: 21.64713922218732 kcal/mol
Top 25 with name 78-hocn-c-o-n-h DFT: 21.574608798153008 kcal/mol
Top 26 with name 49-n2h4-h-n DFT: 21.08342907472712 kcal/mol
Top 27 with name 91-n2-n DFT: 20.832942644380978 kcal/mol
Top 28 with name 98-honc-c-o-n-h DFT: 20.74956684086743 kcal/mol
Top 29 with name 43-c2h3f-c-f-h DFT: 19.8617423649589 kcal/mol
Top 30 with name 126-s3-s DFT: 19.807168991245334 kcal/mol
Top 31 with name 64-formic-c-o-h DFT: 19.786216586849605 kcal/mol
Top 32 with name 32-ch2nh2-c-n-h DFT: 19.777953217711854 kcal/mol
Top 33 with name 27-c2h4-c-h DFT: 19.47180388156312 kcal/mol
Top 34 with name 53-c2h2-c-h DFT: 19.400149039250437 kcal/mol
Top 35 with name 50-ch2nh-c-n-h DFT: 19.368948118386868 kcal/mol
Top 36 with name 42-bf3-b-f DFT: 19.35893589194353 kcal/mol
Top 37 with name 81-hnco-c-o-n-h DFT: 19.000092005092824 kcal/mol
Top 38 with name 80-t-n2h2-h-n DFT: 18.895512525269055 kcal/mol
Top 39 with name 62-ketene-c-o-h DFT: 18.713748628329427 kcal/mol
Top 40 with name 82-c-n2h2-h-n DFT: 18.61323278195573 kcal/mol
Top 41 with name 70-hccf-c-f-h DFT: 18.561063505844402 kcal/mol
Top 42 with name 69-cf4-c-f DFT: 18.50206546059576 kcal/mol
Top 43 with name 71-hcn-h-c-n DFT: 18.405744044621656 kcal/mol
Top 44 with name 86-dioxirane-c-o-h DFT: 18.396483571780095 kcal/mol
Top 45 with name 97-hcno-c-o-n-h DFT: 17.997554980408438 kcal/mol
Top 46 with name 122-p2-p DFT: 17.98209763726406 kcal/mol
Top 47 with name 8-si2h6-si-h DFT: 17.951935836256098 kcal/mol
Top 48 with name 113-n2o-n-o DFT: 17.719352980222368 kcal/mol
Top 49 with name 121-s2o-s-o DFT: 17.705782143738418 kcal/mol
Top 50 with name 72-hnc-h-c-n DFT: 17.609291186001883 kcal/mol
Top 51 with name 26-ch3nh-c-n-h DFT: 17.59815997202611 kcal/mol
Top 52 with name 85-fccf-c-f DFT: 17.58615121353114 kcal/mol
Top 53 with name 106-cn-c-n DFT: 17.4469985798074 kcal/mol
Top 54 with name 28-methanol-c-o-h DFT: 17.320774009987417 kcal/mol
Top 55 with name 110-so2-s-o DFT: 17.270264293533614 kcal/mol
Top 56 with name 101-c-hono-h-n-o DFT: 16.996015045765432 kcal/mol
Top 57 with name 105-cs-c-s DFT: 16.965032858576848 kcal/mol
Top 58 with name 73-cch-c-h DFT: 16.834517623026784 kcal/mol
Top 59 with name 102-t-hono-h-n-o DFT: 16.722120948058205 kcal/mol
Top 60 with name 95-clcn-cl-c-n DFT: 16.660879641007227 kcal/mol
Top 61 with name 47-bef2-be-f DFT: 16.363950386233967 kcal/mol
Top 62 with name 65-hcnh-c-n-h DFT: 16.239358546817243 kcal/mol
Top 63 with name 36-ch2ch-c-h DFT: 16.17116766657739 kcal/mol
Top 64 with name 77-f2co-c-o-f DFT: 16.070886465751357 kcal/mol
Top 65 with name 92-n2h-n-h DFT: 15.46796512915617 kcal/mol
Top 66 with name 12-sih3f-si-h-f DFT: 15.353965505349436 kcal/mol
Top 67 with name 33-bhf2-b-h-f DFT: 14.908775554200531 kcal/mol
Top 68 with name 75-co-c-o DFT: 14.817627515593927 kcal/mol
Top 69 with name 84-co2-c-o DFT: 14.795121649917235 kcal/mol
Top 70 with name 67-hcof-c-o-f-h DFT: 14.674527396997291 kcal/mol
Top 71 with name 55-h2cn-h-c-n DFT: 14.381825796936255 kcal/mol
Top 72 with name 48-ch2c-c-h DFT: 14.176721007406456 kcal/mol
Top 73 with name 45-ch2f2-c-f-h DFT: 13.779785102865617 kcal/mol
Top 74 with name 93-ocs-o-c-s DFT: 13.677938143195831 kcal/mol
Top 75 with name 99-hno-h-n-o DFT: 13.659665106839952 kcal/mol
Top 76 with name 137-o3-o DFT: 13.581042844816807 kcal/mol
Top 77 with name 54-h2co-h-c-o DFT: 13.494728630958548 kcal/mol
Top 78 with name 24-nh3-n-h DFT: 13.233553429650044 kcal/mol
Top 79 with name 58-t-hcoh-c-o-h DFT: 13.038600730467806 kcal/mol
Top 80 with name 60-c-hcoh-c-o-h DFT: 12.956822004001822 kcal/mol
Top 81 with name 103-cs2-c-s DFT: 12.875820910392349 kcal/mol
Top 82 with name 111-no-n-o DFT: 12.264834325532433 kcal/mol
Top 83 with name 79-hooh-h-o DFT: 12.00641549578728 kcal/mol
Top 84 with name 22-ch3f-c-f-h DFT: 11.930415765470059 kcal/mol
Top 85 with name 10-ch4-c-h DFT: 11.899770618150512 kcal/mol
Top 86 with name 59-alcl3-al-cl DFT: 11.628313469047669 kcal/mol
Top 87 with name 124-no2-n-o DFT: 11.549427500258787 kcal/mol
Top 88 with name 94-sio-si-o DFT: 11.195384727685763 kcal/mol
Top 89 with name 109-bn3pi-b-n DFT: 11.187243708508902 kcal/mol
Top 90 with name 13-ph3-p-h DFT: 10.786345901691163 kcal/mol
Top 91 with name 68-nh2cl-n-cl-h DFT: 10.69385759090406 kcal/mol
Top 92 with name 74-hco-h-c-o DFT: 10.651137894355543 kcal/mol
Top 93 with name 3-sih4-si-h DFT: 10.627765456318286 kcal/mol
Top 94 with name 88-ssh-s-h DFT: 10.520112719279268 kcal/mol
Top 95 with name 34-h2o-h-o DFT: 9.638303279947479 kcal/mol
Top 96 with name 83-cf2-c-f DFT: 9.633002132942067 kcal/mol
Top 97 with name 9-ch3-c-h DFT: 9.41325769422508 kcal/mol
Top 98 with name 120-t-hooo-h-o DFT: 9.349882397285427 kcal/mol
Top 99 with name 30-nh2-n-h DFT: 9.097272693656578 kcal/mol
Top 100 with name 18-h2s-h-s DFT: 8.770080895424599 kcal/mol
Top 101 with name 114-c-hooo-h-o DFT: 8.523902039734878 kcal/mol
Top 102 with name 51-alf-al-f DFT: 7.885298935275642 kcal/mol
Top 103 with name 57-becl2-be-cl DFT: 7.617353063566611 kcal/mol
Top 104 with name 16-ch2-sing-c-h DFT: 7.217542938279365 kcal/mol
Top 105 with name 96-hoo-h-o DFT: 7.123562918499914 kcal/mol
Top 106 with name 1-alh3-al-h DFT: 7.023794460628238 kcal/mol
Top 107 with name 4-bh3-b-h DFT: 6.897916790031502 kcal/mol
Top 108 with name 56-bf-b-f DFT: 6.54784418426442 kcal/mol
Top 109 with name 100-hof-h-o-f DFT: 6.014454051169849 kcal/mol
Top 110 with name 108-ccl2-c-cl DFT: 5.969331846146844 kcal/mol
Top 111 with name 6-ch2-trip-c-h DFT: 5.929337076953743 kcal/mol
Top 112 with name 112-so-s-o DFT: 5.475904759263216 kcal/mol
Top 113 with name 63-sif-si-f DFT: 5.386171048180557 kcal/mol
Top 114 with name 35-hf-h-f DFT: 5.134294303214688 kcal/mol
Top 115 with name 37-oh-o-h DFT: 5.001937588931327 kcal/mol
Top 116 with name 31-nh-n-h DFT: 4.764962707246866 kcal/mol
Top 117 with name 115-s2-s DFT: 4.681448306782642 kcal/mol
Top 118 with name 87-cf-c-f DFT: 4.5518068644400955 kcal/mol
Top 119 with name 89-hocl-h-o-cl DFT: 4.50452753593774 kcal/mol
Top 120 with name 61-alcl-al-cl DFT: 4.2327817727178285 kcal/mol
Top 121 with name 19-hs-h-s DFT: 4.098001626029372 kcal/mol
Top 122 with name 134-fo2-f-o DFT: 3.8316261352542824 kcal/mol
Top 123 with name 135-cloo-cl-o DFT: 3.711916578822425 kcal/mol
Top 124 with name 118-o2-o DFT: 3.577550295761668 kcal/mol
Top 125 with name 17-ch-c-h DFT: 3.5251561653248586 kcal/mol
Top 126 with name 2-alh-al-h DFT: 3.490822354767033 kcal/mol
Top 127 with name 29-hcl-h-cl DFT: 3.3666007161266123 kcal/mol
Top 128 with name 139-be2-be DFT: 3.3333291050456464 kcal/mol
Top 129 with name 131-oclo-o-cl DFT: 3.1884008740354375 kcal/mol
Top 130 with name 0-h2-h DFT: 2.946261026537343 kcal/mol
Top 131 with name 7-sih-si-h DFT: 2.87869333569337 kcal/mol
Top 132 with name 136-foof-f-o DFT: 2.592181899389601 kcal/mol
Top 133 with name 117-cl2-cl DFT: 2.5779952300945297 kcal/mol
Top 134 with name 5-bh-b-h DFT: 2.4310111682603406 kcal/mol
Top 135 with name 129-of-o-f DFT: 2.3656024306939827 kcal/mol
Top 136 with name 125-clo-cl-o DFT: 2.1670700864416403 kcal/mol
Top 137 with name 119-f2-f DFT: 1.8682213744892522 kcal/mol
Top 138 with name 132-f2o-f-o DFT: 1.7084148952065163 kcal/mol
Top 139 with name 123-clf-cl-f DFT: 1.568002564049678 kcal/mol
Top 140 with name 127-cl2o-cl-o DFT: 1.1456044106286072 kcal/mol
Top 1 with name 10-nme3-cbh22-nme3-cbh22 DFT: 16.188789434381178 kcal/mol
Top 2 with name 16-pme3-cbh22-pme3-cbh22 DFT: 13.620511109507646 kcal/mol
Top 3 with name 4-me2s-cbh22-me2s-cbh22 DFT: 11.207223495186774 kcal/mol
Top 4 with name 12-pf3-cbh22-pf3-cbh22 DFT: 10.193876948761755 kcal/mol
Top 5 with name 8-nh3-cbh22-nh3-cbh22 DFT: 8.962963522533826 kcal/mol
Top 6 with name 14-ph3-cbh22-ph3-cbh22 DFT: 8.901855080603852 kcal/mol
Top 7 with name 0-f2s-cbh22-f2s-cbh22 DFT: 8.499439025779722 kcal/mol
Top 8 with name 11-nme3-ch2-nme3-ch2 DFT: 7.2533029784013365 kcal/mol
Top 9 with name 2-h2s-cbh22-h2s-cbh22 DFT: 7.253175283557503 kcal/mol
Top 10 with name 1-f2s-ch2-f2s-ch2 DFT: 6.039933033102571 kcal/mol
Top 11 with name 13-pf3-ch2-pf3-ch2 DFT: 5.874626430400099 kcal/mol
Top 12 with name 17-pme3-ch2-pme3-ch2 DFT: 5.731503694787534 kcal/mol
Top 13 with name 5-me2s-ch2-me2s-ch2 DFT: 3.844706554851875 kcal/mol
Top 14 with name 15-ph3-ch2-ph3-ch2 DFT: 3.080381656316021 kcal/mol
Top 15 with name 9-nh3-ch2-nh3-ch2 DFT: 2.256334526618158 kcal/mol
Top 16 with name 6-nf3-cbh22-nf3-cbh22 DFT: 2.1604431956971535 kcal/mol
Top 17 with name 7-nf3-ch2-nf3-ch2 DFT: 1.2319050407026921 kcal/mol
Top 18 with name 3-h2s-ch2-h2s-ch2 DFT: 0.8221467854549687 kcal/mol
Top 1 with name 2-al2cl6-alcl3 DFT: 9.53533701132983 kcal/mol
Top 2 with name 5-al2me6-alme3 DFT: 5.05274255821714 kcal/mol
Top 3 with name 3-al2me4-alme2 DFT: 4.189930978545455 kcal/mol
Top 4 with name 4-al2me5-alme2-alme3 DFT: 3.9114041001128506 kcal/mol
Top 5 with name 0-al2h6-alh3 DFT: 3.157641716883518 kcal/mol
Top 6 with name 1-al2f6-alf3 DFT: 0.28828746757935875 kcal/mol
Top 1 with name 7-mgo-mg-o DFT: 7.668094772077168 kcal/mol
Top 2 with name 0-bef-be-f DFT: 7.38498456533415 kcal/mol
Top 3 with name 8-mgs-mg-s DFT: 7.1135064611036825 kcal/mol
Top 4 with name 1-beo-be-o DFT: 6.630398207738466 kcal/mol
Top 5 with name 3-hf-h-f DFT: 5.479623385175358 kcal/mol
Top 6 with name 9-nao-na-o DFT: 3.6334491125628148 kcal/mol
Top 7 with name 4-kf-k-f DFT: 2.9394115105533274 kcal/mol
Top 8 with name 2-cao-ca-o DFT: 2.758047718697341 kcal/mol

/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/chenzihao/anaconda3/envs/pyscf/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

        scf_ene scf_d3bj_ene Processed
sub1   9.865944     8.813946    9 / 18
sub2  13.907246     5.341473     1 / 9
sub3        NaN          NaN     0 / 7
sub4   2.047967     0.741035    0 / 12
sub5   1.021742     0.553854     0 / 9

wtmad_1

           scf_ene scf_d3bj_ene Processed
sub1      4.294093      3.69959    9 / 18
sub2      6.425508     2.646844     1 / 9
sub3           NaN          NaN     0 / 7
sub4     20.479667     7.410351    0 / 12
sub5      11.63909     5.762892     0 / 9
summary        NaN          NaN        --

wtmad_2

           scf_ene scf_d3bj_ene Processed
sub1      3.335045     3.016844    9 / 18
sub2      3.069999     0.882021     1 / 9
sub3           0.0          0.0     0 / 7
sub4      2.136446      0.77305    0 / 12
sub5      1.561966     0.903288     0 / 9
summary  10.103456     5.575203        --

Summary of Subset
MAE

             scf_ene scf_d3bj_ene Processed
AL2X6       2.442779     4.355891      DONE
ALK8               0            0     0 / 8
ALKBDE10     5.10864     4.646737      DONE
BH76RC             0            0    0 / 30
DC13               0            0    0 / 13
DIPCS10     6.418703     6.403969      DONE
FH51               0            0    0 / 51
G21EA       5.291996     5.287058      DONE
G21IP       3.825676      3.83182      DONE
G2RC               0            0    0 / 25
HEAVYSB11   6.855126     2.534261   10 / 11
NBPRC       4.310531     3.574563    5 / 12
PA26        2.381601     2.792602      DONE
RC21               0            0    0 / 21
SIE4x4     18.283906    18.713203      DONE
TAUT15             0            0    0 / 15
W4_11      14.370496    12.731396      DONE
YBDE18      6.840173     3.189867      DONE
BSR36       9.981292     2.627794      DONE
C60ISO             0            0     0 / 9
CDIE20             0            0    0 / 20
DARC               0            0    0 / 14
ISO34              0            0    0 / 34
ISOL24      1.987123      1.58498    8 / 24
MB16_43     73.08108    37.277565    4 / 43
PArel              0            0    0 / 20
RSE43              0            0    0 / 43
BH76               0            0    0 / 76
BHDIV10            0            0    0 / 10
BHPERI             0            0    0 / 26
BHROT27            0            0    0 / 27
INV24              0            0    0 / 24
PX13               0            0    0 / 13
WCPT18             0            0    0 / 18
ADIM6              0            0     0 / 6
AHB21              0            0    0 / 21
CARBHB12           0            0    0 / 12
CHB6               0            0     0 / 6
HAL59              0            0    0 / 59
HEAVY28            0            0    0 / 28
IL16               0            0    0 / 16
PNICO23            0            0    0 / 23
RG18               0            0    0 / 18
S22                0            0    0 / 22
S66         2.047967     0.741035   46 / 66
WATER27            0            0    0 / 27
ACONF              0            0    0 / 15
Amino20x4   0.547853     0.479072   24 / 80
BUT14DIOL          0            0    0 / 64
ICONF              0            0    0 / 17
IDISP              0            0     0 / 6
MCONF       1.779965     0.673506   15 / 51
PCONF21            0            0    0 / 18
SCONF              0            0    0 / 17
UPU23              0            0    0 / 23